/*
 * contextdata.js  (SC.contextData) – Reise-Kontext-Inhalte für die Lernkarten.
 * REINE DATEN. Wird in data.js auf das volle context-Format gemappt und an die
 * passenden Karten gehängt (Karten-id als Schlüssel).
 *
 * Kompakte Schreibweise pro Eintrag:
 *   e = sentenceEs  – echter, sprechbarer Reisesatz auf Spanisch (LatAm)
 *   d = sentenceDe  – deutsche Übersetzung
 *   s = situation   – konkrete Situation: wann nutzt man das?
 *   n = note        – kurzer Reisetipp / Besonderheit / regionale Variante
 *
 * Inhaltsregeln (siehe data.js): immer ein echter Satz, den man unterwegs sagt –
 * nicht schulisch, nicht künstlich, LatAm-Fokus, lieber ein guter als drei mittlere.
 * Reine Zahlen-Karten (z + Ziffern) bekommen ihren Kontext NICHT hier, sondern
 * praktisch generiert in data.js (Preis/Menge im Reisealltag).
 */
(function () {
  "use strict";

  const C = {
    // ===================== KERN-KARTEN (Showcase, früher inline) =====================
    b10: { e: "Perdón, no entiendo. ¿Puede repetir?", d: "Entschuldigung, ich verstehe nicht. Können Sie das wiederholen?", s: "Wenn jemand zu schnell oder undeutlich spricht.", n: "Bleib ruhig und ergänze direkt ¿Puede repetir? – das hilft fast immer weiter." },
    b16: { e: "Disculpe, ¿dónde está el baño?", d: "Entschuldigung, wo ist die Toilette?", s: "In Restaurants, Hostels, Busbahnhöfen oder Cafés.", n: "In Lateinamerika sagt man meistens el baño, nicht wörtlich el inodoro." },
    b17: { e: "Por favor, necesito ayuda.", d: "Bitte, ich brauche Hilfe.", s: "Wenn du dich unsicher fühlst oder Unterstützung brauchst.", n: "Kurz und klar. In ernsten Situationen kannst du ergänzen: Es urgente." },
    e04: { e: "La cuenta, por favor.", d: "Die Rechnung, bitte.", s: "Im Restaurant, Café oder bei Streetfood mit Sitzbereich.", n: "Kurz, höflich und völlig ausreichend. Noch höflicher: ¿Me trae la cuenta, por favor?" },
    e46: { e: "Para mí sin cebolla, por favor.", d: "Für mich ohne Zwiebeln, bitte.", s: "Beim Bestellen, wenn du eine Zutat vermeiden willst.", n: "Die Struktur sin ... ist extrem praktisch: sin carne, sin queso, sin picante." },
    hostel01: { e: "Hola, tengo una reserva para esta noche.", d: "Hallo, ich habe eine Reservierung für heute Nacht.", s: "Beim Check-in im Hostel, Hotel oder Guesthouse.", n: "Wenn nach dem Namen gefragt wird, sag: A nombre de Marcel." },
    hostel02: { e: "Hola, ¿tiene una cama libre para esta noche?", d: "Hallo, haben Sie für heute Nacht noch ein Bett frei?", s: "Wenn du spontan ein Hostel suchst oder verlängern möchtest.", n: "Alternativ kannst du fragen: ¿Hay una cama disponible?" },
    hostel03: { e: "¿El desayuno está incluido en el precio?", d: "Ist das Frühstück im Preis enthalten?", s: "Beim Check-in oder bei der Buchung vor Ort.", n: "Wenn es nicht inklusive ist, frag einfach: ¿Cuánto cuesta?" },
    hostel04: { e: "Perdón, ¿dónde está mi cama?", d: "Entschuldigung, wo ist mein Bett?", s: "Im Dorm, wenn dir nur eine Bett- oder Zimmernummer genannt wurde.", n: "Oben oder unten? Man unterscheidet cama de arriba und cama de abajo." },
    hostel05: { e: "Perdón, mi llave no funciona. ¿Me puede ayudar?", d: "Entschuldigung, mein Schlüssel funktioniert nicht. Können Sie mir helfen?", s: "An der Rezeption, wenn Karte, Schlüssel oder Türcode streiken.", n: "Für eine Schlüsselkarte sag tarjeta: Mi tarjeta no funciona." },
    hostel06: { e: "¿Puedo dejar mi equipaje aquí hasta la tarde?", d: "Kann ich mein Gepäck hier bis zum Nachmittag lassen?", s: "Vor dem Check-in oder nach dem Check-out.", n: "Sehr praktisch am Reisetag. Für Rucksack sag mochila." },
    hostel07: { e: "¿Hay un locker para guardar mis cosas?", d: "Gibt es ein Schließfach, um meine Sachen aufzubewahren?", s: "Im Dorm, wenn du Wertsachen sicher verstauen willst.", n: "locker wird fast überall verstanden. Spanischer wäre casillero." },
    hostel08: { e: "Perdón, mi cama está ocupada. Creo que hay un error.", d: "Entschuldigung, mein Bett ist belegt. Ich glaube, es gibt einen Fehler.", s: "Wenn jemand auf deinem zugewiesenen Bett liegt.", n: "Der Zusatz Creo que hay un error klingt ruhig, nicht aggressiv." },
    hostel09: { e: "¿Hay cocina para los huéspedes?", d: "Gibt es eine Küche für die Gäste?", s: "Wenn du selbst kochen oder Essen lagern willst.", n: "Gäste heißt huéspedes – im Hostel reicht aber auch nur cocina." },
    hostel10: { e: "Disculpe, ¿podría cambiar de habitación? Hay mucho ruido.", d: "Entschuldigung, könnte ich das Zimmer wechseln? Es ist sehr laut.", s: "Wenn dein Zimmer zu laut, zu heiß oder problematisch ist.", n: "Podría ist höflicher als puedo und passt gut an der Rezeption." },
    v05: { e: "Disculpe, ¿de dónde sale el bus a Cartagena?", d: "Entschuldigung, von wo fährt der Bus nach Cartagena ab?", s: "Am Busbahnhof, bei einer Agentur oder an einer Haltestelle.", n: "Je nach Land heißt der Bus auch colectivo, micro, buseta oder camión." },
    v12: { e: "¿Cuánto cuesta el viaje al centro?", d: "Wie viel kostet die Fahrt ins Zentrum?", s: "Im Taxi oder colectivo, am besten vor dem Einsteigen.", n: "Vorher fragen schützt vor Überraschungen. Für ein Ticket sag boleto oder pasaje." },
    n11: { e: "Perdí mi celular. ¿Alguien lo encontró?", d: "Ich habe mein Handy verloren. Hat es jemand gefunden?", s: "Im Hostel, Bus, Restaurant oder nach einer Tour.", n: "In Lateinamerika ist celular das übliche Wort für Handy." },
    n15: { e: "Disculpe, ¿dónde está la farmacia más cercana?", d: "Entschuldigung, wo ist die nächste Apotheke?", s: "Wenn du Medikamente oder etwas gegen Bauchweh brauchst.", n: "Apotheken sind in LatAm oft auch ohne Rezept hilfreich. Nachts: farmacia de turno." },
    social01: { e: "Hola, ¿de dónde eres?", d: "Hey, woher kommst du?", s: "Beim Frühstück, im Dorm, in einer Tourgruppe oder im Bus.", n: "Perfekter Einstieg. Danach passt: ¿Cuánto tiempo viajas?" },
    social02: { e: "¿Viajas solo o con amigos?", d: "Reist du alleine oder mit Freunden?", s: "Beim Kennenlernen anderer Backpacker.", n: "Bei Männern solo, bei Frauen sola. Im Hostel eine ganz normale Frage." },
    social03: { e: "¿Cuánto tiempo estás aquí en Cartagena?", d: "Wie lange bist du hier in Cartagena?", s: "Wenn du wissen willst, ob jemand länger bleibt oder bald weiterreist.", n: "Den Ort einfach austauschen: aquí en Bogotá, aquí en Lima, aquí en Medellín." },
    social04: { e: "¿A dónde vas después de Cartagena?", d: "Wohin reist du nach Cartagena weiter?", s: "Typischer Backpacker-Smalltalk über Reiserouten.", n: "Super, um Tipps zu bekommen oder gemeinsame Pläne zu entdecken." },
    social05: { e: "¿Qué haces mañana? Quiero ir a la playa.", d: "Was machst du morgen? Ich möchte an den Strand gehen.", s: "Wenn du gemeinsame Pläne anstoßen willst.", n: "Mach es direkt konkret. Nur ¿Qué haces mañana? kann leicht privat klingen." },
    social06: { e: "¿Quieres ir a comer algo más tarde?", d: "Hast du Lust, später etwas essen zu gehen?", s: "Im Hostel, nach einer Tour oder vor dem Abend.", n: "más tarde bedeutet später und macht die Einladung locker." },
    social07: { e: "¿Vamos juntos al centro?", d: "Gehen wir zusammen ins Zentrum?", s: "Wenn ihr dasselbe Ziel habt oder gemeinsam losziehen wollt.", n: "juntos für gemischte Gruppen oder Männer, juntas für nur Frauen." },
    social08: { e: "Vamos a tomar algo. ¿Te unes?", d: "Wir gehen etwas trinken. Kommst du mit?", s: "Um jemanden locker einzuladen.", n: "Klingt natürlicher als eine sehr formelle Einladung. Perfekt im Hostel." },
    social09: { e: "Escríbeme por WhatsApp y nos vemos más tarde.", d: "Schreib mir auf WhatsApp, dann sehen wir uns später.", s: "Wenn ihr euch später treffen oder Pläne abstimmen wollt.", n: "WhatsApp ist in Lateinamerika extrem verbreitet – fast jeder nutzt es." },
    social10: { e: "Mucho gusto. Nos vemos mañana.", d: "Schön, dich kennenzulernen. Wir sehen uns morgen.", s: "Nach einem ersten Gespräch im Hostel oder unterwegs.", n: "Mucho gusto passt beim Kennenlernen. Beim Abschied passt: Fue un gusto conocerte." },

    // ===================== GRUNDLAGEN =====================
    b01: { e: "¡Hola! Buenos días.", d: "Hallo! Guten Morgen.", s: "Beim Betreten von Laden, Hostel oder Restaurant.", n: "Ein freundliches Hola öffnet überall Türen – auch unter Fremden völlig normal." },
    b02: { e: "Buenos días, ¿cómo está?", d: "Guten Morgen, wie geht es Ihnen?", s: "Morgens an der Rezeption, im Café oder beim Bäcker.", n: "Bis etwa mittags Buenos días, danach Buenas tardes." },
    b03: { e: "Buenas tardes, una mesa para dos, por favor.", d: "Guten Tag, einen Tisch für zwei, bitte.", s: "Nachmittags beim Betreten von Restaurant oder Laden.", n: "Ab Einbruch der Dunkelheit wird daraus Buenas noches." },
    b04: { e: "¡Chau, nos vemos!", d: "Tschüss, bis bald!", s: "Beim Verabschieden von Leuten im Hostel oder unterwegs.", n: "Chau ist locker und in ganz Südamerika beliebt; Adiós klingt endgültiger." },
    b05: { e: "Una mesa para dos, por favor.", d: "Einen Tisch für zwei, bitte.", s: "Bei jeder Bitte – Bestellung, Frage, Wunsch.", n: "Por favor am Satzende macht fast jede Bitte sofort höflich." },
    b06: { e: "Muchas gracias, muy amable.", d: "Vielen Dank, sehr freundlich.", s: "Nach Hilfe, Service oder einem Tipp.", n: "Verstärken mit Muchas gracias oder Mil gracias." },
    b07: { e: "– Gracias. – De nada.", d: "– Danke. – Gern geschehen.", s: "Wenn dir jemand dankt.", n: "Lockerer geht auch Con gusto oder No hay de qué." },
    b08: { e: "Disculpe, ¿me puede ayudar?", d: "Entschuldigung, können Sie mir helfen?", s: "Um jemanden anzusprechen oder um Hilfe zu bitten.", n: "Disculpe, um Aufmerksamkeit zu bekommen; Perdón eher beim Anrempeln." },
    b09: { e: "– ¿Todo bien? – Sí, gracias.", d: "– Alles gut? – Ja, danke.", s: "In jeder kurzen Rückfrage.", n: "Ein klares Sí oder No mit einem Lächeln reicht oft völlig." },
    b11: { e: "Disculpe, ¿habla inglés?", d: "Entschuldigung, sprechen Sie Englisch?", s: "Wenn du sprachlich nicht weiterkommst.", n: "Oft hilft die Frage – außerhalb von Touristenorten ist die Antwort aber meist no." },
    b12: { e: "Hola, ¿cómo te llamas?", d: "Hallo, wie heißt du?", s: "Beim Kennenlernen im Hostel oder unterwegs.", n: "Förmlich (Sie): ¿Cómo se llama?" },
    b13: { e: "Me llamo Marcel, ¿y tú?", d: "Ich heiße Marcel, und du?", s: "Wenn du dich vorstellst.", n: "Das ¿y tú? am Ende hält das Gespräch in Gang." },
    b14: { e: "Perdón, ¿me puedes ayudar? Estoy perdido.", d: "Entschuldigung, kannst du mir helfen? Ich habe mich verlaufen.", s: "Wenn du Orientierung oder Unterstützung brauchst.", n: "Höflicher und förmlich: ¿Me puede ayudar?" },
    b15: { e: "Más despacio, por favor. No entiendo.", d: "Langsamer, bitte. Ich verstehe nicht.", s: "Wenn jemand zu schnell spricht.", n: "Kombiniert mit ¿Puede repetir? klappt es fast immer." },
    b18: { e: "Necesito un médico, por favor.", d: "Ich brauche einen Arzt, bitte.", s: "Bei Krankheit oder Verletzung – im Hostel, in der Apotheke.", n: "Im Notfall ergänzen: Es una emergencia." },
    b19: { e: "¡Llame a la policía, por favor!", d: "Rufen Sie die Polizei, bitte!", s: "In einer echten Notlage.", n: "Der Notruf ist in vielen Ländern die 911." },
    b20: { e: "Disculpe, estoy perdido. ¿Dónde queda el centro?", d: "Entschuldigung, ich habe mich verlaufen. Wo ist das Zentrum?", s: "Wenn du die Orientierung verloren hast.", n: "Männer sagen perdido, Frauen perdida." },
    b21: { e: "¿Hay una farmacia cerca?", d: "Gibt es eine Apotheke in der Nähe?", s: "Bei kleinen Wehwehchen oder für Medikamente.", n: "In LatAm bekommt man in der farmacia vieles auch ohne Rezept." },

    // ===================== ZAHLEN (Sonderfälle / Wörter) =====================
    z2025: { e: "Estamos en dos mil veinticinco.", d: "Wir haben 2025.", s: "Wenn nach dem Jahr gefragt wird – Formular, Einreise.", n: "Jahreszahlen sagt man als ganze Zahl: dos mil veinticinco." },
    zp01: { e: "Un café, por favor. – Son tres mil quinientos.", d: "Einen Kaffee, bitte. – Das macht 3.500.", s: "Im Café beim Bezahlen.", n: "Beträge werden oft ohne pesos genannt – nur die Zahl." },
    zp02: { e: "Una cerveza. – Son doce mil.", d: "Ein Bier. – Das macht 12.000.", s: "In der Bar oder im Restaurant.", n: "Trinkgeld (propina) steht oft schon auf der Rechnung." },
    zp03: { e: "El menú del día cuesta veinticinco mil.", d: "Das Tagesmenü kostet 25.000.", s: "Beim Mittagessen (almuerzo).", n: "Das menú del día hat fast überall das beste Preis-Leistungs-Verhältnis." },
    zp04: { e: "La cama cuesta cuarenta y cinco mil por noche.", d: "Das Bett kostet 45.000 pro Nacht.", s: "Beim Check-in im Hostel.", n: "Frag, ob Frühstück inklusive ist: ¿El desayuno está incluido?" },
    zp05: { e: "El boleto a Medellín cuesta ciento veinte mil.", d: "Das Ticket nach Medellín kostet 120.000.", s: "Beim Ticketkauf am Busbahnhof.", n: "Nachtbusse sind oft teurer, sparen aber eine Hostel-Nacht." },
    zp06: { e: "La excursión cuesta trescientos cincuenta mil por persona.", d: "Der Ausflug kostet 350.000 pro Person.", s: "Beim Buchen einer Tour.", n: "Bei Gruppen oft Rabatt – frag: ¿Hay descuento por grupo?" },
    zp07: { e: "El alquiler es un millón quinientos mil al mes.", d: "Die Miete beträgt 1.500.000 pro Monat.", s: "Wenn du länger bleibst und etwas mietest.", n: "Für längere Aufenthalte lohnt es sich, über den Monatspreis zu verhandeln." },
    znum: { e: "¿Cuál es el número de tu habitación?", d: "Welche Nummer hat dein Zimmer?", s: "Im Hostel/Hotel, bei Bett- oder Zimmernummer.", n: "número steht auch für die Telefonnummer: tu número." },
    zmilord: { e: "Cuesta más de un millón de pesos.", d: "Es kostet über eine Million Pesos.", s: "Bei großen Beträgen wie Miete oder Flug.", n: "Achtung Grammatik: un millón de pesos, mit de." },
    zmitad: { e: "Solo quiero la mitad, por favor.", d: "Ich möchte nur die Hälfte, bitte.", s: "Auf dem Markt oder beim Bestellen von Portionen.", n: "medio kilo = ein halbes Kilo; la mitad = die Hälfte von etwas." },
    zo01: { e: "Es la primera vez que vengo aquí.", d: "Es ist das erste Mal, dass ich hier bin.", s: "Im Smalltalk über deine Reise.", n: "Vor männlichem Nomen wird primero zu primer: el primer día." },
    zo02: { e: "Mi cuarto está en el segundo piso.", d: "Mein Zimmer ist im zweiten Stock.", s: "Beim Finden des Zimmers.", n: "In LatAm ist el primer piso meist die erste Etage über dem Erdgeschoss." },
    zo03: { e: "Bájate en la tercera parada.", d: "Steig an der dritten Haltestelle aus.", s: "Beim Busfahren mit Wegbeschreibung.", n: "Vor männlichem Nomen wird tercero zu tercer: el tercer piso." },
    zo04: { e: "Es la cuarta calle a la derecha.", d: "Es ist die vierte Straße rechts.", s: "Bei einer Wegbeschreibung.", n: "cuarto heißt auch Zimmer – aus dem Kontext meist klar." },
    zo05: { e: "Vivo en el quinto piso.", d: "Ich wohne im fünften Stock.", s: "Bei Adressen und Stockwerken.", n: "Gibt es einen Aufzug? Frag: ¿Hay ascensor?" },
    zo06: { e: "El mirador está en el sexto piso.", d: "Die Aussichtsplattform ist im sechsten Stock.", s: "In Hotels oder Aussichtstürmen.", n: "sexto wird in LatAm oft vereinfacht 'ses-to' gesprochen." },
    zo07: { e: "Mi habitación es la séptima puerta.", d: "Mein Zimmer ist die siebte Tür.", s: "Bei der Zimmersuche im Flur.", n: "Das p in séptimo wird oft kaum gesprochen: SE-ti-mo." },
    zo08: { e: "La fiesta es en el octavo piso.", d: "Die Party ist im achten Stock.", s: "Bei Rooftop-Bars oder Events.", n: "Ordnungszahlen über 10 nutzt man im Alltag kaum noch." },
    zo09: { e: "Estamos en el noveno día de viaje.", d: "Wir sind am neunten Reisetag.", s: "Im Gespräch über die Reisedauer.", n: "Ab 11 sagt man im Alltag meist die normale Zahl statt der Ordnungszahl." },
    zo10: { e: "Es mi décimo país en este viaje.", d: "Es ist mein zehntes Land auf dieser Reise.", s: "Beim Erzählen über deine Route.", n: "Danach wird es selten: für höhere Zahlen nimmt man die normale Zahl." },
    zo1f: { e: "Es mi primera vez en Sudamérica.", d: "Es ist mein erstes Mal in Südamerika.", s: "Im Smalltalk über die Reise.", n: "primera ist die weibliche Form von primero (la primera vez)." },
    zopiso: { e: "Mi habitación está en el primer piso.", d: "Mein Zimmer ist im ersten Stock.", s: "Beim Finden des Zimmers im Hostel/Hotel.", n: "In vielen Ländern ist el primer piso die Etage über dem Erdgeschoss (planta baja)." },

    // ===================== ESSEN =====================
    e01: { e: "¿A qué hora es la comida?", d: "Wann gibt es Essen?", s: "Im Hostel mit Verpflegung oder bei einer Tour.", n: "comida heißt Essen allgemein, in Mexiko oft speziell das Mittagessen." },
    e02: { e: "Tengo hambre, ¿vamos a comer algo?", d: "Ich habe Hunger, gehen wir etwas essen?", s: "Wenn du mit anderen Pläne machst.", n: "Großer Hunger: Tengo mucha hambre." },
    e03: { e: "¿Me trae la carta, por favor?", d: "Bringen Sie mir die Karte, bitte?", s: "Beim Hinsetzen im Restaurant.", n: "la carta ist die Speisekarte; el menú oft das feste Tagesmenü." },
    e05: { e: "Soy vegetariano, ¿qué me recomienda?", d: "Ich bin Vegetarier, was empfehlen Sie?", s: "Beim Bestellen.", n: "Frauen sagen vegetariana. Sicherheitshalber: ¿Tiene algo sin carne?" },
    e06: { e: "Algo sin carne, por favor.", d: "Etwas ohne Fleisch, bitte.", s: "Beim Bestellen, wenn du fleischlos isst.", n: "Achtung: pollo (Hähnchen) zählt für viele nicht als carne – extra nachfragen." },
    e07: { e: "¿Me trae un poco de pan?", d: "Bringen Sie mir etwas Brot?", s: "Im Restaurant oder beim Frühstück.", n: "In der panadería (Bäckerei) einfach zeigen und die Menge sagen." },
    e08: { e: "Para mí el pollo, por favor.", d: "Für mich das Hähnchen, bitte.", s: "Beim Bestellen.", n: "pollo a la plancha = gegrillt, pollo frito = frittiert." },
    e09: { e: "¿El pescado es fresco?", d: "Ist der Fisch frisch?", s: "An der Küste oder im Fischrestaurant.", n: "Tagesfang heißt oft pescado del día." },
    e10: { e: "¿Tiene fruta fresca?", d: "Haben Sie frisches Obst?", s: "Am Marktstand oder beim Frühstück.", n: "Frischer Saft: jugo natural de fruta." },
    e11: { e: "¿Es muy picante?", d: "Ist das sehr scharf?", s: "Beim Bestellen, wenn du die Schärfe checken willst.", n: "Nicht scharf: sin picante. Schärfe extra: con ají / con chile." },
    e12: { e: "¡Qué rico está esto!", d: "Wie lecker das ist!", s: "Während des Essens, als Kompliment.", n: "rico heißt lecker – ein Lob, das überall gut ankommt." },
    e13: { e: "¿A qué hora es el desayuno?", d: "Wann gibt es Frühstück?", s: "Im Hostel oder Hotel.", n: "Inklusive? ¿El desayuno está incluido?" },
    e14: { e: "Quiero el almuerzo del día.", d: "Ich möchte das Mittagsmenü.", s: "Mittags im Lokal.", n: "el almuerzo (Mittagessen) ist in LatAm oft die Hauptmahlzeit." },
    e15: { e: "¿A qué hora sirven la cena?", d: "Wann gibt es Abendessen?", s: "Abends im Restaurant oder Hostel.", n: "In vielen Ländern isst man spät zu Abend – oft ab 20 Uhr." },
    e16: { e: "¿Qué me recomienda de la carta?", d: "Was empfehlen Sie von der Karte?", s: "Wenn du Lokales probieren willst.", n: "Nach dem typischen Gericht fragen: ¿Cuál es el plato típico?" },
    e17: { e: "Para llevar, por favor.", d: "Zum Mitnehmen, bitte.", s: "Beim Bestellen zum Mitnehmen.", n: "Gegenteil: para comer aquí (zum Hieressen)." },
    e18: { e: "Tengo una alergia. ¿Esto lleva maní?", d: "Ich habe eine Allergie. Ist da Erdnuss drin?", s: "Beim Bestellen mit Unverträglichkeit.", n: "Wichtig klar sagen – ergänze die konkrete Zutat (maní, gluten, lactosa)." },
    e19: { e: "Con muchas verduras, por favor.", d: "Mit viel Gemüse, bitte.", s: "Beim Bestellen.", n: "In manchen Ländern auch vegetales." },
    e20: { e: "¿Viene con arroz?", d: "Kommt das mit Reis?", s: "Beim Bestellen.", n: "Reis und Bohnen (arroz con frijoles) ist die Standard-Beilage." },
    e21: { e: "¿Tienen huevos para el desayuno?", d: "Gibt es Eier zum Frühstück?", s: "Beim Frühstück.", n: "Rührei = huevos revueltos." },
    e22: { e: "Con queso, por favor.", d: "Mit Käse, bitte.", s: "Beim Bestellen.", n: "Arepa con queso ist ein beliebter Snack." },
    e23: { e: "¿Me pasa la sal, por favor?", d: "Reichen Sie mir das Salz, bitte?", s: "Am Tisch.", n: "Salz sal, Pfeffer pimienta – nicht verwechseln mit pimiento (Paprika)." },
    e24: { e: "Quiero el menú del día.", d: "Ich möchte das Tagesmenü.", s: "Mittags im Lokal.", n: "Meist Suppe, Hauptgang und Getränk zum Festpreis – das beste Angebot." },
    e25: { e: "¿Qué hay de postre?", d: "Was gibt es zum Nachtisch?", s: "Nach dem Hauptgang.", n: "Oft schon im menú del día inklusive." },
    e26: { e: "Otra, por favor.", d: "Noch eins, bitte.", s: "Um Nachschub zu bestellen.", n: "Form passt sich an: otro café, otra cerveza." },
    e27: { e: "Disculpe, ¿podemos ordenar?", d: "Entschuldigung, können wir bestellen?", s: "Wenn du den Kellner rufen willst.", n: "In Spanien eher pedir, in LatAm meist ordenar." },
    e28: { e: "Para mí lo mismo, por favor.", d: "Für mich das Gleiche, bitte.", s: "Beim Bestellen in der Gruppe.", n: "Praktisch, wenn dir die Auswahl schwerfällt." },
    e29: { e: "¿Lo puede hacer menos picante?", d: "Können Sie es weniger scharf machen?", s: "Beim Bestellen scharfer Gerichte.", n: "Ganz ohne: sin picante, por favor." },
    e30: { e: "Sin cebolla y con extra queso, por favor.", d: "Ohne Zwiebel und mit extra Käse, bitte.", s: "Beim Anpassen der Bestellung.", n: "sin = ohne, con extra = mit zusätzlich." },
    e31: { e: "¿Está libre esta mesa?", d: "Ist dieser Tisch frei?", s: "Im vollen Lokal oder Café.", n: "Besetzt? ¿Está ocupado?" },
    e32: { e: "¿Me lo puede empacar para llevar?", d: "Können Sie es mir einpacken? (Reste)", s: "Wenn du Reste mitnehmen willst.", n: "In manchen Ländern auch envolver oder para llevar." },
    e33: { e: "Otra cerveza, por favor.", d: "Noch ein Bier, bitte.", s: "In Bar oder Restaurant.", n: "Eine Runde für alle: una ronda para todos." },
    e34: { e: "¿Qué es esto? Se ve rico.", d: "Was ist das? Sieht lecker aus.", s: "Am Marktstand oder bei unbekanntem Gericht.", n: "Neugier kommt gut an – oft bekommst du etwas zum Probieren." },
    e35: { e: "La comida estuvo excelente, gracias.", d: "Das Essen war ausgezeichnet, danke.", s: "Nach dem Essen als Lob.", n: "estuvo (war) für ein abgeschlossenes Erlebnis." },
    e36: { e: "Todo estuvo delicioso.", d: "Alles war köstlich.", s: "Beim Bezahlen oder Verabschieden.", n: "Kommt beim Personal immer gut an." },
    e37: { e: "Me gustó mucho, estuvo muy rico.", d: "Es hat mir sehr gefallen, war richtig lecker.", s: "Nach dem Essen.", n: "rico = lecker, in ganz LatAm gebräuchlich." },
    e38: { e: "Estoy satisfecho, gracias.", d: "Ich bin satt, danke.", s: "Wenn man dir mehr anbietet.", n: "Höflicher als Estoy lleno. Frauen: satisfecha." },
    e39: { e: "Mis felicitaciones al chef.", d: "Mein Kompliment an den Koch.", s: "Bei besonders gutem Essen.", n: "Ein nettes Extra-Lob, das selten jemand sagt." },
    e40: { e: "Fue el mejor plato del viaje.", d: "Das war das beste Gericht der Reise.", s: "Als großes Kompliment.", n: "plato = Teller und Gericht zugleich." },
    e41: { e: "¿Puedo cambiar algo del plato?", d: "Kann ich etwas am Gericht austauschen?", s: "Wenn du eine Zutat tauschen willst.", n: "Konkretisieren mit en vez de ... (statt ...)." },
    e42: { e: "¿En vez de las papas fritas, una ensalada?", d: "Statt der Pommes lieber einen Salat?", s: "Beim Anpassen der Beilage.", n: "papas = Kartoffeln; in Spanien patatas." },
    e43: { e: "¿Puedo cambiar las papas por ensalada?", d: "Kann ich die Pommes gegen Salat tauschen?", s: "Beim Bestellen.", n: "Die Struktur cambiar X por Y ist überall nützlich." },
    e44: { e: "En vez de arroz, frijoles, por favor.", d: "Statt Reis lieber Bohnen, bitte.", s: "Beim Wählen der Beilage.", n: "Bohnen: frijoles, in manchen Ländern porotos oder caraotas." },
    e45: { e: "¿Puede ser con un acompañamiento a elección?", d: "Geht das mit einer Beilage nach Wahl?", s: "Beim Bestellen von Menüs.", n: "acompañamiento = Beilage." },
    e47: { e: "Sin cilantro, por favor.", d: "Ohne Koriander, bitte.", s: "Beim Bestellen, wenn du Koriander nicht magst.", n: "cilantro ist in LatAm sehr verbreitet – kommt fast überall drauf." },
    e48: { e: "El aderezo aparte, por favor.", d: "Dressing bitte separat.", s: "Beim Salat bestellen.", n: "aparte = separat/daneben." },
    e49: { e: "¿Puedo reemplazar el pollo por verduras?", d: "Kann ich das Hähnchen durch Gemüse ersetzen?", s: "Für eine vegetarische Anpassung.", n: "reemplazar X por Y = X durch Y ersetzen." },
    e50: { e: "¿Tienen Coca en versión Zero?", d: "Gibt es die Cola auch als Zero?", s: "Beim Getränk bestellen.", n: "Light/Zero heißt oft einfach light oder sin azúcar." },
    e51: { e: "¿En vez de jugo, mejor un agua?", d: "Statt Saft lieber ein Wasser?", s: "Beim Getränk wählen.", n: "agua sin gas = still, con gas = mit Kohlensäure." },
    e52: { e: "¿Puedo cambiar la gaseosa por agua sin gas?", d: "Kann ich statt Limo ein stilles Wasser haben?", s: "Beim Menügetränk.", n: "gaseosa = Limo/Softdrink in vielen Ländern." },
    e53: { e: "Un café sin azúcar, por favor.", d: "Einen Kaffee ohne Zucker, bitte.", s: "Beim Heißgetränk.", n: "Zucker steht oft schon mit drauf – sin azúcar vorher sagen." },
    e54: { e: "¿El jugo lleva azúcar?", d: "Ist im Saft Zucker?", s: "Beim Saft bestellen.", n: "Ohne Zucker bestellen: sin azúcar, por favor." },
    e55: { e: "Soy alérgico a las nueces.", d: "Ich bin allergisch gegen Nüsse.", s: "Beim Bestellen mit Allergie.", n: "Frauen: alérgica. Wichtig, das klar und früh zu sagen." },
    e56: { e: "¿Esto contiene gluten?", d: "Enthält das Gluten?", s: "Bei Glutenunverträglichkeit.", n: "Glutenfrei: sin gluten / libre de gluten." },
    e57: { e: "No tolero la lactosa.", d: "Ich vertrage keine Laktose.", s: "Beim Bestellen mit Milchprodukten.", n: "Laktosefrei: sin lactosa. Pflanzenmilch: leche vegetal." },
    e58: { e: "¿Lleva maní? Es importante.", d: "Ist da Erdnuss drin? Das ist wichtig.", s: "Bei Erdnussallergie – ernst.", n: "maní = Erdnuss (Spanien: cacahuete). Bei Allergie immer Es importante betonen." },
    e59: { e: "¿Me lo puede dar para llevar?", d: "Kann ich das zum Mitnehmen bekommen?", s: "Wenn du das Essen mitnehmen willst.", n: "para llevar = zum Mitnehmen, überall verständlich." },
    e60: { e: "El resto para llevar, por favor.", d: "Den Rest bitte einpacken.", s: "Wenn etwas übrig bleibt.", n: "Reste mitnehmen ist normal – kein Grund zur Scheu." },

    // ===================== TRINKEN =====================
    t01: { e: "Tengo sed, ¿me trae un agua?", d: "Ich habe Durst, bringen Sie mir ein Wasser?", s: "Im Lokal oder unterwegs.", n: "Großer Durst: Tengo mucha sed." },
    t02: { e: "Un agua sin gas, por favor.", d: "Ein stilles Wasser, bitte.", s: "Beim Bestellen.", n: "con gas = mit Kohlensäure, sin gas = still." },
    t03: { e: "¿Es potable el agua de la llave?", d: "Ist das Leitungswasser trinkbar?", s: "Im Hostel oder Restaurant.", n: "In vielen Ländern besser Flaschenwasser (agua embotellada) trinken." },
    t04: { e: "Una botella de agua grande, por favor.", d: "Eine große Flasche Wasser, bitte.", s: "Im Laden oder Restaurant.", n: "grande/pequeña für die Größe." },
    t05: { e: "Una cerveza bien fría, por favor.", d: "Ein gut gekühltes Bier, bitte.", s: "In Bar oder Restaurant.", n: "bien fría = schön kalt – wichtig in den Tropen." },
    t06: { e: "Una copa de vino tinto, por favor.", d: "Ein Glas Rotwein, bitte.", s: "Im Restaurant.", n: "tinto = rot, blanco = weiß. Achtung: in Kolumbien ist un tinto ein schwarzer Kaffee!" },
    t07: { e: "Un café, por favor.", d: "Einen Kaffee, bitte.", s: "Im Café oder zum Frühstück.", n: "In Kolumbien heißt schwarzer Kaffee tinto; con leche = mit Milch." },
    t08: { e: "Un jugo natural de mango, por favor.", d: "Einen frischen Mangosaft, bitte.", s: "Am Saftstand oder im Café.", n: "jugo natural = frisch gepresst, oft en agua (Wasser) oder en leche (Milch)." },
    t09: { e: "¿El café viene con leche?", d: "Kommt der Kaffee mit Milch?", s: "Beim Heißgetränk.", n: "Pflanzenmilch oft als leche de almendras / de avena." },
    t10: { e: "¡Salud! Por el viaje.", d: "Prost! Auf die Reise.", s: "Beim Anstoßen.", n: "Salud heißt zugleich Gesundheit – das klassische Prost." },
    t11: { e: "Gracias por el trago.", d: "Danke fürs Getränk.", s: "Wenn dich jemand einlädt.", n: "trago = Drink/Schluck; un trago auszugeben ist eine nette Geste." },
    t12: { e: "¡Por nosotros y el viaje!", d: "Auf uns und die Reise!", s: "Beim Anstoßen mit neuen Leuten.", n: "Por ... = auf ... – flexibel: por la amistad, por Colombia." },
    t13: { e: "La próxima invito yo.", d: "Das nächste Mal lade ich ein.", s: "In geselliger Runde.", n: "La próxima (vez) = das nächste Mal; invitar heißt hier spendieren." },
    t14: { e: "Este jugo está buenísimo.", d: "Dieser Saft schmeckt richtig gut.", s: "Während des Trinkens.", n: "-ísimo verstärkt: bueno wird zu buenísimo (sehr gut)." },

    // ===================== HOTEL =====================
    h01: { e: "Hola, ¿tiene una habitación para esta noche?", d: "Hallo, haben Sie ein Zimmer für heute Nacht?", s: "Beim spontanen Check-in.", n: "habitación = Zimmer; im Hostel eher cama (Bett)." },
    h02: { e: "Quiero una habitación doble, por favor.", d: "Ich möchte ein Doppelzimmer, bitte.", s: "Beim Buchen vor Ort.", n: "doble = Doppel, sencilla/individual = Einzel." },
    h03: { e: "Para una noche, por favor.", d: "Für eine Nacht, bitte.", s: "Beim Check-in.", n: "Für mehrere: para tres noches." },
    h04: { e: "¿Hay wifi en la habitación?", d: "Gibt es WLAN im Zimmer?", s: "Beim Check-in.", n: "Passwort: ¿Cuál es la contraseña del wifi?" },
    h05: { e: "¿Me da la llave, por favor?", d: "Geben Sie mir den Schlüssel, bitte?", s: "Beim Check-in oder Zurückkommen.", n: "Schlüsselkarte: la tarjeta." },
    h06: { e: "La ducha no tiene agua caliente.", d: "Die Dusche hat kein warmes Wasser.", s: "Wenn etwas im Bad nicht stimmt.", n: "agua caliente = warmes Wasser." },
    h07: { e: "¿Me puede dar una toalla?", d: "Können Sie mir ein Handtuch geben?", s: "Wenn keins im Zimmer ist.", n: "In Hostels kostet die toalla manchmal extra." },
    h08: { e: "¿La habitación tiene aire acondicionado?", d: "Hat das Zimmer eine Klimaanlage?", s: "In heißen Regionen wichtig.", n: "Kurz: el aire. Ventilator: el ventilador." },
    h09: { e: "¿Puedo ver la habitación antes?", d: "Kann ich das Zimmer vorher sehen?", s: "Vor dem Buchen vor Ort.", n: "Völlig normal – besonders bei günstigen Unterkünften." },
    h10: { e: "¿A qué hora es el check-out?", d: "Um wie viel Uhr ist der Check-out?", s: "Beim Planen des Abreisetags.", n: "Meist gegen 10–11 Uhr. Später fragen: ¿Puedo salir más tarde?" },
    h11: { e: "¿Puedo cambiar de habitación? Hay mucho ruido.", d: "Kann ich das Zimmer wechseln? Es ist sehr laut.", s: "Bei Problemen mit dem Zimmer.", n: "Höflicher: ¿Podría cambiar de habitación?" },
    h12: { e: "No hay agua caliente en la ducha.", d: "Es gibt kein warmes Wasser in der Dusche.", s: "An der Rezeption melden.", n: "Häufiges Problem – ruhig und freundlich ansprechen." },
    h13: { e: "Algo está roto en el baño.", d: "Etwas ist im Bad kaputt.", s: "Beim Melden eines Defekts.", n: "roto = kaputt, dañado = beschädigt/defekt." },
    h14: { e: "El aire no funciona.", d: "Die Klimaanlage geht nicht.", s: "An der Rezeption.", n: "no funciona = funktioniert nicht – universell einsetzbar." },
    h15: { e: "El wifi no funciona en mi cuarto.", d: "Das WLAN geht nicht in meinem Zimmer.", s: "Bei Internetproblemen.", n: "Vielleicht neu einloggen – nach der contraseña fragen." },
    h16: { e: "La luz no funciona.", d: "Das Licht geht nicht.", s: "Beim Melden.", n: "Glühbirne: el foco / la bombilla." },
    h17: { e: "La habitación es muy ruidosa.", d: "Das Zimmer ist zu laut.", s: "Wenn du nicht schlafen kannst.", n: "Bitte um ein ruhigeres: ¿Tiene una más tranquila?" },
    h18: { e: "¿Lo pueden arreglar hoy?", d: "Können Sie es heute reparieren?", s: "Nach dem Melden eines Defekts.", n: "arreglar = reparieren/in Ordnung bringen." },
    h19: { e: "Necesito otra toalla, por favor.", d: "Ich brauche noch ein Handtuch, bitte.", s: "An der Rezeption.", n: "otra = noch eine/eine weitere." },
    h20: { e: "¿Pueden limpiar la habitación, por favor?", d: "Können Sie das Zimmer sauber machen?", s: "Bei längerem Aufenthalt.", n: "Reinigung: la limpieza." },
    h21: { e: "¿Puedo hacer el check-out más tarde?", d: "Kann ich später auschecken?", s: "Am Abreisetag.", n: "Manchmal gegen Aufpreis möglich – einfach fragen." },
    h22: { e: "¿Puedo dejar mi equipaje aquí hasta la tarde?", d: "Kann ich mein Gepäck hier bis zum Nachmittag lassen?", s: "Nach dem Check-out.", n: "Fast überall kostenlos möglich." },
    h23: { e: "El baño está tapado.", d: "Die Toilette ist verstopft.", s: "Beim Melden an der Rezeption.", n: "tapado = verstopft. Unangenehm, aber wichtig zu sagen." },
    h24: { e: "Tengo mucho calor, ¿puedo prender el aire?", d: "Mir ist sehr warm, kann ich die Klimaanlage anmachen?", s: "Im Zimmer.", n: "Wichtig: Tengo calor (mir ist warm), NICHT Estoy caliente!" },

    // ===================== EINKAUFEN =====================
    c01: { e: "¿Cuánto cuesta esto?", d: "Wie viel kostet das?", s: "Im Laden oder auf dem Markt.", n: "Auch ¿Cuánto vale? oder auf dem Markt ¿A cómo?" },
    c02: { e: "Uff, es muy caro.", d: "Puh, das ist zu teuer.", s: "Beim Handeln auf dem Markt.", n: "Leitet mit einem Lächeln oft das Verhandeln ein." },
    c03: { e: "¿Tiene agua fría?", d: "Haben Sie kaltes Wasser?", s: "Im Laden/Kiosk.", n: "Universelle Frage – das Wort einfach austauschen." },
    c04: { e: "Gracias, solo estoy mirando.", d: "Danke, ich schaue nur.", s: "Wenn dich Verkäufer ansprechen.", n: "Höflich und entspannt – ohne Kaufdruck." },
    c05: { e: "Me llevo esto, gracias.", d: "Ich nehme das, danke.", s: "An der Kasse / beim Stand.", n: "llevarse = mitnehmen/kaufen." },
    c06: { e: "¿Dónde está el mercado?", d: "Wo ist der Markt?", s: "Auf der Suche nach frischen Lebensmitteln.", n: "Märkte sind oft günstiger und authentischer als Supermärkte." },
    c07: { e: "Busco un supermercado cerca.", d: "Ich suche einen Supermarkt in der Nähe.", s: "Beim Selbstversorgen.", n: "Kleiner Laden um die Ecke: la tienda." },
    c08: { e: "Una bolsa, por favor.", d: "Eine Tüte, bitte.", s: "An der Kasse.", n: "Tüten kosten oft extra – ein Stoffbeutel lohnt sich." },
    c09: { e: "¿Hay descuento si llevo dos?", d: "Gibt es Rabatt, wenn ich zwei nehme?", s: "Auf dem Markt oder bei Mengen.", n: "descuento = Rabatt; Mengenrabatt ist oft drin." },
    c10: { e: "¿No tiene algo más barato?", d: "Haben Sie nichts Günstigeres?", s: "Beim Vergleichen.", n: "barato = billig, caro = teuer." },
    c11: { e: "¿Me lo puedo probar?", d: "Kann ich es anprobieren?", s: "Beim Kleiderkauf.", n: "Umkleide: el probador." },
    c12: { e: "¿Qué talla es?", d: "Welche Größe ist das?", s: "Beim Kleiderkauf.", n: "talla = Kleidergröße; Schuhgröße oft número." },
    c13: { e: "¿Dónde está la caja?", d: "Wo ist die Kasse?", s: "Im Laden zum Bezahlen.", n: "caja = Kasse; cajero = Geldautomat (nicht verwechseln)." },
    c14: { e: "¿Está abierto los domingos?", d: "Ist sonntags geöffnet?", s: "Beim Planen von Einkäufen.", n: "abierto = offen, cerrado = geschlossen." },
    c15: { e: "Un kilo de mangos, por favor.", d: "Ein Kilo Mangos, bitte.", s: "Am Obst-/Gemüsestand.", n: "Mengen mit de: un kilo de ..." },
    c16: { e: "Medio kilo de tomates, por favor.", d: "Ein halbes Kilo Tomaten, bitte.", s: "Auf dem Markt.", n: "medio kilo = 500 g." },
    c17: { e: "Un poco más, por favor.", d: "Etwas mehr, bitte.", s: "Beim Abwiegen auf dem Markt.", n: "más = mehr, menos = weniger." },
    c18: { e: "Eso es todo, gracias.", d: "Das ist alles, danke.", s: "Beim Abschließen des Einkaufs.", n: "Auch Nada más (sonst nichts)." },
    c19: { e: "¿Tiene algo más barato?", d: "Haben Sie etwas Günstigeres?", s: "Wenn dir der Preis zu hoch ist.", n: "Freundlicher Einstieg ins Handeln." },
    c20: { e: "Me da dos panes, por favor.", d: "Geben Sie mir zwei Brote, bitte.", s: "Am Tresen / Stand.", n: "Me da ... ist die typische LatAm-Bestellformel." },
    c21: { e: "Quiero este vestido, por favor.", d: "Ich möchte dieses Kleid.", s: "Beim Kleiderkauf.", n: "este = dieses (hier), ese = das (dort)." },
    c22: { e: "¿Lo tiene en otra talla?", d: "Haben Sie es in einer anderen Größe?", s: "Beim Anprobieren.", n: "Größer: más grande; kleiner: más chica/pequeña." },
    c23: { e: "¿Lo tiene en otro color?", d: "Haben Sie es in einer anderen Farbe?", s: "Beim Kleiderkauf.", n: "color = Farbe." },
    c24: { e: "¿Tiene una talla más grande?", d: "Haben Sie eine Nummer größer?", s: "Beim Anprobieren.", n: "chica ist in vielen Ländern üblich für klein (sonst pequeña)." },
    c25: { e: "¿Me lo deja más barato?", d: "Geht beim Preis noch was?", s: "Beim Handeln.", n: "dejar algo más barato = günstiger machen – typische Handelsfloskel." },
    c26: { e: "¿Me hace un descuento?", d: "Machen Sie mir einen Rabatt?", s: "Auf dem Markt.", n: "Mit Charme und Lächeln klappt es eher." },
    c27: { e: "Muy caro, gracias.", d: "Zu teuer, danke.", s: "Wenn du höflich ablehnst.", n: "Oft kommt jetzt ein besseres Angebot – einfach abwarten." },
    c28: { e: "Me llevo dos de esos.", d: "Ich nehme zwei davon.", s: "Am Stand.", n: "de esos = von denen (dort)." },
    c29: { e: "¿Me lo puede mostrar?", d: "Können Sie mir das zeigen?", s: "Wenn etwas hinter der Theke liegt.", n: "mostrar = zeigen." },
    c30: { e: "¿Dónde encuentro el agua?", d: "Wo finde ich Wasser?", s: "Im Supermarkt.", n: "Wort austauschen: ¿Dónde encuentro el pan?" },
    c31: { e: "¿Puedo probar?", d: "Darf ich probieren?", s: "Am Obst-/Käsestand.", n: "probar = kosten UND anprobieren – Kontext klärt es." },
    c32: { e: "¿Me lo puede envolver?", d: "Können Sie es einpacken?", s: "Bei Geschenken.", n: "envolver = (ein)wickeln." },
    c33: { e: "Es para regalo, ¿lo puede envolver?", d: "Es ist ein Geschenk, können Sie es einpacken?", s: "Beim Souvenirkauf.", n: "regalo = Geschenk." },
    c34: { e: "¿Este aguacate está maduro?", d: "Ist diese Avocado reif?", s: "Beim Obstkauf.", n: "maduro = reif, verde = unreif/grün, fresco = frisch." },

    // ===================== GELD =====================
    d01: { e: "¿Cómo puedo pagar?", d: "Wie kann ich bezahlen?", s: "An der Kasse.", n: "Folgefrage: ¿Aceptan tarjeta? (Karten ok?)" },
    d02: { e: "¿Puedo pagar con tarjeta?", d: "Kann ich mit Karte zahlen?", s: "Beim Bezahlen.", n: "Kleine Läden nehmen oft nur efectivo (bar)." },
    d03: { e: "Pago en efectivo.", d: "Ich zahle bar.", s: "Beim Bezahlen.", n: "Bargeld ist in LatAm oft König – immer etwas dabei haben." },
    d04: { e: "¿Aceptan tarjeta?", d: "Akzeptieren Sie Karten?", s: "Vor dem Bestellen/Kaufen.", n: "Gut, vorher zu fragen – nicht überall möglich." },
    d05: { e: "¿Hay un cajero cerca?", d: "Gibt es einen Geldautomaten in der Nähe?", s: "Wenn du Bargeld brauchst.", n: "cajero automático – am sichersten in Banken oder Malls." },
    d06: { e: "¿Me da el vuelto, por favor?", d: "Geben Sie mir das Wechselgeld, bitte?", s: "Nach dem Bezahlen.", n: "vuelto in LatAm, cambio anderswo – beides verständlich." },
    d07: { e: "¿Tiene sencillo? No tengo cambio.", d: "Haben Sie es klein? Ich habe kein Kleingeld.", s: "Beim Bezahlen mit großem Schein.", n: "sencillo = Kleingeld; große Scheine sind oft ein Problem." },
    d08: { e: "¿Me da el recibo, por favor?", d: "Geben Sie mir die Quittung, bitte?", s: "Nach dem Bezahlen.", n: "recibo/boleta = Quittung; factura = formelle Rechnung." },
    d09: { e: "No me queda mucha plata.", d: "Mir bleibt nicht mehr viel Geld.", s: "Im Gespräch über das Budget.", n: "plata ist das alltägliche Wort für Geld in Südamerika." },
    d10: { e: "¿La entrada es gratis?", d: "Ist der Eintritt kostenlos?", s: "Bei Museen, Touren, Events.", n: "gratis = umsonst; manchmal gibt es Gratis-Tage." },
    d11: { e: "¿Dónde puedo cambiar dinero?", d: "Wo kann ich Geld wechseln?", s: "Nach der Ankunft im Land.", n: "Wechselkurs vergleichen – der erste Stand ist selten der beste." },
    d12: { e: "Busco una casa de cambio.", d: "Ich suche eine Wechselstube.", s: "Beim Geldwechseln.", n: "Eine offizielle casa de cambio ist sicherer als Straßenwechsler." },
    d13: { e: "Disculpe, ¿está bien el vuelto?", d: "Stimmt das Wechselgeld so?", s: "Nach dem Bezahlen.", n: "Ruhig nachzählen – freundlich nachfragen ist völlig ok." },

    // ===================== VERKEHR =====================
    v01: { e: "Disculpe, ¿dónde está la estación?", d: "Entschuldigung, wo ist der Bahnhof?", s: "Bei der Orientierung.", n: "Wort austauschen: ¿dónde está el baño / el centro?" },
    v02: { e: "Gire a la derecha en la esquina.", d: "Biegen Sie an der Ecke rechts ab.", s: "Bei Wegbeschreibungen.", n: "izquierda = links, derecha = rechts." },
    v03: { e: "Siga todo recto dos cuadras.", d: "Gehen Sie zwei Blocks geradeaus.", s: "Bei Wegbeschreibungen.", n: "cuadra = Häuserblock, die typische Entfernungseinheit." },
    v04: { e: "¿Cómo llego al centro?", d: "Wie komme ich ins Zentrum?", s: "Bei der Wegsuche.", n: "al = a + el. Zu femininem Ziel: a la plaza." },
    v06: { e: "¿Me puede pedir un taxi?", d: "Können Sie mir ein Taxi rufen?", s: "Im Hostel/Restaurant.", n: "Sicherer als auf der Straße: per App oder vom Personal rufen lassen." },
    v07: { e: "Un boleto a Lima, por favor.", d: "Ein Ticket nach Lima, bitte.", s: "Am Schalter.", n: "boleto/pasaje/billete – je nach Land." },
    v08: { e: "¿Está lejos la estación?", d: "Ist der Bahnhof weit?", s: "Bei der Orientierung.", n: "Busbahnhof: el terminal / la terminal." },
    v09: { e: "¿Cuánto cuesta al aeropuerto?", d: "Wie viel kostet es zum Flughafen?", s: "Beim Taxi vor dem Abflug.", n: "Preis vorher aushandeln – Flughafenfahrten sind oft teurer." },
    v10: { e: "Pare aquí, por favor.", d: "Halten Sie hier, bitte.", s: "Im Taxi/Bus am Ziel.", n: "pare = halten Sie an; déjeme aquí = lassen Sie mich hier." },
    v11: { e: "¿A qué hora sale el próximo?", d: "Wann fährt der nächste?", s: "Am Bahnhof/Busbahnhof.", n: "salir = abfahren, llegar = ankommen." },
    v13: { e: "¿Está lejos de aquí?", d: "Ist es weit von hier?", s: "Bevor du losgehst.", n: "lejos = weit, cerca = nah." },
    v14: { e: "¿Hay un cajero cerca?", d: "Gibt es einen Geldautomaten in der Nähe?", s: "Bei der Suche nach etwas.", n: "cerca de aquí = in der Nähe." },
    v15: { e: "¿Qué tan lejos está la playa?", d: "Wie weit ist der Strand?", s: "Beim Planen.", n: "¿Qué tan ...? = Wie ... – sehr LatAm (Spanien: ¿Cómo de ...?)." },
    v16: { e: "¿Me lo muestra en el mapa?", d: "Können Sie es auf der Karte zeigen?", s: "Wenn die Wegbeschreibung unklar ist.", n: "Einfach das Handy mit der Karte hinhalten." },
    v17: { e: "¿Dónde hay una gasolinera?", d: "Wo gibt es eine Tankstelle?", s: "Beim Mietwagen/Roadtrip.", n: "In manchen Ländern bomba oder grifo (Peru)." },
    v18: { e: "Lleno de gasolina, por favor.", d: "Volltanken, bitte.", s: "An der Tankstelle.", n: "In Chile bencina. Lleno = voll." },
    v19: { e: "Quiero alquilar un auto.", d: "Ich möchte ein Auto mieten.", s: "Bei der Autovermietung.", n: "auto/carro/coche – je nach Land." },
    v20: { e: "¿Dónde me bajo para el centro?", d: "Wo steige ich fürs Zentrum aus?", s: "Im Bus/colectivo.", n: "bajarse = aussteigen, subirse = einsteigen." },
    v21: { e: "Me bajo en la próxima parada.", d: "Ich steige an der nächsten Haltestelle aus.", s: "Im Bus.", n: "parada = Haltestelle." },
    v22: { e: "Lléveme a esta dirección, por favor.", d: "Bringen Sie mich zu dieser Adresse.", s: "Im Taxi – Adresse zeigen.", n: "dirección = Adresse. Am einfachsten auf dem Handy zeigen." },
    v23: { e: "¿Cuánto demora en llegar?", d: "Wie lange dauert es bis dahin?", s: "Im Taxi/Bus.", n: "demorar/tardar = dauern – beide gebräuchlich." },
    v24: { e: "¿Puede poner el taxímetro?", d: "Können Sie das Taxameter einschalten?", s: "Beim Taxieinstieg.", n: "Ohne Taxameter vorher einen Festpreis vereinbaren." },
    v25: { e: "¿Puede esperar aquí un momento?", d: "Können Sie hier kurz warten?", s: "Bei kurzem Stopp mit dem Taxi.", n: "esperar = warten. Wartezeit kostet meist extra." },
    v26: { e: "Me bajo aquí, gracias.", d: "Ich steige hier aus.", s: "Im colectivo/Bus.", n: "Kurz und klar – oft reicht ein lautes aquí." },
    v27: { e: "Más despacio, por favor.", d: "Bitte langsamer fahren.", s: "Im Taxi, wenn es zu schnell wird.", n: "Gilt fürs Fahren und fürs Sprechen gleichermaßen." },

    // ===================== ZEIT =====================
    ti01: { e: "Disculpe, ¿qué hora es?", d: "Entschuldigung, wie spät ist es?", s: "Wenn du die Uhrzeit brauchst.", n: "Antwort meist Son las ... (z. B. Son las tres)." },
    ti02: { e: "¿A qué hora abre el museo?", d: "Um wie viel Uhr öffnet das Museum?", s: "Beim Planen.", n: "abrir = öffnen, cerrar = schließen." },
    ti03: { e: "¿Vamos ahora o más tarde?", d: "Gehen wir jetzt oder später?", s: "Beim Pläne machen.", n: "Achtung: ahorita heißt je nach Land sofort ODER gleich/später." },
    ti04: { e: "¿Qué hacemos hoy?", d: "Was machen wir heute?", s: "Bei der Tagesplanung.", n: "hoy = heute." },
    ti05: { e: "Salgo mañana temprano.", d: "Ich reise morgen früh ab.", s: "Bei Reiseplänen.", n: "mañana = morgen UND Vormittag – Kontext entscheidet." },
    ti06: { e: "Llegué ayer por la noche.", d: "Ich bin gestern Abend angekommen.", s: "Im Smalltalk über die Reise.", n: "ayer = gestern, anteayer = vorgestern." },
    ti07: { e: "El tour es en la mañana.", d: "Die Tour ist am Vormittag.", s: "Bei der Planung.", n: "en la mañana/tarde/noche – die Tageszeiten." },
    ti08: { e: "Me quedo una semana.", d: "Ich bleibe eine Woche.", s: "Bei der Aufenthaltsdauer.", n: "día = Tag, semana = Woche, mes = Monat." },
    ti09: { e: "Mejor salimos temprano.", d: "Wir gehen besser früh los.", s: "Bei der Planung.", n: "temprano = früh, tarde = spät (und Nachmittag)." },
    ti10: { e: "El bus sale el lunes.", d: "Der Bus fährt am Montag.", s: "Bei Reiseplänen.", n: "Wochentage klein und ohne am: el lunes." },
    ti11: { e: "Llego el miércoles.", d: "Ich komme am Mittwoch an.", s: "Bei Verabredungen.", n: "miércoles hat einen Akzent: mi-ÉR-co-les." },
    ti12: { e: "El sábado hay fiesta en el hostel.", d: "Am Samstag ist Party im Hostel.", s: "Beim Wochenende planen.", n: "Am Wochenende: el fin de semana." },

    // ===================== SMALLTALK =====================
    s01: { e: "¡Hola! ¿Cómo estás?", d: "Hallo! Wie geht's?", s: "Bei jeder Begrüßung.", n: "Lockerer: ¿Qué tal? oder ¿Qué más? (Kolumbien)." },
    s02: { e: "Bien, gracias, ¿y tú?", d: "Gut, danke, und dir?", s: "Als Antwort auf ¿Cómo estás?", n: "Das ¿y tú? zurückzugeben gehört dazu." },
    s03: { e: "Mucho gusto, soy Marcel.", d: "Freut mich, ich bin Marcel.", s: "Beim Kennenlernen.", n: "Antwort oft El gusto es mío (die Freude ist meinerseits)." },
    s04: { e: "¿De dónde eres?", d: "Woher kommst du?", s: "Beim Kennenlernen.", n: "Klassischer Gesprächsöffner im Hostel." },
    s05: { e: "Soy de Alemania, de Múnich.", d: "Ich komme aus Deutschland, aus München.", s: "Wenn du nach deiner Herkunft gefragt wirst.", n: "Soy de + Land/Stadt." },
    s06: { e: "Estoy de vacaciones por tres meses.", d: "Ich bin für drei Monate im Urlaub.", s: "Im Smalltalk über die Reise.", n: "de vacaciones = im Urlaub." },
    s07: { e: "Solo estoy de paso un par de días.", d: "Ich bin nur für ein paar Tage auf der Durchreise.", s: "Wenn du kurz bleibst.", n: "de paso = auf der Durchreise." },
    s08: { e: "¡Qué chévere tu viaje!", d: "Wie cool deine Reise!", s: "Als Begeisterung im Gespräch.", n: "chévere (Kolumbien), bacán (Chile/Peru), padre (Mexiko)." },
    s09: { e: "No hay problema, tranquilo.", d: "Kein Problem, alles entspannt.", s: "Wenn sich jemand entschuldigt.", n: "tranquilo/a = keine Sorge – sehr gebräuchlich." },
    s10: { e: "Claro, con gusto.", d: "Klar, gerne.", s: "Zur Zustimmung im Gespräch.", n: "Claro que sí verstärkt: aber klar!" },
    s11: { e: "Quizás mañana, depende.", d: "Vielleicht morgen, kommt drauf an.", s: "Bei unsicheren Plänen.", n: "quizás/tal vez = vielleicht; depende = kommt drauf an." },
    s12: { e: "Hasta luego, ¡que te vaya bien!", d: "Bis später, mach's gut!", s: "Beim Verabschieden.", n: "que te vaya bien = alles Gute." },
    s13: { e: "Hasta mañana, descansa.", d: "Bis morgen, ruh dich aus.", s: "Beim Abschied am Abend.", n: "descansa = ruh dich aus." },
    s14: { e: "¡Que tengas un buen día!", d: "Schönen Tag noch!", s: "Beim Verabschieden.", n: "Antwort: Igualmente (gleichfalls)." },
    s15: { e: "Con permiso.", d: "Entschuldigung (darf ich durch).", s: "Beim Durchgehen in der Menge.", n: "Permiso zum Durchkommen, Disculpe zum Ansprechen." },
    s16: { e: "Muchas gracias por todo.", d: "Vielen Dank für alles.", s: "Beim Verabschieden, z. B. nach dem Hostelaufenthalt.", n: "Herzlich und passend zum Abschied." },
    s17: { e: "¡Mil gracias, muy amable!", d: "Tausend Dank, sehr nett!", s: "Bei besonderer Hilfe.", n: "Verstärktes Danke – kommt von Herzen rüber." },
    s18: { e: "Muy amable de tu parte.", d: "Das ist sehr nett von dir.", s: "Nach einer Gefälligkeit.", n: "Förmlich: de su parte." },
    s19: { e: "Gracias por la invitación.", d: "Danke für die Einladung.", s: "Nach Essen/Drink, zu dem du eingeladen warst.", n: "invitación = Einladung (auch wenn jemand spendiert)." },
    s20: { e: "Te lo agradezco mucho.", d: "Ich weiß das sehr zu schätzen.", s: "Bei echter Dankbarkeit.", n: "Etwas wärmer und persönlicher als nur gracias." },
    s21: { e: "Fue un placer conocerte.", d: "Es war mir ein Vergnügen, dich kennenzulernen.", s: "Beim Abschied von neuen Bekannten.", n: "Ein schöner, herzlicher Abschiedssatz." },
    s22: { e: "Estoy muy contento con todo.", d: "Ich bin sehr zufrieden mit allem.", s: "Als positives Feedback.", n: "Frauen: contenta." },
    s23: { e: "Todo estuvo perfecto, gracias.", d: "Alles war perfekt, danke.", s: "Beim Auschecken/Verabschieden.", n: "Gutes Lob fürs Personal." },
    s24: { e: "La próxima te invito yo.", d: "Das nächste Mal lade ich dich ein.", s: "In geselliger Runde.", n: "Eine nette Geste, die Sympathie schafft." },

    // ===================== ALLTAG =====================
    a01: { e: "¿Cómo se dice esto en español?", d: "Wie sagt man das auf Spanisch?", s: "Beim Lernen unterwegs.", n: "Super, um neue Wörter direkt von Locals zu lernen." },
    a02: { e: "¿Qué significa esta palabra?", d: "Was bedeutet dieses Wort?", s: "Wenn du ein Wort nicht kennst.", n: "palabra = Wort. Zeig einfach drauf." },
    a03: { e: "¿Me lo puede escribir, por favor?", d: "Können Sie es mir aufschreiben?", s: "Bei Adressen, Preisen, Namen.", n: "Hilft enorm bei Zahlen und Eigennamen." },
    a04: { e: "Disculpe mi español, estoy aprendiendo.", d: "Entschuldige mein Spanisch, ich lerne noch.", s: "Wenn du ins Stocken gerätst.", n: "Bricht das Eis – die meisten helfen dann geduldig." },
    a05: { e: "¿Cuál es la contraseña del wifi?", d: "Wie ist das WLAN-Passwort?", s: "Im Café, Hostel, Restaurant.", n: "contraseña/clave = Passwort." },
    a06: { e: "¿Dónde puedo comprar un chip?", d: "Wo kann ich eine SIM-Karte kaufen?", s: "Nach der Ankunft für mobiles Internet.", n: "chip = SIM-Karte in LatAm (Spanien: tarjeta SIM)." },
    a07: { e: "Quiero recargar saldo, por favor.", d: "Ich möchte Guthaben aufladen.", s: "Im Handy-Laden oder Kiosk.", n: "saldo = Guthaben; recarga = die Aufladung." },
    a08: { e: "¿El plan incluye datos móviles?", d: "Enthält der Tarif mobile Daten?", s: "Beim SIM-Kauf.", n: "datos = Datenvolumen; oft als Gigas verkauft." },
    a09: { e: "¿Hay una lavandería cerca?", d: "Gibt es eine Wäscherei in der Nähe?", s: "Wenn die Wäsche dreckig ist.", n: "Oft nach Gewicht (por kilo) – günstig und schnell." },
    a10: { e: "Busco un departamento por un mes.", d: "Ich suche eine Wohnung für einen Monat.", s: "Bei längeren Aufenthalten.", n: "departamento (LatAm) / piso (Spanien) / apartamento." },
    a11: { e: "¿Cuánto es el alquiler al mes?", d: "Wie hoch ist die Miete pro Monat?", s: "Bei der Wohnungssuche.", n: "alquiler/arriendo/renta – je nach Land." },
    a12: { e: "¿Dónde está el banco más cercano?", d: "Wo ist die nächste Bank?", s: "Für Geldgeschäfte.", n: "Geldautomaten in der Bank sind am sichersten." },
    a13: { e: "Quiero enviar una postal desde el correo.", d: "Ich möchte eine Postkarte von der Post schicken.", s: "Beim Postamt.", n: "correo = Post; Postkarte = postal." },
    a14: { e: "Necesito ir a la embajada alemana.", d: "Ich muss zur deutschen Botschaft.", s: "Bei verlorenem Pass oder Notfällen.", n: "embajada = Botschaft; consulado = Konsulat." },
    a15: { e: "¿Dónde puedo comprar agua por aquí?", d: "Wo kann ich hier Wasser kaufen?", s: "Unterwegs bei Durst.", n: "Kleiner Laden: la tienda / el kiosco." },

    // ===================== SÄTZE =====================
    f01: { e: "Quisiera un café, por favor.", d: "Ich hätte gern einen Kaffee, bitte.", s: "Beim Bestellen/Wünschen.", n: "Quisiera ist höflicher als Quiero." },
    f02: { e: "Me gustaría ver el menú.", d: "Ich hätte gern die Karte.", s: "Bei höflichen Wünschen.", n: "Me gustaría + Infinitiv = ich würde gern ..." },
    f03: { e: "Quiero ese, el de allá.", d: "Ich möchte das da, das dort.", s: "Beim Zeigen auf etwas.", n: "ese = das (dort), aquel = das (weiter weg)." },
    f04: { e: "Ese de atrás, por favor.", d: "Das da hinten, bitte.", s: "An der Theke/Vitrine.", n: "atrás = hinten." },
    f05: { e: "Ese de abajo, por favor.", d: "Das da unten, bitte.", s: "Beim Zeigen im Regal.", n: "abajo = unten." },
    f06: { e: "Ese de arriba, el segundo.", d: "Das da oben, das zweite.", s: "Beim Zeigen im Regal.", n: "arriba = oben." },
    f07: { e: "No este, ese.", d: "Nicht dieses, das da.", s: "Beim Auswählen.", n: "este (hier bei mir) vs. ese (dort bei dir)." },
    f08: { e: "Uno más, por favor.", d: "Noch eins, bitte.", s: "Für Nachschub.", n: "Anpassen: una más bei femininem Wort." },
    f09: { e: "Mejor uno menos.", d: "Lieber eins weniger.", s: "Beim Korrigieren der Menge.", n: "menos = weniger." },
    f10: { e: "Un poco más, por favor.", d: "Ein bisschen mehr, bitte.", s: "Beim Abwiegen/Einschenken.", n: "un poco = ein bisschen." },
    f11: { e: "Solo un poquito, gracias.", d: "Nur ein bisschen, danke.", s: "Bei kleinen Mengen.", n: "-ito macht es kleiner und freundlicher: poquito." },
    f12: { e: "Así está bien, gracias.", d: "Das reicht so, danke.", s: "Beim Einschenken/Abwiegen.", n: "Signalisiert: genau richtig, stopp." },
    f13: { e: "Sí, así.", d: "Ja, genau so.", s: "Zur Bestätigung.", n: "Kurz und klar – oft mit einer Geste." },
    f14: { e: "¿Puedo pasar?", d: "Darf ich durch?", s: "Um Erlaubnis bitten.", n: "¿Puedo + Infinitiv? = Darf/Kann ich ...?" },
    f15: { e: "¿Puede ayudarme?", d: "Können Sie mir helfen?", s: "Um etwas bitten (förmlich).", n: "¿Puede + Infinitiv? = Können Sie ...?" },
    f16: { e: "Necesito ayuda, por favor.", d: "Ich brauche Hilfe, bitte.", s: "Bei einem Bedürfnis.", n: "Necesito + Nomen/Infinitiv." },
    f17: { e: "¿Hay baño aquí?", d: "Gibt es hier eine Toilette?", s: "Auf der Suche nach etwas.", n: "hay = es gibt – eines der nützlichsten Wörter." },
    f18: { e: "¿Dónde hay un cajero?", d: "Wo gibt es einen Geldautomaten?", s: "Bei der Suche.", n: "¿Dónde hay ...? = Wo gibt es ...?" },
    f19: { e: "Estoy buscando la estación de bus.", d: "Ich suche den Busbahnhof.", s: "Bei der Orientierung.", n: "buscar = suchen." },
    f20: { e: "¿Qué es esto?", d: "Was ist das?", s: "Bei Unbekanntem.", n: "Neugier öffnet Gespräche – oft mit einer Kostprobe." },
    f21: { e: "¿Cómo se llama esto en español?", d: "Wie nennt man das?", s: "Beim Vokabeln lernen.", n: "Tolle Frage, um Wörter von Locals zu lernen." },
    f22: { e: "Un momento, por favor.", d: "Einen Moment, bitte.", s: "Wenn du kurz Zeit brauchst.", n: "Auch Ya voy = ich komme gleich." },
    f23: { e: "¿Me permite? Con permiso.", d: "Darf ich mal vorbei?", s: "Beim Durchkommen.", n: "Con permiso ist die Standardformel zum Durchgehen." },
    f24: { e: "Disculpe, una pregunta.", d: "Entschuldigung, eine Frage.", s: "Bevor du jemanden etwas fragst.", n: "Höflicher Einstieg, der fast immer gut ankommt." },
    f25: { e: "¿Cómo? No le entendí.", d: "Wie bitte? Ich habe Sie nicht verstanden.", s: "Wenn du nachfragen musst.", n: "¿Cómo? ist höflich; ¿Mande? ist sehr mexikanisch." },
    f26: { e: "¿Puede repetir, por favor?", d: "Können Sie das wiederholen?", s: "Wenn du etwas verpasst hast.", n: "Kombi mit Más despacio wirkt Wunder." },
    f27: { e: "Solo estoy mirando, gracias.", d: "Ich möchte nur schauen, danke.", s: "Wenn Verkäufer aufdringlich werden.", n: "Höflich und ohne Druck." },
    f28: { e: "Un poco más, por favor.", d: "Etwas mehr, bitte.", s: "Beim Dosieren.", n: "más = mehr, menos = weniger." },
    f29: { e: "Quiero uno como este.", d: "Ich möchte eins wie dieses.", s: "Beim Auswählen mit Vergleich.", n: "como = wie. Zeig auf das Vorbild." },
    f30: { e: "No, gracias, estoy bien.", d: "Nein danke, alles gut.", s: "Beim höflichen Annehmen/Ablehnen.", n: "Sí, claro (ja gern) / No, gracias (nein danke)." },

    // ===================== BEHÖRDEN =====================
    g01: { e: "Aquí está mi pasaporte.", d: "Hier ist mein Reisepass.", s: "Bei Einreise/Kontrolle.", n: "Den pasaporte immer griffbereit halten." },
    g02: { e: "¿Necesito visa para entrar?", d: "Brauche ich ein Visum zur Einreise?", s: "Vor/bei der Einreise.", n: "visa (LatAm) / visado (Spanien)." },
    g03: { e: "¿Me puede dar el sello, por favor?", d: "Können Sie mir den Stempel geben?", s: "An der Grenze.", n: "Prüfe, dass der Einreisestempel (sello) wirklich drin ist." },
    g04: { e: "¿Cuánto falta para la frontera?", d: "Wie weit ist es noch bis zur Grenze?", s: "Bei der Anreise zur Grenze.", n: "Grenzübergänge können dauern – Geduld mitbringen." },
    g05: { e: "¿Dónde está la aduana?", d: "Wo ist der Zoll?", s: "Bei der Einreise.", n: "aduana = Zoll; migración = Passkontrolle." },
    g06: { e: "Soy turista, vengo de vacaciones.", d: "Ich bin Tourist, ich komme als Urlauber.", s: "Bei der Einreisebefragung.", n: "Eine einfache, klare Antwort auf den Reisezweck." },
    g07: { e: "Aquí está mi pasaporte y el formulario.", d: "Hier ist mein Reisepass und das Formular.", s: "Am Schalter der Passkontrolle.", n: "Ruhig und freundlich – für die Beamten ist es Routine." },
    g08: { e: "Me quedo quince días.", d: "Ich bleibe 15 Tage.", s: "Auf die Frage nach der Aufenthaltsdauer.", n: "Zahl einsetzen: Me quedo + Zahl + días." },
    g09: { e: "El motivo del viaje es turismo.", d: "Der Grund der Reise ist Tourismus.", s: "Bei der Einreisebefragung.", n: "motivo = Grund/Zweck. Die Standardantwort." },
    g10: { e: "¿Cuánto tiempo puedo quedarme?", d: "Wie lange darf ich bleiben?", s: "An der Grenze.", n: "Oft 90 Tage für Touristen – aber das Land prüfen." },
    g11: { e: "No tengo nada que declarar.", d: "Ich habe nichts zu verzollen.", s: "Am Zoll.", n: "Der Standardsatz beim grünen Ausgang." },
    g12: { e: "¿Dónde firmo?", d: "Wo muss ich unterschreiben?", s: "Beim Ausfüllen von Formularen.", n: "firmar = unterschreiben; firma = Unterschrift." },
    g13: { e: "¿Me da otro formulario, por favor?", d: "Geben Sie mir ein weiteres Formular, bitte?", s: "Bei der Einreise.", n: "Oft schon im Flugzeug/Bus ausfüllbar." },
    g14: { e: "¿Hay un cajero en la frontera?", d: "Gibt es an der Grenze einen Geldautomaten?", s: "Wenn du Bargeld für die Einreise brauchst.", n: "An Grenzen oft schlechter Kurs – nur wenig wechseln." },
    g15: { e: "El cajero se tragó mi tarjeta.", d: "Der Automat hat meine Karte einbehalten.", s: "Am Geldautomaten – Notfall.", n: "Sofort die Bank kontaktieren; tagsüber an Bankautomaten weniger riskant." },
    g16: { e: "Mi tarjeta no funciona en este cajero.", d: "Meine Karte funktioniert an diesem Automaten nicht.", s: "Beim Abheben.", n: "Einen anderen Automaten oder eine Bank probieren." },
    g17: { e: "El cajero no entrega efectivo.", d: "Der Automat gibt kein Geld aus.", s: "Beim Abheben.", n: "efectivo = Bargeld; den Beleg aufheben." },
    g18: { e: "Creo que bloquearon mi tarjeta.", d: "Ich glaube, meine Karte wurde gesperrt.", s: "Wenn nichts mehr geht.", n: "Die Reise vorher der Bank melden, damit das nicht passiert." },
    g19: { e: "Tengo que llamar a mi banco.", d: "Ich muss meine Bank anrufen.", s: "Bei Kartenproblemen.", n: "Die Notfallnummer der Bank separat notieren." },
    g20: { e: "¿Cuál es la comisión por retiro?", d: "Wie hoch ist die Abhebegebühr?", s: "Am Geldautomaten.", n: "comisión = Gebühr; manche Automaten sind deutlich teurer." },

    // ===================== NOTFALL =====================
    n01: { e: "Es una emergencia, por favor ayúdeme.", d: "Es ist ein Notfall, bitte helfen Sie mir.", s: "In einer ernsten Situation.", n: "emergencia macht sofort klar, dass es dringend ist." },
    n02: { e: "Me siento mal, creo que es la comida.", d: "Mir geht es schlecht, ich glaube, es war das Essen.", s: "Bei Übelkeit – im Hostel oder unterwegs.", n: "Sehr häufig auf Reisen. Ergänzen: Necesito descansar (ich muss mich ausruhen)." },
    n03: { e: "Me duele la cabeza. ¿Tiene algo?", d: "Mir tut der Kopf weh. Haben Sie etwas?", s: "In der Apotheke oder im Hostel.", n: "Struktur Me duele + Körperteil: Me duele la espalda, me duele la garganta." },
    n04: { e: "Me duele el estómago desde ayer.", d: "Mir tut der Bauch seit gestern weh.", s: "Beim Arzt oder in der Apotheke.", n: "Magen-Darm ist der Klassiker – sag, seit wann (desde ayer)." },
    n05: { e: "Tengo fiebre y escalofríos.", d: "Ich habe Fieber und Schüttelfrost.", s: "Bei Krankheit – Apotheke oder Arzt.", n: "fiebre = Fieber; bei hohem Fieber besser zum médico." },
    n06: { e: "Soy alérgico a la penicilina.", d: "Ich bin allergisch gegen Penizillin.", s: "Beim Arzt – sehr wichtig.", n: "Frauen: alérgica. Die konkrete Sache nennen (penicilina, maní, polen)." },
    n07: { e: "Lléveme al hospital, por favor.", d: "Bringen Sie mich ins Krankenhaus, bitte.", s: "Im Taxi bei einem Notfall.", n: "hospital = Krankenhaus; clínica oft privat und schneller." },
    n08: { e: "¡Llame a una ambulancia, rápido!", d: "Rufen Sie einen Krankenwagen, schnell!", s: "Bei einem medizinischen Notfall.", n: "ambulancia = Krankenwagen; in vielen Ländern über die 911." },
    n09: { e: "Necesito medicamentos para el dolor.", d: "Ich brauche Medikamente gegen die Schmerzen.", s: "In der Apotheke.", n: "para el dolor = gegen die Schmerzen; Rezept heißt receta." },
    n10: { e: "Me robaron el celular en la calle.", d: "Man hat mir auf der Straße das Handy gestohlen.", s: "Nach einem Diebstahl – Polizei/Hostel.", n: "Für die Versicherung brauchst du eine Anzeige: una denuncia en la policía." },
    n12: { e: "Perdí mi pasaporte. ¿Qué hago?", d: "Ich habe meinen Reisepass verloren. Was tun?", s: "Bei verlorenem Pass.", n: "Sofort zur embajada (Botschaft) – sie hilft beim Ersatz." },
    n13: { e: "Perdí mi celular, ¿lo puedo llamar?", d: "Ich habe mein Handy verloren, kann ich es anrufen?", s: "Im Hostel, Bus oder Restaurant.", n: "celular = Handy in LatAm; vielleicht hat es jemand gefunden." },
    n14: { e: "Por favor, ¿puede ayudarme? Es urgente.", d: "Bitte, können Sie mir helfen? Es ist dringend.", s: "In jeder Notlage, in der du Hilfe brauchst.", n: "Es urgente unterstreicht die Dringlichkeit." },

    // ===================== BUSREISE =====================
    r01: { e: "Un boleto a Cartagena, por favor.", d: "Ein Ticket nach Cartagena, bitte.", s: "Am Schalter im Busterminal.", n: "boleto/pasaje – das Ziel einsetzen." },
    r02: { e: "Solo ida, por favor.", d: "Nur Hinfahrt, bitte.", s: "Beim Ticketkauf.", n: "ida = hin, ida y vuelta = hin und zurück." },
    r03: { e: "¿A qué hora sale el próximo bus?", d: "Wann fährt der nächste Bus?", s: "Am Terminal.", n: "próximo = nächster; salir = abfahren." },
    r04: { e: "¿Es directo o tiene paradas?", d: "Ist das ein Direktbus oder hält er?", s: "Beim Ticketkauf.", n: "directo = ohne Umsteigen." },
    r05: { e: "Prefiero el bus nocturno.", d: "Ich nehme lieber den Nachtbus.", s: "Beim Planen langer Strecken.", n: "Spart eine Hostel-Nacht; warm anziehen – oft eiskalte Klimaanlage." },
    r06: { e: "¿Para el bus en Salento?", d: "Hält der Bus in Salento?", s: "Beim Ticketkauf/Einsteigen.", n: "parar = (an)halten." },
    r07: { e: "¿Dónde está mi asiento?", d: "Wo ist mein Sitzplatz?", s: "Beim Einsteigen.", n: "asiento = Sitzplatz; die Nummer steht auf dem Ticket." },
    r08: { e: "¿Está libre este asiento?", d: "Ist dieser Platz frei?", s: "Im Bus.", n: "libre = frei, ocupado = besetzt." },
    r09: { e: "¿Cuánto dura el viaje?", d: "Wie lange dauert die Fahrt?", s: "Vor der Abfahrt.", n: "durar = dauern; Strecken sind oft länger als gedacht." },
    r10: { e: "¿Dónde dejo mi equipaje?", d: "Wo gebe ich mein Gepäck auf?", s: "Beim Einsteigen in den Fernbus.", n: "Die Marke (ticket) fürs aufgegebene Gepäck aufheben." },
    r11: { e: "¿Me avisa cuando lleguemos?", d: "Sagen Sie mir Bescheid, wenn wir da sind?", s: "Im Bus, wenn du das Ziel nicht kennst.", n: "avisar = Bescheid geben; sehr hilfreich auf unbekannten Strecken." },
    r12: { e: "¿Está lejos el terminal?", d: "Ist der Busbahnhof weit?", s: "Bei der Anreise.", n: "el terminal / la terminal – beide Formen kommen vor." },
    r13: { e: "¿Hay baño en el bus?", d: "Gibt es eine Toilette im Bus?", s: "Vor langen Fahrten.", n: "Bei Nachtbussen meist ja – Papier selbst dabei haben." },
    r14: { e: "¿Cuántas paradas hay?", d: "Wie viele Stopps gibt es?", s: "Vor der Fahrt.", n: "parada = Halt/Stopp." },
    r15: { e: "¿Para a comer en el camino?", d: "Hält er unterwegs zum Essen an?", s: "Bei langen Fahrten.", n: "parar a + Infinitiv = anhalten, um etwas zu tun: para a comer." },
    r16: { e: "¿Me puede llevar hasta el pueblo?", d: "Können Sie mich bis zum Dorf mitnehmen?", s: "Beim Trampen (mit Vorsicht).", n: "llevar = mitnehmen/bringen; nur in sicheren Situationen." },
    r17: { e: "¿Hasta dónde va?", d: "Bis wohin fahren Sie?", s: "Beim colectivo/Sammeltaxi.", n: "Klärt, ob die Fahrt zu deinem Ziel passt." },
    r18: { e: "¿La combi pasa por la playa?", d: "Fährt der Minibus am Strand vorbei?", s: "Beim Nahverkehr.", n: "combi/colectivo/micro/buseta – das lokale Sammeltaxi, günstig." },
    r19: { e: "Pare en la esquina, por favor.", d: "Halten Sie an der Ecke.", s: "Im colectivo/Taxi.", n: "esquina = Straßenecke – ein beliebter Haltepunkt." },
    r20: { e: "Perdí mi bus, ¿hay otro hoy?", d: "Ich habe meinen Bus verpasst, gibt es heute noch einen?", s: "Wenn du zu spät am Terminal bist.", n: "perder el bus = den Bus verpassen; oft fährt bald der nächste." },

    // ===================== KLEIDUNG & SCHMUCK =====================
    kj01: { e: "¿Dónde puedo comprar ropa barata?", d: "Wo kann ich günstige Kleidung kaufen?", s: "Auf dem Markt oder im Einkaufsviertel.", n: "ropa = Kleidung, immer Singular (kein las ropas)." },
    kj02: { e: "Busco una camiseta de algodón.", d: "Ich suche ein T-Shirt aus Baumwolle.", s: "Beim Klamottenkauf.", n: "In Mexiko playera, sonst camiseta; algodón = Baumwolle." },
    kj03: { e: "¿Tiene esta camisa en azul?", d: "Haben Sie dieses Hemd in Blau?", s: "Im Bekleidungsgeschäft.", n: "camisa = Hemd, camiseta = T-Shirt – nicht verwechseln." },
    kj04: { e: "¿Me puedo probar este pantalón?", d: "Kann ich diese Hose anprobieren?", s: "Beim Hosenkauf.", n: "pantalón meist Singular für eine Hose; Umkleide: el probador." },
    kj05: { e: "¿Cuánto cuestan estos jeans?", d: "Wie viel kosten diese Jeans?", s: "Beim Einkaufen.", n: "jeans wird überall verstanden; formell pantalón de mezclilla (Mexiko)." },
    kj06: { e: "Hace calor, busco un short.", d: "Es ist heiß, ich suche eine kurze Hose.", s: "In warmen Regionen oder am Strand.", n: "short ist gängig; auch pantalones cortos." },
    kj07: { e: "¿Tiene esta falda más corta?", d: "Haben Sie diesen Rock kürzer?", s: "Beim Kleiderkauf.", n: "falda = Rock; más corta = kürzer." },
    kj08: { e: "Me gusta este vestido, ¿qué tallas hay?", d: "Mir gefällt dieses Kleid, welche Größen gibt es?", s: "Beim Kleiderkauf.", n: "vestido = Kleid; talla = Größe." },
    kj09: { e: "Necesito una chaqueta para la noche.", d: "Ich brauche eine Jacke für die Nacht.", s: "Abends oder in kühleren Höhen.", n: "In Mexiko chamarra; im Andenhochland werden Nächte kalt." },
    kj10: { e: "En la montaña hace frío, llevo un suéter.", d: "In den Bergen ist es kalt, ich nehme einen Pullover.", s: "Vor einem Ausflug ins Hochland.", n: "suéter aus dem Englischen, überall verständlich." },
    kj11: { e: "¿Necesito un abrigo en Patagonia?", d: "Brauche ich einen Mantel in Patagonien?", s: "Bei der Reiseplanung in kalte Regionen.", n: "abrigo = dicker Mantel." },
    kj12: { e: "¿Dónde venden calcetines?", d: "Wo verkaufen sie Socken?", s: "Beim Nachkaufen unterwegs.", n: "calcetines = Socken; in manchen Ländern medias." },
    kj13: { e: "Necesito comprar ropa interior.", d: "Ich muss Unterwäsche kaufen.", s: "Beim Nachkaufen.", n: "ropa interior = Unterwäsche (Sammelbegriff)." },
    kj14: { e: "¿Tiene estos zapatos en el número 42?", d: "Haben Sie diese Schuhe in Größe 42?", s: "Beim Schuhkauf.", n: "Schuhgröße = número (nicht talla)." },
    kj15: { e: "Busco unas sandalias cómodas.", d: "Ich suche bequeme Sandalen.", s: "Für warme Regionen.", n: "cómodas = bequem." },
    kj16: { e: "Para la playa solo necesito chanclas.", d: "Für den Strand brauche ich nur Flip-Flops.", s: "Am Strand oder im Hostel-Bad.", n: "chanclas = Flip-Flops, praktisch auch für Gemeinschaftsduschen." },
    kj17: { e: "Necesito un sombrero para el sol.", d: "Ich brauche einen Hut gegen die Sonne.", s: "In sonnigen Regionen.", n: "sombrero = (Sonnen-)Hut mit Krempe." },
    kj18: { e: "En la montaña llevo un gorro.", d: "In den Bergen trage ich eine Mütze.", s: "Im kalten Hochland.", n: "gorro = Mütze; sombrero eher mit Krempe." },
    kj19: { e: "Se me rompieron los lentes de sol.", d: "Meine Sonnenbrille ist kaputtgegangen.", s: "Beim Nachkaufen.", n: "In LatAm oft lentes de sol; in Spanien gafas de sol." },
    kj20: { e: "¿Tiene un cinturón de cuero?", d: "Haben Sie einen Ledergürtel?", s: "Auf dem Kunsthandwerksmarkt.", n: "cuero = Leder; cinturón = Gürtel." },
    kj21: { e: "Compré una bufanda de alpaca.", d: "Ich habe einen Alpaka-Schal gekauft.", s: "Im Andenland als Souvenir.", n: "Alpaka-Textilien sind in Peru und Bolivien typisch." },
    kj22: { e: "Para el volcán necesito guantes.", d: "Für den Vulkan brauche ich Handschuhe.", s: "Vor Touren in große Höhen.", n: "guantes = Handschuhe." },
    kj23: { e: "¿Dónde compro un traje de baño?", d: "Wo kaufe ich einen Badeanzug oder eine Badehose?", s: "Vor dem Strand- oder Pooltag.", n: "traje de baño gilt für beides; auch bañador." },
    kj24: { e: "Estas joyas son artesanales.", d: "Dieser Schmuck ist handgemacht.", s: "Auf dem Kunsthandwerksmarkt.", n: "joyas = echter Schmuck, bisutería = Modeschmuck." },
    kj25: { e: "Me gustan estos aretes de plata.", d: "Mir gefallen diese Silberohrringe.", s: "Beim Schmuckkauf.", n: "In LatAm aretes; in Spanien pendientes." },
    kj26: { e: "¿Cuánto cuesta este collar?", d: "Wie viel kostet diese Halskette?", s: "Auf dem Markt.", n: "collar = Halskette." },
    kj27: { e: "¿La cadena es de plata de verdad?", d: "Ist die Kette aus echtem Silber?", s: "Beim Schmuckkauf – Qualität prüfen.", n: "de plata de verdad = aus echtem Silber." },
    kj28: { e: "Me llevo esta pulsera, es bonita.", d: "Ich nehme dieses Armband, es ist schön.", s: "Als Souvenir.", n: "pulsera = Armband." },
    kj29: { e: "¿Tiene este anillo en otra medida?", d: "Haben Sie diesen Ring in einer anderen Größe?", s: "Beim Ringkauf.", n: "Ringgröße = medida/talla; anillo = Ring." },
    kj30: { e: "Compré una tobillera en la playa.", d: "Ich habe eine Fußkette am Strand gekauft.", s: "In Strandorten beliebt.", n: "tobillera = Fußkettchen (von tobillo, Knöchel)." },
    kj31: { e: "Se me paró el reloj.", d: "Meine Uhr ist stehengeblieben.", s: "Beim Uhrmacher oder auf dem Markt.", n: "reloj = Uhr (Armband- und Wanduhr)." },
    kj32: { e: "Este broche es de artesanía local.", d: "Diese Brosche ist lokales Kunsthandwerk.", s: "Auf dem Souvenirmarkt.", n: "broche = Brosche/Anstecker." },
    kj33: { e: "¿Es de plata o de oro?", d: "Ist das aus Silber oder aus Gold?", s: "Beim Schmuckkauf.", n: "plata = Silber (und umgangssprachlich Geld!), oro = Gold." },
    kj34: { e: "¿Qué talla es esta camisa?", d: "Welche Größe hat dieses Hemd?", s: "Beim Kleiderkauf.", n: "talla = Kleidergröße; Schuhe: número." },
    kj35: { e: "Me gusta. ¿Puedo probármelo?", d: "Es gefällt mir. Kann ich es anprobieren?", s: "Im Bekleidungsgeschäft.", n: "Umkleide: el probador; -melo = es mir." },
    kj36: { e: "Me queda chico. ¿Lo tiene en otra talla?", d: "Es ist mir zu klein. Haben Sie es in einer anderen Größe?", s: "Nach dem Anprobieren.", n: "me queda chico/grande = es ist mir zu klein/groß." },
    kj37: { e: "No me queda, es demasiado grande.", d: "Es passt mir nicht, es ist zu groß.", s: "Nach dem Anprobieren.", n: "demasiado = zu (sehr); kleiner: ¿más pequeño?" },

    // ===================== WEGBESCHREIBUNG =====================
    dir01: { e: "Dobla a la derecha en la esquina.", d: "Biege an der Ecke nach rechts ab.", s: "Wenn dir jemand den Weg beschreibt.", n: "derecha = rechts; nicht mit derecho (geradeaus) verwechseln!" },
    dir02: { e: "La farmacia está a la izquierda.", d: "Die Apotheke ist auf der linken Seite.", s: "Beim Suchen eines Ladens auf der Straße.", n: "a la izquierda = links / auf der linken Seite." },
    dir03: { e: "Sigue derecho hasta la plaza.", d: "Geh geradeaus bis zum Platz.", s: "Wenn der Weg ohne Abbiegen weitergeht.", n: "In LatAm hört man fast immer 'derecho', seltener 'recto'." },
    dir04: { e: "El cajero está en la esquina.", d: "Der Geldautomat ist an der Ecke.", s: "Als Orientierungspunkt beim Suchen.", n: "esquina = Straßenecke; 'a la vuelta de la esquina' = gleich um die Ecke." },
    dir05: { e: "Queda a tres cuadras de aquí.", d: "Es ist drei Häuserblocks von hier entfernt.", s: "Wenn dir die Entfernung in Blocks genannt wird.", n: "In ganz LatAm zählt man in cuadras, nicht in Metern." },
    dir06: { e: "¿En qué calle está el hostal?", d: "In welcher Straße ist das Hostel?", s: "Wenn du eine konkrete Adresse suchst.", n: "calle = Straße; größer/breiter: avenida." },
    dir07: { e: "El museo está sobre la avenida principal.", d: "Das Museum liegt an der Hauptstraße.", s: "Bei großen, breiten Straßen im Zentrum.", n: "Adressen kürzen die avenida oft als 'Av.' ab." },
    dir08: { e: "Tranquilo, está muy cerca.", d: "Keine Sorge, es ist ganz nah.", s: "Wenn das Ziel nur ein paar Schritte entfernt ist.", n: "cerca = nah; Gegenteil: lejos." },
    dir09: { e: "Uy, eso queda muy lejos, mejor toma un taxi.", d: "Oje, das ist sehr weit, nimm besser ein Taxi.", s: "Wenn das Ziel zu weit zum Laufen ist.", n: "lejos = weit; bei langen Strecken lohnt das colectivo oder Taxi." },
    dir10: { e: "Baja aquí, por favor.", d: "Steig bitte hier aus.", s: "Im Taxi oder colectivo, wenn du aussteigen willst.", n: "aquí = hier; 'acá' ist in vielen Ländern noch gebräuchlicher." },
    dir11: { e: "El baño está allí, al fondo.", d: "Die Toilette ist dort, ganz hinten.", s: "Wenn dir etwas in der Ferne gezeigt wird.", n: "allí/allá = dort; 'al fondo' = ganz hinten." },
    dir12: { e: "El hostal está enfrente de la iglesia.", d: "Das Hostel ist gegenüber der Kirche.", s: "Wenn ein Gebäude als Orientierung dient.", n: "enfrente de = gegenüber; nicht mit 'al lado de' (daneben) verwechseln." },
    dir13: { e: "La parada está al lado del mercado.", d: "Die Haltestelle ist neben dem Markt.", s: "Beim Beschreiben benachbarter Orte.", n: "al lado de = direkt daneben." },
    dir14: { e: "El cajero está detrás del banco.", d: "Der Geldautomat ist hinter der Bank.", s: "Wenn das Ziel nicht direkt sichtbar ist.", n: "detrás de = hinter; Gegenteil: delante de / enfrente de." },
    dir15: { e: "La tienda está entre el banco y la farmacia.", d: "Der Laden ist zwischen der Bank und der Apotheke.", s: "Zur genauen Lage zwischen zwei Punkten.", n: "entre A y B = zwischen A und B." },
    dir16: { e: "¿Me puede escribir la dirección?", d: "Können Sie mir die Adresse aufschreiben?", s: "Damit du sie dem Taxifahrer zeigen kannst.", n: "dirección = Adresse (und auch Richtung!); aufschreiben hilft enorm." },
    dir17: { e: "¿Me lo marca en el mapa?", d: "Markieren Sie es mir auf der Karte?", s: "Wenn Worte nicht reichen, zeig es auf der Karte.", n: "el mapa ist trotz -a maskulin: 'el mapa'." },
    dir18: { e: "Disculpe, ¿dónde está la escuela?", d: "Entschuldigung, wo ist die Schule?", s: "Die Standardfrage nach einem festen Ort.", n: "está (von estar) für Orte; bei Gebäuden auch 'queda'." },
    dir19: { e: "Perdón, ¿dónde queda el hostal Sol?", d: "Verzeihung, wo liegt das Hostel Sol?", s: "Beim Fragen nach deiner Unterkunft.", n: "'queda' für Lage ist in LatAm sehr verbreitet – wie 'wo liegt …'." },
    dir20: { e: "Perdón, ¿cómo llego al centro?", d: "Verzeihung, wie komme ich ins Zentrum?", s: "Wenn du den Weg zum Stadtzentrum brauchst.", n: "llegar a = ankommen bei; 'al' = a + el." },
    dir21: { e: "¿Puede decirme cómo llegar a la terminal?", d: "Können Sie mir sagen, wie ich zum Busbahnhof komme?", s: "Höfliche, vollständige Frage nach dem Weg.", n: "'¿Puede decirme …?' klingt besonders höflich." },
    dir22: { e: "Oiga, ¿dónde hay un cajero por acá?", d: "Hallo, wo gibt es hier in der Nähe einen Geldautomaten?", s: "Wenn du dringend Bargeld brauchst.", n: "'¿Dónde hay …?' fragt allgemein 'wo gibt es …?'." },
    dir23: { e: "¿Está lejos o cerca de aquí?", d: "Ist es weit weg oder nah von hier?", s: "Um zu entscheiden, ob du läufst oder fährst.", n: "Gleich nachfragen spart dir lange Umwege zu Fuß." },
    dir24: { e: "¿A cuántas cuadras está el mercado?", d: "Wie viele Blocks ist der Markt entfernt?", s: "Wenn die Antwort 'cerca' dir zu ungenau ist.", n: "Antworten kommen meist als 'a dos cuadras' o.ä." },
    dir25: { e: "¿Cuál es la dirección exacta?", d: "Wie lautet die genaue Adresse?", s: "Vor einer Taxifahrt oder zum Eintippen ins Handy.", n: "'¿Cuál es …?' fragt nach einer konkreten Angabe." },
    dir26: { e: "No entiendo bien. ¿Me lo muestra en el mapa?", d: "Ich verstehe nicht ganz. Zeigen Sie es mir auf der Karte?", s: "Wenn die Wegbeschreibung zu kompliziert wird.", n: "Karte zeigen lassen ist der sicherste Weg, sich nicht zu verlaufen." },
    dir27: { e: "Disculpe, ¿hay un banco por aquí?", d: "Entschuldigung, gibt es hier in der Nähe eine Bank?", s: "Auf der Suche nach Bank, Apotheke oder Supermarkt.", n: "'por aquí' = hier in der Gegend / in der Nähe." },
    dir28: { e: "Dobla a la derecha en el semáforo.", d: "Biege an der Ampel nach rechts ab.", s: "Typische Anweisung beim Wegbeschreiben.", n: "doblar = abbiegen; semáforo = Ampel." },
    dir29: { e: "Dobla a la izquierda después del parque.", d: "Biege nach dem Park nach links ab.", s: "Wenn ein Orientierungspunkt den Abbiegepunkt markiert.", n: "después de = nach; antes de = vor." },
    dir30: { e: "Sigue derecho dos cuadras más.", d: "Geh noch zwei Blocks geradeaus.", s: "Wenn der Weg eine Weile gerade weitergeht.", n: "'… dos cuadras más' = noch zwei Blocks weiter." },
    dir31: { e: "Cruza la calle con cuidado.", d: "Überquere die Straße vorsichtig.", s: "Wenn das Ziel auf der anderen Straßenseite liegt.", n: "cruzar = überqueren; 'con cuidado' = vorsichtig." },
    dir32: { e: "Camina dos cuadras y ahí está.", d: "Geh zwei Blocks und dort ist es.", s: "Kurze, klare Wegbeschreibung zu Fuß.", n: "caminar = (zu Fuß) gehen; 'ahí' = dort." },
    dir33: { e: "Toma la primera calle a la derecha.", d: "Nimm die erste Straße rechts.", s: "Beim genauen Abzählen der Abzweigungen.", n: "primera/segunda calle = erste/zweite Straße." },
    dir34: { e: "El restaurante está en la esquina, no tiene pierde.", d: "Das Restaurant ist an der Ecke, du kannst es nicht verfehlen.", s: "Beruhigende Wegauskunft.", n: "'no tiene pierde' = man kann es nicht verfehlen (sehr LatAm)." },
    dir35: { e: "La panadería está al lado del mercado.", d: "Die Bäckerei ist neben dem Markt.", s: "Lage über einen bekannten Nachbarort erklären.", n: "al lado del = a + el lado de el (Verschmelzung del)." },
    dir36: { e: "El hotel está enfrente de la iglesia.", d: "Das Hotel ist gegenüber der Kirche.", s: "Kirchen sind oft der beste Orientierungspunkt.", n: "Plaza und iglesia sind in jeder Stadt verlässliche Landmarken." },
    dir37: { e: "El cajero está entre el banco y la farmacia.", d: "Der Geldautomat ist zwischen der Bank und der Apotheke.", s: "Genaue Lage zwischen zwei Geschäften.", n: "entre … y … grenzt den Ort eindeutig ein." },
    dir38: { e: "Queda a dos cuadras de aquí, nomás.", d: "Es ist nur zwei Blocks von hier entfernt.", s: "Wenn das Ziel zum Glück ganz nah ist.", n: "'nomás' (= nur) ist ein typisches LatAm-Füllwort." },
    dir39: { e: "Camina hacia la plaza, hacia el norte.", d: "Geh in Richtung Platz, nach Norden.", s: "Wenn dir eine grobe Richtung statt eines Ziels genannt wird.", n: "hacia = in Richtung; gibt die Richtung an, nicht das genaue Ziel." },
    dir40: { e: "Sigue derecho hasta el semáforo.", d: "Geh geradeaus bis zur Ampel.", s: "Wenn ein Punkt das Ende der Strecke markiert.", n: "hasta = bis (zu); markiert den Endpunkt des Wegstücks." },
    dir41: { e: "El banco está diagonal al supermercado.", d: "Die Bank ist schräg gegenüber dem Supermarkt.", s: "Für eine Lage über Eck an einer Kreuzung.", n: "diagonal a = schräg/diagonal gegenüber." },
    dir42: { e: "El hostal está junto a la iglesia.", d: "Das Hostel ist direkt bei der Kirche.", s: "Für etwas unmittelbar daneben.", n: "junto a / próximo a = direkt bei / nahe bei." },
    dir43: { e: "Dobla a la derecha antes del puente.", d: "Bieg vor der Brücke rechts ab.", s: "Wenn der Abbiegepunkt vor einer Landmarke liegt.", n: "antes de = vor; del = de + el." },
    dir44: { e: "La farmacia está después del cruce.", d: "Die Apotheke ist nach der Kreuzung.", s: "Wenn das Ziel hinter einem Punkt liegt.", n: "después de = nach (örtlich wie zeitlich)." },
    dir45: { e: "El cajero está a la vuelta de la esquina.", d: "Der Geldautomat ist gleich um die Ecke.", s: "Wenn etwas ganz nah, nur um die Ecke ist.", n: "a la vuelta de la esquina = gleich um die Ecke." },
    dir46: { e: "Tranquilo, está a un paso de aquí.", d: "Keine Sorge, es ist nur einen Katzensprung entfernt.", s: "Wenn das Ziel sehr nah ist.", n: "a un paso = ganz nah, wörtlich 'einen Schritt' entfernt." },
    dir47: { e: "El mar queda hacia el norte.", d: "Das Meer liegt im Norden.", s: "Bei grober Orientierung nach Himmelsrichtung.", n: "Norte, Sur, Este, Oeste – die vier Himmelsrichtungen." },
    dir48: { e: "El centro está más al sur.", d: "Das Zentrum ist weiter südlich.", s: "Grobe Orientierung in der Stadt.", n: "'más al sur' = weiter südlich." },
    dir49: { e: "El sol sale por el este.", d: "Die Sonne geht im Osten auf.", s: "Eselsbrücke zur Orientierung.", n: "este = Osten; nicht mit 'este' (= dieser) verwechseln." },
    dir50: { e: "La playa está al oeste.", d: "Der Strand liegt im Westen.", s: "Orientierung Richtung Küste.", n: "oeste = Westen; dort geht die Sonne unter." },
    dir51: { e: "Dobla a la derecha en el semáforo.", d: "Bieg an der Ampel rechts ab.", s: "Ampeln sind klare Orientierungspunkte.", n: "semáforo = Ampel; wird oft als Wegmarke genannt." },
    dir52: { e: "Da la vuelta en la rotonda y sigue derecho.", d: "Fahr im Kreisverkehr herum und dann geradeaus.", s: "Beim Beschreiben eines Kreisverkehrs.", n: "rotonda; je nach Land auch glorieta (Mexiko) oder redondel." },
    dir53: { e: "Para en el próximo cruce, por favor.", d: "Halt bitte an der nächsten Kreuzung.", s: "Im Taxi oder colectivo zum Aussteigen.", n: "cruce = Kreuzung; auch intersección." },
    dir54: { e: "Cruza el puente y sigue derecho.", d: "Überquere die Brücke und geh geradeaus.", s: "Wenn der Weg über eine Brücke führt.", n: "puente = Brücke; eine gut sichtbare Landmarke." },
    dir55: { e: "La parada está al lado del mercado.", d: "Die Haltestelle ist neben dem Markt.", s: "Auf der Suche nach Bus oder colectivo.", n: "parada = Haltestelle; Busbahnhof: terminal." },
    dir56: { e: "Gira a la derecha en la esquina.", d: "Bieg an der Ecke rechts ab.", s: "Variante zu 'doblar' beim Wegbeschreiben.", n: "girar = abbiegen; in Mexiko auch 'voltear'." },
    dir57: { e: "Sube por esta calle hasta la plaza.", d: "Geh diese Straße hinauf bis zum Platz.", s: "Bei ansteigenden Straßen (Hügel).", n: "subir = hinaufgehen; in hügeligen Städten ständig gebraucht." },
    dir58: { e: "Baja por esta calle dos cuadras.", d: "Geh diese Straße zwei Blocks hinunter.", s: "Bei abfallenden Straßen.", n: "bajar = hinuntergehen; Gegenteil von subir." },
    dir59: { e: "Te pasaste, devuélvete una cuadra.", d: "Du bist zu weit, geh einen Block zurück.", s: "Wenn du zu weit gelaufen bist.", n: "devuélvete / regrésate = geh zurück (sehr LatAm)." },
    dir60: { e: "Pasa el semáforo y está a la izquierda.", d: "Geh an der Ampel vorbei, dann ist es links.", s: "Wenn das Ziel kurz hinter einem Punkt liegt.", n: "pasar = vorbeigehen / passieren." },
    dir61: { e: "Disculpe, ¿por dónde se va al mercado?", d: "Entschuldigung, wo geht's zum Markt lang?", s: "Allgemeine Frage nach der Richtung.", n: "'¿Por dónde se va a…?' = wie kommt man zu…?" },
    dir62: { e: "Perdón, ¿voy bien para la plaza?", d: "Verzeihung, bin ich auf dem richtigen Weg zur Plaza?", s: "Unterwegs kurz rückversichern.", n: "'¿Voy bien para…?' = bin ich richtig Richtung…?" },
    dir63: { e: "¿Dónde hay una tienda de ropa por aquí?", d: "Wo gibt es hier in der Nähe ein Bekleidungsgeschäft?", s: "Auf der Suche nach einem bestimmten Laden.", n: "'¿Dónde hay…?' fragt allgemein nach 'wo gibt es…?'." },
    dir64: { e: "¿Se puede ir caminando o mejor tomo un taxi?", d: "Kann man zu Fuß gehen oder nehme ich besser ein Taxi?", s: "Um den Aufwand abzuschätzen.", n: "ir caminando / a pie = zu Fuß gehen." },
    dir65: { e: "¿Cuánto se tarda a pie hasta el centro?", d: "Wie lange dauert es zu Fuß bis ins Zentrum?", s: "Die Gehzeit erfragen.", n: "'a pie' = zu Fuß; 'tardar' = (Zeit) brauchen." },
  };

  window.SC = window.SC || {};
  window.SC.contextData = C;
})();
