/*
 * dialogos.js  (SC.dialogos) – Daten für die Gesprächs-Simulationen (Diálogos).
 * REINE DATEN, additiv – die Wörterbasis bleibt unangetastet.
 *
 * Idee: echte Reisesituationen Zug für Zug durchspielen. Die Gegenseite (npc)
 * wird angezeigt und – wenn der Browser TTS kann – vorgelesen; der Nutzer
 * antwortet je nach Zug per Multiple-Choice (kind:"mc") oder tippt eine
 * Schlüssel-Replik frei (kind:"type", großzügig per matcher.normalize geprüft).
 *
 * Die Dialoge sind bewusst lang gehalten (7–9 Repliken pro Runde), damit sich
 * ein echtes Gespräch entfaltet statt nur dreier Stichworte.
 *
 * Struktur:
 *   DIALOGOS_SCENARIOS = Menü: { id, title, icon, lvl, intro }
 *   DIALOGOS           = die Dialoge: { id, cat(=scenario.id), title, lvl, turns[] }
 *     turn npc  : { who:"npc",  es, de }
 *     turn mc   : { who:"user", kind:"mc",   de, solEs, options:[{es, ok}] }
 *     turn type : { who:"user", kind:"type", de, solEs, accept:[…] }
 *       de    = Handlungsanweisung („(sag, dass du einchecken willst)")
 *       solEs = die Musterantwort (erscheint in der Verlaufsspur)
 *       accept= zusätzlich akzeptierte (normalisierte) Eingaben neben solEs
 */
(function () {
  "use strict";

  const DIALOGOS_SCENARIOS = [
    { id: "hotel",      title: "Hotel-Check-in",  icon: "🛎️", lvl: 1, intro: "An der Rezeption einchecken." },
    { id: "restaurante",title: "Im Restaurant",   icon: "🍽️", lvl: 1, intro: "Bestellen, fragen, zahlen." },
    { id: "bus",        title: "Busticket kaufen", icon: "🚌", lvl: 1, intro: "Am Schalter ein Ticket lösen." },
    { id: "taxi",       title: "Taxifahrt",       icon: "🚕", lvl: 1, intro: "Ziel nennen und Preis klären." },
    { id: "mercado",    title: "Auf dem Markt",   icon: "🛍️", lvl: 2, intro: "Fragen und freundlich feilschen." },
    { id: "farmacia",   title: "In der Apotheke", icon: "💊", lvl: 2, intro: "Beschwerden schildern, Hilfe holen." },
    { id: "hostel",     title: "Hostel-Smalltalk", icon: "🛏️", lvl: 2, intro: "Andere Reisende kennenlernen." },
    { id: "frontera",   title: "An der Grenze",   icon: "🛂", lvl: 2, intro: "Ein- und Ausreise-Fragen." },
    { id: "emergencia", title: "Notfall",         icon: "🆘", lvl: 2, intro: "Schnell um Hilfe bitten." },
    { id: "calle",      title: "Nach dem Weg fragen", icon: "🧭", lvl: 1, intro: "Sich auf der Straße orientieren." },
  ];

  const DIALOGOS = [
    {
      id: "hotel01", cat: "hotel", title: "An der Rezeption", lvl: 1,
      turns: [
        { who: "npc", es: "¡Buenas! Bienvenido al Hotel Sol Andino. ¿En qué le puedo ayudar?", de: "Hallo! Willkommen im Hotel Sol Andino. Wie kann ich Ihnen helfen?" },
        { who: "user", kind: "mc", de: "(sag, dass du einchecken möchtest)", solEs: "Quisiera hacer el check-in, por favor.",
          options: [
            { es: "Quisiera hacer el check-in, por favor.", ok: true },
            { es: "La cuenta, por favor.", ok: false },
            { es: "¿Dónde está el baño?", ok: false },
          ] },
        { who: "npc", es: "Claro que sí. ¿A nombre de quién está la reserva?", de: "Aber natürlich. Auf welchen Namen läuft die Reservierung?" },
        { who: "user", kind: "type", de: "(antworte: auf den Namen Marco)", solEs: "A nombre de Marco.",
          accept: ["a nombre de marco", "marco", "es marco", "me llamo marco", "esta a nombre de marco"] },
        { who: "npc", es: "Perfecto, aquí la tengo. Una habitación doble por tres noches, ¿verdad?", de: "Perfekt, hier habe ich sie. Ein Doppelzimmer für drei Nächte, richtig?" },
        { who: "user", kind: "mc", de: "(bestätige: ja, genau, drei Nächte)", solEs: "Sí, exacto, tres noches.",
          options: [
            { es: "Sí, exacto, tres noches.", ok: true },
            { es: "No, solo una noche.", ok: false },
            { es: "No tengo reserva.", ok: false },
          ] },
        { who: "npc", es: "Muy bien. ¿Me permite su pasaporte, por favor?", de: "Sehr gut. Dürfte ich bitte Ihren Reisepass haben?" },
        { who: "user", kind: "type", de: "(sag, hier bitte, und reich ihn rüber)", solEs: "Sí, aquí tiene.",
          accept: ["aqui tiene", "si aqui tiene", "aqui esta", "tenga", "aqui lo tiene"] },
        { who: "npc", es: "Gracias. ¿Prefiere una habitación con vista a la calle o una más tranquila?", de: "Danke. Möchten Sie lieber ein Zimmer zur Straße oder ein ruhigeres?" },
        { who: "user", kind: "mc", de: "(sag, du hättest gern ein ruhiges Zimmer)", solEs: "Una tranquila, por favor.",
          options: [
            { es: "Una tranquila, por favor.", ok: true },
            { es: "Con vista a la calle, mejor.", ok: false },
            { es: "Me da igual el precio.", ok: false },
          ] },
        { who: "npc", es: "Entendido. Le doy la habitación doscientos cuatro, en el segundo piso.", de: "Verstanden. Ich gebe Ihnen Zimmer zweihundertvier im zweiten Stock." },
        { who: "user", kind: "type", de: "(frag, um wie viel Uhr es Frühstück gibt)", solEs: "¿A qué hora es el desayuno?",
          accept: ["a que hora es el desayuno", "cuando es el desayuno", "a que hora el desayuno", "a que hora hay desayuno"] },
        { who: "npc", es: "De siete a diez de la mañana, en el comedor de la planta baja.", de: "Von sieben bis zehn Uhr morgens, im Speisesaal im Erdgeschoss." },
        { who: "user", kind: "mc", de: "(frag, ob es WLAN im Zimmer gibt)", solEs: "¿Hay wifi en la habitación?",
          options: [
            { es: "¿Hay wifi en la habitación?", ok: true },
            { es: "¿Tienen piscina?", ok: false },
            { es: "¿Puedo pagar mañana?", ok: false },
          ] },
        { who: "npc", es: "Sí, la clave está en el reverso de su tarjeta-llave. Aquí tiene.", de: "Ja, das Passwort steht auf der Rückseite Ihrer Schlüsselkarte. Hier bitte." },
        { who: "user", kind: "type", de: "(bedanke dich freundlich)", solEs: "Muchas gracias, muy amable.",
          accept: ["muchas gracias muy amable", "muchas gracias", "gracias", "mil gracias", "muy amable, gracias"] },
        { who: "npc", es: "A usted. Cualquier cosa, estamos en recepción las veinticuatro horas. ¡Que descanse!", de: "Gern. Bei Fragen: Die Rezeption ist rund um die Uhr besetzt. Gute Erholung!" },
      ],
    },
    {
      id: "restaurante01", cat: "restaurante", title: "Bestellen & zahlen", lvl: 1,
      turns: [
        { who: "npc", es: "Buenas tardes, bienvenidos. ¿Mesa para cuántas personas?", de: "Guten Tag, willkommen. Ein Tisch für wie viele Personen?" },
        { who: "user", kind: "mc", de: "(sag: ein Tisch für zwei)", solEs: "Una mesa para dos, por favor.",
          options: [
            { es: "Una mesa para dos, por favor.", ok: true },
            { es: "La cuenta, por favor.", ok: false },
            { es: "Estoy lleno, gracias.", ok: false },
          ] },
        { who: "npc", es: "Perfecto, síganme. ¿Esta mesa junto a la ventana les parece bien?", de: "Perfekt, folgen Sie mir. Ist dieser Tisch am Fenster in Ordnung?" },
        { who: "user", kind: "mc", de: "(sag, der Tisch ist super)", solEs: "Sí, está perfecta, gracias.",
          options: [
            { es: "Sí, está perfecta, gracias.", ok: true },
            { es: "No, prefiero afuera en la calle.", ok: false },
            { es: "No hablo español.", ok: false },
          ] },
        { who: "npc", es: "Aquí tienen la carta. ¿Algo para tomar mientras deciden?", de: "Hier ist die Speisekarte. Etwas zu trinken, während Sie sich entscheiden?" },
        { who: "user", kind: "type", de: "(bestelle zwei Wasser)", solEs: "Dos aguas, por favor.",
          accept: ["dos aguas", "dos aguas por favor", "dos botellas de agua", "queremos dos aguas", "dos aguas porfa"] },
        { who: "npc", es: "Enseguida se las traigo. ¿Ya saben qué van a pedir de comer?", de: "Bringe ich gleich. Wissen Sie schon, was Sie essen möchten?" },
        { who: "user", kind: "type", de: "(frag, was das Tagesgericht ist)", solEs: "¿Cuál es el plato del día?",
          accept: ["cual es el plato del dia", "que es el plato del dia", "que hay de plato del dia", "cual es el menu del dia"] },
        { who: "npc", es: "Hoy tenemos lomo saltado con arroz y papas. Está muy rico.", de: "Heute gibt es Lomo Saltado mit Reis und Kartoffeln. Es ist sehr lecker." },
        { who: "user", kind: "mc", de: "(bestelle das Tagesgericht zweimal)", solEs: "Entonces dos platos del día, por favor.",
          options: [
            { es: "Entonces dos platos del día, por favor.", ok: true },
            { es: "No, gracias, solo la cuenta.", ok: false },
            { es: "¿Tienen mesa para dos?", ok: false },
          ] },
        { who: "npc", es: "Excelente elección. ¿Desean algo más, un postre quizás?", de: "Ausgezeichnete Wahl. Möchten Sie noch etwas, vielleicht ein Dessert?" },
        { who: "user", kind: "mc", de: "(lehne höflich ab – erst mal nichts weiter)", solEs: "No, así está bien, gracias.",
          options: [
            { es: "No, así está bien, gracias.", ok: true },
            { es: "Sí, la cuenta, por favor.", ok: false },
            { es: "No tengo hambre.", ok: false },
          ] },
        { who: "npc", es: "Muy bien. … (más tarde) ¿Qué tal estuvo todo? ¿Les gustó?", de: "Sehr gut. … (später) Wie war alles? Hat es geschmeckt?" },
        { who: "user", kind: "type", de: "(sag, es war sehr lecker)", solEs: "Estuvo todo muy rico.",
          accept: ["estuvo todo muy rico", "muy rico", "estuvo muy rico", "todo muy rico", "estaba muy rico"] },
        { who: "npc", es: "Me alegra mucho. ¿Les traigo algo más o ya la cuenta?", de: "Das freut mich sehr. Bringe ich Ihnen noch etwas, oder schon die Rechnung?" },
        { who: "user", kind: "type", de: "(bitte um die Rechnung)", solEs: "La cuenta, por favor.",
          accept: ["la cuenta por favor", "la cuenta", "me trae la cuenta", "nos trae la cuenta", "la cuenta porfa"] },
        { who: "npc", es: "Claro, ya se la traigo. ¿Van a pagar en efectivo o con tarjeta?", de: "Klar, ich bringe sie. Zahlen Sie bar oder mit Karte?" },
        { who: "user", kind: "mc", de: "(sag: mit Karte)", solEs: "Con tarjeta, por favor.",
          options: [
            { es: "Con tarjeta, por favor.", ok: true },
            { es: "En efectivo.", ok: false },
            { es: "Pago mañana.", ok: false },
          ] },
        { who: "npc", es: "Perfecto. Muchas gracias por su visita. ¡Vuelvan pronto!", de: "Perfekt. Vielen Dank für Ihren Besuch. Kommen Sie bald wieder!" },
      ],
    },
    {
      id: "bus01", cat: "bus", title: "Am Busschalter", lvl: 1,
      turns: [
        { who: "npc", es: "¡Siguiente, por favor! ¿Para dónde va?", de: "Der Nächste bitte! Wohin möchten Sie?" },
        { who: "user", kind: "type", de: "(sag, du willst ein Ticket nach Cusco)", solEs: "Quiero un boleto para Cusco.",
          accept: ["quiero un boleto para cusco", "un boleto para cusco", "para cusco", "un pasaje para cusco", "quiero un pasaje para cusco"] },
        { who: "npc", es: "Muy bien. ¿Para hoy o para mañana?", de: "Sehr gut. Für heute oder für morgen?" },
        { who: "user", kind: "mc", de: "(sag: für morgen früh)", solEs: "Para mañana en la mañana.",
          options: [
            { es: "Para mañana en la mañana.", ok: true },
            { es: "Para hoy en la noche.", ok: false },
            { es: "No sé, gracias.", ok: false },
          ] },
        { who: "npc", es: "Tenemos uno a las ocho y otro a las diez. ¿Cuál prefiere?", de: "Wir haben einen um acht und einen um zehn. Welchen möchten Sie?" },
        { who: "user", kind: "mc", de: "(nimm den um acht)", solEs: "El de las ocho, por favor.",
          options: [
            { es: "El de las ocho, por favor.", ok: true },
            { es: "El de medianoche.", ok: false },
            { es: "Ninguno, gracias.", ok: false },
          ] },
        { who: "npc", es: "¿Asiento normal o cama? El cama es más cómodo para el viaje largo.", de: "Normaler Sitz oder Liegesitz? Der Liegesitz ist bequemer für die lange Fahrt." },
        { who: "user", kind: "type", de: "(sag, du willst einen normalen Sitz)", solEs: "Asiento normal, por favor.",
          accept: ["asiento normal", "asiento normal por favor", "un asiento normal", "normal por favor", "el normal"] },
        { who: "npc", es: "Perfecto. ¿Prefiere ventana o pasillo?", de: "Perfekt. Möchten Sie lieber Fenster oder Gang?" },
        { who: "user", kind: "mc", de: "(sag: Fenster)", solEs: "Ventana, por favor.",
          options: [
            { es: "Ventana, por favor.", ok: true },
            { es: "Pasillo, mejor.", ok: false },
            { es: "Me da igual el horario.", ok: false },
          ] },
        { who: "npc", es: "Listo. ¿Me da su nombre completo, por favor?", de: "Geht klar. Geben Sie mir bitte Ihren vollständigen Namen?" },
        { who: "user", kind: "type", de: "(nenne deinen Namen: Marco Pérez)", solEs: "Marco Pérez.",
          accept: ["marco perez", "me llamo marco perez", "soy marco perez", "mi nombre es marco perez"] },
        { who: "npc", es: "Gracias. Son cuarenta soles. ¿Cómo va a pagar?", de: "Danke. Das macht vierzig Soles. Wie möchten Sie zahlen?" },
        { who: "user", kind: "mc", de: "(sag: bar)", solEs: "En efectivo.",
          options: [
            { es: "En efectivo.", ok: true },
            { es: "¿Puedo pagar en Cusco?", ok: false },
            { es: "No tengo dinero.", ok: false },
          ] },
        { who: "npc", es: "Aquí tiene su boleto y su vuelto. El bus sale del andén número cinco.", de: "Hier ist Ihr Ticket und Ihr Wechselgeld. Der Bus fährt von Bahnsteig fünf." },
        { who: "user", kind: "type", de: "(frag nach, wie lange die Fahrt dauert)", solEs: "¿Cuánto dura el viaje?",
          accept: ["cuanto dura el viaje", "cuanto demora el viaje", "cuanto tiempo dura el viaje", "cuanto se demora", "cuanto dura"] },
        { who: "npc", es: "Unas seis horas, llega a las dos de la tarde. ¡Buen viaje!", de: "Etwa sechs Stunden, Ankunft um zwei Uhr nachmittags. Gute Reise!" },
      ],
    },
    {
      id: "taxi01", cat: "taxi", title: "Ins Zentrum", lvl: 1,
      turns: [
        { who: "npc", es: "¡Buenas! ¿A dónde lo llevo?", de: "Hallo! Wohin darf ich Sie fahren?" },
        { who: "user", kind: "type", de: "(sag, du willst zum Stadtzentrum)", solEs: "Al centro, por favor.",
          accept: ["al centro", "al centro por favor", "quiero ir al centro", "voy al centro", "al centro porfa"] },
        { who: "npc", es: "Claro. ¿Conoce la dirección exacta o lo dejo en la plaza?", de: "Klar. Kennen Sie die genaue Adresse oder setze ich Sie an der Plaza ab?" },
        { who: "user", kind: "mc", de: "(sag, an der Plaza ist gut)", solEs: "Déjeme en la plaza, está bien.",
          options: [
            { es: "Déjeme en la plaza, está bien.", ok: true },
            { es: "No sé dónde estoy.", ok: false },
            { es: "¿Puedo pagar mañana?", ok: false },
          ] },
        { who: "npc", es: "Perfecto. ¿Tiene apuro o vamos con calma?", de: "Perfekt. Haben Sie es eilig oder fahren wir gemütlich?" },
        { who: "user", kind: "mc", de: "(frag vorher, wie viel die Fahrt kostet)", solEs: "¿Cuánto cuesta hasta allá?",
          options: [
            { es: "¿Cuánto cuesta hasta allá?", ok: true },
            { es: "¿Tiene cambio de cien?", ok: false },
            { es: "¿Es muy lejos su casa?", ok: false },
          ] },
        { who: "npc", es: "Unos quince soles, más o menos. ¿Le parece bien?", de: "So um die fünfzehn Soles, mehr oder weniger. Geht das in Ordnung?" },
        { who: "user", kind: "mc", de: "(stimm zu und bitte ihn loszufahren)", solEs: "Está bien, vamos.",
          options: [
            { es: "Está bien, vamos.", ok: true },
            { es: "No, gracias, camino.", ok: false },
            { es: "Es muy barato.", ok: false },
          ] },
        { who: "npc", es: "(en el camino) ¿Es la primera vez que visita la ciudad?", de: "(unterwegs) Sind Sie zum ersten Mal in der Stadt?" },
        { who: "user", kind: "type", de: "(sag: ja, du bist Tourist)", solEs: "Sí, soy turista.",
          accept: ["si soy turista", "soy turista", "vengo de turista", "si de vacaciones", "si estoy de vacaciones"] },
        { who: "npc", es: "¡Qué bueno! ¿De qué país viene, si no es indiscreción?", de: "Wie schön! Aus welchem Land kommen Sie, wenn ich fragen darf?" },
        { who: "user", kind: "type", de: "(sag, du kommst aus Deutschland)", solEs: "Vengo de Alemania.",
          accept: ["vengo de alemania", "soy de alemania", "de alemania", "soy aleman", "yo soy de alemania"] },
        { who: "npc", es: "¡Alemania, qué lejos! ¿Le pongo un poco de música o prefiere tranquilo?", de: "Deutschland, so weit weg! Soll ich etwas Musik anmachen oder lieber ruhig?" },
        { who: "user", kind: "mc", de: "(sag, etwas Musik wäre schön)", solEs: "Un poco de música, por favor.",
          options: [
            { es: "Un poco de música, por favor.", ok: true },
            { es: "No, en silencio, gracias.", ok: false },
            { es: "Más rápido, por favor.", ok: false },
          ] },
        { who: "npc", es: "¡Listo! Ya casi llegamos. Aquí es la plaza, son quince soles.", de: "Geht klar! Wir sind fast da. Hier ist die Plaza, das macht fünfzehn Soles." },
        { who: "user", kind: "type", de: "(sag, hier bitte – und bedanke dich)", solEs: "Aquí tiene, gracias.",
          accept: ["aqui tiene gracias", "aqui tiene", "aqui esta", "tenga gracias", "aqui tiene esta bien"] },
        { who: "npc", es: "Muchas gracias. ¡Que disfrute la ciudad y buen viaje!", de: "Vielen Dank. Genießen Sie die Stadt und gute Reise!" },
      ],
    },
    {
      id: "mercado01", cat: "mercado", title: "Obst & Feilschen", lvl: 2,
      turns: [
        { who: "npc", es: "¡Pásele, casero! Tengo fruta fresquita. ¿Qué va a llevar?", de: "Kommen Sie ran, mein Lieber! Ich hab ganz frisches Obst. Was darf's sein?" },
        { who: "user", kind: "mc", de: "(frag, wie viel das Kilo Mangos kostet)", solEs: "¿A cuánto está el kilo de mango?",
          options: [
            { es: "¿A cuánto está el kilo de mango?", ok: true },
            { es: "¿Dónde está la salida?", ok: false },
            { es: "¿Me regala una bolsa?", ok: false },
          ] },
        { who: "npc", es: "A cinco soles el kilo, bien dulces, recién traídos.", de: "Fünf Soles das Kilo, schön süß, frisch geliefert." },
        { who: "user", kind: "type", de: "(sag, das sei ein bisschen teuer)", solEs: "Está un poco caro.",
          accept: ["esta un poco caro", "esta caro", "un poco caro", "esta medio caro", "me parece caro"] },
        { who: "npc", es: "¿Caro? ¡Pero si es la mejor fruta del mercado, casero!", de: "Teuer? Aber das ist doch das beste Obst auf dem Markt, mein Lieber!" },
        { who: "user", kind: "type", de: "(feilsche freundlich: ob er es etwas billiger macht)", solEs: "¿Me lo deja más barato?",
          accept: ["me lo deja mas barato", "mas barato", "un poco mas barato", "me hace un descuento", "me da mas barato"] },
        { who: "npc", es: "A ver… ¿cuánto va a llevar? Si lleva harto, le bajo el precio.", de: "Mal sehen … wie viel nehmen Sie? Wenn Sie viel nehmen, mache ich es billiger." },
        { who: "user", kind: "mc", de: "(sag, du willst zwei Kilo)", solEs: "Quiero dos kilos.",
          options: [
            { es: "Quiero dos kilos.", ok: true },
            { es: "Solo uno, gracias.", ok: false },
            { es: "No quiero nada.", ok: false },
          ] },
        { who: "npc", es: "Bueno… para usted, cuatro soles el kilo. ¿Le parece?", de: "Na gut … für Sie vier Soles das Kilo. Geht das?" },
        { who: "user", kind: "mc", de: "(akzeptiere zufrieden)", solEs: "Listo, está bien, deme dos.",
          options: [
            { es: "Listo, está bien, deme dos.", ok: true },
            { es: "No, sigue muy caro.", ok: false },
            { es: "Mejor lo pienso.", ok: false },
          ] },
        { who: "npc", es: "¡Eso, casero! ¿Le gustaría probar una papaya también? Está en oferta.", de: "So ist's recht, mein Lieber! Möchten Sie auch eine Papaya probieren? Die ist im Angebot." },
        { who: "user", kind: "mc", de: "(lehne diesmal höflich ab)", solEs: "No, gracias, así está bien.",
          options: [
            { es: "No, gracias, así está bien.", ok: true },
            { es: "Sí, deme cinco kilos.", ok: false },
            { es: "No entiendo nada.", ok: false },
          ] },
        { who: "npc", es: "Como guste. Son ocho soles los dos kilos de mango.", de: "Wie Sie möchten. Das macht acht Soles für die zwei Kilo Mango." },
        { who: "user", kind: "type", de: "(frag, ob du mit Karte zahlen kannst)", solEs: "¿Puedo pagar con tarjeta?",
          accept: ["puedo pagar con tarjeta", "se puede con tarjeta", "aceptan tarjeta", "con tarjeta se puede", "puedo con tarjeta"] },
        { who: "npc", es: "No, casero, aquí solo efectivo. ¿Tiene sencillo?", de: "Nein, mein Lieber, hier nur bar. Haben Sie es passend?" },
        { who: "user", kind: "type", de: "(sag, ja, hier bitte)", solEs: "Sí, aquí tiene.",
          accept: ["aqui tiene", "si aqui tiene", "aqui esta", "tenga", "aqui tiene esta"] },
        { who: "npc", es: "¡Gracias, casero! Aquí está su fruta. ¡Que le aproveche!", de: "Danke, mein Lieber! Hier ist Ihr Obst. Lassen Sie es sich schmecken!" },
      ],
    },
    {
      id: "farmacia01", cat: "farmacia", title: "Kopfschmerzen", lvl: 2,
      turns: [
        { who: "npc", es: "Buenos días, ¿en qué le puedo ayudar?", de: "Guten Morgen, wie kann ich Ihnen helfen?" },
        { who: "user", kind: "type", de: "(sag, du hast Kopfschmerzen)", solEs: "Me duele la cabeza.",
          accept: ["me duele la cabeza", "tengo dolor de cabeza", "me duele mucho la cabeza", "me duele la cabeza desde hoy"] },
        { who: "npc", es: "Lo siento. ¿Desde cuándo se siente así?", de: "Das tut mir leid. Seit wann fühlen Sie sich so?" },
        { who: "user", kind: "mc", de: "(sag: seit heute Morgen)", solEs: "Desde esta mañana.",
          options: [
            { es: "Desde esta mañana.", ok: true },
            { es: "Desde hace un año.", ok: false },
            { es: "No tengo dinero.", ok: false },
          ] },
        { who: "npc", es: "¿Tiene también fiebre o solo el dolor de cabeza?", de: "Haben Sie auch Fieber oder nur die Kopfschmerzen?" },
        { who: "user", kind: "mc", de: "(sag, nur Kopfschmerzen, kein Fieber)", solEs: "Solo dolor de cabeza, no tengo fiebre.",
          options: [
            { es: "Solo dolor de cabeza, no tengo fiebre.", ok: true },
            { es: "Sí, tengo mucha fiebre.", ok: false },
            { es: "No sé, gracias.", ok: false },
          ] },
        { who: "npc", es: "Entiendo. ¿Es alérgico a algún medicamento?", de: "Verstehe. Sind Sie gegen ein Medikament allergisch?" },
        { who: "user", kind: "type", de: "(sag, du bist gegen nichts allergisch)", solEs: "No soy alérgico a nada.",
          accept: ["no soy alergico a nada", "no soy alergico", "no tengo alergias", "a nada", "no soy alergica a nada"] },
        { who: "npc", es: "Bien. Le puedo dar paracetamol o ibuprofeno. ¿Cuál prefiere?", de: "Gut. Ich kann Ihnen Paracetamol oder Ibuprofen geben. Was möchten Sie lieber?" },
        { who: "user", kind: "mc", de: "(sag: Paracetamol ist gut)", solEs: "Paracetamol está bien.",
          options: [
            { es: "Paracetamol está bien.", ok: true },
            { es: "No quiero nada, gracias.", ok: false },
            { es: "¿Cuánto cuesta el taxi?", ok: false },
          ] },
        { who: "npc", es: "Perfecto. Tome una pastilla cada ocho horas, siempre con comida.", de: "Perfekt. Nehmen Sie alle acht Stunden eine Tablette, immer mit dem Essen." },
        { who: "user", kind: "type", de: "(frag nach, wie viele Tabletten pro Tag)", solEs: "¿Cuántas pastillas tomo al día?",
          accept: ["cuantas pastillas tomo al dia", "cuantas pastillas al dia", "cuantas tomo al dia", "cuantas pastillas tomo", "cuantas al dia"] },
        { who: "npc", es: "Máximo tres al día. Si en dos días no mejora, vaya al médico.", de: "Höchstens drei pro Tag. Wenn es in zwei Tagen nicht besser wird, gehen Sie zum Arzt." },
        { who: "user", kind: "mc", de: "(frag, wie viel es kostet)", solEs: "¿Cuánto le debo?",
          options: [
            { es: "¿Cuánto le debo?", ok: true },
            { es: "¿Dónde está el hospital?", ok: false },
            { es: "¿Tiene wifi?", ok: false },
          ] },
        { who: "npc", es: "Son ocho soles la caja. ¿Algo más que necesite?", de: "Das macht acht Soles die Packung. Brauchen Sie noch etwas?" },
        { who: "user", kind: "type", de: "(bedanke dich, das ist alles)", solEs: "No, gracias, eso es todo.",
          accept: ["no gracias eso es todo", "eso es todo", "no eso es todo", "gracias eso es todo", "nada mas gracias"] },
        { who: "npc", es: "Que se mejore pronto. ¡Que esté bien!", de: "Gute Besserung. Alles Gute!" },
      ],
    },
    {
      id: "hostel01", cat: "hostel", title: "Im Gemeinschaftsraum", lvl: 2,
      turns: [
        { who: "npc", es: "¡Hola! ¿Recién llegas? No te había visto por aquí.", de: "Hi! Gerade angekommen? Ich hab dich hier noch nicht gesehen." },
        { who: "user", kind: "type", de: "(sag, ja, du bist gerade angekommen)", solEs: "Sí, acabo de llegar.",
          accept: ["si acabo de llegar", "acabo de llegar", "recien llegue", "si recien llego", "llegue hace poco"] },
        { who: "npc", es: "¡Bienvenido! ¿De dónde eres?", de: "Willkommen! Woher kommst du?" },
        { who: "user", kind: "type", de: "(sag, du kommst aus Deutschland)", solEs: "Soy de Alemania.",
          accept: ["soy de alemania", "de alemania", "vengo de alemania", "yo soy de alemania", "soy aleman"] },
        { who: "npc", es: "¡Qué bueno! ¿Y es tu primera vez en Perú?", de: "Wie schön! Und bist du zum ersten Mal in Peru?" },
        { who: "user", kind: "mc", de: "(sag: ja, das erste Mal)", solEs: "Sí, es mi primera vez.",
          options: [
            { es: "Sí, es mi primera vez.", ok: true },
            { es: "No, vivo aquí.", ok: false },
            { es: "No me gusta viajar.", ok: false },
          ] },
        { who: "npc", es: "¡Te va a encantar! ¿Cuánto tiempo vas a quedarte?", de: "Es wird dir gefallen! Wie lange bleibst du?" },
        { who: "user", kind: "mc", de: "(sag: drei Nächte)", solEs: "Tres noches.",
          options: [
            { es: "Tres noches.", ok: true },
            { es: "Cuesta mucho.", ok: false },
            { es: "Estoy perdido.", ok: false },
          ] },
        { who: "npc", es: "¿Y ya sabes qué vas a visitar? Hay un montón que ver.", de: "Und weißt du schon, was du besichtigen willst? Es gibt jede Menge zu sehen." },
        { who: "user", kind: "type", de: "(sag, du willst Machu Picchu sehen)", solEs: "Quiero ver Machu Picchu.",
          accept: ["quiero ver machu picchu", "quiero ir a machu picchu", "ver machu picchu", "quiero conocer machu picchu", "machu picchu"] },
        { who: "npc", es: "¡Obvio! Tienes que ir. Oye, ¿quieres que te recomiende un buen restaurante?", de: "Klar! Da musst du hin. Hey, soll ich dir ein gutes Restaurant empfehlen?" },
        { who: "user", kind: "mc", de: "(sag begeistert ja)", solEs: "¡Sí, por favor, me encantaría!",
          options: [
            { es: "¡Sí, por favor, me encantaría!", ok: true },
            { es: "No, no tengo hambre.", ok: false },
            { es: "¿Cuánto cuesta la cama?", ok: false },
          ] },
        { who: "npc", es: "Hay uno aquí cerca, comida típica, baratísimo. Varios vamos hoy. ¿Te apuntas?", de: "Es gibt eins ganz in der Nähe, typisches Essen, spottbillig. Ein paar von uns gehen heute hin. Bist du dabei?" },
        { who: "user", kind: "mc", de: "(sag begeistert zu)", solEs: "¡Claro, me apunto!",
          options: [
            { es: "¡Claro, me apunto!", ok: true },
            { es: "No, estoy lleno.", ok: false },
            { es: "Otra vez, por favor.", ok: false },
          ] },
        { who: "npc", es: "¡Genial! ¿A qué hora te viene bien? ¿Como a las ocho?", de: "Super! Wann passt es dir? So gegen acht?" },
        { who: "user", kind: "type", de: "(sag, acht Uhr ist perfekt)", solEs: "A las ocho está perfecto.",
          accept: ["a las ocho esta perfecto", "a las ocho", "perfecto a las ocho", "las ocho esta bien", "a las ocho me viene bien"] },
        { who: "npc", es: "¡Listo! Nos vemos a las ocho aquí en la sala. ¡Qué chévere conocerte!", de: "Abgemacht! Wir sehen uns um acht hier im Aufenthaltsraum. Schön, dich kennenzulernen!" },
      ],
    },
    {
      id: "frontera01", cat: "frontera", title: "Einreise-Kontrolle", lvl: 2,
      turns: [
        { who: "npc", es: "Buenas. Pasaporte, por favor.", de: "Guten Tag. Reisepass, bitte." },
        { who: "user", kind: "type", de: "(sag, hier bitte, und reich den Pass)", solEs: "Sí, aquí tiene.",
          accept: ["aqui tiene", "si aqui tiene", "aqui esta", "tenga", "aqui tiene mi pasaporte"] },
        { who: "npc", es: "Gracias. ¿Cuál es el motivo de su viaje?", de: "Danke. Was ist der Grund Ihrer Reise?" },
        { who: "user", kind: "mc", de: "(sag, du bist als Tourist hier)", solEs: "Soy turista, vengo de vacaciones.",
          options: [
            { es: "Soy turista, vengo de vacaciones.", ok: true },
            { es: "Vengo a trabajar aquí.", ok: false },
            { es: "No sé, gracias.", ok: false },
          ] },
        { who: "npc", es: "¿Cuántos días piensa quedarse en el país?", de: "Wie viele Tage möchten Sie im Land bleiben?" },
        { who: "user", kind: "type", de: "(sag: zwei Wochen)", solEs: "Dos semanas.",
          accept: ["dos semanas", "unas dos semanas", "catorce dias", "quince dias", "dos semanas mas o menos"] },
        { who: "npc", es: "¿Tiene dónde quedarse durante su estadía?", de: "Haben Sie eine Unterkunft für Ihren Aufenthalt?" },
        { who: "user", kind: "mc", de: "(sag, du hast ein Hostel reserviert)", solEs: "Sí, tengo una reserva en un hostal.",
          options: [
            { es: "Sí, tengo una reserva en un hostal.", ok: true },
            { es: "No, no tengo nada.", ok: false },
            { es: "Quiero un boleto de bus.", ok: false },
          ] },
        { who: "npc", es: "¿Me puede mostrar la reserva o la dirección, por favor?", de: "Können Sie mir die Reservierung oder die Adresse zeigen, bitte?" },
        { who: "user", kind: "type", de: "(sag, ja, du hast sie auf dem Handy)", solEs: "Sí, la tengo en el celular.",
          accept: ["si la tengo en el celular", "la tengo en el celular", "esta en mi celular", "en el celular", "si en el celular"] },
        { who: "npc", es: "Muy bien. ¿Trae algo que declarar? ¿Alimentos, plantas?", de: "Sehr gut. Haben Sie etwas zu verzollen? Lebensmittel, Pflanzen?" },
        { who: "user", kind: "mc", de: "(sag, du hast nichts zu verzollen)", solEs: "No, no traigo nada que declarar.",
          options: [
            { es: "No, no traigo nada que declarar.", ok: true },
            { es: "Sí, traigo mucha comida.", ok: false },
            { es: "No entiendo la pregunta.", ok: false },
          ] },
        { who: "npc", es: "¿Tiene boleto de salida del país?", de: "Haben Sie ein Ausreiseticket?" },
        { who: "user", kind: "type", de: "(sag, ja, du fliegst in zwei Wochen zurück)", solEs: "Sí, regreso en dos semanas.",
          accept: ["si regreso en dos semanas", "regreso en dos semanas", "vuelvo en dos semanas", "si vuelvo en dos semanas", "regreso en quince dias"] },
        { who: "npc", es: "Perfecto. Aquí tiene su pasaporte sellado. Bienvenido al país.", de: "Perfekt. Hier ist Ihr abgestempelter Reisepass. Willkommen im Land." },
        { who: "user", kind: "type", de: "(bedanke dich)", solEs: "Muchas gracias.",
          accept: ["muchas gracias", "gracias", "muchas gracias muy amable", "mil gracias", "gracias muy amable"] },
        { who: "npc", es: "Que disfrute su viaje. ¡Buena estadía!", de: "Genießen Sie Ihre Reise. Schönen Aufenthalt!" },
      ],
    },
    {
      id: "emergencia01", cat: "emergencia", title: "Hilfe rufen", lvl: 2,
      turns: [
        { who: "npc", es: "¿Está bien? ¿Qué pasó? Lo vi caerse.", de: "Geht es Ihnen gut? Was ist passiert? Ich habe Sie stürzen sehen." },
        { who: "user", kind: "type", de: "(bitte dringend um Hilfe)", solEs: "¡Necesito ayuda, por favor!",
          accept: ["necesito ayuda", "necesito ayuda por favor", "ayuda por favor", "ayudenme", "ayuda"] },
        { who: "npc", es: "Tranquilo, lo voy a ayudar. ¿Qué le pasó?", de: "Ruhig, ich helfe Ihnen. Was ist Ihnen passiert?" },
        { who: "user", kind: "mc", de: "(sag, du bist hingefallen)", solEs: "Me caí y me golpeé.",
          options: [
            { es: "Me caí y me golpeé.", ok: true },
            { es: "Quiero la cuenta.", ok: false },
            { es: "Estoy de vacaciones.", ok: false },
          ] },
        { who: "npc", es: "¿Le duele algo? ¿Dónde le duele?", de: "Tut Ihnen etwas weh? Wo tut es weh?" },
        { who: "user", kind: "mc", de: "(sag, dein Bein tut sehr weh)", solEs: "Sí, me duele mucho la pierna.",
          options: [
            { es: "Sí, me duele mucho la pierna.", ok: true },
            { es: "No, estoy bien, gracias.", ok: false },
            { es: "Necesito un taxi.", ok: false },
          ] },
        { who: "npc", es: "No se mueva. ¿Quiere que llame a una ambulancia?", de: "Bewegen Sie sich nicht. Soll ich einen Krankenwagen rufen?" },
        { who: "user", kind: "type", de: "(sag: ja, bitte ruf einen Krankenwagen)", solEs: "Sí, llame a una ambulancia, por favor.",
          accept: ["si llame a una ambulancia", "llame a una ambulancia", "llame una ambulancia por favor", "si una ambulancia", "llame a la ambulancia"] },
        { who: "npc", es: "Ya la estoy llamando. ¿Cómo se llama usted?", de: "Ich rufe ihn schon. Wie heißen Sie?" },
        { who: "user", kind: "type", de: "(nenne deinen Namen: Marco)", solEs: "Me llamo Marco.",
          accept: ["me llamo marco", "soy marco", "marco", "mi nombre es marco", "me llaman marco"] },
        { who: "npc", es: "Marco, ¿puede mover los dedos del pie?", de: "Marco, können Sie die Zehen bewegen?" },
        { who: "user", kind: "mc", de: "(sag, ja, ein bisschen)", solEs: "Sí, un poco.",
          options: [
            { es: "Sí, un poco.", ok: true },
            { es: "No siento nada.", ok: false },
            { es: "No, gracias.", ok: false },
          ] },
        { who: "npc", es: "Bien, eso es buena señal. ¿Está tomando algún medicamento?", de: "Gut, das ist ein gutes Zeichen. Nehmen Sie irgendein Medikament?" },
        { who: "user", kind: "mc", de: "(sag, nein, keine Medikamente)", solEs: "No, ningún medicamento.",
          options: [
            { es: "No, ningún medicamento.", ok: true },
            { es: "Sí, muchos.", ok: false },
            { es: "No sé dónde estoy.", ok: false },
          ] },
        { who: "npc", es: "La ambulancia ya viene en camino. Quédese quieto, yo me quedo con usted.", de: "Der Krankenwagen ist schon unterwegs. Bleiben Sie ruhig liegen, ich bleibe bei Ihnen." },
        { who: "user", kind: "type", de: "(bedanke dich erleichtert)", solEs: "Muchas gracias por su ayuda.",
          accept: ["muchas gracias por su ayuda", "gracias por su ayuda", "muchas gracias", "gracias", "mil gracias"] },
        { who: "npc", es: "No se preocupe. Todo va a estar bien. La ayuda ya casi llega.", de: "Keine Sorge. Alles wird gut. Die Hilfe ist gleich da." },
      ],
    },
    {
      id: "calle01", cat: "calle", title: "Wo ist die Bushaltestelle?", lvl: 1,
      turns: [
        { who: "npc", es: "¿Sí? ¿Necesita ayuda? Lo veo un poco perdido.", de: "Ja? Brauchen Sie Hilfe? Sie wirken etwas verloren." },
        { who: "user", kind: "mc", de: "(frag höflich, wo die Bushaltestelle ist)", solEs: "Disculpe, ¿dónde está el paradero?",
          options: [
            { es: "Disculpe, ¿dónde está el paradero?", ok: true },
            { es: "¿Qué hora es?", ok: false },
            { es: "¿Cuánto cuesta?", ok: false },
          ] },
        { who: "npc", es: "¿El paradero? ¿Para qué bus, el que va al centro?", de: "Die Haltestelle? Für welchen Bus, den ins Zentrum?" },
        { who: "user", kind: "type", de: "(sag, ja, ins Zentrum)", solEs: "Sí, al centro.",
          accept: ["si al centro", "al centro", "si quiero ir al centro", "al centro por favor", "si para el centro"] },
        { who: "npc", es: "Ah, ya. Siga derecho dos cuadras y doble a la derecha.", de: "Ah, gut. Gehen Sie zwei Blocks geradeaus und biegen Sie rechts ab." },
        { who: "user", kind: "type", de: "(frag nach, ob es weit ist)", solEs: "¿Está lejos?",
          accept: ["esta lejos", "queda lejos", "es lejos", "esta muy lejos", "esta lejos de aqui"] },
        { who: "npc", es: "No, está cerca. Unos cinco minutos a pie, no más.", de: "Nein, es ist nah. Etwa fünf Minuten zu Fuß, nicht mehr." },
        { who: "user", kind: "mc", de: "(frag, welcher Bus zum Zentrum fährt)", solEs: "¿Qué bus va al centro?",
          options: [
            { es: "¿Qué bus va al centro?", ok: true },
            { es: "¿Tiene un cigarro?", ok: false },
            { es: "¿Dónde vive usted?", ok: false },
          ] },
        { who: "npc", es: "Tome el que dice \"Centro\" o el número veinte. Pasan seguido.", de: "Nehmen Sie den mit „Centro“ oder die Nummer zwanzig. Die kommen oft." },
        { who: "user", kind: "type", de: "(frag, wie viel die Fahrt kostet)", solEs: "¿Cuánto cuesta el pasaje?",
          accept: ["cuanto cuesta el pasaje", "cuanto es el pasaje", "cuanto cuesta", "cuanto vale el pasaje", "cuanto cuesta el boleto"] },
        { who: "npc", es: "Un sol cincuenta. Tenga sencillo a la mano, casi no dan vuelto.", de: "Eineinhalb Soles. Halten Sie es passend bereit, Wechselgeld gibt es kaum." },
        { who: "user", kind: "mc", de: "(frag, ob du dem Fahrer sagen sollst, wo du raus willst)", solEs: "¿Le aviso al chofer dónde bajar?",
          options: [
            { es: "¿Le aviso al chofer dónde bajar?", ok: true },
            { es: "¿Puedo ir en taxi gratis?", ok: false },
            { es: "¿El bus tiene wifi?", ok: false },
          ] },
        { who: "npc", es: "Sí, dígale \"centro\" al subir y él le avisa dónde bajar.", de: "Ja, sagen Sie ihm beim Einsteigen „centro“, dann sagt er Ihnen, wo Sie aussteigen." },
        { who: "user", kind: "type", de: "(bedanke dich herzlich)", solEs: "Muchas gracias, muy amable.",
          accept: ["muchas gracias muy amable", "muchas gracias", "gracias", "muy amable", "mil gracias"] },
        { who: "npc", es: "De nada. ¡Que le vaya bien y buen viaje!", de: "Gern geschehen. Alles Gute und gute Reise!" },
      ],
    },
  ];

  window.SC = window.SC || {};
  window.SC.dialogos = { DIALOGOS_SCENARIOS, DIALOGOS };
})();
