/*
 * dialogos.js  (SC.dialogos) – Daten für die Gesprächs-Simulationen (Diálogos).
 * REINE DATEN, additiv – die Wörterbasis bleibt unangetastet.
 *
 * Idee: echte Reisesituationen Zug für Zug durchspielen. Die Gegenseite (npc)
 * wird angezeigt und – wenn der Browser TTS kann – vorgelesen; der Nutzer
 * antwortet je nach Zug per Multiple-Choice (kind:"mc") oder tippt eine
 * Schlüssel-Replik frei (kind:"type", großzügig per matcher.normalize geprüft).
 *
 * Die Dialoge sind bewusst lang gehalten (7–9 Repliken pro Runde), damit sich
 * ein echtes Gespräch entfaltet statt nur dreier Stichworte.
 *
 * Struktur:
 *   DIALOGOS_SCENARIOS = Menü: { id, title, icon, lvl, intro }
 *   DIALOGOS           = die Dialoge: { id, cat(=scenario.id), title, lvl, turns[] }
 *     turn npc  : { who:"npc",  es, de }
 *     turn mc   : { who:"user", kind:"mc",   de, solEs, options:[{es, ok}] }
 *     turn type : { who:"user", kind:"type", de, solEs, accept:[…] }
 *       de    = Handlungsanweisung („(sag, dass du einchecken willst)")
 *       solEs = die Musterantwort (erscheint in der Verlaufsspur)
 *       accept= zusätzlich akzeptierte (normalisierte) Eingaben neben solEs
 */
(function () {
  "use strict";

  const DIALOGOS_SCENARIOS = [
    { id: "hotel",      title: "Hotel-Check-in",  titleEn: "Hotel check-in",  icon: "🛎️", lvl: 1, intro: "An der Rezeption einchecken.", introEn: "Check in at reception." },
    { id: "restaurante",title: "Im Restaurant",   titleEn: "At the restaurant",   icon: "🍽️", lvl: 1, intro: "Bestellen, fragen, zahlen.", introEn: "Order, ask, pay." },
    { id: "bus",        title: "Busticket kaufen", titleEn: "Buy a bus ticket", icon: "🚌", lvl: 1, intro: "Am Schalter ein Ticket lösen.", introEn: "Get a ticket at the counter." },
    { id: "taxi",       title: "Taxifahrt",       titleEn: "Taxi ride",       icon: "🚕", lvl: 1, intro: "Ziel nennen und Preis klären.", introEn: "Give your destination and sort out the price." },
    { id: "mercado",    title: "Auf dem Markt",   titleEn: "At the market",   icon: "🛍️", lvl: 2, intro: "Fragen und freundlich feilschen.", introEn: "Ask questions and haggle nicely." },
    { id: "farmacia",   title: "In der Apotheke", titleEn: "At the pharmacy", icon: "💊", lvl: 2, intro: "Beschwerden schildern, Hilfe holen.", introEn: "Describe your symptoms and get help." },
    { id: "hostel",     title: "Hostel-Smalltalk", titleEn: "Hostel small talk", icon: "🛏️", lvl: 2, intro: "Andere Reisende kennenlernen.", introEn: "Get to know other travellers." },
    { id: "frontera",   title: "An der Grenze",   titleEn: "At the border",   icon: "🛂", lvl: 2, intro: "Ein- und Ausreise-Fragen.", introEn: "Entry and exit questions." },
    { id: "emergencia", title: "Notfall",         titleEn: "Emergency",         icon: "🆘", lvl: 2, intro: "Schnell um Hilfe bitten.", introEn: "Ask for help quickly." },
    { id: "calle",      title: "Nach dem Weg fragen", titleEn: "Asking for directions", icon: "🧭", lvl: 1, intro: "Sich auf der Straße orientieren.", introEn: "Find your way around on the street." },
  ];

  const DIALOGOS = [
    {
      id: "hotel01", cat: "hotel", title: "An der Rezeption", titleEn: "At reception", lvl: 1,
      turns: [
        { who: "npc", es: "¡Buenas! Bienvenido al Hotel Sol Andino. ¿En qué le puedo ayudar?", de: "Hallo! Willkommen im Hotel Sol Andino. Wie kann ich Ihnen helfen?", en: "Hi there! Welcome to the Hotel Sol Andino. How can I help you?" },
        { who: "user", kind: "mc", de: "(sag, dass du einchecken möchtest)", en: "(say you'd like to check in)", solEs: "Quisiera hacer el check-in, por favor.",
          options: [
            { es: "Quisiera hacer el check-in, por favor.", ok: true },
            { es: "La cuenta, por favor.", ok: false },
            { es: "¿Dónde está el baño?", ok: false },
          ] },
        { who: "npc", es: "Claro que sí. ¿A nombre de quién está la reserva?", de: "Aber natürlich. Auf welchen Namen läuft die Reservierung?", en: "Of course. What name is the booking under?" },
        { who: "user", kind: "type", de: "(antworte: auf den Namen Marco)", en: "(answer: under the name Marco)", solEs: "A nombre de Marco.",
          accept: ["a nombre de marco", "marco", "es marco", "me llamo marco", "esta a nombre de marco"] },
        { who: "npc", es: "Perfecto, aquí la tengo. Una habitación doble por tres noches, ¿verdad?", de: "Perfekt, hier habe ich sie. Ein Doppelzimmer für drei Nächte, richtig?", en: "Perfect, here it is. A double room for three nights, right?" },
        { who: "user", kind: "mc", de: "(bestätige: ja, genau, drei Nächte)", en: "(confirm: yes, exactly, three nights)", solEs: "Sí, exacto, tres noches.",
          options: [
            { es: "Sí, exacto, tres noches.", ok: true },
            { es: "No, solo una noche.", ok: false },
            { es: "No tengo reserva.", ok: false },
          ] },
        { who: "npc", es: "Muy bien. ¿Me permite su pasaporte, por favor?", de: "Sehr gut. Dürfte ich bitte Ihren Reisepass haben?", en: "Very good. May I have your passport, please?" },
        { who: "user", kind: "type", de: "(sag, hier bitte, und reich ihn rüber)", en: "(say here you go and hand it over)", solEs: "Sí, aquí tiene.",
          accept: ["aqui tiene", "si aqui tiene", "aqui esta", "tenga", "aqui lo tiene"] },
        { who: "npc", es: "Gracias. ¿Prefiere una habitación con vista a la calle o una más tranquila?", de: "Danke. Möchten Sie lieber ein Zimmer zur Straße oder ein ruhigeres?", en: "Thanks. Would you prefer a room facing the street or a quieter one?" },
        { who: "user", kind: "mc", de: "(sag, du hättest gern ein ruhiges Zimmer)", en: "(say you'd like a quiet room)", solEs: "Una tranquila, por favor.",
          options: [
            { es: "Una tranquila, por favor.", ok: true },
            { es: "Con vista a la calle, mejor.", ok: false },
            { es: "Me da igual el precio.", ok: false },
          ] },
        { who: "npc", es: "Entendido. Le doy la habitación doscientos cuatro, en el segundo piso.", de: "Verstanden. Ich gebe Ihnen Zimmer zweihundertvier im zweiten Stock.", en: "Understood. I'll give you room two hundred and four, on the second floor." },
        { who: "user", kind: "type", de: "(frag, um wie viel Uhr es Frühstück gibt)", en: "(ask what time breakfast is)", solEs: "¿A qué hora es el desayuno?",
          accept: ["a que hora es el desayuno", "cuando es el desayuno", "a que hora el desayuno", "a que hora hay desayuno"] },
        { who: "npc", es: "De siete a diez de la mañana, en el comedor de la planta baja.", de: "Von sieben bis zehn Uhr morgens, im Speisesaal im Erdgeschoss.", en: "From seven to ten in the morning, in the dining room on the ground floor." },
        { who: "user", kind: "mc", de: "(frag, ob es WLAN im Zimmer gibt)", en: "(ask whether there's WiFi in the room)", solEs: "¿Hay wifi en la habitación?",
          options: [
            { es: "¿Hay wifi en la habitación?", ok: true },
            { es: "¿Tienen piscina?", ok: false },
            { es: "¿Puedo pagar mañana?", ok: false },
          ] },
        { who: "npc", es: "Sí, la clave está en el reverso de su tarjeta-llave. Aquí tiene.", de: "Ja, das Passwort steht auf der Rückseite Ihrer Schlüsselkarte. Hier bitte.", en: "Yes, the password is on the back of your key card. Here you go." },
        { who: "user", kind: "type", de: "(bedanke dich freundlich)", en: "(thank them warmly)", solEs: "Muchas gracias, muy amable.",
          accept: ["muchas gracias muy amable", "muchas gracias", "gracias", "mil gracias", "muy amable, gracias"] },
        { who: "npc", es: "A usted. Cualquier cosa, estamos en recepción las veinticuatro horas. ¡Que descanse!", de: "Gern. Bei Fragen: Die Rezeption ist rund um die Uhr besetzt. Gute Erholung!", en: "Thank you. If you need anything, reception is staffed around the clock. Have a good rest!" },
      ],
    },
    {
      id: "restaurante01", cat: "restaurante", title: "Bestellen & zahlen", titleEn: "Ordering & paying", lvl: 1,
      turns: [
        { who: "npc", es: "Buenas tardes, bienvenidos. ¿Mesa para cuántas personas?", de: "Guten Tag, willkommen. Ein Tisch für wie viele Personen?", en: "Good afternoon, welcome. A table for how many people?" },
        { who: "user", kind: "mc", de: "(sag: ein Tisch für zwei)", en: "(say: a table for two)", solEs: "Una mesa para dos, por favor.",
          options: [
            { es: "Una mesa para dos, por favor.", ok: true },
            { es: "La cuenta, por favor.", ok: false },
            { es: "Estoy lleno, gracias.", ok: false },
          ] },
        { who: "npc", es: "Perfecto, síganme. ¿Esta mesa junto a la ventana les parece bien?", de: "Perfekt, folgen Sie mir. Ist dieser Tisch am Fenster in Ordnung?", en: "Perfect, follow me. Is this table by the window all right?" },
        { who: "user", kind: "mc", de: "(sag, der Tisch ist super)", en: "(say the table is great)", solEs: "Sí, está perfecta, gracias.",
          options: [
            { es: "Sí, está perfecta, gracias.", ok: true },
            { es: "No, prefiero afuera en la calle.", ok: false },
            { es: "No hablo español.", ok: false },
          ] },
        { who: "npc", es: "Aquí tienen la carta. ¿Algo para tomar mientras deciden?", de: "Hier ist die Speisekarte. Etwas zu trinken, während Sie sich entscheiden?", en: "Here's the menu. Something to drink while you decide?" },
        { who: "user", kind: "type", de: "(bestelle zwei Wasser)", en: "(order two waters)", solEs: "Dos aguas, por favor.",
          accept: ["dos aguas", "dos aguas por favor", "dos botellas de agua", "queremos dos aguas", "dos aguas porfa"] },
        { who: "npc", es: "Enseguida se las traigo. ¿Ya saben qué van a pedir de comer?", de: "Bringe ich gleich. Wissen Sie schon, was Sie essen möchten?", en: "I'll bring them right over. Do you know yet what you'd like to eat?" },
        { who: "user", kind: "type", de: "(frag, was das Tagesgericht ist)", en: "(ask what the dish of the day is)", solEs: "¿Cuál es el plato del día?",
          accept: ["cual es el plato del dia", "que es el plato del dia", "que hay de plato del dia", "cual es el menu del dia"] },
        { who: "npc", es: "Hoy tenemos lomo saltado con arroz y papas. Está muy rico.", de: "Heute gibt es Lomo Saltado mit Reis und Kartoffeln. Es ist sehr lecker.", en: "Today we've got lomo saltado with rice and potatoes. It's really tasty." },
        { who: "user", kind: "mc", de: "(bestelle das Tagesgericht zweimal)", en: "(order the dish of the day twice)", solEs: "Entonces dos platos del día, por favor.",
          options: [
            { es: "Entonces dos platos del día, por favor.", ok: true },
            { es: "No, gracias, solo la cuenta.", ok: false },
            { es: "¿Tienen mesa para dos?", ok: false },
          ] },
        { who: "npc", es: "Excelente elección. ¿Desean algo más, un postre quizás?", de: "Ausgezeichnete Wahl. Möchten Sie noch etwas, vielleicht ein Dessert?", en: "Excellent choice. Would you like anything else, a dessert perhaps?" },
        { who: "user", kind: "mc", de: "(lehne höflich ab – erst mal nichts weiter)", en: "(politely decline – nothing more for now)", solEs: "No, así está bien, gracias.",
          options: [
            { es: "No, así está bien, gracias.", ok: true },
            { es: "Sí, la cuenta, por favor.", ok: false },
            { es: "No tengo hambre.", ok: false },
          ] },
        { who: "npc", es: "Muy bien. … (más tarde) ¿Qué tal estuvo todo? ¿Les gustó?", de: "Sehr gut. … (später) Wie war alles? Hat es geschmeckt?", en: "Very good. … (later) How was everything? Did you enjoy it?" },
        { who: "user", kind: "type", de: "(sag, es war sehr lecker)", en: "(say it was really tasty)", solEs: "Estuvo todo muy rico.",
          accept: ["estuvo todo muy rico", "muy rico", "estuvo muy rico", "todo muy rico", "estaba muy rico"] },
        { who: "npc", es: "Me alegra mucho. ¿Les traigo algo más o ya la cuenta?", de: "Das freut mich sehr. Bringe ich Ihnen noch etwas, oder schon die Rechnung?", en: "I'm really glad. Shall I bring you anything else, or the bill now?" },
        { who: "user", kind: "type", de: "(bitte um die Rechnung)", en: "(ask for the bill)", solEs: "La cuenta, por favor.",
          accept: ["la cuenta por favor", "la cuenta", "me trae la cuenta", "nos trae la cuenta", "la cuenta porfa"] },
        { who: "npc", es: "Claro, ya se la traigo. ¿Van a pagar en efectivo o con tarjeta?", de: "Klar, ich bringe sie. Zahlen Sie bar oder mit Karte?", en: "Of course, I'll bring it. Will you pay by cash or card?" },
        { who: "user", kind: "mc", de: "(sag: mit Karte)", en: "(say: by card)", solEs: "Con tarjeta, por favor.",
          options: [
            { es: "Con tarjeta, por favor.", ok: true },
            { es: "En efectivo.", ok: false },
            { es: "Pago mañana.", ok: false },
          ] },
        { who: "npc", es: "Perfecto. Muchas gracias por su visita. ¡Vuelvan pronto!", de: "Perfekt. Vielen Dank für Ihren Besuch. Kommen Sie bald wieder!", en: "Perfect. Thank you very much for your visit. Come back soon!" },
      ],
    },
    {
      id: "bus01", cat: "bus", title: "Am Busschalter", titleEn: "At the bus counter", lvl: 1,
      turns: [
        { who: "npc", es: "¡Siguiente, por favor! ¿Para dónde va?", de: "Der Nächste bitte! Wohin möchten Sie?", en: "Next, please! Where are you heading?" },
        { who: "user", kind: "type", de: "(sag, du willst ein Ticket nach Cusco)", en: "(say you want a ticket to Cusco)", solEs: "Quiero un boleto para Cusco.",
          accept: ["quiero un boleto para cusco", "un boleto para cusco", "para cusco", "un pasaje para cusco", "quiero un pasaje para cusco"] },
        { who: "npc", es: "Muy bien. ¿Para hoy o para mañana?", de: "Sehr gut. Für heute oder für morgen?", en: "Very good. For today or for tomorrow?" },
        { who: "user", kind: "mc", de: "(sag: für morgen früh)", en: "(say: for tomorrow morning)", solEs: "Para mañana en la mañana.",
          options: [
            { es: "Para mañana en la mañana.", ok: true },
            { es: "Para hoy en la noche.", ok: false },
            { es: "No sé, gracias.", ok: false },
          ] },
        { who: "npc", es: "Tenemos uno a las ocho y otro a las diez. ¿Cuál prefiere?", de: "Wir haben einen um acht und einen um zehn. Welchen möchten Sie?", en: "We've got one at eight and another at ten. Which would you prefer?" },
        { who: "user", kind: "mc", de: "(nimm den um acht)", en: "(take the eight o'clock one)", solEs: "El de las ocho, por favor.",
          options: [
            { es: "El de las ocho, por favor.", ok: true },
            { es: "El de medianoche.", ok: false },
            { es: "Ninguno, gracias.", ok: false },
          ] },
        { who: "npc", es: "¿Asiento normal o cama? El cama es más cómodo para el viaje largo.", de: "Normaler Sitz oder Liegesitz? Der Liegesitz ist bequemer für die lange Fahrt.", en: "A normal seat or a reclining one? The reclining seat is more comfortable for the long journey." },
        { who: "user", kind: "type", de: "(sag, du willst einen normalen Sitz)", en: "(say you want a normal seat)", solEs: "Asiento normal, por favor.",
          accept: ["asiento normal", "asiento normal por favor", "un asiento normal", "normal por favor", "el normal"] },
        { who: "npc", es: "Perfecto. ¿Prefiere ventana o pasillo?", de: "Perfekt. Möchten Sie lieber Fenster oder Gang?", en: "Perfect. Would you prefer window or aisle?" },
        { who: "user", kind: "mc", de: "(sag: Fenster)", en: "(say: window)", solEs: "Ventana, por favor.",
          options: [
            { es: "Ventana, por favor.", ok: true },
            { es: "Pasillo, mejor.", ok: false },
            { es: "Me da igual el horario.", ok: false },
          ] },
        { who: "npc", es: "Listo. ¿Me da su nombre completo, por favor?", de: "Geht klar. Geben Sie mir bitte Ihren vollständigen Namen?", en: "Right. Could you give me your full name, please?" },
        { who: "user", kind: "type", de: "(nenne deinen Namen: Marco Pérez)", en: "(give your name: Marco Pérez)", solEs: "Marco Pérez.",
          accept: ["marco perez", "me llamo marco perez", "soy marco perez", "mi nombre es marco perez"] },
        { who: "npc", es: "Gracias. Son cuarenta soles. ¿Cómo va a pagar?", de: "Danke. Das macht vierzig Soles. Wie möchten Sie zahlen?", en: "Thanks. That's forty soles. How would you like to pay?" },
        { who: "user", kind: "mc", de: "(sag: bar)", en: "(say: cash)", solEs: "En efectivo.",
          options: [
            { es: "En efectivo.", ok: true },
            { es: "¿Puedo pagar en Cusco?", ok: false },
            { es: "No tengo dinero.", ok: false },
          ] },
        { who: "npc", es: "Aquí tiene su boleto y su vuelto. El bus sale del andén número cinco.", de: "Hier ist Ihr Ticket und Ihr Wechselgeld. Der Bus fährt von Bahnsteig fünf.", en: "Here's your ticket and your change. The bus leaves from platform five." },
        { who: "user", kind: "type", de: "(frag nach, wie lange die Fahrt dauert)", en: "(ask how long the journey takes)", solEs: "¿Cuánto dura el viaje?",
          accept: ["cuanto dura el viaje", "cuanto demora el viaje", "cuanto tiempo dura el viaje", "cuanto se demora", "cuanto dura"] },
        { who: "npc", es: "Unas seis horas, llega a las dos de la tarde. ¡Buen viaje!", de: "Etwa sechs Stunden, Ankunft um zwei Uhr nachmittags. Gute Reise!", en: "About six hours, arriving at two in the afternoon. Have a good trip!" },
      ],
    },
    {
      id: "taxi01", cat: "taxi", title: "Ins Zentrum", titleEn: "Into the centre", lvl: 1,
      turns: [
        { who: "npc", es: "¡Buenas! ¿A dónde lo llevo?", de: "Hallo! Wohin darf ich Sie fahren?", en: "Hi there! Where can I take you?" },
        { who: "user", kind: "type", de: "(sag, du willst zum Stadtzentrum)", en: "(say you want to go to the city centre)", solEs: "Al centro, por favor.",
          accept: ["al centro", "al centro por favor", "quiero ir al centro", "voy al centro", "al centro porfa"] },
        { who: "npc", es: "Claro. ¿Conoce la dirección exacta o lo dejo en la plaza?", de: "Klar. Kennen Sie die genaue Adresse oder setze ich Sie an der Plaza ab?", en: "Sure. Do you know the exact address, or shall I drop you at the plaza?" },
        { who: "user", kind: "mc", de: "(sag, an der Plaza ist gut)", en: "(say the plaza is fine)", solEs: "Déjeme en la plaza, está bien.",
          options: [
            { es: "Déjeme en la plaza, está bien.", ok: true },
            { es: "No sé dónde estoy.", ok: false },
            { es: "¿Puedo pagar mañana?", ok: false },
          ] },
        { who: "npc", es: "Perfecto. ¿Tiene apuro o vamos con calma?", de: "Perfekt. Haben Sie es eilig oder fahren wir gemütlich?", en: "Perfect. Are you in a hurry or shall we take it easy?" },
        { who: "user", kind: "mc", de: "(frag vorher, wie viel die Fahrt kostet)", en: "(ask first how much the ride costs)", solEs: "¿Cuánto cuesta hasta allá?",
          options: [
            { es: "¿Cuánto cuesta hasta allá?", ok: true },
            { es: "¿Tiene cambio de cien?", ok: false },
            { es: "¿Es muy lejos su casa?", ok: false },
          ] },
        { who: "npc", es: "Unos quince soles, más o menos. ¿Le parece bien?", de: "So um die fünfzehn Soles, mehr oder weniger. Geht das in Ordnung?", en: "Around fifteen soles, more or less. Does that sound all right?" },
        { who: "user", kind: "mc", de: "(stimm zu und bitte ihn loszufahren)", en: "(agree and ask them to set off)", solEs: "Está bien, vamos.",
          options: [
            { es: "Está bien, vamos.", ok: true },
            { es: "No, gracias, camino.", ok: false },
            { es: "Es muy barato.", ok: false },
          ] },
        { who: "npc", es: "(en el camino) ¿Es la primera vez que visita la ciudad?", de: "(unterwegs) Sind Sie zum ersten Mal in der Stadt?", en: "(on the way) Is it your first time in the city?" },
        { who: "user", kind: "type", de: "(sag: ja, du bist Tourist)", en: "(say: yes, you're a tourist)", solEs: "Sí, soy turista.",
          accept: ["si soy turista", "soy turista", "vengo de turista", "si de vacaciones", "si estoy de vacaciones"] },
        { who: "npc", es: "¡Qué bueno! ¿De qué país viene, si no es indiscreción?", de: "Wie schön! Aus welchem Land kommen Sie, wenn ich fragen darf?", en: "How lovely! Which country are you from, if you don't mind me asking?" },
        { who: "user", kind: "type", de: "(sag, du kommst aus Deutschland)", en: "(say you're from Germany)", solEs: "Vengo de Alemania.",
          accept: ["vengo de alemania", "soy de alemania", "de alemania", "soy aleman", "yo soy de alemania"] },
        { who: "npc", es: "¡Alemania, qué lejos! ¿Le pongo un poco de música o prefiere tranquilo?", de: "Deutschland, so weit weg! Soll ich etwas Musik anmachen oder lieber ruhig?", en: "Germany, so far away! Shall I put on some music, or would you rather have it quiet?" },
        { who: "user", kind: "mc", de: "(sag, etwas Musik wäre schön)", en: "(say some music would be nice)", solEs: "Un poco de música, por favor.",
          options: [
            { es: "Un poco de música, por favor.", ok: true },
            { es: "No, en silencio, gracias.", ok: false },
            { es: "Más rápido, por favor.", ok: false },
          ] },
        { who: "npc", es: "¡Listo! Ya casi llegamos. Aquí es la plaza, son quince soles.", de: "Geht klar! Wir sind fast da. Hier ist die Plaza, das macht fünfzehn Soles.", en: "Right! We're almost there. Here's the plaza, that's fifteen soles." },
        { who: "user", kind: "type", de: "(sag, hier bitte – und bedanke dich)", en: "(say here you go – and thank them)", solEs: "Aquí tiene, gracias.",
          accept: ["aqui tiene gracias", "aqui tiene", "aqui esta", "tenga gracias", "aqui tiene esta bien"] },
        { who: "npc", es: "Muchas gracias. ¡Que disfrute la ciudad y buen viaje!", de: "Vielen Dank. Genießen Sie die Stadt und gute Reise!", en: "Thank you very much. Enjoy the city and have a good trip!" },
      ],
    },
    {
      id: "mercado01", cat: "mercado", title: "Obst & Feilschen", titleEn: "Fruit & haggling", lvl: 2,
      turns: [
        { who: "npc", es: "¡Pásele, casero! Tengo fruta fresquita. ¿Qué va a llevar?", de: "Kommen Sie ran, mein Lieber! Ich hab ganz frisches Obst. Was darf's sein?", en: "Come on over, casero! I've got lovely fresh fruit. What can I get you?" },
        { who: "user", kind: "mc", de: "(frag, wie viel das Kilo Mangos kostet)", en: "(ask how much a kilo of mangoes costs)", solEs: "¿A cuánto está el kilo de mango?",
          options: [
            { es: "¿A cuánto está el kilo de mango?", ok: true },
            { es: "¿Dónde está la salida?", ok: false },
            { es: "¿Me regala una bolsa?", ok: false },
          ] },
        { who: "npc", es: "A cinco soles el kilo, bien dulces, recién traídos.", de: "Fünf Soles das Kilo, schön süß, frisch geliefert.", en: "Five soles a kilo, nice and sweet, just delivered." },
        { who: "user", kind: "type", de: "(sag, das sei ein bisschen teuer)", en: "(say that's a bit pricey)", solEs: "Está un poco caro.",
          accept: ["esta un poco caro", "esta caro", "un poco caro", "esta medio caro", "me parece caro"] },
        { who: "npc", es: "¿Caro? ¡Pero si es la mejor fruta del mercado, casero!", de: "Teuer? Aber das ist doch das beste Obst auf dem Markt, mein Lieber!", en: "Pricey? But this is the best fruit in the market, casero!" },
        { who: "user", kind: "type", de: "(feilsche freundlich: ob er es etwas billiger macht)", en: "(haggle nicely: whether they'll make it a bit cheaper)", solEs: "¿Me lo deja más barato?",
          accept: ["me lo deja mas barato", "mas barato", "un poco mas barato", "me hace un descuento", "me da mas barato"] },
        { who: "npc", es: "A ver… ¿cuánto va a llevar? Si lleva harto, le bajo el precio.", de: "Mal sehen … wie viel nehmen Sie? Wenn Sie viel nehmen, mache ich es billiger.", en: "Let's see… how much will you take? If you take a lot, I'll drop the price." },
        { who: "user", kind: "mc", de: "(sag, du willst zwei Kilo)", en: "(say you want two kilos)", solEs: "Quiero dos kilos.",
          options: [
            { es: "Quiero dos kilos.", ok: true },
            { es: "Solo uno, gracias.", ok: false },
            { es: "No quiero nada.", ok: false },
          ] },
        { who: "npc", es: "Bueno… para usted, cuatro soles el kilo. ¿Le parece?", de: "Na gut … für Sie vier Soles das Kilo. Geht das?", en: "All right… for you, four soles a kilo. How's that?" },
        { who: "user", kind: "mc", de: "(akzeptiere zufrieden)", en: "(accept, happy with it)", solEs: "Listo, está bien, deme dos.",
          options: [
            { es: "Listo, está bien, deme dos.", ok: true },
            { es: "No, sigue muy caro.", ok: false },
            { es: "Mejor lo pienso.", ok: false },
          ] },
        { who: "npc", es: "¡Eso, casero! ¿Le gustaría probar una papaya también? Está en oferta.", de: "So ist's recht, mein Lieber! Möchten Sie auch eine Papaya probieren? Die ist im Angebot.", en: "That's it, casero! Would you like to try a papaya too? It's on offer." },
        { who: "user", kind: "mc", de: "(lehne diesmal höflich ab)", en: "(politely decline this time)", solEs: "No, gracias, así está bien.",
          options: [
            { es: "No, gracias, así está bien.", ok: true },
            { es: "Sí, deme cinco kilos.", ok: false },
            { es: "No entiendo nada.", ok: false },
          ] },
        { who: "npc", es: "Como guste. Son ocho soles los dos kilos de mango.", de: "Wie Sie möchten. Das macht acht Soles für die zwei Kilo Mango.", en: "As you like. That's eight soles for the two kilos of mango." },
        { who: "user", kind: "type", de: "(frag, ob du mit Karte zahlen kannst)", en: "(ask whether you can pay by card)", solEs: "¿Puedo pagar con tarjeta?",
          accept: ["puedo pagar con tarjeta", "se puede con tarjeta", "aceptan tarjeta", "con tarjeta se puede", "puedo con tarjeta"] },
        { who: "npc", es: "No, casero, aquí solo efectivo. ¿Tiene sencillo?", de: "Nein, mein Lieber, hier nur bar. Haben Sie es passend?", en: "No, casero, it's cash only here. Have you got the right change?" },
        { who: "user", kind: "type", de: "(sag, ja, hier bitte)", en: "(say yes, here you go)", solEs: "Sí, aquí tiene.",
          accept: ["aqui tiene", "si aqui tiene", "aqui esta", "tenga", "aqui tiene esta"] },
        { who: "npc", es: "¡Gracias, casero! Aquí está su fruta. ¡Que le aproveche!", de: "Danke, mein Lieber! Hier ist Ihr Obst. Lassen Sie es sich schmecken!", en: "Thanks, casero! Here's your fruit. Enjoy it!" },
      ],
    },
    {
      id: "farmacia01", cat: "farmacia", title: "Kopfschmerzen", titleEn: "Headache", lvl: 2,
      turns: [
        { who: "npc", es: "Buenos días, ¿en qué le puedo ayudar?", de: "Guten Morgen, wie kann ich Ihnen helfen?", en: "Good morning, how can I help you?" },
        { who: "user", kind: "type", de: "(sag, du hast Kopfschmerzen)", en: "(say you have a headache)", solEs: "Me duele la cabeza.",
          accept: ["me duele la cabeza", "tengo dolor de cabeza", "me duele mucho la cabeza", "me duele la cabeza desde hoy"] },
        { who: "npc", es: "Lo siento. ¿Desde cuándo se siente así?", de: "Das tut mir leid. Seit wann fühlen Sie sich so?", en: "I'm sorry. Since when have you felt like this?" },
        { who: "user", kind: "mc", de: "(sag: seit heute Morgen)", en: "(say: since this morning)", solEs: "Desde esta mañana.",
          options: [
            { es: "Desde esta mañana.", ok: true },
            { es: "Desde hace un año.", ok: false },
            { es: "No tengo dinero.", ok: false },
          ] },
        { who: "npc", es: "¿Tiene también fiebre o solo el dolor de cabeza?", de: "Haben Sie auch Fieber oder nur die Kopfschmerzen?", en: "Do you also have a fever or just the headache?" },
        { who: "user", kind: "mc", de: "(sag, nur Kopfschmerzen, kein Fieber)", en: "(say just a headache, no fever)", solEs: "Solo dolor de cabeza, no tengo fiebre.",
          options: [
            { es: "Solo dolor de cabeza, no tengo fiebre.", ok: true },
            { es: "Sí, tengo mucha fiebre.", ok: false },
            { es: "No sé, gracias.", ok: false },
          ] },
        { who: "npc", es: "Entiendo. ¿Es alérgico a algún medicamento?", de: "Verstehe. Sind Sie gegen ein Medikament allergisch?", en: "I see. Are you allergic to any medication?" },
        { who: "user", kind: "type", de: "(sag, du bist gegen nichts allergisch)", en: "(say you're not allergic to anything)", solEs: "No soy alérgico a nada.",
          accept: ["no soy alergico a nada", "no soy alergico", "no tengo alergias", "a nada", "no soy alergica a nada"] },
        { who: "npc", es: "Bien. Le puedo dar paracetamol o ibuprofeno. ¿Cuál prefiere?", de: "Gut. Ich kann Ihnen Paracetamol oder Ibuprofen geben. Was möchten Sie lieber?", en: "Good. I can give you paracetamol or ibuprofen. Which would you prefer?" },
        { who: "user", kind: "mc", de: "(sag: Paracetamol ist gut)", en: "(say: paracetamol is fine)", solEs: "Paracetamol está bien.",
          options: [
            { es: "Paracetamol está bien.", ok: true },
            { es: "No quiero nada, gracias.", ok: false },
            { es: "¿Cuánto cuesta el taxi?", ok: false },
          ] },
        { who: "npc", es: "Perfecto. Tome una pastilla cada ocho horas, siempre con comida.", de: "Perfekt. Nehmen Sie alle acht Stunden eine Tablette, immer mit dem Essen.", en: "Perfect. Take one tablet every eight hours, always with food." },
        { who: "user", kind: "type", de: "(frag nach, wie viele Tabletten pro Tag)", en: "(ask how many tablets per day)", solEs: "¿Cuántas pastillas tomo al día?",
          accept: ["cuantas pastillas tomo al dia", "cuantas pastillas al dia", "cuantas tomo al dia", "cuantas pastillas tomo", "cuantas al dia"] },
        { who: "npc", es: "Máximo tres al día. Si en dos días no mejora, vaya al médico.", de: "Höchstens drei pro Tag. Wenn es in zwei Tagen nicht besser wird, gehen Sie zum Arzt.", en: "Three a day at most. If it doesn't improve in two days, see a doctor." },
        { who: "user", kind: "mc", de: "(frag, wie viel es kostet)", en: "(ask how much it costs)", solEs: "¿Cuánto le debo?",
          options: [
            { es: "¿Cuánto le debo?", ok: true },
            { es: "¿Dónde está el hospital?", ok: false },
            { es: "¿Tiene wifi?", ok: false },
          ] },
        { who: "npc", es: "Son ocho soles la caja. ¿Algo más que necesite?", de: "Das macht acht Soles die Packung. Brauchen Sie noch etwas?", en: "That's eight soles for the box. Anything else you need?" },
        { who: "user", kind: "type", de: "(bedanke dich, das ist alles)", en: "(thank them, that's all)", solEs: "No, gracias, eso es todo.",
          accept: ["no gracias eso es todo", "eso es todo", "no eso es todo", "gracias eso es todo", "nada mas gracias"] },
        { who: "npc", es: "Que se mejore pronto. ¡Que esté bien!", de: "Gute Besserung. Alles Gute!", en: "Get well soon. All the best!" },
      ],
    },
    {
      id: "hostel01", cat: "hostel", title: "Im Gemeinschaftsraum", titleEn: "In the common room", lvl: 2,
      turns: [
        { who: "npc", es: "¡Hola! ¿Recién llegas? No te había visto por aquí.", de: "Hi! Gerade angekommen? Ich hab dich hier noch nicht gesehen.", en: "Hi! Just arrived? I hadn't seen you around here." },
        { who: "user", kind: "type", de: "(sag, ja, du bist gerade angekommen)", en: "(say yes, you've just arrived)", solEs: "Sí, acabo de llegar.",
          accept: ["si acabo de llegar", "acabo de llegar", "recien llegue", "si recien llego", "llegue hace poco"] },
        { who: "npc", es: "¡Bienvenido! ¿De dónde eres?", de: "Willkommen! Woher kommst du?", en: "Welcome! Where are you from?" },
        { who: "user", kind: "type", de: "(sag, du kommst aus Deutschland)", en: "(say you're from Germany)", solEs: "Soy de Alemania.",
          accept: ["soy de alemania", "de alemania", "vengo de alemania", "yo soy de alemania", "soy aleman"] },
        { who: "npc", es: "¡Qué bueno! ¿Y es tu primera vez en Perú?", de: "Wie schön! Und bist du zum ersten Mal in Peru?", en: "How nice! And is it your first time in Peru?" },
        { who: "user", kind: "mc", de: "(sag: ja, das erste Mal)", en: "(say: yes, the first time)", solEs: "Sí, es mi primera vez.",
          options: [
            { es: "Sí, es mi primera vez.", ok: true },
            { es: "No, vivo aquí.", ok: false },
            { es: "No me gusta viajar.", ok: false },
          ] },
        { who: "npc", es: "¡Te va a encantar! ¿Cuánto tiempo vas a quedarte?", de: "Es wird dir gefallen! Wie lange bleibst du?", en: "You're going to love it! How long are you staying?" },
        { who: "user", kind: "mc", de: "(sag: drei Nächte)", en: "(say: three nights)", solEs: "Tres noches.",
          options: [
            { es: "Tres noches.", ok: true },
            { es: "Cuesta mucho.", ok: false },
            { es: "Estoy perdido.", ok: false },
          ] },
        { who: "npc", es: "¿Y ya sabes qué vas a visitar? Hay un montón que ver.", de: "Und weißt du schon, was du besichtigen willst? Es gibt jede Menge zu sehen.", en: "And do you know yet what you're going to visit? There's loads to see." },
        { who: "user", kind: "type", de: "(sag, du willst Machu Picchu sehen)", en: "(say you want to see Machu Picchu)", solEs: "Quiero ver Machu Picchu.",
          accept: ["quiero ver machu picchu", "quiero ir a machu picchu", "ver machu picchu", "quiero conocer machu picchu", "machu picchu"] },
        { who: "npc", es: "¡Obvio! Tienes que ir. Oye, ¿quieres que te recomiende un buen restaurante?", de: "Klar! Da musst du hin. Hey, soll ich dir ein gutes Restaurant empfehlen?", en: "Obviously! You've got to go. Hey, want me to recommend a good restaurant?" },
        { who: "user", kind: "mc", de: "(sag begeistert ja)", en: "(say yes, enthusiastically)", solEs: "¡Sí, por favor, me encantaría!",
          options: [
            { es: "¡Sí, por favor, me encantaría!", ok: true },
            { es: "No, no tengo hambre.", ok: false },
            { es: "¿Cuánto cuesta la cama?", ok: false },
          ] },
        { who: "npc", es: "Hay uno aquí cerca, comida típica, baratísimo. Varios vamos hoy. ¿Te apuntas?", de: "Es gibt eins ganz in der Nähe, typisches Essen, spottbillig. Ein paar von uns gehen heute hin. Bist du dabei?", en: "There's one nearby, typical food, dirt cheap. A few of us are going today. Are you in?" },
        { who: "user", kind: "mc", de: "(sag begeistert zu)", en: "(say yes, enthusiastically)", solEs: "¡Claro, me apunto!",
          options: [
            { es: "¡Claro, me apunto!", ok: true },
            { es: "No, estoy lleno.", ok: false },
            { es: "Otra vez, por favor.", ok: false },
          ] },
        { who: "npc", es: "¡Genial! ¿A qué hora te viene bien? ¿Como a las ocho?", de: "Super! Wann passt es dir? So gegen acht?", en: "Great! What time works for you? Around eight?" },
        { who: "user", kind: "type", de: "(sag, acht Uhr ist perfekt)", en: "(say eight o'clock is perfect)", solEs: "A las ocho está perfecto.",
          accept: ["a las ocho esta perfecto", "a las ocho", "perfecto a las ocho", "las ocho esta bien", "a las ocho me viene bien"] },
        { who: "npc", es: "¡Listo! Nos vemos a las ocho aquí en la sala. ¡Qué chévere conocerte!", de: "Abgemacht! Wir sehen uns um acht hier im Aufenthaltsraum. Schön, dich kennenzulernen!", en: "Sorted! See you at eight here in the common room. So nice to meet you!" },
      ],
    },
    {
      id: "frontera01", cat: "frontera", title: "Einreise-Kontrolle", titleEn: "Immigration control", lvl: 2,
      turns: [
        { who: "npc", es: "Buenas. Pasaporte, por favor.", de: "Guten Tag. Reisepass, bitte.", en: "Hello. Passport, please." },
        { who: "user", kind: "type", de: "(sag, hier bitte, und reich den Pass)", en: "(say here you go and hand over the passport)", solEs: "Sí, aquí tiene.",
          accept: ["aqui tiene", "si aqui tiene", "aqui esta", "tenga", "aqui tiene mi pasaporte"] },
        { who: "npc", es: "Gracias. ¿Cuál es el motivo de su viaje?", de: "Danke. Was ist der Grund Ihrer Reise?", en: "Thanks. What's the purpose of your trip?" },
        { who: "user", kind: "mc", de: "(sag, du bist als Tourist hier)", en: "(say you're here as a tourist)", solEs: "Soy turista, vengo de vacaciones.",
          options: [
            { es: "Soy turista, vengo de vacaciones.", ok: true },
            { es: "Vengo a trabajar aquí.", ok: false },
            { es: "No sé, gracias.", ok: false },
          ] },
        { who: "npc", es: "¿Cuántos días piensa quedarse en el país?", de: "Wie viele Tage möchten Sie im Land bleiben?", en: "How many days are you planning to stay in the country?" },
        { who: "user", kind: "type", de: "(sag: zwei Wochen)", en: "(say: two weeks)", solEs: "Dos semanas.",
          accept: ["dos semanas", "unas dos semanas", "catorce dias", "quince dias", "dos semanas mas o menos"] },
        { who: "npc", es: "¿Tiene dónde quedarse durante su estadía?", de: "Haben Sie eine Unterkunft für Ihren Aufenthalt?", en: "Do you have somewhere to stay during your visit?" },
        { who: "user", kind: "mc", de: "(sag, du hast ein Hostel reserviert)", en: "(say you've booked a hostel)", solEs: "Sí, tengo una reserva en un hostal.",
          options: [
            { es: "Sí, tengo una reserva en un hostal.", ok: true },
            { es: "No, no tengo nada.", ok: false },
            { es: "Quiero un boleto de bus.", ok: false },
          ] },
        { who: "npc", es: "¿Me puede mostrar la reserva o la dirección, por favor?", de: "Können Sie mir die Reservierung oder die Adresse zeigen, bitte?", en: "Could you show me the booking or the address, please?" },
        { who: "user", kind: "type", de: "(sag, ja, du hast sie auf dem Handy)", en: "(say yes, you have it on your phone)", solEs: "Sí, la tengo en el celular.",
          accept: ["si la tengo en el celular", "la tengo en el celular", "esta en mi celular", "en el celular", "si en el celular"] },
        { who: "npc", es: "Muy bien. ¿Trae algo que declarar? ¿Alimentos, plantas?", de: "Sehr gut. Haben Sie etwas zu verzollen? Lebensmittel, Pflanzen?", en: "Very good. Do you have anything to declare? Food, plants?" },
        { who: "user", kind: "mc", de: "(sag, du hast nichts zu verzollen)", en: "(say you have nothing to declare)", solEs: "No, no traigo nada que declarar.",
          options: [
            { es: "No, no traigo nada que declarar.", ok: true },
            { es: "Sí, traigo mucha comida.", ok: false },
            { es: "No entiendo la pregunta.", ok: false },
          ] },
        { who: "npc", es: "¿Tiene boleto de salida del país?", de: "Haben Sie ein Ausreiseticket?", en: "Do you have a ticket to leave the country?" },
        { who: "user", kind: "type", de: "(sag, ja, du fliegst in zwei Wochen zurück)", en: "(say yes, you fly back in two weeks)", solEs: "Sí, regreso en dos semanas.",
          accept: ["si regreso en dos semanas", "regreso en dos semanas", "vuelvo en dos semanas", "si vuelvo en dos semanas", "regreso en quince dias"] },
        { who: "npc", es: "Perfecto. Aquí tiene su pasaporte sellado. Bienvenido al país.", de: "Perfekt. Hier ist Ihr abgestempelter Reisepass. Willkommen im Land.", en: "Perfect. Here's your stamped passport. Welcome to the country." },
        { who: "user", kind: "type", de: "(bedanke dich)", en: "(thank them)", solEs: "Muchas gracias.",
          accept: ["muchas gracias", "gracias", "muchas gracias muy amable", "mil gracias", "gracias muy amable"] },
        { who: "npc", es: "Que disfrute su viaje. ¡Buena estadía!", de: "Genießen Sie Ihre Reise. Schönen Aufenthalt!", en: "Enjoy your trip. Have a good stay!" },
      ],
    },
    {
      id: "emergencia01", cat: "emergencia", title: "Hilfe rufen", titleEn: "Calling for help", lvl: 2,
      turns: [
        { who: "npc", es: "¿Está bien? ¿Qué pasó? Lo vi caerse.", de: "Geht es Ihnen gut? Was ist passiert? Ich habe Sie stürzen sehen.", en: "Are you all right? What happened? I saw you fall." },
        { who: "user", kind: "type", de: "(bitte dringend um Hilfe)", en: "(urgently ask for help)", solEs: "¡Necesito ayuda, por favor!",
          accept: ["necesito ayuda", "necesito ayuda por favor", "ayuda por favor", "ayudenme", "ayuda"] },
        { who: "npc", es: "Tranquilo, lo voy a ayudar. ¿Qué le pasó?", de: "Ruhig, ich helfe Ihnen. Was ist Ihnen passiert?", en: "Stay calm, I'm going to help you. What happened to you?" },
        { who: "user", kind: "mc", de: "(sag, du bist hingefallen)", en: "(say you fell over)", solEs: "Me caí y me golpeé.",
          options: [
            { es: "Me caí y me golpeé.", ok: true },
            { es: "Quiero la cuenta.", ok: false },
            { es: "Estoy de vacaciones.", ok: false },
          ] },
        { who: "npc", es: "¿Le duele algo? ¿Dónde le duele?", de: "Tut Ihnen etwas weh? Wo tut es weh?", en: "Does anything hurt? Where does it hurt?" },
        { who: "user", kind: "mc", de: "(sag, dein Bein tut sehr weh)", en: "(say your leg hurts a lot)", solEs: "Sí, me duele mucho la pierna.",
          options: [
            { es: "Sí, me duele mucho la pierna.", ok: true },
            { es: "No, estoy bien, gracias.", ok: false },
            { es: "Necesito un taxi.", ok: false },
          ] },
        { who: "npc", es: "No se mueva. ¿Quiere que llame a una ambulancia?", de: "Bewegen Sie sich nicht. Soll ich einen Krankenwagen rufen?", en: "Don't move. Would you like me to call an ambulance?" },
        { who: "user", kind: "type", de: "(sag: ja, bitte ruf einen Krankenwagen)", en: "(say: yes, please call an ambulance)", solEs: "Sí, llame a una ambulancia, por favor.",
          accept: ["si llame a una ambulancia", "llame a una ambulancia", "llame una ambulancia por favor", "si una ambulancia", "llame a la ambulancia"] },
        { who: "npc", es: "Ya la estoy llamando. ¿Cómo se llama usted?", de: "Ich rufe ihn schon. Wie heißen Sie?", en: "I'm calling it now. What's your name?" },
        { who: "user", kind: "type", de: "(nenne deinen Namen: Marco)", en: "(give your name: Marco)", solEs: "Me llamo Marco.",
          accept: ["me llamo marco", "soy marco", "marco", "mi nombre es marco", "me llaman marco"] },
        { who: "npc", es: "Marco, ¿puede mover los dedos del pie?", de: "Marco, können Sie die Zehen bewegen?", en: "Marco, can you move your toes?" },
        { who: "user", kind: "mc", de: "(sag, ja, ein bisschen)", en: "(say yes, a little)", solEs: "Sí, un poco.",
          options: [
            { es: "Sí, un poco.", ok: true },
            { es: "No siento nada.", ok: false },
            { es: "No, gracias.", ok: false },
          ] },
        { who: "npc", es: "Bien, eso es buena señal. ¿Está tomando algún medicamento?", de: "Gut, das ist ein gutes Zeichen. Nehmen Sie irgendein Medikament?", en: "Good, that's a good sign. Are you taking any medication?" },
        { who: "user", kind: "mc", de: "(sag, nein, keine Medikamente)", en: "(say no, no medication)", solEs: "No, ningún medicamento.",
          options: [
            { es: "No, ningún medicamento.", ok: true },
            { es: "Sí, muchos.", ok: false },
            { es: "No sé dónde estoy.", ok: false },
          ] },
        { who: "npc", es: "La ambulancia ya viene en camino. Quédese quieto, yo me quedo con usted.", de: "Der Krankenwagen ist schon unterwegs. Bleiben Sie ruhig liegen, ich bleibe bei Ihnen.", en: "The ambulance is on its way. Stay still, I'll stay with you." },
        { who: "user", kind: "type", de: "(bedanke dich erleichtert)", en: "(thank them, relieved)", solEs: "Muchas gracias por su ayuda.",
          accept: ["muchas gracias por su ayuda", "gracias por su ayuda", "muchas gracias", "gracias", "mil gracias"] },
        { who: "npc", es: "No se preocupe. Todo va a estar bien. La ayuda ya casi llega.", de: "Keine Sorge. Alles wird gut. Die Hilfe ist gleich da.", en: "Don't worry. Everything's going to be fine. Help is almost here." },
      ],
    },
    {
      id: "calle01", cat: "calle", title: "Wo ist die Bushaltestelle?", titleEn: "Where is the bus stop?", lvl: 1,
      turns: [
        { who: "npc", es: "¿Sí? ¿Necesita ayuda? Lo veo un poco perdido.", de: "Ja? Brauchen Sie Hilfe? Sie wirken etwas verloren.", en: "Yes? Do you need help? You look a bit lost." },
        { who: "user", kind: "mc", de: "(frag höflich, wo die Bushaltestelle ist)", en: "(politely ask where the bus stop is)", solEs: "Disculpe, ¿dónde está el paradero?",
          options: [
            { es: "Disculpe, ¿dónde está el paradero?", ok: true },
            { es: "¿Qué hora es?", ok: false },
            { es: "¿Cuánto cuesta?", ok: false },
          ] },
        { who: "npc", es: "¿El paradero? ¿Para qué bus, el que va al centro?", de: "Die Haltestelle? Für welchen Bus, den ins Zentrum?", en: "The bus stop? For which bus, the one to the centre?" },
        { who: "user", kind: "type", de: "(sag, ja, ins Zentrum)", en: "(say yes, to the centre)", solEs: "Sí, al centro.",
          accept: ["si al centro", "al centro", "si quiero ir al centro", "al centro por favor", "si para el centro"] },
        { who: "npc", es: "Ah, ya. Siga derecho dos cuadras y doble a la derecha.", de: "Ah, gut. Gehen Sie zwei Blocks geradeaus und biegen Sie rechts ab.", en: "Ah, right. Go straight on for two blocks and turn right." },
        { who: "user", kind: "type", de: "(frag nach, ob es weit ist)", en: "(ask whether it's far)", solEs: "¿Está lejos?",
          accept: ["esta lejos", "queda lejos", "es lejos", "esta muy lejos", "esta lejos de aqui"] },
        { who: "npc", es: "No, está cerca. Unos cinco minutos a pie, no más.", de: "Nein, es ist nah. Etwa fünf Minuten zu Fuß, nicht mehr.", en: "No, it's close. About five minutes on foot, no more." },
        { who: "user", kind: "mc", de: "(frag, welcher Bus zum Zentrum fährt)", en: "(ask which bus goes to the centre)", solEs: "¿Qué bus va al centro?",
          options: [
            { es: "¿Qué bus va al centro?", ok: true },
            { es: "¿Tiene un cigarro?", ok: false },
            { es: "¿Dónde vive usted?", ok: false },
          ] },
        { who: "npc", es: "Tome el que dice \"Centro\" o el número veinte. Pasan seguido.", de: "Nehmen Sie den mit „Centro“ oder die Nummer zwanzig. Die kommen oft.", en: "Take the one that says \"Centro\" or number twenty. They come often." },
        { who: "user", kind: "type", de: "(frag, wie viel die Fahrt kostet)", en: "(ask how much the fare is)", solEs: "¿Cuánto cuesta el pasaje?",
          accept: ["cuanto cuesta el pasaje", "cuanto es el pasaje", "cuanto cuesta", "cuanto vale el pasaje", "cuanto cuesta el boleto"] },
        { who: "npc", es: "Un sol cincuenta. Tenga sencillo a la mano, casi no dan vuelto.", de: "Eineinhalb Soles. Halten Sie es passend bereit, Wechselgeld gibt es kaum.", en: "One sol fifty. Keep small change handy, they hardly ever give change." },
        { who: "user", kind: "mc", de: "(frag, ob du dem Fahrer sagen sollst, wo du raus willst)", en: "(ask whether you should tell the driver where to get off)", solEs: "¿Le aviso al chofer dónde bajar?",
          options: [
            { es: "¿Le aviso al chofer dónde bajar?", ok: true },
            { es: "¿Puedo ir en taxi gratis?", ok: false },
            { es: "¿El bus tiene wifi?", ok: false },
          ] },
        { who: "npc", es: "Sí, dígale \"centro\" al subir y él le avisa dónde bajar.", de: "Ja, sagen Sie ihm beim Einsteigen „centro“, dann sagt er Ihnen, wo Sie aussteigen.", en: "Yes, say \"centro\" as you get on and he'll tell you where to get off." },
        { who: "user", kind: "type", de: "(bedanke dich herzlich)", en: "(thank them warmly)", solEs: "Muchas gracias, muy amable.",
          accept: ["muchas gracias muy amable", "muchas gracias", "gracias", "muy amable", "mil gracias"] },
        { who: "npc", es: "De nada. ¡Que le vaya bien y buen viaje!", de: "Gern geschehen. Alles Gute und gute Reise!", en: "You're welcome. Take care and have a good trip!" },
      ],
    },
  ];

  window.SC = window.SC || {};
  window.SC.dialogos = { DIALOGOS_SCENARIOS, DIALOGOS };
})();
