/*
 * dialogos.js  (SC.dialogos) – Daten für die Gesprächs-Simulationen (Diálogos).
 * REINE DATEN, additiv – die Wörterbasis bleibt unangetastet.
 *
 * Idee: echte Reisesituationen Zug für Zug durchspielen. Die Gegenseite (npc)
 * wird angezeigt und – wenn der Browser TTS kann – vorgelesen; der Nutzer
 * antwortet je nach Zug per Multiple-Choice (kind:"mc") oder tippt eine
 * Schlüssel-Replik frei (kind:"type", großzügig per matcher.normalize geprüft).
 *
 * Die Dialoge sind bewusst lang gehalten (7–9 Repliken pro Runde), damit sich
 * ein echtes Gespräch entfaltet statt nur dreier Stichworte.
 *
 * Struktur:
 *   DIALOGOS_SCENARIOS = Menü: { id, title, icon, lvl, intro }
 *   DIALOGOS           = die Dialoge: { id, cat(=scenario.id), title, lvl, turns[] }
 *     turn npc  : { who:"npc",  es, de }
 *     turn mc   : { who:"user", kind:"mc",   de, solEs, why, whyEn, options:[{es, ok}] }
 *     turn type : { who:"user", kind:"type", de, solEs, why, whyEn, accept:[…] }
 *       de    = Handlungsanweisung („(sag, dass du einchecken willst)")
 *       solEs = die Musterantwort (erscheint in der Verlaufsspur)
 *       accept= zusätzlich akzeptierte (normalisierte) Eingaben neben solEs
 *       why / whyEn = kurzer Hintergrund, WARUM die Musterantwort so lautet
 *                     (Grammatik/Wortschatz/Höflichkeit). Erscheint beim
 *                     „Besser so" aufklappbar. Pflichtfeld jedes user-Zugs.
 *
 * Platzhalter {name}: wird beim Anzeigen/Prüfen durch den im Profil hinterlegten
 * Reise-Namen ersetzt (ohne Eintrag bleibt der Beispielname „Marco"). So nennt
 * der Nutzer in den Dialogen seinen eigenen Namen statt eines fremden.
 */
(function () {
  "use strict";

  const DIALOGOS_SCENARIOS = [
    { id: "hotel",      title: "Hotel-Check-in",  titleEn: "Hotel check-in",  icon: "🛎️", lvl: 1, intro: "An der Rezeption einchecken.", introEn: "Check in at reception." },
    { id: "restaurante",title: "Im Restaurant",   titleEn: "At the restaurant",   icon: "🍽️", lvl: 1, intro: "Bestellen, fragen, zahlen.", introEn: "Order, ask, pay." },
    { id: "bus",        title: "Busticket kaufen", titleEn: "Buy a bus ticket", icon: "🚌", lvl: 1, intro: "Am Schalter ein Ticket lösen.", introEn: "Get a ticket at the counter." },
    { id: "taxi",       title: "Taxifahrt",       titleEn: "Taxi ride",       icon: "🚕", lvl: 1, intro: "Ziel nennen und Preis klären.", introEn: "Give your destination and sort out the price." },
    { id: "mercado",    title: "Auf dem Markt",   titleEn: "At the market",   icon: "🛍️", lvl: 2, intro: "Fragen und freundlich feilschen.", introEn: "Ask questions and haggle nicely." },
    { id: "farmacia",   title: "In der Apotheke", titleEn: "At the pharmacy", icon: "💊", lvl: 2, intro: "Beschwerden schildern, Hilfe holen.", introEn: "Describe your symptoms and get help." },
    { id: "hostel",     title: "Hostel-Smalltalk", titleEn: "Hostel small talk", icon: "🛏️", lvl: 2, intro: "Andere Reisende kennenlernen.", introEn: "Get to know other travellers." },
    { id: "frontera",   title: "An der Grenze",   titleEn: "At the border",   icon: "🛂", lvl: 2, intro: "Ein- und Ausreise-Fragen.", introEn: "Entry and exit questions." },
    { id: "emergencia", title: "Notfall",         titleEn: "Emergency",         icon: "🆘", lvl: 2, intro: "Schnell um Hilfe bitten.", introEn: "Ask for help quickly." },
    { id: "calle",      title: "Nach dem Weg fragen", titleEn: "Asking for directions", icon: "🧭", lvl: 1, intro: "Sich auf der Straße orientieren.", introEn: "Find your way around on the street." },
    { id: "coqueteo",   title: "Coquetear con respeto", titleEn: "Flirting with respect", icon: "💘", lvl: 2, intro: "Jemanden kennenlernen: ansprechen, Kompliment, Date – und Konsens.", introEn: "Meeting someone: an opening line, a compliment, a date – and consent." },
  ];

  const DIALOGOS = [
    {
      id: "hotel01", cat: "hotel", title: "An der Rezeption", titleEn: "At reception", lvl: 1,
      turns: [
        { who: "npc", es: "¡Buenas! Bienvenido al Hotel Sol Andino. ¿En qué le puedo ayudar?", de: "Hallo! Willkommen im Hotel Sol Andino. Wie kann ich Ihnen helfen?", en: "Hi there! Welcome to the Hotel Sol Andino. How can I help you?" },
        { who: "user", kind: "mc", de: "(sag, dass du einchecken möchtest)", en: "(say you'd like to check in)", solEs: "Quisiera hacer el check-in, por favor.",
          why: "„Quisiera“ ist die höfliche Konjunktiv-Form von „querer“ – klingt freundlicher als das direkte „quiero“.",
          whyEn: "„Quisiera“ (I would like) is the polite subjunctive of „querer“ – softer than a plain „quiero“.",
          options: [
            { es: "Quisiera hacer el check-in, por favor.", ok: true },
            { es: "La cuenta, por favor.", ok: false },
            { es: "¿Dónde está el baño?", ok: false },
          ] },
        { who: "npc", es: "Claro que sí. ¿A nombre de quién está la reserva?", de: "Aber natürlich. Auf welchen Namen läuft die Reservierung?", en: "Of course. What name is the booking under?" },
        { who: "user", kind: "type", de: "(antworte: auf den Namen {name})", en: "(answer: under the name {name})", solEs: "A nombre de {name}.",
          why: "„A nombre de …“ = „auf den Namen …“ – die feststehende Wendung bei Reservierungen.",
          whyEn: "„A nombre de …“ = „under the name …“ – the set phrase used for bookings.",
          accept: ["a nombre de {name}", "{name}", "es {name}", "me llamo {name}", "esta a nombre de {name}"] },
        { who: "npc", es: "Perfecto, aquí la tengo. Una habitación doble por tres noches, ¿verdad?", de: "Perfekt, hier habe ich sie. Ein Doppelzimmer für drei Nächte, richtig?", en: "Perfect, here it is. A double room for three nights, right?" },
        { who: "user", kind: "mc", de: "(bestätige: ja, genau, drei Nächte)", en: "(confirm: yes, exactly, three nights)", solEs: "Sí, exacto, tres noches.",
          why: "„exacto“ bestätigt kurz „genau so“; „noche“ wird im Plural zu „noches“.",
          whyEn: "„exacto“ is a quick „that's right“; „noche“ becomes „noches“ in the plural.",
          options: [
            { es: "Sí, exacto, tres noches.", ok: true },
            { es: "No, solo una noche.", ok: false },
            { es: "No tengo reserva.", ok: false },
          ] },
        { who: "npc", es: "Muy bien. ¿Me permite su pasaporte, por favor?", de: "Sehr gut. Dürfte ich bitte Ihren Reisepass haben?", en: "Very good. May I have your passport, please?" },
        { who: "user", kind: "type", de: "(sag, hier bitte, und reich ihn rüber)", en: "(say here you go and hand it over)", solEs: "Sí, aquí tiene.",
          why: "„Aquí tiene“ (wörtlich „hier haben Sie“) ist die höfliche Sie-Form beim Überreichen; zu Freunden „aquí tienes“.",
          whyEn: "„Aquí tiene“ (lit. „here you have“) is the polite usted form when handing something over; to a friend it's „aquí tienes“.",
          accept: ["aqui tiene", "si aqui tiene", "aqui esta", "tenga", "aqui lo tiene"] },
        { who: "npc", es: "Gracias. ¿Prefiere una habitación con vista a la calle o una más tranquila?", de: "Danke. Möchten Sie lieber ein Zimmer zur Straße oder ein ruhigeres?", en: "Thanks. Would you prefer a room facing the street or a quieter one?" },
        { who: "user", kind: "mc", de: "(sag, du hättest gern ein ruhiges Zimmer)", en: "(say you'd like a quiet room)", solEs: "Una tranquila, por favor.",
          why: "„una tranquila“ steht für „una habitación tranquila“; das Adjektiv ist weiblich (–a), weil „habitación“ weiblich ist.",
          whyEn: "„una tranquila“ stands for „una habitación tranquila“; the adjective is feminine (–a) because „habitación“ is feminine.",
          options: [
            { es: "Una tranquila, por favor.", ok: true },
            { es: "Con vista a la calle, mejor.", ok: false },
            { es: "Me da igual el precio.", ok: false },
          ] },
        { who: "npc", es: "Entendido. Le doy la habitación doscientos cuatro, en el segundo piso.", de: "Verstanden. Ich gebe Ihnen Zimmer zweihundertvier im zweiten Stock.", en: "Understood. I'll give you room two hundred and four, on the second floor." },
        { who: "user", kind: "type", de: "(frag, um wie viel Uhr es Frühstück gibt)", en: "(ask what time breakfast is)", solEs: "¿A qué hora es el desayuno?",
          why: "„¿A qué hora …?“ = „Um wie viel Uhr …?“; das kleine „a“ gehört fest zur Uhrzeit-Frage.",
          whyEn: "„¿A qué hora …?“ = „At what time …?“; the little „a“ is part of asking about a time.",
          accept: ["a que hora es el desayuno", "cuando es el desayuno", "a que hora el desayuno", "a que hora hay desayuno"] },
        { who: "npc", es: "De siete a diez de la mañana, en el comedor de la planta baja.", de: "Von sieben bis zehn Uhr morgens, im Speisesaal im Erdgeschoss.", en: "From seven to ten in the morning, in the dining room on the ground floor." },
        { who: "user", kind: "mc", de: "(frag, ob es WLAN im Zimmer gibt)", en: "(ask whether there's WiFi in the room)", solEs: "¿Hay wifi en la habitación?",
          why: "„hay“ = „es gibt“ und bleibt unverändert – egal ob Singular oder Plural.",
          whyEn: "„hay“ = „there is/are“ and never changes – singular or plural.",
          options: [
            { es: "¿Hay wifi en la habitación?", ok: true },
            { es: "¿Tienen piscina?", ok: false },
            { es: "¿Puedo pagar mañana?", ok: false },
          ] },
        { who: "npc", es: "Sí, la clave está en el reverso de su tarjeta-llave. Aquí tiene.", de: "Ja, das Passwort steht auf der Rückseite Ihrer Schlüsselkarte. Hier bitte.", en: "Yes, the password is on the back of your key card. Here you go." },
        { who: "user", kind: "type", de: "(bedanke dich freundlich)", en: "(thank them warmly)", solEs: "Muchas gracias, muy amable.",
          why: "„muchas“ passt sich an „gracias“ an (weiblich, Plural); „muy amable“ = „sehr freundlich“ als kleines Kompliment.",
          whyEn: "„muchas“ agrees with „gracias“ (feminine plural); „muy amable“ = „very kind“ as a little compliment.",
          accept: ["muchas gracias muy amable", "muchas gracias", "gracias", "mil gracias", "muy amable, gracias"] },
        { who: "npc", es: "A usted. Cualquier cosa, estamos en recepción las veinticuatro horas. ¡Que descanse!", de: "Gern. Bei Fragen: Die Rezeption ist rund um die Uhr besetzt. Gute Erholung!", en: "Thank you. If you need anything, reception is staffed around the clock. Have a good rest!" },
      ],
    },
    {
      id: "restaurante01", cat: "restaurante", title: "Bestellen & zahlen", titleEn: "Ordering & paying", lvl: 1,
      turns: [
        { who: "npc", es: "Buenas tardes, bienvenidos. ¿Mesa para cuántas personas?", de: "Guten Tag, willkommen. Ein Tisch für wie viele Personen?", en: "Good afternoon, welcome. A table for how many people?" },
        { who: "user", kind: "mc", de: "(sag: ein Tisch für zwei)", en: "(say: a table for two)", solEs: "Una mesa para dos, por favor.",
          why: "„para dos“ = „für zwei (Personen)“; „para“ gibt hier den Zweck/Empfänger an.",
          whyEn: "„para dos“ = „for two (people)“; „para“ marks the purpose/recipient here.",
          options: [
            { es: "Una mesa para dos, por favor.", ok: true },
            { es: "La cuenta, por favor.", ok: false },
            { es: "Estoy lleno, gracias.", ok: false },
          ] },
        { who: "npc", es: "Perfecto, síganme. ¿Esta mesa junto a la ventana les parece bien?", de: "Perfekt, folgen Sie mir. Ist dieser Tisch am Fenster in Ordnung?", en: "Perfect, follow me. Is this table by the window all right?" },
        { who: "user", kind: "mc", de: "(sag, der Tisch ist super)", en: "(say the table is great)", solEs: "Sí, está perfecta, gracias.",
          why: "„está“ (von estar) für einen aktuellen Zustand; „perfecta“ weiblich wegen „mesa“.",
          whyEn: "„está“ (from estar) for a current state; „perfecta“ is feminine because of „mesa“.",
          options: [
            { es: "Sí, está perfecta, gracias.", ok: true },
            { es: "No, prefiero afuera en la calle.", ok: false },
            { es: "No hablo español.", ok: false },
          ] },
        { who: "npc", es: "Aquí tienen la carta. ¿Algo para tomar mientras deciden?", de: "Hier ist die Speisekarte. Etwas zu trinken, während Sie sich entscheiden?", en: "Here's the menu. Something to drink while you decide?" },
        { who: "user", kind: "type", de: "(bestelle zwei Wasser)", en: "(order two waters)", solEs: "Dos aguas, por favor.",
          why: "Beim Bestellen zählt man „agua“: „dos aguas“ (zwei Wasser/Flaschen) ist im Lokal völlig normal.",
          whyEn: "When ordering you count „agua“: „dos aguas“ (two waters) is perfectly normal in a café.",
          accept: ["dos aguas", "dos aguas por favor", "dos botellas de agua", "queremos dos aguas", "dos aguas porfa"] },
        { who: "npc", es: "Enseguida se las traigo. ¿Ya saben qué van a pedir de comer?", de: "Bringe ich gleich. Wissen Sie schon, was Sie essen möchten?", en: "I'll bring them right over. Do you know yet what you'd like to eat?" },
        { who: "user", kind: "type", de: "(frag, was das Tagesgericht ist)", en: "(ask what the dish of the day is)", solEs: "¿Cuál es el plato del día?",
          why: "„¿Cuál es …?“ fragt nach einer Auswahl („welches“); „del“ ist die Verschmelzung de + el.",
          whyEn: "„¿Cuál es …?“ asks about a choice („which one“); „del“ is de + el merged.",
          accept: ["cual es el plato del dia", "que es el plato del dia", "que hay de plato del dia", "cual es el menu del dia"] },
        { who: "npc", es: "Hoy tenemos lomo saltado con arroz y papas. Está muy rico.", de: "Heute gibt es Lomo Saltado mit Reis und Kartoffeln. Es ist sehr lecker.", en: "Today we've got lomo saltado with rice and potatoes. It's really tasty." },
        { who: "user", kind: "mc", de: "(bestelle das Tagesgericht zweimal)", en: "(order the dish of the day twice)", solEs: "Entonces dos platos del día, por favor.",
          why: "„entonces“ = „dann/also“ knüpft an das Gesagte an; „plato“ wird im Plural zu „platos“.",
          whyEn: "„entonces“ = „then/so“ picks up on what was said; „plato“ becomes „platos“ in the plural.",
          options: [
            { es: "Entonces dos platos del día, por favor.", ok: true },
            { es: "No, gracias, solo la cuenta.", ok: false },
            { es: "¿Tienen mesa para dos?", ok: false },
          ] },
        { who: "npc", es: "Excelente elección. ¿Desean algo más, un postre quizás?", de: "Ausgezeichnete Wahl. Möchten Sie noch etwas, vielleicht ein Dessert?", en: "Excellent choice. Would you like anything else, a dessert perhaps?" },
        { who: "user", kind: "mc", de: "(lehne höflich ab – erst mal nichts weiter)", en: "(politely decline – nothing more for now)", solEs: "No, así está bien, gracias.",
          why: "„así está bien“ = „so ist es gut“ – die höfliche Art, „nein danke, das reicht“ zu sagen.",
          whyEn: "„así está bien“ = „it's fine like this“ – the polite way to say „no thanks, that's enough“.",
          options: [
            { es: "No, así está bien, gracias.", ok: true },
            { es: "Sí, la cuenta, por favor.", ok: false },
            { es: "No tengo hambre.", ok: false },
          ] },
        { who: "npc", es: "Muy bien. … (más tarde) ¿Qué tal estuvo todo? ¿Les gustó?", de: "Sehr gut. … (später) Wie war alles? Hat es geschmeckt?", en: "Very good. … (later) How was everything? Did you enjoy it?" },
        { who: "user", kind: "type", de: "(sag, es war sehr lecker)", en: "(say it was really tasty)", solEs: "Estuvo todo muy rico.",
          why: "„estuvo“ (Indefinido von estar) für etwas Abgeschlossenes; beim Essen heißt „rico“ „lecker“.",
          whyEn: "„estuvo“ (preterite of estar) for something finished; with food „rico“ means „tasty“.",
          accept: ["estuvo todo muy rico", "muy rico", "estuvo muy rico", "todo muy rico", "estaba muy rico"] },
        { who: "npc", es: "Me alegra mucho. ¿Les traigo algo más o ya la cuenta?", de: "Das freut mich sehr. Bringe ich Ihnen noch etwas, oder schon die Rechnung?", en: "I'm really glad. Shall I bring you anything else, or the bill now?" },
        { who: "user", kind: "type", de: "(bitte um die Rechnung)", en: "(ask for the bill)", solEs: "La cuenta, por favor.",
          why: "„la cuenta“ = „die Rechnung“; das Wort ist weiblich, daher „la“.",
          whyEn: "„la cuenta“ = „the bill“; the word is feminine, hence „la“.",
          accept: ["la cuenta por favor", "la cuenta", "me trae la cuenta", "nos trae la cuenta", "la cuenta porfa"] },
        { who: "npc", es: "Claro, ya se la traigo. ¿Van a pagar en efectivo o con tarjeta?", de: "Klar, ich bringe sie. Zahlen Sie bar oder mit Karte?", en: "Of course, I'll bring it. Will you pay by cash or card?" },
        { who: "user", kind: "mc", de: "(sag: mit Karte)", en: "(say: by card)", solEs: "Con tarjeta, por favor.",
          why: "„con“ = „mit“; „pagar con tarjeta / en efectivo“ sind die festen Wendungen fürs Bezahlen.",
          whyEn: "„con“ = „with“; „pagar con tarjeta / en efectivo“ are the set phrases for paying.",
          options: [
            { es: "Con tarjeta, por favor.", ok: true },
            { es: "En efectivo.", ok: false },
            { es: "Pago mañana.", ok: false },
          ] },
        { who: "npc", es: "Perfecto. Muchas gracias por su visita. ¡Vuelvan pronto!", de: "Perfekt. Vielen Dank für Ihren Besuch. Kommen Sie bald wieder!", en: "Perfect. Thank you very much for your visit. Come back soon!" },
      ],
    },
    {
      id: "bus01", cat: "bus", title: "Am Busschalter", titleEn: "At the bus counter", lvl: 1,
      turns: [
        { who: "npc", es: "¡Siguiente, por favor! ¿Para dónde va?", de: "Der Nächste bitte! Wohin möchten Sie?", en: "Next, please! Where are you heading?" },
        { who: "user", kind: "type", de: "(sag, du willst ein Ticket nach Cusco)", en: "(say you want a ticket to Cusco)", solEs: "Quiero un boleto para Cusco.",
          why: "„boleto“ ist in Lateinamerika das Ticket; „para Cusco“ gibt das Ziel an.",
          whyEn: "„boleto“ is the word for ticket in Latin America; „para Cusco“ marks the destination.",
          accept: ["quiero un boleto para cusco", "un boleto para cusco", "para cusco", "un pasaje para cusco", "quiero un pasaje para cusco"] },
        { who: "npc", es: "Muy bien. ¿Para hoy o para mañana?", de: "Sehr gut. Für heute oder für morgen?", en: "Very good. For today or for tomorrow?" },
        { who: "user", kind: "mc", de: "(sag: für morgen früh)", en: "(say: for tomorrow morning)", solEs: "Para mañana en la mañana.",
          why: "„mañana“ heißt „morgen“ UND „Morgen“ – „en la mañana“ stellt klar: am Vormittag.",
          whyEn: "„mañana“ means both „tomorrow“ and „morning“ – „en la mañana“ makes clear: in the morning.",
          options: [
            { es: "Para mañana en la mañana.", ok: true },
            { es: "Para hoy en la noche.", ok: false },
            { es: "No sé, gracias.", ok: false },
          ] },
        { who: "npc", es: "Tenemos uno a las ocho y otro a las diez. ¿Cuál prefiere?", de: "Wir haben einen um acht und einen um zehn. Welchen möchten Sie?", en: "We've got one at eight and another at ten. Which would you prefer?" },
        { who: "user", kind: "mc", de: "(nimm den um acht)", en: "(take the eight o'clock one)", solEs: "El de las ocho, por favor.",
          why: "„el de las ocho“ = „der von acht (Uhr)“; „el de …“ spart das Wort „bus“ ein.",
          whyEn: "„el de las ocho“ = „the eight o'clock one“; „el de …“ drops the word „bus“.",
          options: [
            { es: "El de las ocho, por favor.", ok: true },
            { es: "El de medianoche.", ok: false },
            { es: "Ninguno, gracias.", ok: false },
          ] },
        { who: "npc", es: "¿Asiento normal o cama? El cama es más cómodo para el viaje largo.", de: "Normaler Sitz oder Liegesitz? Der Liegesitz ist bequemer für die lange Fahrt.", en: "A normal seat or a reclining one? The reclining seat is more comfortable for the long journey." },
        { who: "user", kind: "type", de: "(sag, du willst einen normalen Sitz)", en: "(say you want a normal seat)", solEs: "Asiento normal, por favor.",
          why: "Das Adjektiv steht hinter dem Nomen: „asiento normal“, nicht „normal asiento“.",
          whyEn: "The adjective follows the noun: „asiento normal“, not „normal asiento“.",
          accept: ["asiento normal", "asiento normal por favor", "un asiento normal", "normal por favor", "el normal"] },
        { who: "npc", es: "Perfecto. ¿Prefiere ventana o pasillo?", de: "Perfekt. Möchten Sie lieber Fenster oder Gang?", en: "Perfect. Would you prefer window or aisle?" },
        { who: "user", kind: "mc", de: "(sag: Fenster)", en: "(say: window)", solEs: "Ventana, por favor.",
          why: "Kurzantwort: das Stichwort allein + „por favor“ reicht im Gespräch völlig aus.",
          whyEn: "Short answer: just the keyword + „por favor“ is plenty in conversation.",
          options: [
            { es: "Ventana, por favor.", ok: true },
            { es: "Pasillo, mejor.", ok: false },
            { es: "Me da igual el horario.", ok: false },
          ] },
        { who: "npc", es: "Listo. ¿Me da su nombre completo, por favor?", de: "Geht klar. Geben Sie mir bitte Ihren vollständigen Namen?", en: "Right. Could you give me your full name, please?" },
        { who: "user", kind: "type", de: "(nenne deinen Namen: {name} Pérez)", en: "(give your name: {name} Pérez)", solEs: "{name} Pérez.",
          why: "Auf die Frage nach dem Namen genügt der Name allein – knapp und natürlich.",
          whyEn: "To a name question, just the name is enough – brief and natural.",
          accept: ["{name} perez", "me llamo {name} perez", "soy {name} perez", "mi nombre es {name} perez"] },
        { who: "npc", es: "Gracias. Son cuarenta soles. ¿Cómo va a pagar?", de: "Danke. Das macht vierzig Soles. Wie möchten Sie zahlen?", en: "Thanks. That's forty soles. How would you like to pay?" },
        { who: "user", kind: "mc", de: "(sag: bar)", en: "(say: cash)", solEs: "En efectivo.",
          why: "„en efectivo“ = „bar“; feste Wendung mit „en“.",
          whyEn: "„en efectivo“ = „(in) cash“; a set phrase with „en“.",
          options: [
            { es: "En efectivo.", ok: true },
            { es: "¿Puedo pagar en Cusco?", ok: false },
            { es: "No tengo dinero.", ok: false },
          ] },
        { who: "npc", es: "Aquí tiene su boleto y su vuelto. El bus sale del andén número cinco.", de: "Hier ist Ihr Ticket und Ihr Wechselgeld. Der Bus fährt von Bahnsteig fünf.", en: "Here's your ticket and your change. The bus leaves from platform five." },
        { who: "user", kind: "type", de: "(frag nach, wie lange die Fahrt dauert)", en: "(ask how long the journey takes)", solEs: "¿Cuánto dura el viaje?",
          why: "„durar“ = „dauern“; „¿Cuánto dura …?“ = „Wie lange dauert …?“.",
          whyEn: "„durar“ = „to last“; „¿Cuánto dura …?“ = „How long does … take?“.",
          accept: ["cuanto dura el viaje", "cuanto demora el viaje", "cuanto tiempo dura el viaje", "cuanto se demora", "cuanto dura"] },
        { who: "npc", es: "Unas seis horas, llega a las dos de la tarde. ¡Buen viaje!", de: "Etwa sechs Stunden, Ankunft um zwei Uhr nachmittags. Gute Reise!", en: "About six hours, arriving at two in the afternoon. Have a good trip!" },
      ],
    },
    {
      id: "taxi01", cat: "taxi", title: "Ins Zentrum", titleEn: "Into the centre", lvl: 1,
      turns: [
        { who: "npc", es: "¡Buenas! ¿A dónde lo llevo?", de: "Hallo! Wohin darf ich Sie fahren?", en: "Hi there! Where can I take you?" },
        { who: "user", kind: "type", de: "(sag, du willst zum Stadtzentrum)", en: "(say you want to go to the city centre)", solEs: "Al centro, por favor.",
          why: "„al“ ist a + el; „al centro“ = „ins Zentrum“ – Richtung mit „a“.",
          whyEn: "„al“ is a + el; „al centro“ = „to the centre“ – direction with „a“.",
          accept: ["al centro", "al centro por favor", "quiero ir al centro", "voy al centro", "al centro porfa"] },
        { who: "npc", es: "Claro. ¿Conoce la dirección exacta o lo dejo en la plaza?", de: "Klar. Kennen Sie die genaue Adresse oder setze ich Sie an der Plaza ab?", en: "Sure. Do you know the exact address, or shall I drop you at the plaza?" },
        { who: "user", kind: "mc", de: "(sag, an der Plaza ist gut)", en: "(say the plaza is fine)", solEs: "Déjeme en la plaza, está bien.",
          why: "„déjeme“ = höflicher Befehl (Sie-Form) von „dejar“ + „me“ = „setzen Sie mich ab“.",
          whyEn: "„déjeme“ = polite command (usted) of „dejar“ + „me“ = „drop me off“.",
          options: [
            { es: "Déjeme en la plaza, está bien.", ok: true },
            { es: "No sé dónde estoy.", ok: false },
            { es: "¿Puedo pagar mañana?", ok: false },
          ] },
        { who: "npc", es: "Perfecto. ¿Tiene apuro o vamos con calma?", de: "Perfekt. Haben Sie es eilig oder fahren wir gemütlich?", en: "Perfect. Are you in a hurry or shall we take it easy?" },
        { who: "user", kind: "mc", de: "(frag vorher, wie viel die Fahrt kostet)", en: "(ask first how much the ride costs)", solEs: "¿Cuánto cuesta hasta allá?",
          why: "Erst den Preis klären! „¿Cuánto cuesta?“ = „Was kostet es?“; „hasta allá“ = „bis dorthin“.",
          whyEn: "Settle the price first! „¿Cuánto cuesta?“ = „How much is it?“; „hasta allá“ = „all the way there“.",
          options: [
            { es: "¿Cuánto cuesta hasta allá?", ok: true },
            { es: "¿Tiene cambio de cien?", ok: false },
            { es: "¿Es muy lejos su casa?", ok: false },
          ] },
        { who: "npc", es: "Unos quince soles, más o menos. ¿Le parece bien?", de: "So um die fünfzehn Soles, mehr oder weniger. Geht das in Ordnung?", en: "Around fifteen soles, more or less. Does that sound all right?" },
        { who: "user", kind: "mc", de: "(stimm zu und bitte ihn loszufahren)", en: "(agree and ask them to set off)", solEs: "Está bien, vamos.",
          why: "„vamos“ = „los/fahren wir“ – die 1. Person Plural als Aufforderung.",
          whyEn: "„vamos“ = „let's go“ – the 1st-person plural used as a prompt.",
          options: [
            { es: "Está bien, vamos.", ok: true },
            { es: "No, gracias, camino.", ok: false },
            { es: "Es muy barato.", ok: false },
          ] },
        { who: "npc", es: "(en el camino) ¿Es la primera vez que visita la ciudad?", de: "(unterwegs) Sind Sie zum ersten Mal in der Stadt?", en: "(on the way) Is it your first time in the city?" },
        { who: "user", kind: "type", de: "(sag: ja, du bist Tourist)", en: "(say: yes, you're a tourist)", solEs: "Sí, soy turista.",
          why: "„ser“ (soy) für eine dauerhafte Eigenschaft/Rolle wie „Tourist“.",
          whyEn: "„ser“ (soy) for a lasting trait/role such as „tourist“.",
          accept: ["si soy turista", "soy turista", "vengo de turista", "si de vacaciones", "si estoy de vacaciones"] },
        { who: "npc", es: "¡Qué bueno! ¿De qué país viene, si no es indiscreción?", de: "Wie schön! Aus welchem Land kommen Sie, wenn ich fragen darf?", en: "How lovely! Which country are you from, if you don't mind me asking?" },
        { who: "user", kind: "type", de: "(sag, du kommst aus Deutschland)", en: "(say you're from Germany)", solEs: "Vengo de Alemania.",
          why: "„venir de“ = „kommen aus“; Länder stehen hier ohne Artikel: „de Alemania“.",
          whyEn: "„venir de“ = „to come from“; countries take no article here: „de Alemania“.",
          accept: ["vengo de alemania", "soy de alemania", "de alemania", "soy aleman", "yo soy de alemania"] },
        { who: "npc", es: "¡Alemania, qué lejos! ¿Le pongo un poco de música o prefiere tranquilo?", de: "Deutschland, so weit weg! Soll ich etwas Musik anmachen oder lieber ruhig?", en: "Germany, so far away! Shall I put on some music, or would you rather have it quiet?" },
        { who: "user", kind: "mc", de: "(sag, etwas Musik wäre schön)", en: "(say some music would be nice)", solEs: "Un poco de música, por favor.",
          why: "„un poco de“ = „ein bisschen“; immer mit „de“ vor dem Nomen.",
          whyEn: "„un poco de“ = „a bit of“; always with „de“ before the noun.",
          options: [
            { es: "Un poco de música, por favor.", ok: true },
            { es: "No, en silencio, gracias.", ok: false },
            { es: "Más rápido, por favor.", ok: false },
          ] },
        { who: "npc", es: "¡Listo! Ya casi llegamos. Aquí es la plaza, son quince soles.", de: "Geht klar! Wir sind fast da. Hier ist die Plaza, das macht fünfzehn Soles.", en: "Right! We're almost there. Here's the plaza, that's fifteen soles." },
        { who: "user", kind: "type", de: "(sag, hier bitte – und bedanke dich)", en: "(say here you go – and thank them)", solEs: "Aquí tiene, gracias.",
          why: "„aquí tiene“ beim Übergeben des Geldes (Sie-Form), danach kurz „gracias“.",
          whyEn: "„aquí tiene“ when handing over the money (usted), then a quick „gracias“.",
          accept: ["aqui tiene gracias", "aqui tiene", "aqui esta", "tenga gracias", "aqui tiene esta bien"] },
        { who: "npc", es: "Muchas gracias. ¡Que disfrute la ciudad y buen viaje!", de: "Vielen Dank. Genießen Sie die Stadt und gute Reise!", en: "Thank you very much. Enjoy the city and have a good trip!" },
      ],
    },
    {
      id: "mercado01", cat: "mercado", title: "Obst & Feilschen", titleEn: "Fruit & haggling", lvl: 2,
      turns: [
        { who: "npc", es: "¡Pásele, casero! Tengo fruta fresquita. ¿Qué va a llevar?", de: "Kommen Sie ran, mein Lieber! Ich hab ganz frisches Obst. Was darf's sein?", en: "Come on over, casero! I've got lovely fresh fruit. What can I get you?" },
        { who: "user", kind: "mc", de: "(frag, wie viel das Kilo Mangos kostet)", en: "(ask how much a kilo of mangoes costs)", solEs: "¿A cuánto está el kilo de mango?",
          why: "„¿A cuánto está …?“ fragt nach dem (schwankenden) Tagespreis – typisch auf dem Markt.",
          whyEn: "„¿A cuánto está …?“ asks for the current/daily price (it varies) – typical at a market.",
          options: [
            { es: "¿A cuánto está el kilo de mango?", ok: true },
            { es: "¿Dónde está la salida?", ok: false },
            { es: "¿Me regala una bolsa?", ok: false },
          ] },
        { who: "npc", es: "A cinco soles el kilo, bien dulces, recién traídos.", de: "Fünf Soles das Kilo, schön süß, frisch geliefert.", en: "Five soles a kilo, nice and sweet, just delivered." },
        { who: "user", kind: "type", de: "(sag, das sei ein bisschen teuer)", en: "(say that's a bit pricey)", solEs: "Está un poco caro.",
          why: "„está“ für einen veränderlichen Zustand (Preis heute); „un poco“ mildert die Kritik ab.",
          whyEn: "„está“ for a changeable state (today's price); „un poco“ softens the complaint.",
          accept: ["esta un poco caro", "esta caro", "un poco caro", "esta medio caro", "me parece caro"] },
        { who: "npc", es: "¿Caro? ¡Pero si es la mejor fruta del mercado, casero!", de: "Teuer? Aber das ist doch das beste Obst auf dem Markt, mein Lieber!", en: "Pricey? But this is the best fruit in the market, casero!" },
        { who: "user", kind: "type", de: "(feilsche freundlich: ob er es etwas billiger macht)", en: "(haggle nicely: whether they'll make it a bit cheaper)", solEs: "¿Me lo deja más barato?",
          why: "„¿Me lo deja …?“ = „Lassen Sie es mir …?“ – die höfliche Standardfrage beim Feilschen.",
          whyEn: "„¿Me lo deja …?“ = „Will you let me have it …?“ – the polite go-to phrase for haggling.",
          accept: ["me lo deja mas barato", "mas barato", "un poco mas barato", "me hace un descuento", "me da mas barato"] },
        { who: "npc", es: "A ver… ¿cuánto va a llevar? Si lleva harto, le bajo el precio.", de: "Mal sehen … wie viel nehmen Sie? Wenn Sie viel nehmen, mache ich es billiger.", en: "Let's see… how much will you take? If you take a lot, I'll drop the price." },
        { who: "user", kind: "mc", de: "(sag, du willst zwei Kilo)", en: "(say you want two kilos)", solEs: "Quiero dos kilos.",
          why: "Nach der Zahl steht „kilo“ im Plural: „dos kilos“.",
          whyEn: "After the number „kilo“ goes plural: „dos kilos“.",
          options: [
            { es: "Quiero dos kilos.", ok: true },
            { es: "Solo uno, gracias.", ok: false },
            { es: "No quiero nada.", ok: false },
          ] },
        { who: "npc", es: "Bueno… para usted, cuatro soles el kilo. ¿Le parece?", de: "Na gut … für Sie vier Soles das Kilo. Geht das?", en: "All right… for you, four soles a kilo. How's that?" },
        { who: "user", kind: "mc", de: "(akzeptiere zufrieden)", en: "(accept, happy with it)", solEs: "Listo, está bien, deme dos.",
          why: "„listo“ = „abgemacht/okay“; „deme“ = höflicher Befehl „geben Sie mir“.",
          whyEn: "„listo“ = „done/okay“; „deme“ = polite command „give me“.",
          options: [
            { es: "Listo, está bien, deme dos.", ok: true },
            { es: "No, sigue muy caro.", ok: false },
            { es: "Mejor lo pienso.", ok: false },
          ] },
        { who: "npc", es: "¡Eso, casero! ¿Le gustaría probar una papaya también? Está en oferta.", de: "So ist's recht, mein Lieber! Möchten Sie auch eine Papaya probieren? Die ist im Angebot.", en: "That's it, casero! Would you like to try a papaya too? It's on offer." },
        { who: "user", kind: "mc", de: "(lehne diesmal höflich ab)", en: "(politely decline this time)", solEs: "No, gracias, así está bien.",
          why: "„así está bien“ lehnt freundlich ab, ohne unhöflich zu wirken.",
          whyEn: "„así está bien“ declines politely without sounding rude.",
          options: [
            { es: "No, gracias, así está bien.", ok: true },
            { es: "Sí, deme cinco kilos.", ok: false },
            { es: "No entiendo nada.", ok: false },
          ] },
        { who: "npc", es: "Como guste. Son ocho soles los dos kilos de mango.", de: "Wie Sie möchten. Das macht acht Soles für die zwei Kilo Mango.", en: "As you like. That's eight soles for the two kilos of mango." },
        { who: "user", kind: "type", de: "(frag, ob du mit Karte zahlen kannst)", en: "(ask whether you can pay by card)", solEs: "¿Puedo pagar con tarjeta?",
          why: "„¿Puedo …?“ + Infinitiv = „Darf/Kann ich …?“ – eine höfliche Erlaubnisfrage.",
          whyEn: "„¿Puedo …?“ + infinitive = „May/Can I …?“ – a polite way to ask permission.",
          accept: ["puedo pagar con tarjeta", "se puede con tarjeta", "aceptan tarjeta", "con tarjeta se puede", "puedo con tarjeta"] },
        { who: "npc", es: "No, casero, aquí solo efectivo. ¿Tiene sencillo?", de: "Nein, mein Lieber, hier nur bar. Haben Sie es passend?", en: "No, casero, it's cash only here. Have you got the right change?" },
        { who: "user", kind: "type", de: "(sag, ja, hier bitte)", en: "(say yes, here you go)", solEs: "Sí, aquí tiene.",
          why: "Wieder „aquí tiene“ beim Übergeben – diesmal des Geldes.",
          whyEn: "Again „aquí tiene“ when handing over – this time the money.",
          accept: ["aqui tiene", "si aqui tiene", "aqui esta", "tenga", "aqui tiene esta"] },
        { who: "npc", es: "¡Gracias, casero! Aquí está su fruta. ¡Que le aproveche!", de: "Danke, mein Lieber! Hier ist Ihr Obst. Lassen Sie es sich schmecken!", en: "Thanks, casero! Here's your fruit. Enjoy it!" },
      ],
    },
    {
      id: "farmacia01", cat: "farmacia", title: "Kopfschmerzen", titleEn: "Headache", lvl: 2,
      turns: [
        { who: "npc", es: "Buenos días, ¿en qué le puedo ayudar?", de: "Guten Morgen, wie kann ich Ihnen helfen?", en: "Good morning, how can I help you?" },
        { who: "user", kind: "type", de: "(sag, du hast Kopfschmerzen)", en: "(say you have a headache)", solEs: "Me duele la cabeza.",
          why: "„doler“ funktioniert wie „gustar“: „me duele …“ = „mir schmerzt …“; der Körperteil steht mit Artikel „la“.",
          whyEn: "„doler“ works like „gustar“: „me duele …“ = „… hurts me“; the body part takes the article „la“.",
          accept: ["me duele la cabeza", "tengo dolor de cabeza", "me duele mucho la cabeza", "me duele la cabeza desde hoy"] },
        { who: "npc", es: "Lo siento. ¿Desde cuándo se siente así?", de: "Das tut mir leid. Seit wann fühlen Sie sich so?", en: "I'm sorry. Since when have you felt like this?" },
        { who: "user", kind: "mc", de: "(sag: seit heute Morgen)", en: "(say: since this morning)", solEs: "Desde esta mañana.",
          why: "„desde“ = „seit“; „esta mañana“ = „heute Morgen“.",
          whyEn: "„desde“ = „since“; „esta mañana“ = „this morning“.",
          options: [
            { es: "Desde esta mañana.", ok: true },
            { es: "Desde hace un año.", ok: false },
            { es: "No tengo dinero.", ok: false },
          ] },
        { who: "npc", es: "¿Tiene también fiebre o solo el dolor de cabeza?", de: "Haben Sie auch Fieber oder nur die Kopfschmerzen?", en: "Do you also have a fever or just the headache?" },
        { who: "user", kind: "mc", de: "(sag, nur Kopfschmerzen, kein Fieber)", en: "(say just a headache, no fever)", solEs: "Solo dolor de cabeza, no tengo fiebre.",
          why: "„tener fiebre“ = „Fieber haben“ – mit „tener“, nicht mit „ser/estar“.",
          whyEn: "„tener fiebre“ = „to have a fever“ – with „tener“, not „ser/estar“.",
          options: [
            { es: "Solo dolor de cabeza, no tengo fiebre.", ok: true },
            { es: "Sí, tengo mucha fiebre.", ok: false },
            { es: "No sé, gracias.", ok: false },
          ] },
        { who: "npc", es: "Entiendo. ¿Es alérgic{o/a} a algún medicamento?", de: "Verstehe. Sind Sie gegen ein Medikament allergisch?", en: "I see. Are you allergic to any medication?" },
        { who: "user", kind: "type", de: "(sag, du bist gegen nichts allergisch)", en: "(say you're not allergic to anything)", solEs: "No soy alérgic{o/a} a nada.",
          why: "„alérgico a …“ = „allergisch gegen …“; die doppelte Verneinung „no … nada“ ist im Spanischen korrekt.",
          whyEn: "„alérgico a …“ = „allergic to …“; the double negative „no … nada“ is correct in Spanish.",
          accept: ["no soy alergico a nada", "no soy alergico", "no tengo alergias", "a nada", "no soy alergica a nada"] },
        { who: "npc", es: "Bien. Le puedo dar paracetamol o ibuprofeno. ¿Cuál prefiere?", de: "Gut. Ich kann Ihnen Paracetamol oder Ibuprofen geben. Was möchten Sie lieber?", en: "Good. I can give you paracetamol or ibuprofen. Which would you prefer?" },
        { who: "user", kind: "mc", de: "(sag: Paracetamol ist gut)", en: "(say: paracetamol is fine)", solEs: "Paracetamol está bien.",
          why: "„está bien“ = „ist in Ordnung/passt“ als kurze Zustimmung.",
          whyEn: "„está bien“ = „is fine/okay“ as a short way to agree.",
          options: [
            { es: "Paracetamol está bien.", ok: true },
            { es: "No quiero nada, gracias.", ok: false },
            { es: "¿Cuánto cuesta el taxi?", ok: false },
          ] },
        { who: "npc", es: "Perfecto. Tome una pastilla cada ocho horas, siempre con comida.", de: "Perfekt. Nehmen Sie alle acht Stunden eine Tablette, immer mit dem Essen.", en: "Perfect. Take one tablet every eight hours, always with food." },
        { who: "user", kind: "type", de: "(frag nach, wie viele Tabletten pro Tag)", en: "(ask how many tablets per day)", solEs: "¿Cuántas pastillas tomo al día?",
          why: "„cuántas“ ist weiblich/Plural wegen „pastillas“; „al día“ = „pro Tag“.",
          whyEn: "„cuántas“ is feminine plural because of „pastillas“; „al día“ = „per day“.",
          accept: ["cuantas pastillas tomo al dia", "cuantas pastillas al dia", "cuantas tomo al dia", "cuantas pastillas tomo", "cuantas al dia"] },
        { who: "npc", es: "Máximo tres al día. Si en dos días no mejora, vaya al médico.", de: "Höchstens drei pro Tag. Wenn es in zwei Tagen nicht besser wird, gehen Sie zum Arzt.", en: "Three a day at most. If it doesn't improve in two days, see a doctor." },
        { who: "user", kind: "mc", de: "(frag, wie viel es kostet)", en: "(ask how much it costs)", solEs: "¿Cuánto le debo?",
          why: "„deber“ = „schulden“; „¿Cuánto le debo?“ ist die höfliche Art zu fragen „Was bin ich schuldig?“.",
          whyEn: "„deber“ = „to owe“; „¿Cuánto le debo?“ is the polite „What do I owe you?“.",
          options: [
            { es: "¿Cuánto le debo?", ok: true },
            { es: "¿Dónde está el hospital?", ok: false },
            { es: "¿Tiene wifi?", ok: false },
          ] },
        { who: "npc", es: "Son ocho soles la caja. ¿Algo más que necesite?", de: "Das macht acht Soles die Packung. Brauchen Sie noch etwas?", en: "That's eight soles for the box. Anything else you need?" },
        { who: "user", kind: "type", de: "(bedanke dich, das ist alles)", en: "(thank them, that's all)", solEs: "No, gracias, eso es todo.",
          why: "„eso es todo“ = „das ist alles“ – ein höflicher Abschluss.",
          whyEn: "„eso es todo“ = „that's all“ – a polite way to wrap up.",
          accept: ["no gracias eso es todo", "eso es todo", "no eso es todo", "gracias eso es todo", "nada mas gracias"] },
        { who: "npc", es: "Que se mejore pronto. ¡Que esté bien!", de: "Gute Besserung. Alles Gute!", en: "Get well soon. All the best!" },
      ],
    },
    {
      id: "hostel01", cat: "hostel", title: "Im Gemeinschaftsraum", titleEn: "In the common room", lvl: 2,
      turns: [
        { who: "npc", es: "¡Hola! ¿Recién llegas? No te había visto por aquí.", de: "Hi! Gerade angekommen? Ich hab dich hier noch nicht gesehen.", en: "Hi! Just arrived? I hadn't seen you around here." },
        { who: "user", kind: "type", de: "(sag, ja, du bist gerade angekommen)", en: "(say yes, you've just arrived)", solEs: "Sí, acabo de llegar.",
          why: "„acabar de“ + Infinitiv = „gerade etwas getan haben“: „acabo de llegar“ = „bin gerade angekommen“.",
          whyEn: "„acabar de“ + infinitive = „to have just done“: „acabo de llegar“ = „I've just arrived“.",
          accept: ["si acabo de llegar", "acabo de llegar", "recien llegue", "si recien llego", "llegue hace poco"] },
        { who: "npc", es: "¡Bienvenido! ¿De dónde eres?", de: "Willkommen! Woher kommst du?", en: "Welcome! Where are you from?" },
        { who: "user", kind: "type", de: "(sag, du kommst aus Deutschland)", en: "(say you're from Germany)", solEs: "Soy de Alemania.",
          why: "„ser de“ = „kommen/stammen aus“ für die Herkunft.",
          whyEn: "„ser de“ = „to be from“ for where you're from.",
          accept: ["soy de alemania", "de alemania", "vengo de alemania", "yo soy de alemania", "soy aleman"] },
        { who: "npc", es: "¡Qué bueno! ¿Y es tu primera vez en Perú?", de: "Wie schön! Und bist du zum ersten Mal in Peru?", en: "How nice! And is it your first time in Peru?" },
        { who: "user", kind: "mc", de: "(sag: ja, das erste Mal)", en: "(say: yes, the first time)", solEs: "Sí, es mi primera vez.",
          why: "„mi primera vez“ = „mein erstes Mal“; „primera“ ist weiblich wegen „vez“.",
          whyEn: "„mi primera vez“ = „my first time“; „primera“ is feminine because of „vez“.",
          options: [
            { es: "Sí, es mi primera vez.", ok: true },
            { es: "No, vivo aquí.", ok: false },
            { es: "No me gusta viajar.", ok: false },
          ] },
        { who: "npc", es: "¡Te va a encantar! ¿Cuánto tiempo vas a quedarte?", de: "Es wird dir gefallen! Wie lange bleibst du?", en: "You're going to love it! How long are you staying?" },
        { who: "user", kind: "mc", de: "(sag: drei Nächte)", en: "(say: three nights)", solEs: "Tres noches.",
          why: "Kurze Antwort auf „wie lange“ – Zahl + Nomen genügt; „noche“ → „noches“.",
          whyEn: "Short answer to „how long“ – number + noun is enough; „noche“ → „noches“.",
          options: [
            { es: "Tres noches.", ok: true },
            { es: "Cuesta mucho.", ok: false },
            { es: "Estoy perdid{o/a}.", ok: false },
          ] },
        { who: "npc", es: "¿Y ya sabes qué vas a visitar? Hay un montón que ver.", de: "Und weißt du schon, was du besichtigen willst? Es gibt jede Menge zu sehen.", en: "And do you know yet what you're going to visit? There's loads to see." },
        { who: "user", kind: "type", de: "(sag, du willst Machu Picchu sehen)", en: "(say you want to see Machu Picchu)", solEs: "Quiero ver Machu Picchu.",
          why: "„querer“ + Infinitiv = „etwas tun wollen“: „quiero ver“ = „ich will sehen“.",
          whyEn: "„querer“ + infinitive = „to want to do“: „quiero ver“ = „I want to see“.",
          accept: ["quiero ver machu picchu", "quiero ir a machu picchu", "ver machu picchu", "quiero conocer machu picchu", "machu picchu"] },
        { who: "npc", es: "¡Obvio! Tienes que ir. Oye, ¿quieres que te recomiende un buen restaurante?", de: "Klar! Da musst du hin. Hey, soll ich dir ein gutes Restaurant empfehlen?", en: "Obviously! You've got to go. Hey, want me to recommend a good restaurant?" },
        { who: "user", kind: "mc", de: "(sag begeistert ja)", en: "(say yes, enthusiastically)", solEs: "¡Sí, por favor, me encantaría!",
          why: "„me encantaría“ (Konditional von „encantar“) = „das würde mir gefallen“ – eine begeisterte Zusage.",
          whyEn: "„me encantaría“ (conditional of „encantar“) = „I'd love that“ – an enthusiastic yes.",
          options: [
            { es: "¡Sí, por favor, me encantaría!", ok: true },
            { es: "No, no tengo hambre.", ok: false },
            { es: "¿Cuánto cuesta la cama?", ok: false },
          ] },
        { who: "npc", es: "Hay uno aquí cerca, comida típica, baratísimo. Varios vamos hoy. ¿Te apuntas?", de: "Es gibt eins ganz in der Nähe, typisches Essen, spottbillig. Ein paar von uns gehen heute hin. Bist du dabei?", en: "There's one nearby, typical food, dirt cheap. A few of us are going today. Are you in?" },
        { who: "user", kind: "mc", de: "(sag begeistert zu)", en: "(say yes, enthusiastically)", solEs: "¡Claro, me apunto!",
          why: "„apuntarse“ = „mitmachen/dabei sein“: „me apunto“ = „ich bin dabei“.",
          whyEn: "„apuntarse“ = „to join in“: „me apunto“ = „I'm in“.",
          options: [
            { es: "¡Claro, me apunto!", ok: true },
            { es: "No, estoy lleno.", ok: false },
            { es: "Otra vez, por favor.", ok: false },
          ] },
        { who: "npc", es: "¡Genial! ¿A qué hora te viene bien? ¿Como a las ocho?", de: "Super! Wann passt es dir? So gegen acht?", en: "Great! What time works for you? Around eight?" },
        { who: "user", kind: "type", de: "(sag, acht Uhr ist perfekt)", en: "(say eight o'clock is perfect)", solEs: "A las ocho está perfecto.",
          why: "Uhrzeiten stehen mit „a las …“: „a las ocho“ = „um acht“.",
          whyEn: "Times use „a las …“: „a las ocho“ = „at eight“.",
          accept: ["a las ocho esta perfecto", "a las ocho", "perfecto a las ocho", "las ocho esta bien", "a las ocho me viene bien"] },
        { who: "npc", es: "¡Listo! Nos vemos a las ocho aquí en la sala. ¡Qué chévere conocerte!", de: "Abgemacht! Wir sehen uns um acht hier im Aufenthaltsraum. Schön, dich kennenzulernen!", en: "Sorted! See you at eight here in the common room. So nice to meet you!" },
      ],
    },
    {
      id: "frontera01", cat: "frontera", title: "Einreise-Kontrolle", titleEn: "Immigration control", lvl: 2,
      turns: [
        { who: "npc", es: "Buenas. Pasaporte, por favor.", de: "Guten Tag. Reisepass, bitte.", en: "Hello. Passport, please." },
        { who: "user", kind: "type", de: "(sag, hier bitte, und reich den Pass)", en: "(say here you go and hand over the passport)", solEs: "Sí, aquí tiene.",
          why: "„aquí tiene“ beim Überreichen des Passes – die höfliche Sie-Form.",
          whyEn: "„aquí tiene“ when handing over your passport – the polite usted form.",
          accept: ["aqui tiene", "si aqui tiene", "aqui esta", "tenga", "aqui tiene mi pasaporte"] },
        { who: "npc", es: "Gracias. ¿Cuál es el motivo de su viaje?", de: "Danke. Was ist der Grund Ihrer Reise?", en: "Thanks. What's the purpose of your trip?" },
        { who: "user", kind: "mc", de: "(sag, du bist als Tourist hier)", en: "(say you're here as a tourist)", solEs: "Soy turista, vengo de vacaciones.",
          why: "„venir/estar de vacaciones“ = „im Urlaub sein“ – feste Wendung mit „de“.",
          whyEn: "„venir/estar de vacaciones“ = „to be on holiday“ – set phrase with „de“.",
          options: [
            { es: "Soy turista, vengo de vacaciones.", ok: true },
            { es: "Vengo a trabajar aquí.", ok: false },
            { es: "No sé, gracias.", ok: false },
          ] },
        { who: "npc", es: "¿Cuántos días piensa quedarse en el país?", de: "Wie viele Tage möchten Sie im Land bleiben?", en: "How many days are you planning to stay in the country?" },
        { who: "user", kind: "type", de: "(sag: zwei Wochen)", en: "(say: two weeks)", solEs: "Dos semanas.",
          why: "„semana“ wird im Plural zu „semanas“; eine knappe Zeitangabe genügt.",
          whyEn: "„semana“ pluralises to „semanas“; a short time answer is enough.",
          accept: ["dos semanas", "unas dos semanas", "catorce dias", "quince dias", "dos semanas mas o menos"] },
        { who: "npc", es: "¿Tiene dónde quedarse durante su estadía?", de: "Haben Sie eine Unterkunft für Ihren Aufenthalt?", en: "Do you have somewhere to stay during your visit?" },
        { who: "user", kind: "mc", de: "(sag, du hast ein Hostel reserviert)", en: "(say you've booked a hostel)", solEs: "Sí, tengo una reserva en un hostal.",
          why: "„tener una reserva“ = „eine Reservierung haben“; „en un hostal“ = „in einem Hostel“.",
          whyEn: "„tener una reserva“ = „to have a booking“; „en un hostal“ = „in a hostel“.",
          options: [
            { es: "Sí, tengo una reserva en un hostal.", ok: true },
            { es: "No, no tengo nada.", ok: false },
            { es: "Quiero un boleto de bus.", ok: false },
          ] },
        { who: "npc", es: "¿Me puede mostrar la reserva o la dirección, por favor?", de: "Können Sie mir die Reservierung oder die Adresse zeigen, bitte?", en: "Could you show me the booking or the address, please?" },
        { who: "user", kind: "type", de: "(sag, ja, du hast sie auf dem Handy)", en: "(say yes, you have it on your phone)", solEs: "Sí, la tengo en el celular.",
          why: "„la“ ersetzt „la reserva“ (weiblich); „celular“ ist in Lateinamerika das Handy.",
          whyEn: "„la“ replaces „la reserva“ (feminine); „celular“ is the word for mobile in Latin America.",
          accept: ["si la tengo en el celular", "la tengo en el celular", "esta en mi celular", "en el celular", "si en el celular"] },
        { who: "npc", es: "Muy bien. ¿Trae algo que declarar? ¿Alimentos, plantas?", de: "Sehr gut. Haben Sie etwas zu verzollen? Lebensmittel, Pflanzen?", en: "Very good. Do you have anything to declare? Food, plants?" },
        { who: "user", kind: "mc", de: "(sag, du hast nichts zu verzollen)", en: "(say you have nothing to declare)", solEs: "No, no traigo nada que declarar.",
          why: "„nada que declarar“ = „nichts zu verzollen“; doppelte Verneinung „no … nada“.",
          whyEn: "„nada que declarar“ = „nothing to declare“; double negative „no … nada“.",
          options: [
            { es: "No, no traigo nada que declarar.", ok: true },
            { es: "Sí, traigo mucha comida.", ok: false },
            { es: "No entiendo la pregunta.", ok: false },
          ] },
        { who: "npc", es: "¿Tiene boleto de salida del país?", de: "Haben Sie ein Ausreiseticket?", en: "Do you have a ticket to leave the country?" },
        { who: "user", kind: "type", de: "(sag, ja, du fliegst in zwei Wochen zurück)", en: "(say yes, you fly back in two weeks)", solEs: "Sí, regreso en dos semanas.",
          why: "Das Präsens „regreso“ steht hier für eine feste Zukunftsplanung; „en dos semanas“ = „in zwei Wochen“.",
          whyEn: "The present tense „regreso“ expresses a fixed future plan; „en dos semanas“ = „in two weeks“.",
          accept: ["si regreso en dos semanas", "regreso en dos semanas", "vuelvo en dos semanas", "si vuelvo en dos semanas", "regreso en quince dias"] },
        { who: "npc", es: "Perfecto. Aquí tiene su pasaporte sellado. Bienvenido al país.", de: "Perfekt. Hier ist Ihr abgestempelter Reisepass. Willkommen im Land.", en: "Perfect. Here's your stamped passport. Welcome to the country." },
        { who: "user", kind: "type", de: "(bedanke dich)", en: "(thank them)", solEs: "Muchas gracias.",
          why: "Ein knappes, höfliches Dankeschön zum Abschluss.",
          whyEn: "A short, polite thank-you to finish.",
          accept: ["muchas gracias", "gracias", "muchas gracias muy amable", "mil gracias", "gracias muy amable"] },
        { who: "npc", es: "Que disfrute su viaje. ¡Buena estadía!", de: "Genießen Sie Ihre Reise. Schönen Aufenthalt!", en: "Enjoy your trip. Have a good stay!" },
      ],
    },
    {
      id: "emergencia01", cat: "emergencia", title: "Hilfe rufen", titleEn: "Calling for help", lvl: 2,
      turns: [
        { who: "npc", es: "¿Está bien? ¿Qué pasó? Lo vi caerse.", de: "Geht es Ihnen gut? Was ist passiert? Ich habe Sie stürzen sehen.", en: "Are you all right? What happened? I saw you fall." },
        { who: "user", kind: "type", de: "(bitte dringend um Hilfe)", en: "(urgently ask for help)", solEs: "¡Necesito ayuda, por favor!",
          why: "„necesitar“ = „brauchen“; „ayuda“ (Hilfe) steht hier ohne Artikel – ein klarer Hilferuf.",
          whyEn: "„necesitar“ = „to need“; „ayuda“ (help) takes no article here – a clear call for help.",
          accept: ["necesito ayuda", "necesito ayuda por favor", "ayuda por favor", "ayudenme", "ayuda"] },
        { who: "npc", es: "Tranquilo, lo voy a ayudar. ¿Qué le pasó?", de: "Ruhig, ich helfe Ihnen. Was ist Ihnen passiert?", en: "Stay calm, I'm going to help you. What happened to you?" },
        { who: "user", kind: "mc", de: "(sag, du bist hingefallen)", en: "(say you fell over)", solEs: "Me caí y me golpeé.",
          why: "„caerse“ (hinfallen) und „golpearse“ (sich stoßen) sind reflexiv; Indefinido „me caí“.",
          whyEn: "„caerse“ (to fall) and „golpearse“ (to hit oneself) are reflexive; preterite „me caí“.",
          options: [
            { es: "Me caí y me golpeé.", ok: true },
            { es: "Quiero la cuenta.", ok: false },
            { es: "Estoy de vacaciones.", ok: false },
          ] },
        { who: "npc", es: "¿Le duele algo? ¿Dónde le duele?", de: "Tut Ihnen etwas weh? Wo tut es weh?", en: "Does anything hurt? Where does it hurt?" },
        { who: "user", kind: "mc", de: "(sag, dein Bein tut sehr weh)", en: "(say your leg hurts a lot)", solEs: "Sí, me duele mucho la pierna.",
          why: "„me duele … la pierna“ wie „me duele la cabeza“; „mucho“ verstärkt den Schmerz.",
          whyEn: "„me duele … la pierna“ like „me duele la cabeza“; „mucho“ intensifies the pain.",
          options: [
            { es: "Sí, me duele mucho la pierna.", ok: true },
            { es: "No, estoy bien, gracias.", ok: false },
            { es: "Necesito un taxi.", ok: false },
          ] },
        { who: "npc", es: "No se mueva. ¿Quiere que llame a una ambulancia?", de: "Bewegen Sie sich nicht. Soll ich einen Krankenwagen rufen?", en: "Don't move. Would you like me to call an ambulance?" },
        { who: "user", kind: "type", de: "(sag: ja, bitte ruf einen Krankenwagen)", en: "(say: yes, please call an ambulance)", solEs: "Sí, llame a una ambulancia, por favor.",
          why: "„llame“ = höflicher Befehl (Sie); „llamar a“ braucht das persönliche „a“ vor der Person/Sache.",
          whyEn: "„llame“ = polite command (usted); „llamar a“ needs the personal „a“.",
          accept: ["si llame a una ambulancia", "llame a una ambulancia", "llame una ambulancia por favor", "si una ambulancia", "llame a la ambulancia"] },
        { who: "npc", es: "Ya la estoy llamando. ¿Cómo se llama usted?", de: "Ich rufe ihn schon. Wie heißen Sie?", en: "I'm calling it now. What's your name?" },
        { who: "user", kind: "type", de: "(nenne deinen Namen: {name})", en: "(give your name: {name})", solEs: "Me llamo {name}.",
          why: "„llamarse“ = „heißen“; „me llamo …“ heißt wörtlich „ich nenne mich …“.",
          whyEn: "„llamarse“ = „to be called“; „me llamo …“ literally means „I call myself …“.",
          accept: ["me llamo {name}", "soy {name}", "{name}", "mi nombre es {name}", "me llaman {name}"] },
        { who: "npc", es: "{name}, ¿puede mover los dedos del pie?", de: "{name}, können Sie die Zehen bewegen?", en: "{name}, can you move your toes?" },
        { who: "user", kind: "mc", de: "(sag, ja, ein bisschen)", en: "(say yes, a little)", solEs: "Sí, un poco.",
          why: "„un poco“ = „ein bisschen“ – eine kurze, klare Antwort.",
          whyEn: "„un poco“ = „a little“ – a short, clear answer.",
          options: [
            { es: "Sí, un poco.", ok: true },
            { es: "No siento nada.", ok: false },
            { es: "No, gracias.", ok: false },
          ] },
        { who: "npc", es: "Bien, eso es buena señal. ¿Está tomando algún medicamento?", de: "Gut, das ist ein gutes Zeichen. Nehmen Sie irgendein Medikament?", en: "Good, that's a good sign. Are you taking any medication?" },
        { who: "user", kind: "mc", de: "(sag, nein, keine Medikamente)", en: "(say no, no medication)", solEs: "No, ningún medicamento.",
          why: "„ningún“ = „kein“ vor einem männlichen Nomen (gekürzt aus „ninguno“).",
          whyEn: "„ningún“ = „no/not any“ before a masculine noun (shortened from „ninguno“).",
          options: [
            { es: "No, ningún medicamento.", ok: true },
            { es: "Sí, muchos.", ok: false },
            { es: "No sé dónde estoy.", ok: false },
          ] },
        { who: "npc", es: "La ambulancia ya viene en camino. Quédese quieto, yo me quedo con usted.", de: "Der Krankenwagen ist schon unterwegs. Bleiben Sie ruhig liegen, ich bleibe bei Ihnen.", en: "The ambulance is on its way. Stay still, I'll stay with you." },
        { who: "user", kind: "type", de: "(bedanke dich erleichtert)", en: "(thank them, relieved)", solEs: "Muchas gracias por su ayuda.",
          why: "„gracias por …“ = „danke für …“; „su ayuda“ = „Ihre Hilfe“.",
          whyEn: "„gracias por …“ = „thanks for …“; „su ayuda“ = „your help“.",
          accept: ["muchas gracias por su ayuda", "gracias por su ayuda", "muchas gracias", "gracias", "mil gracias"] },
        { who: "npc", es: "No se preocupe. Todo va a estar bien. La ayuda ya casi llega.", de: "Keine Sorge. Alles wird gut. Die Hilfe ist gleich da.", en: "Don't worry. Everything's going to be fine. Help is almost here." },
      ],
    },
    {
      id: "calle01", cat: "calle", title: "Wo ist die Bushaltestelle?", titleEn: "Where is the bus stop?", lvl: 1,
      turns: [
        { who: "npc", es: "¿Sí? ¿Necesita ayuda? {Lo/La} veo un poco perdid{o/a}.", de: "Ja? Brauchen Sie Hilfe? Sie wirken etwas verloren.", en: "Yes? Do you need help? You look a bit lost." },
        { who: "user", kind: "mc", de: "(frag höflich, wo die Bushaltestelle ist)", en: "(politely ask where the bus stop is)", solEs: "Disculpe, ¿dónde está el paradero?",
          why: "„Disculpe“ leitet höflich ein; „paradero“ ist in Lateinamerika die Bushaltestelle; „está“ für den Ort.",
          whyEn: "„Disculpe“ opens politely; „paradero“ is the bus stop in Latin America; „está“ for location.",
          options: [
            { es: "Disculpe, ¿dónde está el paradero?", ok: true },
            { es: "¿Qué hora es?", ok: false },
            { es: "¿Cuánto cuesta?", ok: false },
          ] },
        { who: "npc", es: "¿El paradero? ¿Para qué bus, el que va al centro?", de: "Die Haltestelle? Für welchen Bus, den ins Zentrum?", en: "The bus stop? For which bus, the one to the centre?" },
        { who: "user", kind: "type", de: "(sag, ja, ins Zentrum)", en: "(say yes, to the centre)", solEs: "Sí, al centro.",
          why: "„al centro“ = „ins Zentrum“ (a + el); eine kurze Bestätigung reicht.",
          whyEn: "„al centro“ = „to the centre“ (a + el); a short confirmation is enough.",
          accept: ["si al centro", "al centro", "si quiero ir al centro", "al centro por favor", "si para el centro"] },
        { who: "npc", es: "Ah, ya. Siga derecho dos cuadras y doble a la derecha.", de: "Ah, gut. Gehen Sie zwei Blocks geradeaus und biegen Sie rechts ab.", en: "Ah, right. Go straight on for two blocks and turn right." },
        { who: "user", kind: "type", de: "(frag nach, ob es weit ist)", en: "(ask whether it's far)", solEs: "¿Está lejos?",
          why: "„lejos“ = „weit (weg)“; „¿Está lejos?“ fragt nach der Entfernung.",
          whyEn: "„lejos“ = „far“; „¿Está lejos?“ asks about distance.",
          accept: ["esta lejos", "queda lejos", "es lejos", "esta muy lejos", "esta lejos de aqui"] },
        { who: "npc", es: "No, está cerca. Unos cinco minutos a pie, no más.", de: "Nein, es ist nah. Etwa fünf Minuten zu Fuß, nicht mehr.", en: "No, it's close. About five minutes on foot, no more." },
        { who: "user", kind: "mc", de: "(frag, welcher Bus zum Zentrum fährt)", en: "(ask which bus goes to the centre)", solEs: "¿Qué bus va al centro?",
          why: "„¿Qué bus …?“ = „Welcher Bus …?“; „va a“ = „fährt nach“.",
          whyEn: "„¿Qué bus …?“ = „Which bus …?“; „va a“ = „goes to“.",
          options: [
            { es: "¿Qué bus va al centro?", ok: true },
            { es: "¿Tiene un cigarro?", ok: false },
            { es: "¿Dónde vive usted?", ok: false },
          ] },
        { who: "npc", es: "Tome el que dice \"Centro\" o el número veinte. Pasan seguido.", de: "Nehmen Sie den mit „Centro“ oder die Nummer zwanzig. Die kommen oft.", en: "Take the one that says \"Centro\" or number twenty. They come often." },
        { who: "user", kind: "type", de: "(frag, wie viel die Fahrt kostet)", en: "(ask how much the fare is)", solEs: "¿Cuánto cuesta el pasaje?",
          why: "„pasaje“ = der Fahrpreis/das Ticket; „¿Cuánto cuesta?“ = „Was kostet es?“.",
          whyEn: "„pasaje“ = the fare/ticket; „¿Cuánto cuesta?“ = „How much is it?“.",
          accept: ["cuanto cuesta el pasaje", "cuanto es el pasaje", "cuanto cuesta", "cuanto vale el pasaje", "cuanto cuesta el boleto"] },
        { who: "npc", es: "Un sol cincuenta. Tenga sencillo a la mano, casi no dan vuelto.", de: "Eineinhalb Soles. Halten Sie es passend bereit, Wechselgeld gibt es kaum.", en: "One sol fifty. Keep small change handy, they hardly ever give change." },
        { who: "user", kind: "mc", de: "(frag, ob du dem Fahrer sagen sollst, wo du raus willst)", en: "(ask whether you should tell the driver where to get off)", solEs: "¿Le aviso al chofer dónde bajar?",
          why: "„avisar a alguien“ = „jemandem Bescheid geben“; „bajar“ = „aussteigen“.",
          whyEn: "„avisar a alguien“ = „to let someone know“; „bajar“ = „to get off“.",
          options: [
            { es: "¿Le aviso al chofer dónde bajar?", ok: true },
            { es: "¿Puedo ir en taxi gratis?", ok: false },
            { es: "¿El bus tiene wifi?", ok: false },
          ] },
        { who: "npc", es: "Sí, dígale \"centro\" al subir y él le avisa dónde bajar.", de: "Ja, sagen Sie ihm beim Einsteigen „centro“, dann sagt er Ihnen, wo Sie aussteigen.", en: "Yes, say \"centro\" as you get on and he'll tell you where to get off." },
        { who: "user", kind: "type", de: "(bedanke dich herzlich)", en: "(thank them warmly)", solEs: "Muchas gracias, muy amable.",
          why: "„muy amable“ = „sehr freundlich“ – ein höfliches Dankeschön für die Hilfe.",
          whyEn: "„muy amable“ = „very kind“ – a polite thank-you for the help.",
          accept: ["muchas gracias muy amable", "muchas gracias", "gracias", "muy amable", "mil gracias"] },
        { who: "npc", es: "De nada. ¡Que le vaya bien y buen viaje!", de: "Gern geschehen. Alles Gute und gute Reise!", en: "You're welcome. Take care and have a good trip!" },
      ],
    },
    {
      id: "coqueteo01", cat: "coqueteo", title: "En la noche de salsa", titleEn: "At the salsa night", lvl: 2,
      turns: [
        { who: "npc", es: "¡Hola! Te vi bailando, lo haces muy bien.", de: "Hi! Ich hab dich tanzen sehen, du machst das richtig gut.", en: "Hi! I saw you dancing, you're really good at it." },
        { who: "user", kind: "mc", de: "(bedanke dich und gib das Kompliment zurück)", en: "(say thanks and give the compliment back)", solEs: "¡Gracias! Tú también bailas genial.",
          why: "„también“ = „auch“; ein Kompliment freundlich zurückgeben hält das Gespräch leicht.",
          whyEn: "„también“ = „too/also“; returning a compliment kindly keeps the conversation light.",
          options: [
            { es: "¡Gracias! Tú también bailas genial.", ok: true },
            { es: "No me gusta bailar.", ok: false },
            { es: "¿Cuánto cuesta la entrada?", ok: false },
          ] },
        { who: "npc", es: "Qué amable. ¿De dónde eres?", de: "Wie nett. Woher kommst du?", en: "How kind. Where are you from?" },
        { who: "user", kind: "type", de: "(sag, du bist aus Deutschland, und frag zurück)", en: "(say you're from Germany, and ask back)", solEs: "Soy de Alemania, ¿y tú?",
          why: "„Soy de …“ = „Ich bin aus …“; das angehängte „¿y tú?“ gibt die Frage charmant zurück.",
          whyEn: "„Soy de …“ = „I'm from …“; tagging on „¿y tú?“ hands the question back charmingly.",
          accept: ["soy de alemania y tu", "soy de alemania", "de alemania", "soy alemana y tu", "soy aleman y tu"] },
        { who: "npc", es: "De aquí, de Cali. ¿Quieres bailar la próxima?", de: "Von hier, aus Cali. Magst du den nächsten Tanz?", en: "From here, from Cali. Do you want to dance the next one?" },
        { who: "user", kind: "mc", de: "(nimm gern an)", en: "(accept gladly)", solEs: "¡Claro, me encantaría!",
          why: "„me encantaría“ (Konditional von „encantar“) klingt begeisterter und höflicher als ein knappes „sí“.",
          whyEn: "„me encantaría“ (conditional of „encantar“) sounds more enthusiastic and polite than a curt „sí“.",
          options: [
            { es: "¡Claro, me encantaría!", ok: true },
            { es: "No, gracias, estoy cansado.", ok: false },
            { es: "Mejor me voy a casa.", ok: false },
          ] },
        { who: "npc", es: "¡Genial! … Bailas muy rico. ¿Te invito algo de tomar?", de: "Super! … Du tanzt richtig schön. Darf ich dir was zu trinken ausgeben?", en: "Great! … You dance really nicely. Can I get you something to drink?" },
        { who: "user", kind: "type", de: "(nimm an und bestell ein Wasser)", en: "(accept and order a water)", solEs: "Sí, gracias. Un agua, por favor.",
          why: "Beim eigenen Getränk behältst du die Kontrolle; „un agua“ ist völlig normal und bleibt klar im Kopf.",
          whyEn: "Ordering your own drink keeps you in control; „un agua“ is perfectly normal and keeps your head clear.",
          accept: ["si gracias un agua por favor", "un agua por favor", "un agua", "una agua por favor", "agua por favor"] },
        { who: "npc", es: "Me cae muy bien hablar contigo. ¿Te gustaría salir mañana?", de: "Ich rede echt gern mit dir. Hättest du Lust, morgen was zu machen?", en: "I really enjoy talking with you. Would you like to go out tomorrow?" },
        { who: "user", kind: "mc", de: "(schlag etwas Lockeres vor: einen Kaffee)", en: "(suggest something low-key: a coffee)", solEs: "Me encantaría. ¿Tomamos un café?",
          why: "Ein Kaffee tagsüber ist unverbindlich und öffentlich – perfekt für ein erstes Date ohne Druck.",
          whyEn: "A daytime coffee is low-key and public – perfect for a relaxed first date with no pressure.",
          options: [
            { es: "Me encantaría. ¿Tomamos un café?", ok: true },
            { es: "Vamos ya a tu casa.", ok: false },
            { es: "No sé, déjame pensarlo un mes.", ok: false },
          ] },
        { who: "npc", es: "¡Perfecto! ¿Me das tu WhatsApp?", de: "Perfekt! Gibst du mir dein WhatsApp?", en: "Perfect! Can I have your WhatsApp?" },
        { who: "user", kind: "type", de: "(sag ja klar und biete an, es ihr zu geben)", en: "(say sure and offer to give it to her)", solEs: "Claro, te lo doy.",
          why: "„te lo doy“ = „ich gebe es dir“; Kontakt nur tauschen, wenn du selbst willst – nie aus Druck.",
          whyEn: "„te lo doy“ = „I'll give it to you“; only swap contacts if you want to – never out of pressure.",
          accept: ["claro te lo doy", "si claro te lo doy", "te lo doy", "claro", "si te lo paso"] },
        { who: "npc", es: "La pasé muy bien contigo esta noche.", de: "Ich hatte heute Abend eine richtig schöne Zeit mit dir.", en: "I had a really nice time with you tonight." },
        { who: "user", kind: "mc", de: "(frag nach, ob ein Kuss okay ist – frag um Erlaubnis)", en: "(check whether a kiss is okay – ask for consent)", solEs: "¿Está bien si te doy un beso?",
          why: "Vor einem Kuss kurz nachfragen zeigt Respekt – ein „Ja“ vorher macht den Moment für beide schöner.",
          whyEn: "Asking before a kiss shows respect – a clear „yes“ first makes the moment better for both.",
          options: [
            { es: "¿Está bien si te doy un beso?", ok: true },
            { es: "Te doy un beso, no preguntes.", ok: false },
            { es: "Tienes que darme un beso.", ok: false },
          ] },
        { who: "npc", es: "Sí, me encantaría. Nos vemos mañana en el café.", de: "Ja, sehr gern. Wir sehen uns morgen im Café.", en: "Yes, I'd love that. See you tomorrow at the café." },
        { who: "user", kind: "type", de: "(verabschiede dich nett und freu dich auf morgen)", en: "(say a warm goodbye and look forward to tomorrow)", solEs: "Buenas noches, nos vemos mañana.",
          why: "„nos vemos mañana“ = „wir sehen uns morgen“; ein warmer, einfacher Abschied rundet den Abend ab.",
          whyEn: "„nos vemos mañana“ = „see you tomorrow“; a warm, simple goodbye rounds off the night.",
          accept: ["buenas noches nos vemos manana", "nos vemos manana", "buenas noches", "hasta manana", "nos vemos manana buenas noches"] },
        { who: "npc", es: "¡Buenas noches! Que descanses.", de: "Gute Nacht! Schlaf gut.", en: "Good night! Rest well." },
      ],
    },
  ];

  window.SC = window.SC || {};
  window.SC.dialogos = { DIALOGOS_SCENARIOS, DIALOGOS };
})();
