/*
 * historia.js  (SC.historia) – Modell für die Erklärseite "Historia de
 * Sudamérica". REINE DATEN, keine Logik (wie countries.js / data.js). Wird von
 * ui.renderHistoria gerendert; der Controller (app.js) reicht die Daten per
 * localizeDeep für die aktive Sprache durch (deutsche Felder + …En-Pendants).
 *
 * Aufbau:
 *   INTRO     { de, en }                       – Einleitungstext (Hero)
 *   ERAS      [ Epoche ]                        – der interaktive Zeitstrahl
 *   FIGURES   [ Person ]                        – die Protagonisten (Galerie)
 *   TENSIONS  [ Spannung ]                      – "Heute": Lage & Konflikte
 *   FACTS     [ { de, en } ]                    – "¿Sabías que…?"-Häppchen
 *
 * Epoche:   { id, icon, period, title, lead, body:[Absatz], points:[Punkt],
 *             img, imgCaption }  (+ …En-Pendants für die Übersetzung)
 * Person:   { id, name, role, years, flag, img, text, quote }  (+ …En)
 * Spannung: { id, icon, title, where, tone, status, text }  (+ …En)
 *   tone = "crisis" | "tense" | "shift" | "progress"  (Farbe der Status-Plakette)
 *
 * img = nur der Wikimedia-Commons-Dateiname (z. B. "Bolivar Arturo Michelena.jpg").
 *       ui.js baut daraus eine Special:FilePath-URL (kein Hash-Raten nötig).
 *       Offline/bei Fehler wird das Bild ausgeblendet (onerror in ui.js).
 */
(function () {
  "use strict";
  window.SC = window.SC || {};

  // ---------- Einleitung ----------
  const INTRO = {
    de: "Ein Kontinent, eine bewegte Geschichte: In wenigen Jahrzehnten wurde aus uralten Hochkulturen ein spanisches Kolonialreich – und daraus, im Feuer eines gemeinsamen Freiheitskampfes, ein Dutzend junger Republiken. Hier ist die große Linie: wie es war, wie aus einem Traum von Einheit viele Nationen wurden, und wie es heute weitergeht.",
    en: "One continent, one turbulent story: in just a few decades, ancient civilisations became a Spanish colonial empire – and out of that, in the fire of a shared struggle for freedom, came a dozen young republics. Here's the big picture: how it was, how a dream of unity turned into many nations, and where it all stands today.",
  };

  // ---------- Zeitstrahl: die Epochen ----------
  const ERAS = [
    {
      id: "precolombino",
      icon: "🏔️",
      period: "bis 1492",
      periodEn: "before 1492",
      title: "Vor den Spaniern – die Hochkulturen",
      titleEn: "Before the Spanish – the great civilisations",
      lead: "Lange vor Kolumbus blühten in den Anden und im Amazonas hochentwickelte Reiche.",
      leadEn: "Long before Columbus, sophisticated empires flourished in the Andes and the Amazon.",
      body: [
        "Das größte war das Reich der Inka, Tawantinsuyu, „Land der vier Teile“. Von ihrer Hauptstadt Cusco aus beherrschten die Inka im 15. Jahrhundert ein Gebiet von Kolumbien bis Chile – über 4.000 Kilometer Anden, verbunden durch ein gigantisches Straßennetz (Qhapaq Ñan) mit Hängebrücken und Läuferstaffeten (chasquis).",
        "Ohne Schrift im klassischen Sinn verwalteten sie alles über Knotenschnüre (quipus); ohne Eisen und Rad bauten sie Terrassen, Bewässerung und steinerne Festungen wie Machu Picchu oder Sacsayhuamán, deren fugenlose Mauern bis heute Erdbeben überstehen.",
        "Daneben gab es viele weitere Kulturen: die Muisca im Hochland von Kolumbien (deren Goldritual die El-Dorado-Legende auslöste), die kriegerischen Mapuche im Süden Chiles, die nie ganz unterworfen wurden, und unzählige Völker im Amazonasbecken.",
      ],
      bodyEn: [
        "The largest was the empire of the Inca, Tawantinsuyu, \"the land of the four parts\". From their capital Cusco, the Inca ruled in the 15th century over a territory stretching from Colombia to Chile – more than 4,000 kilometres of Andes, linked by a vast road network (Qhapaq Ñan) with rope bridges and relay runners (chasquis).",
        "Without writing in the classic sense, they administered everything through knotted cords (quipus); without iron or the wheel, they built terraces, irrigation and stone fortresses such as Machu Picchu and Sacsayhuamán, whose seamless walls still survive earthquakes today.",
        "Alongside them were many other cultures: the Muisca in the highlands of Colombia (whose gold ritual sparked the legend of El Dorado), the warlike Mapuche in southern Chile, who were never fully subdued, and countless peoples of the Amazon basin.",
      ],
      points: [
        "Inka-Reich: ~12 Mio. Menschen, von Kolumbien bis Chile",
        "Quechua, die Sprache der Inka, sprechen bis heute Millionen",
        "Machu Picchu wurde erst 1911 weltweit bekannt",
      ],
      pointsEn: [
        "Inca Empire: ~12 million people, from Colombia to Chile",
        "Quechua, the language of the Inca, is still spoken by millions",
        "Machu Picchu only became world-famous in 1911",
      ],
      level: "B1",
      es: [
        "Mucho antes de la llegada de los españoles, en los Andes y en la selva del Amazonas *florecieron* grandes civilizaciones. La más poderosa de todas fue el *imperio* de los incas, que ellos mismos llamaban Tawantinsuyu, „la tierra de las cuatro partes“. Desde su capital, Cusco, los incas dominaban en el siglo XV un *territorio* enorme, que iba desde el sur de Colombia hasta el centro de Chile.",
        "Lo más increíble es que lograron todo esto sin escritura, sin *rueda* y sin hierro. Para gobernar y llevar las cuentas usaban cuerdas con *nudos*, los quipus. Construían largos *caminos* de montaña, *puentes* colgantes sobre los ríos y terrazas para cultivar en las laderas. Ciudades de piedra como Machu Picchu, con muros tan perfectos que todavía *resisten* los terremotos, siguen *asombrando* al mundo entero.",
        "Pero los incas no estaban solos. También existían otros *pueblos* importantes: los muiscas, en las montañas de Colombia, cuyo ritual del oro dio origen a la *leyenda* de El Dorado; los mapuches del sur de Chile, guerreros que nunca fueron *conquistados* del todo; y cientos de comunidades en la inmensa selva amazónica, cada una con su propia lengua y sus costumbres.",
      ],
      vocab: [
        { es: "florecieron", de: "blühten (florecer)", en: "flourished (florecer)", take: true },
        { es: "imperio", de: "das Reich", en: "empire", take: true },
        { es: "territorio", de: "das Gebiet", en: "territory", take: true },
        { es: "rueda", de: "das Rad", en: "wheel", take: true },
        { es: "nudos", de: "die Knoten", en: "knots", take: true },
        { es: "caminos", de: "die Wege, Straßen", en: "roads, paths", take: true },
        { es: "puentes", de: "die Brücken", en: "bridges", take: true },
        { es: "resisten", de: "halten stand (resistir)", en: "withstand (resistir)", take: true },
        { es: "asombrando", de: "in Staunen versetzen (asombrar)", en: "amazing (asombrar)", take: false },
        { es: "pueblos", de: "die Völker, Dörfer", en: "peoples, villages", take: true },
        { es: "leyenda", de: "die Legende", en: "legend", take: false },
        { es: "conquistados", de: "erobert (conquistar)", en: "conquered (conquistar)", take: false },
      ],
      img: "Machu Picchu, Peru.jpg",
      imgCaption: "Machu Picchu – Inka-Stadt in den Anden Perus",
      imgCaptionEn: "Machu Picchu – Inca city in the Peruvian Andes",
    },
    {
      id: "conquista",
      icon: "⚔️",
      period: "1492–1572",
      title: "Die Conquista – die Eroberung",
      titleEn: "The Conquista – the conquest",
      lead: "Wenige hundert Spanier brachten in einer Generation ganze Reiche zu Fall.",
      leadEn: "A few hundred Spaniards brought entire empires down in a single generation.",
      body: [
        "1492 erreichte Kolumbus die Karibik. Innerhalb weniger Jahrzehnte stießen die conquistadores aufs Festland vor. In Südamerika nutzte Francisco Pizarro 1532 einen blutigen Inka-Bürgerkrieg aus: In Cajamarca nahm er den Herrscher Atahualpa gefangen, ließ ihn ein riesiges Lösegeld an Gold zahlen – und hinrichten.",
        "Der eigentliche Verbündete der Eroberer waren jedoch eingeschleppte Krankheiten. Pocken, Masern und Grippe töteten Schätzungen zufolge bis zu 90 Prozent der indigenen Bevölkerung – ein demografischer Zusammenbruch, der den Widerstand brach, bevor die meisten je einen Spanier sahen.",
        "Mit Schwert, Pferd, Feuerwaffen und einheimischen Bündnispartnern unterwarfen die Spanier bis 1572 (Fall des letzten Inka-Rückzugsorts Vilcabamba) den Kontinent. Begründet wurde das mit Kreuz und Krone: Mission und Reichtum gingen Hand in Hand.",
      ],
      bodyEn: [
        "In 1492 Columbus reached the Caribbean. Within a few decades the conquistadors pushed onto the mainland. In South America, Francisco Pizarro exploited a bloody Inca civil war in 1532: at Cajamarca he captured the ruler Atahualpa, had him pay an enormous ransom in gold – and then executed him.",
        "The conquerors' real ally, however, was imported disease. Smallpox, measles and influenza killed up to 90 per cent of the indigenous population by some estimates – a demographic collapse that broke resistance before most people ever saw a Spaniard.",
        "With swords, horses, firearms and native allies, the Spanish subjugated the continent by 1572 (the fall of the last Inca refuge of Vilcabamba). It was all justified by cross and crown: mission and riches went hand in hand.",
      ],
      points: [
        "Pizarro nahm Atahualpa mit nur ~170 Mann gefangen",
        "Krankheiten töteten weit mehr Menschen als Waffen",
        "1572 fiel Vilcabamba, der letzte Inka-Widerstand",
      ],
      pointsEn: [
        "Pizarro captured Atahualpa with only ~170 men",
        "Disease killed far more people than weapons did",
        "In 1572 Vilcabamba fell, the last Inca resistance",
      ],
      level: "B1",
      es: [
        "En 1492, Cristóbal Colón llegó al Caribe sin saber que había encontrado un continente nuevo. Pocas décadas después, los conquistadores avanzaron hacia tierra firme en busca de oro y gloria. En 1532, Francisco Pizarro *aprovechó* una sangrienta guerra civil entre dos hermanos incas: en la ciudad de Cajamarca *capturó* por sorpresa al rey Atahualpa, le pidió un enorme *rescate* de oro y plata y, aun así, lo mandó *matar*.",
        "Sin embargo, el *aliado* más poderoso de los españoles no fueron las armas, sino las *enfermedades* que trajeron de Europa. La viruela, el sarampión y la gripe mataron, según algunos cálculos, hasta el noventa por ciento de la población indígena. Fue un *desastre* tan grande que muchos pueblos se *derrumbaron* antes de ver siquiera a un español.",
        "Con caballos, *armas* de fuego, acero y la ayuda de pueblos locales que odiaban a los incas, los españoles *conquistaron* poco a poco el continente. En 1572 cayó Vilcabamba, el último refugio inca. Todo se justificaba con la cruz y la corona: la religión y la *riqueza* siempre iban de la mano.",
      ],
      vocab: [
        { es: "aprovechó", de: "nutzte aus (aprovechar)", en: "took advantage (aprovechar)", take: true },
        { es: "capturó", de: "nahm gefangen (capturar)", en: "captured (capturar)", take: true },
        { es: "rescate", de: "das Lösegeld; die Rettung", en: "ransom; rescue", take: true },
        { es: "matar", de: "töten", en: "to kill", take: true },
        { es: "aliado", de: "der Verbündete", en: "ally", take: true },
        { es: "enfermedades", de: "die Krankheiten", en: "diseases", take: true },
        { es: "desastre", de: "die Katastrophe", en: "disaster", take: true },
        { es: "derrumbaron", de: "brachen zusammen (derrumbarse)", en: "collapsed (derrumbarse)", take: false },
        { es: "armas", de: "die Waffen", en: "weapons", take: true },
        { es: "conquistaron", de: "eroberten (conquistar)", en: "conquered (conquistar)", take: true },
        { es: "riqueza", de: "der Reichtum", en: "wealth", take: true },
      ],
      img: "John Everett Millais - Pizarro seizing the Inca of Peru.jpg",
      imgCaption: "Pizarro nimmt den Inka gefangen (J. E. Millais, 1846)",
      imgCaptionEn: "Pizarro seizing the Inca (J. E. Millais, 1846)",
    },
    {
      id: "colonial",
      icon: "👑",
      period: "1542–1808",
      title: "Die Kolonialzeit – Vizekönige & Silber",
      titleEn: "The colonial era – viceroys & silver",
      lead: "Fast drei Jahrhunderte regierte Spanien von Lima und Bogotá aus – getragen vom Silber.",
      leadEn: "For almost three centuries Spain ruled from Lima and Bogotá – carried by silver.",
      body: [
        "Südamerika wurde in Vizekönigreiche (virreinatos) gegliedert. Lange war das Virreinato del Perú mit Hauptstadt Lima das Herzstück; später kamen Nueva Granada (Bogotá, 1717) und Río de la Plata (Buenos Aires, 1776) hinzu. Ein Vizekönig vertrat den spanischen König direkt.",
        "Den Motor bildete der Silberberg Cerro Rico in Potosí (heute Bolivien): Über zwei Jahrhunderte kam von hier ein großer Teil des Weltsilbers – geschürft in der mita, einer Zwangsarbeit, die unzählige indigene und versklavte afrikanische Menschen das Leben kostete.",
        "Die Gesellschaft war streng nach Herkunft geschichtet: oben die in Spanien geborenen peninsulares, darunter die im Land geborenen Weißen (criollos), dann mestizos, indígenas und versklavte Afrikaner. Genau dieser Riss – reiche, gebildete criollos ohne politische Macht – sollte später den Freiheitskampf entzünden.",
      ],
      bodyEn: [
        "South America was organised into viceroyalties (virreinatos). For a long time the Viceroyalty of Peru, with its capital Lima, was the heart of it; later came New Granada (Bogotá, 1717) and Río de la Plata (Buenos Aires, 1776). A viceroy represented the Spanish king directly.",
        "The engine was the silver mountain Cerro Rico at Potosí (in today's Bolivia): for over two centuries a large share of the world's silver came from here – mined under the mita, a forced-labour system that cost countless indigenous and enslaved African people their lives.",
        "Society was strictly layered by origin: at the top the Spanish-born peninsulares, below them the locally born whites (criollos), then mestizos, indígenas and enslaved Africans. It was precisely this fault line – wealthy, educated criollos with no political power – that would later ignite the struggle for freedom.",
      ],
      points: [
        "Potosí war um 1600 eine der größten Städte der Welt",
        "Drei Vizekönigreiche: Perú, Nueva Granada, Río de la Plata",
        "Die Kirche prägte Sprache, Bildung und Alltag tief",
      ],
      pointsEn: [
        "Around 1600 Potosí was one of the largest cities in the world",
        "Three viceroyalties: Peru, New Granada, Río de la Plata",
        "The Church deeply shaped language, education and daily life",
      ],
      level: "B2",
      es: [
        "Durante casi tres siglos, España *gobernó* sus colonias americanas desde ciudades como Lima y Bogotá. El continente se dividió en grandes virreinatos, *mandados* por un virrey que representaba directamente al rey español y tenía un poder casi total.",
        "El verdadero motor de todo era la plata. Del cerro Rico de Potosí, en la actual Bolivia, salió durante dos siglos gran parte de la plata del mundo. Se *extraía* con trabajo *forzado*, un sistema llamado mita, que costó la *vida* a muchísimos indígenas y a africanos *esclavizados*. Ese metal financió guerras y palacios al otro lado del *océano*.",
        "La sociedad colonial estaba *dividida* de forma muy estricta según el origen de cada persona: arriba, los nacidos en España; después, los criollos (hijos de españoles nacidos en América); y abajo, los indígenas, los mestizos y los *esclavos*. Justamente esa profunda *desigualdad* —criollos ricos y cultos, pero sin poder político— encendería más tarde la lucha por la *libertad*.",
      ],
      vocab: [
        { es: "gobernó", de: "regierte (gobernar)", en: "governed (gobernar)", take: true },
        { es: "mandados", de: "befehligt (mandar)", en: "commanded (mandar)", take: true },
        { es: "extraía", de: "förderte, baute ab (extraer)", en: "extracted (extraer)", take: false },
        { es: "forzado", de: "Zwangs-, erzwungen", en: "forced", take: true },
        { es: "vida", de: "das Leben", en: "life", take: true },
        { es: "esclavizados", de: "versklavt (esclavizar)", en: "enslaved (esclavizar)", take: false },
        { es: "océano", de: "der Ozean", en: "ocean", take: true },
        { es: "dividida", de: "geteilt (dividir)", en: "divided (dividir)", take: true },
        { es: "esclavos", de: "die Sklaven", en: "slaves", take: true },
        { es: "desigualdad", de: "die Ungleichheit", en: "inequality", take: true },
        { es: "libertad", de: "die Freiheit", en: "freedom", take: true },
      ],
      img: "Virreinato del Perú en el mapa de la América del Sur de Agustín Ibáñez y Bojons, 1800.jpg",
      imgCaption: "Südamerika unter spanischer Herrschaft (Karte, 1800)",
      imgCaptionEn: "South America under Spanish rule (map, 1800)",
    },
    {
      id: "chispa",
      icon: "🔥",
      period: "1780–1810",
      title: "Der Funke – Aufklärung, Napoleon & die ersten Junten",
      titleEn: "The spark – Enlightenment, Napoleon & the first juntas",
      lead: "Neue Ideen und eine Krise in Europa öffneten plötzlich das Fenster zur Freiheit.",
      leadEn: "New ideas and a crisis in Europe suddenly opened a window to freedom.",
      body: [
        "Schon 1780 erhob sich im Hochland Perus Túpac Amaru II., Nachfahre der Inka, gegen die Ausbeutung – ein gewaltiger indigener Aufstand, blutig niedergeschlagen, aber unvergessen. Gleichzeitig sickerten die Ideen der Aufklärung und das Vorbild der US-amerikanischen und der Französischen Revolution ins Land.",
        "Den entscheidenden Stoß gab Europa selbst: 1808 besetzte Napoleon Spanien und setzte König Fernando VII. ab. Damit fehlte plötzlich die Legitimität – in wessen Namen sollten die Kolonien regiert werden?",
        "Die Antwort der criollos: 1810 bildeten sie eigene Regierungsräte (juntas) – in Caracas, Buenos Aires, Bogotá und Santiago. Offiziell „bis zur Rückkehr des Königs“, in Wahrheit der erste Schritt in die Unabhängigkeit.",
      ],
      bodyEn: [
        "As early as 1780, Túpac Amaru II, a descendant of the Inca, rose up in the Peruvian highlands against exploitation – a massive indigenous revolt, brutally crushed but never forgotten. At the same time, the ideas of the Enlightenment and the example of the American and French Revolutions seeped into the land.",
        "The decisive push came from Europe itself: in 1808 Napoleon occupied Spain and deposed King Ferdinand VII. Suddenly legitimacy was gone – in whose name were the colonies to be governed?",
        "The criollos' answer: in 1810 they formed their own governing councils (juntas) – in Caracas, Buenos Aires, Bogotá and Santiago. Officially \"until the king returns\", but in truth the first step towards independence.",
      ],
      points: [
        "1780: Aufstand des Túpac Amaru II. in Peru",
        "1808: Napoleon besetzt Spanien – Machtvakuum",
        "1810: die ersten Junten von Caracas bis Santiago",
      ],
      pointsEn: [
        "1780: revolt of Túpac Amaru II in Peru",
        "1808: Napoleon occupies Spain – a power vacuum",
        "1810: the first juntas from Caracas to Santiago",
      ],
      level: "B2",
      es: [
        "Ya en 1780, en los Andes del Perú, un descendiente de los incas llamado Túpac Amaru II se *rebeló* contra la *explotación* de su pueblo. Fue una enorme revuelta indígena, *aplastada* con mucha violencia, pero que nunca se olvidó y se convirtió en un símbolo.",
        "Al mismo tiempo, las ideas de la Ilustración y el ejemplo de las revoluciones de Estados Unidos y Francia *entraban* poco a poco en las colonias. Muchos criollos empezaron a *soñar* con gobernarse a sí mismos y a leer libros que hablaban de libertad e igualdad.",
        "El *empujón* decisivo vino de Europa: en 1808, Napoleón *invadió* España y quitó del trono al rey Fernando VII. De repente faltaba la *legitimidad*: ¿en nombre de quién había que gobernar? La respuesta de los criollos llegó en 1810, cuando formaron sus propias juntas de gobierno en Caracas, Buenos Aires, Bogotá y Santiago. Decían que era „hasta el *regreso* del rey“, pero en realidad era el primer *paso* hacia la independencia.",
      ],
      vocab: [
        { es: "rebeló", de: "lehnte sich auf (rebelarse)", en: "rebelled (rebelarse)", take: true },
        { es: "explotación", de: "die Ausbeutung", en: "exploitation", take: true },
        { es: "aplastada", de: "niedergeschlagen (aplastar)", en: "crushed (aplastar)", take: false },
        { es: "entraban", de: "drangen ein, kamen herein (entrar)", en: "were entering (entrar)", take: true },
        { es: "soñar", de: "träumen", en: "to dream", take: true },
        { es: "empujón", de: "der Stoß, Schubs (empujar)", en: "push, shove (empujar)", take: true },
        { es: "invadió", de: "fiel ein (invadir)", en: "invaded (invadir)", take: true },
        { es: "legitimidad", de: "die Legitimität", en: "legitimacy", take: false },
        { es: "regreso", de: "die Rückkehr (regresar)", en: "return (regresar)", take: true },
        { es: "paso", de: "der Schritt", en: "step", take: true },
      ],
      img: "Túpac Amaru II.JPG",
      imgCaption: "Túpac Amaru II. – früher Aufstand gegen die Kolonialmacht",
      imgCaptionEn: "Túpac Amaru II – an early revolt against colonial power",
    },
    {
      id: "independencia",
      icon: "🗡️",
      period: "1810–1825",
      title: "Der Freiheitskampf – Bolívar & San Martín",
      titleEn: "The fight for freedom – Bolívar & San Martín",
      lead: "Zwei große Befreiungszüge – aus dem Norden und dem Süden – trafen sich in der Mitte.",
      leadEn: "Two great campaigns of liberation – from the north and the south – met in the middle.",
      body: [
        "Aus dem Norden kämpfte Simón Bolívar, „El Libertador“. Nach Jahren der Niederlagen gelang ihm 1819 ein kühner Marsch über die eisigen Anden und der Sieg bei Boyacá – Kolumbien war frei. 1821 entschied Carabobo Venezuela, 1822 Pichincha Ecuador.",
        "Aus dem Süden zog José de San Martín. Argentinien hatte sich 1816 in Tucumán für unabhängig erklärt. San Martín überquerte mit seiner Armee die Anden, befreite 1818 mit Bernardo O'Higgins Chile (Schlacht von Maipú) und landete 1821 in Peru, wo er die Unabhängigkeit ausrief.",
        "1822 trafen sich die beiden Befreier in Guayaquil. Was genau besprochen wurde, ist bis heute ein Rätsel – doch San Martín zog sich danach zurück und überließ Bolívar das Feld. Dessen General Antonio José de Sucre besiegte 1824 bei Ayacucho die letzte große spanische Armee. 1825 war ganz Südamerika frei; das neue Land Bolivien trug Bolívars Namen.",
      ],
      bodyEn: [
        "From the north fought Simón Bolívar, \"El Libertador\". After years of defeats, in 1819 he pulled off a daring march across the icy Andes and won at Boyacá – Colombia was free. In 1821 Carabobo decided Venezuela, in 1822 Pichincha decided Ecuador.",
        "From the south came José de San Martín. Argentina had declared independence at Tucumán in 1816. San Martín led his army across the Andes, liberated Chile with Bernardo O'Higgins in 1818 (Battle of Maipú) and landed in Peru in 1821, where he proclaimed independence.",
        "In 1822 the two liberators met in Guayaquil. Exactly what was said remains a mystery to this day – but San Martín then withdrew and left the field to Bolívar. Bolívar's general Antonio José de Sucre defeated the last great Spanish army at Ayacucho in 1824. By 1825 all of South America was free; the new country of Bolivia bore Bolívar's name.",
      ],
      points: [
        "1819 Boyacá · 1821 Carabobo · 1822 Pichincha · 1824 Ayacucho",
        "San Martín & Bolívar trafen sich 1822 in Guayaquil",
        "1825: Bolivien entsteht – benannt nach Bolívar",
      ],
      pointsEn: [
        "1819 Boyacá · 1821 Carabobo · 1822 Pichincha · 1824 Ayacucho",
        "San Martín & Bolívar met in Guayaquil in 1822",
        "1825: Bolivia is founded – named after Bolívar",
      ],
      level: "B1",
      es: [
        "La independencia llegó en dos grandes oleadas que avanzaban una hacia la otra. Desde el norte luchó Simón Bolívar, „El Libertador“. Tras años de *derrotas* y exilios, en 1819 cruzó los Andes *helados* con su ejército y *venció* por sorpresa en la batalla de Boyacá. Colombia quedó libre, y poco después también Venezuela y Ecuador.",
        "Desde el sur avanzó José de San Martín. Después de liberar Argentina, hizo algo casi imposible: cruzó la enorme cordillera de los Andes con un *ejército* entero, *liberó* Chile junto a Bernardo O'Higgins y llegó por mar hasta el Perú, donde *proclamó* la independencia en 1821.",
        "En 1822, los dos grandes libertadores se *reunieron* en secreto en Guayaquil. Nadie sabe con certeza qué hablaron, pero después San Martín se *retiró* de la política y dejó todo el camino libre a Bolívar. Dos años más tarde, en 1824, el joven general Sucre *ganó* la *batalla* de Ayacucho contra el último ejército español. Toda Sudamérica era por fin libre.",
      ],
      vocab: [
        { es: "derrotas", de: "die Niederlagen (derrota)", en: "defeats (derrota)", take: true },
        { es: "helados", de: "eisig; auch: Eis", en: "icy; also: ice cream", take: true },
        { es: "venció", de: "siegte (vencer)", en: "won, defeated (vencer)", take: true },
        { es: "ejército", de: "das Heer, die Armee", en: "army", take: true },
        { es: "liberó", de: "befreite (liberar)", en: "liberated (liberar)", take: true },
        { es: "proclamó", de: "rief aus (proclamar)", en: "proclaimed (proclamar)", take: false },
        { es: "reunieron", de: "trafen sich (reunirse)", en: "met (reunirse)", take: true },
        { es: "retiró", de: "zog sich zurück (retirarse)", en: "withdrew (retirarse)", take: true },
        { es: "ganó", de: "gewann (ganar)", en: "won (ganar)", take: true },
        { es: "batalla", de: "die Schlacht", en: "battle", take: false },
      ],
      img: "Batalla de Ayacucho by Martín Tovar y Tovar (1827 - 1902).jpg",
      imgCaption: "Schlacht von Ayacucho 1824 – das Ende der Kolonialherrschaft",
      imgCaptionEn: "Battle of Ayacucho 1824 – the end of colonial rule",
    },
    {
      id: "naciones",
      icon: "🗺️",
      period: "1819–1860",
      title: "Die Abspaltung – vom Traum zu vielen Nationen",
      titleEn: "The break-up – from one dream to many nations",
      lead: "Bolívars Vision eines geeinten Südamerika zerbrach an Entfernungen und Rivalitäten.",
      leadEn: "Bolívar's vision of a united South America shattered on distance and rivalry.",
      body: [
        "Bolívar träumte von einem großen, geeinten Staat. Aus dem Norden formte er Gran Colombia – das heutige Venezuela, Kolumbien, Ecuador und Panama in einem Land. Doch das Reich war riesig, die Regionen eigensinnig, und lokale Anführer (caudillos) wollten selbst herrschen.",
        "Schon 1830 zerfiel Gran Colombia in Venezuela, Kolumbien und Ecuador. Im selben Jahr starb Bolívar verbittert und mittellos. Sein berühmter Satz: „Wer einer Revolution dient, pflügt im Meer.“ Auch im Süden splitterten die Vereinigten Provinzen des Río de la Plata in Argentinien, Uruguay, Paraguay und Bolivien.",
        "Brasilien ging einen ganz eigenen Weg: portugiesisch statt spanisch, und zunächst ein Kaiserreich statt einer Republik. Überall folgten Jahrzehnte der Bürgerkriege zwischen Zentralisten und Föderalisten – die Landkarte Südamerikas, wie wir sie heute kennen, war geboren.",
      ],
      bodyEn: [
        "Bolívar dreamed of one great, united state. In the north he forged Gran Colombia – today's Venezuela, Colombia, Ecuador and Panama in a single country. But the realm was vast, the regions headstrong, and local strongmen (caudillos) wanted to rule themselves.",
        "By 1830 Gran Colombia had already broken apart into Venezuela, Colombia and Ecuador. That same year Bolívar died, bitter and penniless. His famous line: \"He who serves a revolution ploughs the sea.\" In the south, too, the United Provinces of the Río de la Plata splintered into Argentina, Uruguay, Paraguay and Bolivia.",
        "Brazil took an entirely separate path: Portuguese rather than Spanish, and at first an empire rather than a republic. Everywhere there followed decades of civil war between centralists and federalists – and the map of South America as we know it today was born.",
      ],
      points: [
        "Gran Colombia: Venezuela + Kolumbien + Ecuador + Panama",
        "1830: Zerfall – und Bolívars Tod",
        "Brasilien blieb portugiesisch und war erst ein Kaiserreich",
      ],
      pointsEn: [
        "Gran Colombia: Venezuela + Colombia + Ecuador + Panama",
        "1830: the break-up – and Bolívar's death",
        "Brazil stayed Portuguese and was at first an empire",
      ],
      level: "B2",
      es: [
        "Bolívar *soñaba* con un solo país grande y unido, como una „patria americana“. En el norte logró crear la Gran Colombia, que reunía a Venezuela, Colombia, Ecuador y Panamá en un mismo Estado. Pero el *territorio* era inmenso, las distancias enormes y los jefes locales, los *caudillos*, querían mandar cada uno en su región.",
        "El sueño se *rompió* muy rápido. Ya en 1830 la Gran Colombia se *deshizo* en varios países. Ese mismo año Bolívar murió, *amargado* y pobre, lejos del poder. Una frase suya resume su tristeza: „El que sirve una revolución *ara* en el mar“. En el sur pasó algo parecido: las antiguas provincias se *separaron* en Argentina, Uruguay, Paraguay y Bolivia.",
        "Brasil siguió un camino totalmente distinto: hablaba *portugués* en vez de español y, al principio, fue un *imperio* con su propio emperador, no una república. En casi todos los países nuevos vinieron después décadas de guerras civiles entre quienes querían un gobierno central fuerte y quienes preferían más poder para las regiones. Así nació, poco a poco, el *mapa* de Sudamérica que conocemos hoy.",
      ],
      vocab: [
        { es: "soñaba", de: "träumte (soñar)", en: "dreamed (soñar)", take: true },
        { es: "territorio", de: "das Gebiet", en: "territory", take: true },
        { es: "caudillos", de: "die Machthaber, Anführer", en: "strongmen, warlords", take: false },
        { es: "rompió", de: "zerbrach (romperse)", en: "broke (romperse)", take: true },
        { es: "deshizo", de: "zerfiel (deshacerse)", en: "fell apart (deshacerse)", take: true },
        { es: "amargado", de: "verbittert", en: "embittered", take: false },
        { es: "ara", de: "pflügt (arar)", en: "ploughs (arar)", take: false },
        { es: "separaron", de: "trennten sich (separarse)", en: "separated (separarse)", take: true },
        { es: "portugués", de: "portugiesisch", en: "Portuguese", take: true },
        { es: "imperio", de: "das Kaiserreich, Reich", en: "empire", take: true },
        { es: "mapa", de: "die Karte", en: "map", take: true },
      ],
      img: "Gran Colombia in 1824.svg",
      imgCaption: "Gran Colombia 1824 – Bolívars Traum von der Einheit",
      imgCaptionEn: "Gran Colombia in 1824 – Bolívar's dream of unity",
    },
    {
      id: "moderno",
      icon: "⏳",
      period: "1860–heute",
      periodEn: "1860–today",
      title: "Bis heute – Kriege, Diktaturen, Demokratie",
      titleEn: "Up to today – wars, dictatorships, democracy",
      lead: "Grenzkriege, ein dunkles Jahrhundert der Militärregime – und die Rückkehr der Demokratie.",
      leadEn: "Border wars, a dark century of military regimes – and the return of democracy.",
      body: [
        "Die jungen Staaten stritten um Grenzen. Im Salpeterkrieg (1879–1883) verlor Bolivien seinen Zugang zum Meer an Chile – ein Trauma bis heute. Im Krieg der Tripel-Allianz (1864–1870) wurde Paraguay verheert und verlor einen großen Teil seiner Bevölkerung.",
        "Das 20. Jahrhundert brachte Populismus (etwa Juan Perón in Argentinien) und im Kalten Krieg eine Welle von Militärdiktaturen: Chile unter Pinochet ab 1973, die argentinische Junta mit ihren „Verschwundenen“, dazu Brasilien, Uruguay und andere – grenzüberschreitend vernetzt in der „Operación Cóndor“.",
        "In den 1980er- und 90er-Jahren kehrten fast überall Demokratie und Wahlen zurück. Heute ist Südamerika ein Kontinent demokratischer Republiken – mit lebendiger Kultur und großem Reichtum, aber auch mit Ungleichheit, Korruption und politischen Erschütterungen, die bis in die Gegenwart reichen.",
      ],
      bodyEn: [
        "The young states fought over borders. In the War of the Pacific (1879–1883) Bolivia lost its access to the sea to Chile – a trauma to this day. In the War of the Triple Alliance (1864–1870) Paraguay was devastated and lost a huge share of its population.",
        "The 20th century brought populism (such as Juan Perón in Argentina) and, during the Cold War, a wave of military dictatorships: Chile under Pinochet from 1973, the Argentine junta with its \"disappeared\", along with Brazil, Uruguay and others – networked across borders in \"Operation Condor\".",
        "In the 1980s and 90s, democracy and elections returned almost everywhere. Today South America is a continent of democratic republics – with vibrant culture and great wealth, but also with inequality, corruption and political upheavals that reach into the present.",
      ],
      points: [
        "1879–83 Salpeterkrieg: Bolivien verliert die Küste",
        "1973–1990: Militärdiktaturen & „Operación Cóndor“",
        "Ab ~1985: Rückkehr zu Demokratie und Wahlen",
      ],
      pointsEn: [
        "1879–83 War of the Pacific: Bolivia loses its coast",
        "1973–1990: military dictatorships & \"Operation Condor\"",
        "From ~1985: a return to democracy and elections",
      ],
      level: "B1",
      es: [
        "Una vez libres, los nuevos países empezaron a *pelear* entre sí por sus *fronteras*. En la Guerra del Pacífico (1879–1883), Bolivia *perdió* toda su costa y se quedó sin salida al mar, una herida que todavía duele hoy. Antes, en la Guerra de la Triple Alianza, Paraguay quedó *destrozado* y perdió a una gran parte de su población.",
        "El siglo XX trajo líderes *populistas* muy queridos, como Juan Perón en Argentina, pero también una época muy oscura. Durante la Guerra Fría, varios países cayeron bajo *dictaduras* militares: Chile con Pinochet desde 1973, la junta de Argentina con sus miles de *desaparecidos*, y también Brasil, Uruguay y otros. Muchos opositores fueron *perseguidos*, torturados o asesinados.",
        "Por suerte, en los años ochenta y noventa *volvió* la *democracia* a casi toda la región, con elecciones y libertad de prensa. Hoy Sudamérica es un continente de *repúblicas*, con una cultura muy *viva* y mucha riqueza natural, pero todavía con grandes problemas de desigualdad, corrupción y crisis políticas que llegan hasta el presente.",
      ],
      vocab: [
        { es: "pelear", de: "kämpfen, streiten", en: "to fight", take: true },
        { es: "fronteras", de: "die Grenzen", en: "borders", take: true },
        { es: "perdió", de: "verlor (perder)", en: "lost (perder)", take: true },
        { es: "destrozado", de: "zerstört (destrozar)", en: "destroyed (destrozar)", take: true },
        { es: "populistas", de: "populistisch; Populisten", en: "populist", take: false },
        { es: "dictaduras", de: "die Diktaturen", en: "dictatorships", take: true },
        { es: "desaparecidos", de: "die Verschwundenen", en: "the disappeared", take: false },
        { es: "perseguidos", de: "verfolgt (perseguir)", en: "persecuted (perseguir)", take: true },
        { es: "volvió", de: "kehrte zurück (volver)", en: "returned (volver)", take: true },
        { es: "democracia", de: "die Demokratie", en: "democracy", take: true },
        { es: "repúblicas", de: "die Republiken", en: "republics", take: true },
        { es: "viva", de: "lebendig (vivo/viva)", en: "lively, alive", take: true },
      ],
      img: "",
      imgCaption: "",
    },
  ];

  // ---------- Die Protagonisten (Galerie) ----------
  const FIGURES = [
    {
      id: "bolivar",
      name: "Simón Bolívar",
      level: "B1",
      es: [
        "Es, sin duda, el nombre más grande de todo el continente. Simón Bolívar nació en una familia *rica* de criollos en Caracas y, de joven, viajó por Europa, donde *juró* dedicar su vida a liberar a su tierra de España.",
        "Cumplió esa promesa con creces. *Lideró* la dura *lucha* por la libertad en el norte y *liberó* nada menos que cinco países: Venezuela, Colombia, Ecuador, Perú y Bolivia, que lleva su nombre en su honor. Por eso lo llaman „El Libertador“.",
        "Pero su gran sueño era otro: una sola Sudamérica unida y fuerte. Cuando vio que ese sueño se *rompía* en pedazos y que cada región tiraba por su lado, murió *decepcionado*, enfermo y casi sin dinero. Hoy varios países lo *honran* como su héroe nacional.",
      ],
      vocab: [
        { es: "rica", de: "reich (rico/rica)", en: "rich", take: true },
        { es: "juró", de: "schwor (jurar)", en: "swore (jurar)", take: true },
        { es: "lideró", de: "führte an (liderar)", en: "led (liderar)", take: true },
        { es: "lucha", de: "der Kampf (luchar)", en: "struggle, fight (luchar)", take: true },
        { es: "liberó", de: "befreite (liberar)", en: "liberated (liberar)", take: true },
        { es: "rompía", de: "zerbrach (romperse)", en: "was breaking (romperse)", take: true },
        { es: "decepcionado", de: "enttäuscht", en: "disappointed", take: true },
        { es: "honran", de: "ehren (honrar)", en: "honour (honrar)", take: false },
      ],
      role: "„El Libertador“ – befreite sechs Länder",
      roleEn: "\"El Libertador\" – liberated six countries",
      years: "1783–1830",
      flag: "🇻🇪",
      img: "Bolivar Arturo Michelena.jpg",
      text: "Der wohl größte Name des Kontinents. Der reiche criollo aus Caracas führte den Freiheitskampf im Norden, befreite das heutige Venezuela, Kolumbien, Ecuador, Peru und Bolivien und träumte von einem geeinten Südamerika. Er starb desillusioniert, als sein Traum zerbrach – heute ehren ihn gleich mehrere Länder als Nationalhelden.",
      textEn: "Probably the greatest name on the continent. The wealthy criollo from Caracas led the fight for freedom in the north, liberated today's Venezuela, Colombia, Ecuador, Peru and Bolivia, and dreamed of a united South America. He died disillusioned as his dream fell apart – today several countries honour him as a national hero.",
      quote: "„Die Kunst des Siegens lernt man in Niederlagen.“",
      quoteEn: "\"The art of victory is learned in defeat.\"",
    },
    {
      id: "sanmartin",
      name: "José de San Martín",
      level: "B1",
      es: [
        "Si Bolívar era pura pasión, José de San Martín era el *estratega* frío y paciente del sur. Militar de profesión, pensaba cada campaña con mucho cuidado antes de actuar.",
        "Primero aseguró la independencia de Argentina. Después *cruzó* la enorme cordillera de los Andes con todo un ejército, una *hazaña* casi imposible, y *liberó* Chile y el Perú uno tras otro.",
        "En 1822 se *reunió* con Bolívar en Guayaquil. Para evitar una guerra entre patriotas y dejar que Bolívar terminara la obra, San Martín tomó una decisión sorprendente: *renunció* a todo su poder y se marchó a vivir a Europa, donde murió pobre y casi olvidado. Hoy se le admira justamente por esa *humildad*.",
      ],
      vocab: [
        { es: "estratega", de: "der Stratege", en: "strategist", take: false },
        { es: "cruzó", de: "überquerte (cruzar)", en: "crossed (cruzar)", take: true },
        { es: "hazaña", de: "die Heldentat, Meisterleistung", en: "feat, exploit", take: false },
        { es: "liberó", de: "befreite (liberar)", en: "liberated (liberar)", take: true },
        { es: "reunió", de: "traf sich (reunirse)", en: "met (reunirse)", take: true },
        { es: "renunció", de: "verzichtete (renunciar)", en: "renounced, gave up (renunciar)", take: true },
        { es: "humildad", de: "die Bescheidenheit", en: "humility", take: true },
      ],
      role: "Befreier des Südens",
      roleEn: "Liberator of the south",
      years: "1778–1850",
      flag: "🇦🇷",
      img: "José de San Martín (retrato, c.1828).jpg",
      text: "Der nüchterne Stratege des Südens. Er machte Argentinien frei, überquerte mit einer ganzen Armee die Anden, befreite Chile und Peru. Nach dem geheimnisvollen Treffen mit Bolívar in Guayaquil 1822 trat er freiwillig zurück, um einen Machtkampf zu vermeiden, und ging ins Exil nach Frankreich – ein seltener Fall von Verzicht aus Staatsräson.",
      textEn: "The sober strategist of the south. He freed Argentina, crossed the Andes with an entire army, and liberated Chile and Peru. After the mysterious meeting with Bolívar in Guayaquil in 1822, he voluntarily stepped down to avoid a power struggle and went into exile in France – a rare case of renunciation for reasons of state.",
      quote: "„Du wirst sein, was du sein musst, oder du wirst nichts sein.“",
      quoteEn: "\"You shall be what you must be, or you shall be nothing.\"",
    },
    {
      id: "sucre",
      name: "Antonio José de Sucre",
      level: "B2",
      es: [
        "Antonio José de Sucre fue el general más joven y más *brillante* de Bolívar, su mano derecha y la persona de mayor *confianza*.",
        "Su gran momento llegó en 1824, en la batalla de Ayacucho. Allí *derrotó* por completo al último gran ejército español de Sudamérica y *aseguró* la independencia de todo el continente. Tenía apenas treinta años.",
        "Después se convirtió en el primer presidente de Bolivia, el país que tomó el nombre de Bolívar. Gobernó con *honradez*, pero la política de la época era muy violenta: lo *asesinaron* en una *emboscada* cuando solo tenía treinta y cinco años. La capital del país, Sucre, lleva su nombre para recordarlo.",
      ],
      vocab: [
        { es: "brillante", de: "brillant, glänzend", en: "brilliant", take: false },
        { es: "confianza", de: "das Vertrauen", en: "trust", take: true },
        { es: "derrotó", de: "besiegte (derrotar)", en: "defeated (derrotar)", take: true },
        { es: "aseguró", de: "sicherte (asegurar)", en: "secured (asegurar)", take: true },
        { es: "honradez", de: "die Ehrlichkeit", en: "honesty", take: false },
        { es: "asesinaron", de: "ermordeten (asesinar)", en: "assassinated (asesinar)", take: false },
        { es: "emboscada", de: "der Hinterhalt", en: "ambush", take: false },
      ],
      role: "Der Sieger von Ayacucho",
      roleEn: "The victor of Ayacucho",
      years: "1795–1830",
      flag: "🇧🇴",
      img: "Jose Antonio de Sucre.JPG",
      text: "Bolívars genialer junger General. In der Schlacht von Ayacucho 1824 zerschlug er die letzte große spanische Armee und besiegelte damit die Unabhängigkeit ganz Südamerikas. Als Präsident regierte er das neue Bolivien, dessen Hauptstadt Sucre bis heute seinen Namen trägt. Mit nur 35 Jahren wurde er aus dem Hinterhalt ermordet.",
      textEn: "Bolívar's brilliant young general. At the Battle of Ayacucho in 1824 he smashed the last great Spanish army and thereby sealed the independence of all South America. As president he governed the new Bolivia, whose capital Sucre still bears his name today. At just 35 he was assassinated in an ambush.",
      quote: "",
      quoteEn: "",
    },
    {
      id: "ohiggins",
      name: "Bernardo O'Higgins",
      level: "B1",
      es: [
        "Bernardo O'Higgins tuvo una vida de novela. Era hijo de un virrey español de origen irlandés, pero terminó convirtiéndose en el gran *héroe* de la independencia de Chile.",
        "Junto a San Martín *ganó* la decisiva batalla de Maipú en 1818 y llevó por fin a Chile a la *libertad*. Como primer jefe del país, con el título de „Director Supremo“, intentó *modernizar* la joven nación.",
        "Sin embargo, muchas de sus reformas molestaron a los poderosos, y O'Higgins tuvo que *renunciar* al poder. Se marchó al *exilio* en el Perú, donde vivió sus últimos años y murió sin volver a ver su país. Hoy es uno de los grandes símbolos de Chile.",
      ],
      vocab: [
        { es: "héroe", de: "der Held", en: "hero", take: true },
        { es: "ganó", de: "gewann (ganar)", en: "won (ganar)", take: true },
        { es: "libertad", de: "die Freiheit", en: "freedom", take: true },
        { es: "modernizar", de: "modernisieren", en: "to modernise", take: false },
        { es: "renunciar", de: "verzichten, zurücktreten", en: "to renounce, resign", take: true },
        { es: "exilio", de: "das Exil", en: "exile", take: false },
      ],
      role: "Vater des unabhängigen Chile",
      roleEn: "Father of independent Chile",
      years: "1778–1842",
      flag: "🇨🇱",
      img: "Retrato de Don Bernardo O'Higgins (José Gil de Castro, 1820).jpg",
      text: "Sohn eines irischstämmigen Vizekönigs, wurde er zum Helden Chiles. Gemeinsam mit San Martín gewann er die Schlacht von Maipú 1818 und führte Chile in die Unabhängigkeit. Als erster Regierungschef („Director Supremo“) modernisierte er das Land – musste aber bald ins Exil nach Peru, wo er starb.",
      textEn: "Son of a viceroy of Irish descent, he became the hero of Chile. Together with San Martín he won the Battle of Maipú in 1818 and led Chile to independence. As the first head of government (\"Supreme Director\") he modernised the country – but soon had to go into exile in Peru, where he died.",
      quote: "",
      quoteEn: "",
    },
    {
      id: "manuela",
      name: "Manuela Sáenz",
      level: "B1",
      es: [
        "Manuela Sáenz fue mucho más que „la novia de Bolívar“, como la pintaron durante mucho tiempo. Fue una verdadera *revolucionaria*: luchó por la independencia, transmitió mensajes secretos y trabajó como *espía*.",
        "Su momento más famoso llegó en 1828, en Bogotá. Un grupo de enemigos entró de noche en el palacio para *matar* a Bolívar, pero Manuela los *frustró* y lo ayudó a *escapar* por una ventana. Desde entonces la llaman „la Libertadora del Libertador“.",
        "Durante años, la historia oficial la trató con desprecio y casi la *olvidó*. Hoy, en cambio, se la reconoce como una heroína por derecho propio y como un *símbolo* del papel, muchas veces escondido, de las mujeres en la lucha por la libertad.",
      ],
      vocab: [
        { es: "revolucionaria", de: "Revolutionärin; revolutionär", en: "revolutionary", take: false },
        { es: "espía", de: "der/die Spion(in)", en: "spy", take: false },
        { es: "matar", de: "töten", en: "to kill", take: true },
        { es: "frustró", de: "vereitelte (frustrar)", en: "foiled, thwarted (frustrar)", take: true },
        { es: "escapar", de: "entkommen, fliehen", en: "to escape", take: true },
        { es: "olvidó", de: "vergaß (olvidar)", en: "forgot (olvidar)", take: true },
        { es: "símbolo", de: "das Symbol", en: "symbol", take: true },
      ],
      role: "„Libertadora del Libertador“",
      roleEn: "\"Liberator of the Liberator\"",
      years: "1797–1856",
      flag: "🇪🇨",
      img: "Manuela Saenz 1825.jpg",
      text: "Revolutionärin, Spionin und Bolívars Gefährtin. Sie rettete ihm 1828 in Bogotá das Leben, indem sie einen Mordanschlag vereitelte – daher ihr Beiname. Lange als bloße Geliebte abgetan, gilt sie heute als eigenständige Heldin der Unabhängigkeit und Ikone für die Rolle der Frauen im Freiheitskampf.",
      textEn: "Revolutionary, spy and Bolívar's companion. She saved his life in Bogotá in 1828 by foiling an assassination attempt – hence her nickname. Long dismissed as a mere lover, she is today regarded as an independence heroine in her own right and an icon for the role of women in the struggle for freedom.",
      quote: "",
      quoteEn: "",
    },
    {
      id: "atahualpa",
      name: "Atahualpa",
      level: "B1",
      es: [
        "Atahualpa fue el último gran rey de los incas. Acababa de *ganar* una larga guerra civil contra su hermano por el trono cuando, de repente, aparecieron los españoles de Pizarro.",
        "En la ciudad de Cajamarca cayó en una *trampa*: los españoles lo *capturaron* por sorpresa en medio de una matanza. Para recuperar su libertad, ofreció algo increíble: llenar un cuarto entero de oro como *rescate*.",
        "Atahualpa cumplió su promesa y entregó un enorme *tesoro*, pero los españoles, aun así, lo *ejecutaron*. Su muerte fue mucho más que la de un rey: marcó la *caída* de todo un mundo, el de los incas, y el comienzo de una nueva era.",
      ],
      vocab: [
        { es: "ganar", de: "gewinnen", en: "to win", take: true },
        { es: "trampa", de: "die Falle", en: "trap", take: true },
        { es: "capturaron", de: "nahmen gefangen (capturar)", en: "captured (capturar)", take: true },
        { es: "rescate", de: "das Lösegeld; die Rettung", en: "ransom; rescue", take: true },
        { es: "tesoro", de: "der Schatz", en: "treasure", take: true },
        { es: "ejecutaron", de: "hinrichteten (ejecutar)", en: "executed (ejecutar)", take: false },
        { es: "caída", de: "der Fall, Sturz (caer)", en: "fall, downfall (caer)", take: true },
      ],
      role: "Der letzte Herrscher der Inka",
      roleEn: "The last Inca ruler",
      years: "≈1500–1533",
      flag: "🇵🇪",
      img: "Brooklyn Museum - Atahualpa, Fourteenth Inca, 1 of 14 Portraits of Inca Kings - overall.jpg",
      text: "Hatte gerade einen Bürgerkrieg um den Inka-Thron gewonnen, als die Spanier kamen. In Cajamarca von Pizarro überrumpelt und gefangen genommen, füllte er einen ganzen Raum mit Gold als Lösegeld – und wurde dennoch hingerichtet. Sein Sturz steht für das jähe Ende einer ganzen Welt.",
      textEn: "He had just won a civil war for the Inca throne when the Spanish arrived. Ambushed and captured by Pizarro at Cajamarca, he filled an entire room with gold as ransom – and was executed anyway. His downfall stands for the abrupt end of a whole world.",
      quote: "",
      quoteEn: "",
    },
  ];

  // ---------- Heute: Lage & Spannungen ----------
  const TENSIONS = [
    {
      id: "venezuela",
      icon: "🇻🇪",
      level: "B1",
      es: [
        "Venezuela tiene las mayores reservas de *petróleo* del mundo y, sin embargo, vive una de las peores crisis de su historia. Bajo los gobiernos de Hugo Chávez y, después, de Nicolás Maduro, la economía se *hundió* casi por completo.",
        "Durante años faltaron alimentos, medicinas y dinero, y los precios subían sin parar (una *inflación* altísima). Tras unas elecciones muy *discutidas* en 2024, Maduro sigue en el poder, aunque gran parte del mundo duda de que ganara de verdad.",
        "El resultado humano es enorme: alrededor de ocho millones de venezolanos han *huido* del país en busca de una vida mejor. Es la mayor *crisis* migratoria de toda la historia reciente de América Latina, y se nota en casi todos los países vecinos.",
      ],
      vocab: [
        { es: "petróleo", de: "das Erdöl", en: "oil, petroleum", take: true },
        { es: "hundió", de: "brach zusammen (hundirse)", en: "collapsed, sank (hundirse)", take: true },
        { es: "inflación", de: "die Inflation", en: "inflation", take: true },
        { es: "discutidas", de: "umstritten (discutir)", en: "disputed (discutir)", take: false },
        { es: "huido", de: "geflohen (huir)", en: "fled (huir)", take: true },
        { es: "crisis", de: "die Krise", en: "crisis", take: true },
      ],
      title: "Venezuela: Krise & Massenflucht",
      titleEn: "Venezuela: crisis & mass exodus",
      where: "Venezuela → ganz Lateinamerika",
      whereEn: "Venezuela → all of Latin America",
      tone: "crisis",
      status: "Krise",
      statusEn: "Crisis",
      text: "Das ölreichste Land der Welt steckt in einem wirtschaftlichen und politischen Kollaps. Unter Hugo Chávez und seinem Nachfolger Nicolás Maduro brachen Wirtschaft und Versorgung zusammen; nach der umstrittenen Wahl 2024 hält Maduro trotz breiter Zweifel an der Macht fest. Rund 8 Millionen Venezolaner sind geflohen – die größte Fluchtbewegung der Region.",
      textEn: "The most oil-rich country in the world is mired in economic and political collapse. Under Hugo Chávez and his successor Nicolás Maduro, the economy and basic supplies broke down; after the disputed 2024 election Maduro is clinging to power despite widespread doubts. Around 8 million Venezuelans have fled – the largest displacement in the region.",
    },
    {
      id: "essequibo",
      icon: "🛢️",
      level: "B2",
      es: [
        "El Esequibo es una enorme región de selva que forma casi dos tercios del pequeño país de Guyana. Venezuela dice que ese territorio le pertenece desde hace más de un siglo.",
        "El conflicto estaba casi dormido, pero todo cambió cuando se *descubrió* muchísimo *petróleo* frente a sus costas. De repente, esa zona se volvió riquísima, y Venezuela empezó a *reclamarla* otra vez con mucha fuerza.",
        "En 2023, Maduro organizó una votación y *amenazó* incluso con *anexar* la región. El tribunal más importante del mundo, en La Haya, ha pedido calma a los dos países. Aun así, sigue siendo uno de los *conflictos* de fronteras más peligrosos del continente.",
      ],
      vocab: [
        { es: "descubrió", de: "entdeckte (descubrir)", en: "discovered (descubrir)", take: true },
        { es: "petróleo", de: "das Erdöl", en: "oil, petroleum", take: true },
        { es: "reclamarla", de: "sie beanspruchen (reclamar)", en: "to claim it (reclamar)", take: true },
        { es: "amenazó", de: "drohte (amenazar)", en: "threatened (amenazar)", take: true },
        { es: "anexar", de: "annektieren, angliedern", en: "to annex", take: false },
        { es: "conflictos", de: "die Konflikte", en: "conflicts", take: true },
      ],
      title: "Essequibo: Grenzstreit mit Guyana",
      titleEn: "Essequibo: border dispute with Guyana",
      where: "Venezuela ↔ Guyana",
      whereEn: "Venezuela ↔ Guyana",
      tone: "tense",
      status: "Spannung",
      statusEn: "Tension",
      text: "Seit riesige Ölfunde das kleine Guyana reich machen, beansprucht Venezuela wieder lautstark die Region Essequibo – zwei Drittel des Nachbarlandes. 2023 ließ Maduro darüber abstimmen und drohte mit Annexion. Der Internationale Gerichtshof mahnt zur Ruhe; die Lage bleibt einer der heißesten Grenzkonflikte des Kontinents.",
      textEn: "Ever since huge oil discoveries made tiny Guyana rich, Venezuela has again loudly claimed the Essequibo region – two thirds of its neighbour. In 2023 Maduro held a vote on it and threatened annexation. The International Court of Justice urges calm; the situation remains one of the hottest border conflicts on the continent.",
    },
    {
      id: "salida-al-mar",
      icon: "🌊",
      level: "B1",
      es: [
        "Hace más de cien años, en la Guerra del Pacífico (1879–1883), Bolivia *perdió* contra Chile toda su costa. Desde entonces es un país sin *mar*, rodeado por completo de tierra.",
        "Para los bolivianos, esto no es solo un tema de mapas: es una herida nacional. Recuperar una *salida* al mar es un sueño que aparece en los discursos, en las canciones y hasta en el ejército, que todavía tiene una marina sin costa.",
        "Bolivia llevó el caso ante el tribunal internacional de La Haya, pero en 2018 los jueces *rechazaron* su *demanda*: Chile no está obligado a *negociar*. El asunto sigue *envenenando* la relación entre los dos países vecinos.",
      ],
      vocab: [
        { es: "perdió", de: "verlor (perder)", en: "lost (perder)", take: true },
        { es: "mar", de: "das Meer", en: "sea", take: true },
        { es: "salida", de: "der Ausgang, Zugang", en: "exit, way out", take: true },
        { es: "rechazaron", de: "lehnten ab (rechazar)", en: "rejected (rechazar)", take: true },
        { es: "demanda", de: "die Klage; die Nachfrage", en: "lawsuit; demand", take: true },
        { es: "negociar", de: "verhandeln", en: "to negotiate", take: true },
        { es: "envenenando", de: "vergiftend (envenenar)", en: "poisoning (envenenar)", take: false },
      ],
      title: "Bolivien ohne Meer",
      titleEn: "Bolivia without a coast",
      where: "Bolivien ↔ Chile",
      whereEn: "Bolivia ↔ Chile",
      tone: "tense",
      status: "Altlast",
      statusEn: "Old wound",
      text: "Im Salpeterkrieg (1879–1883) verlor Bolivien seine Pazifikküste an Chile und ist seither ein Binnenland. Die „salida al mar“, die Rückkehr zum Meer, ist bis heute nationale Herzensangelegenheit. 2018 wies der Internationale Gerichtshof Boliviens Klage ab – Chile muss nicht verhandeln. Das Thema vergiftet die Beziehung weiter.",
      textEn: "In the War of the Pacific (1879–1883) Bolivia lost its Pacific coast to Chile and has been landlocked ever since. The \"salida al mar\", the return to the sea, remains a deeply emotional national cause. In 2018 the International Court of Justice rejected Bolivia's claim – Chile is not obliged to negotiate. The issue keeps poisoning the relationship.",
    },
    {
      id: "colombia-paz",
      icon: "🕊️",
      level: "B2",
      es: [
        "Durante más de cincuenta años, Colombia vivió una guerra interna durísima entre el Estado y la guerrilla de las FARC, con miles de muertos, secuestrados y desplazados.",
        "En 2016 llegó un momento histórico: el gobierno y la guerrilla firmaron un *acuerdo* de paz que *terminó* oficialmente con ese conflicto. El presidente que lo logró fue *premiado* con el Premio Nobel de la Paz.",
        "Pero la paz todavía es *frágil*. Quedan grupos *disidentes* que no aceptaron el acuerdo, otra guerrilla llamada ELN y poderosos carteles del narcotráfico. Por eso, bajo el presidente Gustavo Petro, el país sigue *buscando* lo que llaman una „paz total“.",
      ],
      vocab: [
        { es: "acuerdo", de: "das Abkommen, die Einigung", en: "agreement", take: true },
        { es: "terminó", de: "beendete (terminar)", en: "ended (terminar)", take: true },
        { es: "premiado", de: "ausgezeichnet (premiar)", en: "awarded (premiar)", take: false },
        { es: "frágil", de: "zerbrechlich, fragil", en: "fragile", take: true },
        { es: "disidentes", de: "die Abtrünnigen, Dissidenten", en: "dissidents", take: false },
        { es: "buscando", de: "suchend (buscar)", en: "seeking (buscar)", take: true },
      ],
      title: "Kolumbien: ein fragiler Frieden",
      titleEn: "Colombia: a fragile peace",
      where: "Kolumbien",
      whereEn: "Colombia",
      tone: "shift",
      status: "Wandel",
      statusEn: "In flux",
      text: "2016 beendete ein historisches Friedensabkommen den über 50 Jahre währenden Krieg mit der FARC-Guerilla – ein Erfolg, der mit dem Friedensnobelpreis geehrt wurde. Doch abtrünnige Gruppen, die ELN und Drogenkartelle bleiben aktiv. Unter Präsident Gustavo Petro, dem ersten linken Staatschef des Landes, ringt Kolumbien um eine „paz total“, einen vollständigen Frieden.",
      textEn: "In 2016 a historic peace deal ended the more than 50-year war with the FARC guerrillas – a success honoured with the Nobel Peace Prize. But splinter groups, the ELN and drug cartels remain active. Under President Gustavo Petro, the country's first left-wing leader, Colombia is striving for a \"paz total\", a complete peace.",
    },
    {
      id: "peru-politica",
      icon: "🏛️",
      level: "B2",
      es: [
        "Pocos países del mundo *cambian* de presidente tan rápido como el Perú. Entre 2016 y 2023, el país tuvo cerca de media docena de gobernantes, además de muchos *escándalos* de corrupción.",
        "El momento más dramático llegó en 2022: el presidente Pedro Castillo intentó cerrar el Congreso por su cuenta, una especie de autogolpe. El plan fracasó y, ese mismo día, fue *destituido* y *detenido*.",
        "Lo que vino después fue muy grave: estallaron grandes *protestas*, sobre todo en el sur del país, y la represión dejó decenas de muertos. La *confianza* de la gente en sus políticos quedó muy *dañada*, y la crisis aún no termina.",
      ],
      vocab: [
        { es: "cambian", de: "wechseln (cambiar)", en: "change (cambiar)", take: true },
        { es: "escándalos", de: "die Skandale", en: "scandals", take: true },
        { es: "destituido", de: "abgesetzt (destituir)", en: "removed from office (destituir)", take: false },
        { es: "detenido", de: "festgenommen (detener)", en: "detained, arrested (detener)", take: true },
        { es: "protestas", de: "die Proteste", en: "protests", take: true },
        { es: "confianza", de: "das Vertrauen", en: "trust", take: true },
        { es: "dañada", de: "beschädigt (dañar)", en: "damaged (dañar)", take: true },
      ],
      title: "Peru: politische Dauerkrise",
      titleEn: "Peru: permanent political crisis",
      where: "Peru",
      whereEn: "Peru",
      tone: "tense",
      status: "Instabil",
      statusEn: "Unstable",
      text: "Kaum ein Land wechselt seine Präsidenten so schnell: Allein zwischen 2016 und 2023 erlebte Peru rund ein halbes Dutzend Staatschefs, Amtsenthebungen und Skandale. 2022 wurde Präsident Pedro Castillo nach einem Selbstputsch-Versuch abgesetzt und verhaftet; die folgenden Proteste forderten Dutzende Tote. Das Vertrauen in die Politik ist tief erschüttert.",
      textEn: "Few countries change presidents so quickly: between 2016 and 2023 alone, Peru went through roughly half a dozen heads of state, impeachments and scandals. In 2022 President Pedro Castillo was removed and arrested after an attempted self-coup; the protests that followed cost dozens of lives. Trust in politics is deeply shaken.",
    },
    {
      id: "argentina-economia",
      icon: "💸",
      level: "B1",
      es: [
        "Hace cien años, Argentina era uno de los países más *ricos* del mundo. Hoy, en cambio, lleva décadas luchando contra la *inflación*, las deudas y crisis económicas que se repiten una y otra vez.",
        "El dinero pierde su valor tan rápido que ahorrar es casi imposible, y muchas familias ven cómo los precios suben cada semana. Cansados de tantos años de problemas, en 2023 los argentinos *eligieron* a un presidente muy diferente: el liberal radical Javier Milei.",
        "Milei promete arreglar la economía con medidas muy duras: *recortar* el gasto del Estado con „la motosierra“, como él mismo dice. Es una *apuesta* arriesgada y dolorosa, y ahora mismo se está *decidiendo* si funciona o no.",
      ],
      vocab: [
        { es: "ricos", de: "reich (rico)", en: "rich", take: true },
        { es: "inflación", de: "die Inflation", en: "inflation", take: true },
        { es: "eligieron", de: "wählten (elegir)", en: "elected, chose (elegir)", take: true },
        { es: "recortar", de: "kürzen", en: "to cut", take: false },
        { es: "apuesta", de: "die Wette, das Wagnis (apostar)", en: "bet, gamble (apostar)", take: true },
        { es: "decidiendo", de: "am Entscheiden (decidir)", en: "being decided (decidir)", take: true },
      ],
      title: "Argentinien: Inflation & Kurswechsel",
      titleEn: "Argentina: inflation & a sharp turn",
      where: "Argentinien",
      whereEn: "Argentina",
      tone: "shift",
      status: "Wandel",
      statusEn: "In flux",
      text: "Einst eines der reichsten Länder der Welt, kämpft Argentinien seit Jahrzehnten mit Staatspleiten und galoppierender Inflation. 2023 wählte das Land den radikalen Liberalen Javier Milei, der mit drastischen Sparmaßnahmen („la motosierra“, die Kettensäge) das Defizit bekämpft. Ob die schmerzhafte Schocktherapie aufgeht, entscheidet sich gerade.",
      textEn: "Once one of the richest countries in the world, Argentina has struggled for decades with debt defaults and runaway inflation. In 2023 the country elected the radical libertarian Javier Milei, who is fighting the deficit with drastic austerity (\"la motosierra\", the chainsaw). Whether the painful shock therapy works is being decided right now.",
    },
    {
      id: "amazonia",
      icon: "🌳",
      level: "B2",
      es: [
        "La selva amazónica es mucho más que un bosque: es el hogar de cientos de *pueblos* indígenas y una pieza clave para el clima de todo el planeta. Por eso muchos la llaman „el pulmón verde“ del mundo.",
        "Pero la selva está *amenazada*. La *deforestación* para criar ganado, plantar soja o buscar oro destruye cada año enormes zonas de bosque. La minería ilegal, además, *contamina* los ríos con mercurio y enferma a la gente que vive allí.",
        "Al mismo tiempo, hay esperanza: los movimientos indígenas *ganan* cada vez más voz, derechos sobre sus tierras y presencia en la política. Cómo *equilibrar* el cuidado del medio ambiente con el desarrollo es una de las grandes preguntas del futuro de Sudamérica.",
      ],
      vocab: [
        { es: "pueblos", de: "die Völker, Dörfer", en: "peoples, villages", take: true },
        { es: "amenazada", de: "bedroht (amenazar)", en: "threatened (amenazar)", take: true },
        { es: "deforestación", de: "die Abholzung", en: "deforestation", take: false },
        { es: "contamina", de: "verschmutzt (contaminar)", en: "pollutes (contaminar)", take: true },
        { es: "ganan", de: "gewinnen (ganar)", en: "gain, win (ganar)", take: true },
        { es: "equilibrar", de: "ins Gleichgewicht bringen", en: "to balance", take: false },
      ],
      title: "Amazonas & indigene Rechte",
      titleEn: "The Amazon & indigenous rights",
      where: "Brasilien, Peru, Bolivien, Ecuador …",
      whereEn: "Brazil, Peru, Bolivia, Ecuador …",
      tone: "shift",
      status: "Wandel",
      statusEn: "In flux",
      text: "Der Amazonas-Regenwald – die „grüne Lunge“ und Heimat hunderter indigener Völker – steht unter Druck durch Abholzung, Goldsuche und Viehzucht. Zugleich erkämpfen sich indigene Bewegungen mehr Mitsprache, Landrechte und politische Sichtbarkeit. Klimaschutz und Entwicklung gegeneinander auszubalancieren ist eine der großen Zukunftsfragen des Kontinents.",
      textEn: "The Amazon rainforest – the \"green lung\" and home to hundreds of indigenous peoples – is under pressure from deforestation, gold mining and cattle ranching. At the same time, indigenous movements are winning more of a voice, land rights and political visibility. Balancing climate protection against development is one of the continent's great questions for the future.",
    },
    {
      id: "migracion",
      icon: "🚶",
      level: "B1",
      es: [
        "En los últimos años, cientos de miles de personas, muchas de ellas venezolanas, han salido de sus países en busca de trabajo y seguridad. La mayoría *viaja* hacia el norte, soñando con llegar a Estados Unidos.",
        "En el camino tienen que *cruzar* el Tapón del Darién, una selva espesa y sin carreteras entre Colombia y Panamá. Es una de las *rutas* migratorias más *peligrosas* del mundo: hay ríos, enfermedades y bandas criminales que *asaltan* a los viajeros.",
        "Estos grandes movimientos de gente ponen a prueba a los países que los reciben y se han convertido en un tema político central, desde Chile hasta la *frontera* con Estados Unidos. La migración marca hoy la vida de toda la región.",
      ],
      vocab: [
        { es: "viaja", de: "reist (viajar)", en: "travels (viajar)", take: true },
        { es: "cruzar", de: "überqueren", en: "to cross", take: true },
        { es: "rutas", de: "die Routen, Strecken", en: "routes", take: true },
        { es: "peligrosas", de: "gefährlich (peligroso)", en: "dangerous (peligroso)", take: true },
        { es: "asaltan", de: "überfallen (asaltar)", en: "assault, rob (asaltar)", take: false },
        { es: "frontera", de: "die Grenze", en: "border", take: true },
      ],
      title: "Migration & der Darién",
      titleEn: "Migration & the Darién Gap",
      where: "Kolumbien ↔ Panama (Richtung Norden)",
      whereEn: "Colombia ↔ Panama (heading north)",
      tone: "crisis",
      status: "Krise",
      statusEn: "Crisis",
      text: "Hunderttausende Menschen – viele aus Venezuela – ziehen Richtung Norden und durchqueren dabei den Darién-Dschungel zwischen Kolumbien und Panama, eine der gefährlichsten Migrationsrouten der Welt. Die Wanderungsbewegungen belasten die Aufnahmeländer und prägen die Politik von Santiago bis an die US-Grenze.",
      textEn: "Hundreds of thousands of people – many from Venezuela – are moving north, crossing the Darién jungle between Colombia and Panama, one of the most dangerous migration routes in the world. These movements strain the receiving countries and shape politics from Santiago all the way to the US border.",
    },
  ];

  // ---------- ¿Sabías que…? (kurze Häppchen) ----------
  const FACTS = [
    {
      de: "Bolivien und Kolumbien sind nach Menschen benannt: nach Bolívar und Christoph Kolumbus.",
      en: "Bolivia and Colombia are named after people: after Bolívar and Christopher Columbus.",
    },
    {
      de: "San Martíns Marsch über die Anden wird oft mit Hannibals Alpenüberquerung verglichen.",
      en: "San Martín's march across the Andes is often compared to Hannibal crossing the Alps.",
    },
    {
      de: "Quechua, die Sprache der Inka, ist bis heute in mehreren Ländern Amtssprache.",
      en: "Quechua, the language of the Inca, is still an official language in several countries today.",
    },
    {
      de: "Das Silber aus Potosí finanzierte über zwei Jahrhunderte das spanische Weltreich.",
      en: "The silver from Potosí financed the Spanish world empire for over two centuries.",
    },
    {
      de: "Brasilien spricht Portugiesisch und war bis 1889 ein Kaiserreich – ein Sonderweg in Südamerika.",
      en: "Brazil speaks Portuguese and was an empire until 1889 – a path all its own in South America.",
    },
    {
      de: "Bolívar und San Martín trafen sich nur ein einziges Mal: 1822 in Guayaquil, hinter verschlossenen Türen.",
      en: "Bolívar and San Martín met only once: in Guayaquil in 1822, behind closed doors.",
    },
  ];

  window.SC.historia = { INTRO, ERAS, FIGURES, TENSIONS, FACTS };
})();
