/*
 * historiaCentro.js  (SC.historiaCentro) – Modell für die Erklärseite "Historia
 * de Centroamérica". REINE DATEN, keine Logik – exakt dieselbe Struktur wie
 * historia.js (Sudamérica), damit das Feature-Modul SC.cronologia beide
 * Sektionen über dieselbe Render- und Lesetraining-Mechanik bedienen kann.
 *
 * Aufbau (wie historia.js):
 *   INTRO     { de, en }                       – Einleitungstext (Hero)
 *   ERAS      [ Epoche ]                        – der interaktive Zeitstrahl
 *   FIGURES   [ Person ]                        – die Protagonisten (Galerie)
 *   TENSIONS  [ Spannung ]                      – "Heute": Lage & Konflikte
 *   FACTS     [ { de, en } ]                    – "¿Sabías que…?"-Häppchen
 *
 * Epoche:   { id, icon, period, title, lead, body:[Absatz], points:[Punkt],
 *             level, es:[Absatz], vocab:[{es,de,en,take}], img, imgCaption } (+ …En)
 * Person:   { id, name, role, years, flag, img, text, quote, level, es, vocab } (+ …En)
 * Spannung: { id, icon, title, where, tone, status, text, level, es, vocab } (+ …En)
 *   tone = "crisis" | "tense" | "shift" | "progress"
 *
 * img = nur der Wikimedia-Commons-Dateiname; ui.js baut die Special:FilePath-URL.
 *       Offline/bei Fehler blendet onerror das Bild aus (graceful degradation).
 */
(function () {
  "use strict";
  window.SC = window.SC || {};

  // ---------- Einleitung ----------
  const INTRO = {
    de: "Eine schmale Landbrücke zwischen zwei Kontinenten – und eine erstaunlich große Geschichte: Hier rechneten die Maya schon mit der Null, hier wurde aus einem spanischen Königreich für kurze Zeit eine einzige Republik, und hier rangen im Kalten Krieg ganze Völker um ihre Zukunft. Das ist die große Linie Mittelamerikas: von den Maya über Morazáns Traum von Einheit bis zu den sieben Republiken von heute.",
    en: "A narrow land bridge between two continents – and a surprisingly big story: here the Maya were already counting with zero, here a Spanish kingdom briefly became a single republic, and here whole peoples fought for their future during the Cold War. This is the big picture of Central America: from the Maya through Morazán's dream of unity to today's seven republics.",
  };

  // ---------- Zeitstrahl: die Epochen ----------
  const ERAS = [
    {
      id: "maya",
      icon: "lc:mountain",
      period: "bis 1523",
      periodEn: "before 1523",
      title: "Vor den Spaniern – die Welt der Maya",
      titleEn: "Before the Spanish – the world of the Maya",
      lead: "Lange vor den Spaniern blühte hier eine der genialsten Hochkulturen Amerikas.",
      leadEn: "Long before the Spanish, one of the most brilliant civilisations of the Americas flourished here.",
      body: [
        "Die Maya lebten über tausend Jahre in dutzenden Stadtstaaten – im Tiefland von Guatemala, in Yucatán, Belize und Honduras. Städte wie Tikal, Copán oder Palenque hatten Tempelpyramiden, Paläste und Ballspielplätze; in ihrer Blütezeit (250–900 n. Chr.) lebten in der Region Millionen Menschen.",
        "Die Maya entwickelten eine echte Schrift mit Hunderten von Zeichen, einen extrem genauen Kalender und eine Mathematik, die – Jahrhunderte vor Europa – die Null kannte. Ihre Astronomen sagten Sonnenfinsternisse voraus.",
        "Um 900 n. Chr. wurden viele der großen Tieflandstädte rätselhaft aufgegeben – wohl wegen Dürren, Überbevölkerung und Krieg. Doch „die Maya“ verschwanden nie: Millionen ihrer Nachfahren leben bis heute in Guatemala und Südmexiko. Daneben gab es viele weitere Völker – Lenca, Pipil, Miskito und die Kuna.",
      ],
      bodyEn: [
        "The Maya lived for over a thousand years in dozens of city-states – in the lowlands of Guatemala, in Yucatán, Belize and Honduras. Cities like Tikal, Copán and Palenque had temple pyramids, palaces and ball courts; at their peak (250–900 AD) millions of people lived in the region.",
        "The Maya developed a true writing system with hundreds of signs, an extremely precise calendar, and a mathematics that – centuries before Europe – knew the zero. Their astronomers predicted solar eclipses.",
        "Around 900 AD many of the great lowland cities were mysteriously abandoned – probably because of droughts, overpopulation and war. But \"the Maya\" never disappeared: millions of their descendants still live in Guatemala and southern Mexico today. Alongside them lived many other peoples – the Lenca, Pipil, Miskito and Kuna.",
      ],
      points: [
        "Tikal: Tempelpyramiden bis 70 Meter hoch, mitten im Dschungel",
        "Die Maya kannten die Null – lange vor Europa",
        "Über 6 Millionen Menschen sprechen heute noch Maya-Sprachen",
      ],
      pointsEn: [
        "Tikal: temple pyramids up to 70 metres high, deep in the jungle",
        "The Maya knew the zero – long before Europe",
        "Over 6 million people still speak Maya languages today",
      ],
      level: "B1",
      es: [
        "Mucho antes de la llegada de los españoles, en las selvas de Guatemala, Belice y el sur de México, *floreció* una de las civilizaciones más *asombrosas* de América: los mayas. No formaban un solo país, sino decenas de ciudades-estado como Tikal, Copán o Palenque, con grandes pirámides, palacios y canchas para el juego de pelota.",
        "Lo más sorprendente es lo que lograron con las matemáticas y el cielo. Los mayas inventaron una verdadera *escritura* con cientos de signos, crearon un *calendario* muy exacto y usaron el *cero* siglos antes que Europa. Sus *sacerdotes* observaban las estrellas y podían *predecir* los eclipses de sol.",
        "Hacia el año 900, muchas de las grandes ciudades del *bosque* fueron *abandonadas*, quizá por sequías, guerras y demasiada gente. Pero los mayas nunca *desaparecieron*: hoy millones de sus *descendientes* siguen vivos en Guatemala, y hablan más de veinte lenguas mayas distintas.",
      ],
      vocab: [
        { es: "floreció", de: "blühte (florecer)", en: "flourished (florecer)", take: true },
        { es: "asombrosas", de: "erstaunlich", en: "amazing", take: false },
        { es: "escritura", de: "die Schrift", en: "writing", take: true },
        { es: "calendario", de: "der Kalender", en: "calendar", take: true },
        { es: "cero", de: "die Null", en: "zero", take: true },
        { es: "sacerdotes", de: "die Priester", en: "priests", take: false },
        { es: "predecir", de: "vorhersagen", en: "to predict", take: true },
        { es: "bosque", de: "der Wald", en: "forest", take: true },
        { es: "abandonadas", de: "verlassen (abandonar)", en: "abandoned", take: true },
        { es: "desaparecieron", de: "verschwanden (desaparecer)", en: "disappeared", take: true },
        { es: "descendientes", de: "die Nachfahren", en: "descendants", take: false },
      ],
      img: "Tikal temple 1 2009u.JPG",
      imgCaption: "Tikal – Tempel I, im Tiefland-Dschungel Guatemalas",
      imgCaptionEn: "Tikal – Temple I, in the lowland jungle of Guatemala",
    },
    {
      id: "conquista",
      icon: "lc:swords",
      period: "1519–1540",
      periodEn: "1519–1540",
      title: "Die Conquista – Eroberung der Landbrücke",
      titleEn: "The Conquista – conquering the land bridge",
      lead: "In nur zwei Jahrzehnten unterwarfen die Spanier die ganze Region.",
      leadEn: "In just two decades, the Spanish subdued the whole region.",
      body: [
        "Nach dem Fall des Aztekenreichs (1521) zogen die Spanier weiter nach Süden. Pedro de Alvarado, ein brutaler Hauptmann von Hernán Cortés, eroberte ab 1524 das heutige Guatemala und El Salvador. Andere Truppen kamen von Panama aus nach Norden.",
        "Die Spanier nutzten die alten Rivalitäten zwischen den Maya-Reichen und verbündeten sich mit dem einen Volk gegen das andere. Ihre größte Waffe war jedoch unsichtbar: eingeschleppte Krankheiten wie Pocken töteten oft mehr Menschen als jedes Schwert.",
        "Panama war schon seit 1519 spanisch und wurde zum Tor zwischen den Ozeanen: Über die schmale Landenge schleppten die Spanier das Silber Perus zum Atlantik. Nur die Maya im Hochland und Völker wie die Miskito an der Karibikküste leisteten noch lange Widerstand.",
      ],
      bodyEn: [
        "After the fall of the Aztec Empire (1521), the Spanish pushed further south. Pedro de Alvarado, a brutal captain of Hernán Cortés, conquered today's Guatemala and El Salvador from 1524. Other forces came north from Panama.",
        "The Spanish exploited the old rivalries between the Maya kingdoms, allying with one people against another. But their greatest weapon was invisible: imported diseases such as smallpox often killed more people than any sword.",
        "Panama had been Spanish since 1519 and became the gateway between the oceans: across the narrow isthmus the Spanish hauled the silver of Peru to the Atlantic. Only the Maya of the highlands and peoples like the Miskito of the Caribbean coast held out for a long time.",
      ],
      points: [
        "Pedro de Alvarado eroberte Guatemala ab 1524",
        "Krankheiten töteten mehr Menschen als die Waffen",
        "Panama wurde Spaniens Tor zwischen den Ozeanen",
      ],
      pointsEn: [
        "Pedro de Alvarado conquered Guatemala from 1524",
        "Diseases killed more people than weapons did",
        "Panama became Spain's gateway between the oceans",
      ],
      level: "B1",
      es: [
        "Después de *vencer* al imperio azteca, los españoles siguieron hacia el sur. En 1524, Pedro de Alvarado, un capitán muy *cruel*, entró en lo que hoy es Guatemala y El Salvador. Otros soldados subieron desde Panamá, que ya era español desde 1519.",
        "Para *conquistar* la región, los españoles aprovecharon las viejas *rivalidades* entre los pueblos mayas: se aliaban con unos para luchar contra otros. Pero su arma más terrible no se veía: las *enfermedades* traídas de Europa, como la *viruela*, mataron a muchísima gente.",
        "Panamá se convirtió en la *puerta* entre los dos océanos. Por aquella *estrecha* franja de tierra, los españoles llevaban la plata del Perú hasta el Atlántico. Solo algunos pueblos, como los mayas de las montañas y los miskitos de la *costa* caribeña, *resistieron* durante mucho tiempo.",
      ],
      vocab: [
        { es: "vencer", de: "besiegen", en: "to defeat", take: true },
        { es: "cruel", de: "grausam", en: "cruel", take: true },
        { es: "conquistar", de: "erobern", en: "to conquer", take: true },
        { es: "rivalidades", de: "die Rivalitäten", en: "rivalries", take: false },
        { es: "enfermedades", de: "die Krankheiten", en: "diseases", take: true },
        { es: "viruela", de: "die Pocken", en: "smallpox", take: false },
        { es: "puerta", de: "die Tür, das Tor", en: "door, gateway", take: true },
        { es: "estrecha", de: "schmal, eng", en: "narrow", take: true },
        { es: "costa", de: "die Küste", en: "coast", take: true },
        { es: "resistieron", de: "leisteten Widerstand (resistir)", en: "resisted", take: true },
      ],
      img: "Pedro de Alvarado.JPG",
      imgCaption: "Pedro de Alvarado, Eroberer Guatemalas",
      imgCaptionEn: "Pedro de Alvarado, conqueror of Guatemala",
    },
    {
      id: "colonial",
      icon: "lc:church",
      period: "1540–1821",
      periodEn: "1540–1821",
      title: "Die Kolonialzeit – das Königreich Guatemala",
      titleEn: "The colonial era – the Kingdom of Guatemala",
      lead: "Fast drei Jahrhunderte war die Region eine einzige Verwaltungseinheit.",
      leadEn: "For almost three centuries the region was a single administrative unit.",
      body: [
        "Spanien fasste fast ganz Mittelamerika zur Capitanía General de Guatemala zusammen – von Chiapas im Norden bis Costa Rica im Süden. Verwaltet wurde sie von der prächtigen Hauptstadt Antigua, bis ein schweres Erdbeben sie 1773 zerstörte und die Regierung in die heutige Stadt Guatemala umzog.",
        "Es gab hier kein Gold und kaum Silber wie in Peru. Reich wurde man mit Färbemitteln: Indigoblau und der Cochenille-Laus für leuchtendes Rot, später mit Kaffee. Die Wirtschaft ruhte auf der Arbeit der indigenen Bevölkerung, die in einer strengen Ständegesellschaft ganz unten stand.",
        "Weil die Region arm und abgelegen war, kümmerte sich Madrid wenig um sie. Costa Rica zum Beispiel war so dünn besiedelt, dass selbst der Gouverneur sein Feld selbst bestellen musste – eine Armut, aus der später ein eigenes, gleicheres Selbstbild wuchs.",
      ],
      bodyEn: [
        "Spain combined almost all of Central America into the Captaincy General of Guatemala – from Chiapas in the north to Costa Rica in the south. It was governed from the splendid capital Antigua, until a severe earthquake destroyed it in 1773 and the government moved to today's Guatemala City.",
        "There was no gold here and barely any silver as in Peru. People grew rich on dyes: indigo blue and the cochineal insect for brilliant red, and later coffee. The economy rested on the labour of the indigenous population, who stood at the very bottom of a rigid class society.",
        "Because the region was poor and remote, Madrid paid it little attention. Costa Rica, for example, was so sparsely populated that even the governor had to till his own field – a poverty out of which a more equal self-image later grew.",
      ],
      points: [
        "Eine Verwaltung: von Chiapas bis Costa Rica",
        "Reichtum aus Färbemitteln statt aus Silber",
        "Ein Erdbeben zerstörte 1773 die Hauptstadt Antigua",
      ],
      pointsEn: [
        "One administration: from Chiapas to Costa Rica",
        "Wealth from dyes instead of silver",
        "An earthquake destroyed the capital Antigua in 1773",
      ],
      level: "B2",
      es: [
        "Durante casi trescientos años, España unió a casi toda la región en un solo territorio: la Capitanía General de Guatemala, que iba desde Chiapas hasta Costa Rica. Se *gobernaba* desde la hermosa ciudad de Antigua, hasta que un fuerte *terremoto* la destruyó en 1773.",
        "Aquí no había oro ni mucha plata como en el Perú. La *riqueza* venía de los tintes: el añil, de color azul, y la cochinilla, un pequeño insecto del que se sacaba un rojo *brillante*. Toda la economía se *apoyaba* en el trabajo de los pueblos indígenas, que vivían en lo más bajo de una sociedad muy *desigual*.",
        "Como la región era *pobre* y estaba lejos de todo, Madrid casi no se *ocupaba* de ella. Costa Rica tenía tan poca gente que hasta el gobernador tenía que cultivar su propia *tierra*. De esa pobreza nació, con el tiempo, una idea de igualdad que el país todavía recuerda con orgullo.",
      ],
      vocab: [
        { es: "gobernaba", de: "wurde regiert (gobernar)", en: "was governed", take: true },
        { es: "terremoto", de: "das Erdbeben", en: "earthquake", take: true },
        { es: "riqueza", de: "der Reichtum", en: "wealth", take: true },
        { es: "brillante", de: "leuchtend, glänzend", en: "brilliant, bright", take: true },
        { es: "apoyaba", de: "stützte sich (apoyarse)", en: "rested on (apoyarse)", take: false },
        { es: "desigual", de: "ungleich", en: "unequal", take: true },
        { es: "pobre", de: "arm", en: "poor", take: true },
        { es: "ocupaba", de: "kümmerte sich (ocuparse)", en: "took care of (ocuparse)", take: false },
        { es: "tierra", de: "die Erde, das Land", en: "land, earth", take: true },
      ],
      img: "Arco de Santa Catarina, Antigua Guatemala.jpg",
      imgCaption: "Antigua Guatemala – einst Hauptstadt des Königreichs",
      imgCaptionEn: "Antigua Guatemala – once capital of the kingdom",
    },
    {
      id: "independencia",
      icon: "lc:bell",
      period: "1821",
      periodEn: "1821",
      title: "Die Unabhängigkeit – fast ohne einen Schuss",
      titleEn: "Independence – almost without a shot",
      lead: "Mittelamerika wurde 1821 frei – friedlich, fast über Nacht.",
      leadEn: "Central America became free in 1821 – peacefully, almost overnight.",
      body: [
        "Während im Süden Bolívar und San Martín jahrelang blutige Kriege führten, ging es hier erstaunlich ruhig zu. Als Mexiko sich von Spanien löste, unterschrieben die Honoratioren in Guatemala am 15. September 1821 einfach eine Unabhängigkeitserklärung. Bis heute feiern fünf Länder an diesem Tag.",
        "Kaum frei, schloss sich die Region für kurze Zeit dem Kaiserreich Mexiko unter Agustín de Iturbide an. Doch als dieser Kaiser schon 1823 stürzte, war Mittelamerika wieder auf sich gestellt.",
        "Nun stand die große Frage im Raum: Sollten die Provinzen ein einziges Land bilden – oder jede ihren eigenen Weg gehen? Aus dieser Frage wuchs der nächste, bittere Streit.",
      ],
      bodyEn: [
        "While in the south Bolívar and San Martín fought bloody wars for years, here things stayed remarkably calm. When Mexico broke away from Spain, the notables in Guatemala simply signed a declaration of independence on 15 September 1821. Five countries still celebrate on this day.",
        "Barely free, the region briefly joined the Mexican Empire under Agustín de Iturbide. But when that emperor fell as early as 1823, Central America was on its own again.",
        "Now the big question loomed: should the provinces form a single country – or should each go its own way? Out of this question grew the next, bitter quarrel.",
      ],
      points: [
        "15. September 1821: Unabhängigkeit – bis heute Nationalfeiertag",
        "Kurzer Anschluss an Mexikos Kaiserreich (bis 1823)",
        "Ein Land oder viele? Diese Frage spaltete die Region",
      ],
      pointsEn: [
        "15 September 1821: independence – still a national holiday",
        "Brief annexation to the Mexican Empire (until 1823)",
        "One country or many? This question split the region",
      ],
      level: "B1",
      es: [
        "Mientras en el sur Bolívar luchaba durante años en guerras *sangrientas*, en Centroamérica todo fue mucho más *tranquilo*. Cuando México se *separó* de España, los líderes reunidos en Guatemala simplemente *firmaron* un acta de independencia el 15 de septiembre de 1821. Por eso, todavía hoy, cinco países celebran su fiesta nacional ese día.",
        "Apenas libres, los centroamericanos se *unieron* por poco tiempo al imperio de México, gobernado por Agustín de Iturbide. Pero ese emperador *cayó* muy pronto, en 1823, y la región se quedó otra vez sola.",
        "Entonces apareció la gran *pregunta*: ¿debían formar un solo país o debía cada provincia seguir su propio camino? De esa duda nació la siguiente gran *pelea*.",
      ],
      vocab: [
        { es: "sangrientas", de: "blutig", en: "bloody", take: false },
        { es: "tranquilo", de: "ruhig", en: "calm", take: true },
        { es: "separó", de: "trennte sich (separarse)", en: "broke away (separarse)", take: true },
        { es: "firmaron", de: "unterschrieben (firmar)", en: "signed (firmar)", take: true },
        { es: "unieron", de: "schlossen sich an (unirse)", en: "joined (unirse)", take: true },
        { es: "cayó", de: "fiel, stürzte (caer)", en: "fell (caer)", take: true },
        { es: "pregunta", de: "die Frage", en: "question", take: true },
        { es: "pelea", de: "der Streit, Kampf", en: "fight, quarrel", take: true },
      ],
    },
    {
      id: "federacion",
      icon: "lc:star",
      period: "1823–1839",
      periodEn: "1823–1839",
      title: "Die Föderation – ein Traum von Einheit",
      titleEn: "The Federation – a dream of unity",
      lead: "Für 15 Jahre waren fünf Länder ein einziger Staat.",
      leadEn: "For 15 years, five countries were a single state.",
      body: [
        "1823 gründeten Guatemala, El Salvador, Honduras, Nicaragua und Costa Rica gemeinsam die Republik Mittelamerika – die Provincias Unidas del Centro de América. Es war derselbe Traum, den Bolívar im Süden hatte: ein großer, geeinter Staat statt vieler kleiner Länder.",
        "Ihr großer Held wurde Francisco Morazán, ein liberaler Präsident aus Honduras. Er wollte Schulen, Religionsfreiheit und weniger Macht für die Kirche. Genau das brachte ihm die erbitterte Feindschaft der Konservativen und der Großgrundbesitzer ein.",
        "Liberale gegen Konservative, Stadt gegen Land, Provinz gegen Provinz: Die junge Föderation zerriss im Bürgerkrieg. Bis 1841 hatte sich jeder der fünf Staaten für unabhängig erklärt. Morazán wurde 1842 in Costa Rica erschossen – sein Traum war gescheitert.",
      ],
      bodyEn: [
        "In 1823 Guatemala, El Salvador, Honduras, Nicaragua and Costa Rica together founded the Republic of Central America – the United Provinces of Central America. It was the same dream Bolívar had in the south: one large, united state instead of many small countries.",
        "Their great hero was Francisco Morazán, a liberal president from Honduras. He wanted schools, freedom of religion and less power for the Church. That earned him the bitter enmity of the conservatives and the big landowners.",
        "Liberals against conservatives, city against countryside, province against province: the young federation tore apart in civil war. By 1841 each of the five states had declared itself independent. Morazán was shot in Costa Rica in 1842 – his dream had failed.",
      ],
      points: [
        "Fünf Länder, ein Staat (1823–1839)",
        "Francisco Morazán: der „Bolívar Mittelamerikas“",
        "Liberale gegen Konservative – die Föderation zerriss",
      ],
      pointsEn: [
        "Five countries, one state (1823–1839)",
        "Francisco Morazán: the \"Bolívar of Central America\"",
        "Liberals against conservatives – the federation tore apart",
      ],
      level: "B2",
      es: [
        "En 1823, Guatemala, El Salvador, Honduras, Nicaragua y Costa Rica decidieron *unirse* en un solo país: las Provincias Unidas del Centro de América. Era el mismo *sueño* que tenía Bolívar en el sur: un gran Estado *unido* en lugar de muchos países pequeños y débiles.",
        "Su gran héroe fue Francisco Morazán, un presidente *liberal* nacido en Honduras. Quería escuelas, libertad de religión y menos poder para la Iglesia. Por eso se ganó el odio de los *conservadores* y de los dueños de las grandes tierras.",
        "Liberales contra conservadores, una región contra otra: la joven federación se *rompió* en una guerra civil. Hacia 1841, cada uno de los cinco estados ya se había declarado *independiente*. Morazán fue *fusilado* en Costa Rica en 1842, y con él murió el sueño de una Centroamérica unida.",
      ],
      vocab: [
        { es: "unirse", de: "sich vereinen", en: "to unite", take: true },
        { es: "sueño", de: "der Traum", en: "dream", take: true },
        { es: "unido", de: "geeint, vereint", en: "united", take: true },
        { es: "liberal", de: "liberal", en: "liberal", take: false },
        { es: "conservadores", de: "die Konservativen", en: "conservatives", take: true },
        { es: "rompió", de: "zerbrach (romperse)", en: "broke apart (romperse)", take: true },
        { es: "independiente", de: "unabhängig", en: "independent", take: true },
        { es: "fusilado", de: "erschossen (fusilar)", en: "shot (executed)", take: true },
      ],
      img: "Francisco Morazán Quesada.JPG",
      imgCaption: "Francisco Morazán – Held der mittelamerikanischen Einheit",
      imgCaptionEn: "Francisco Morazán – hero of Central American unity",
    },
    {
      id: "cafe-bananas",
      icon: "lc:banana",
      period: "1840–1930",
      periodEn: "1840–1930",
      title: "Kaffee & Bananen – die Exportzeit",
      titleEn: "Coffee & bananas – the export era",
      lead: "Zwei Pflanzen prägten Wirtschaft und Politik – und holten die USA ins Land.",
      leadEn: "Two plants shaped economy and politics – and drew the USA into the region.",
      body: [
        "Im 19. Jahrhundert wurde Kaffee zum großen Geschäft. Eine kleine Schicht von Großgrundbesitzern – die „Kaffee-Oligarchie“ – wurde reich und mächtig, während die meisten Menschen arm blieben und auf den Plantagen schufteten.",
        "Dann kamen die Bananen. US-Konzerne wie die United Fruit Company kauften riesige Flächen, bauten Eisenbahnen und Häfen – und wurden so mächtig, dass sie Regierungen ein- und absetzen konnten. Der Spottname „Bananenrepublik“ wurde genau hier, in Honduras, geboren.",
        "Wer der Firma im Weg stand, bekam Probleme; mehrmals landeten US-Marines „zum Schutz amerikanischer Interessen“. 1903 half Washington Panama sogar bei der Abspaltung von Kolumbien – um den Panamakanal bauen zu können, der 1914 eröffnet wurde.",
      ],
      bodyEn: [
        "In the 19th century coffee became big business. A small layer of large landowners – the \"coffee oligarchy\" – grew rich and powerful, while most people stayed poor and toiled on the plantations.",
        "Then came the bananas. US corporations like the United Fruit Company bought up vast tracts of land, built railways and ports – and grew so powerful they could install and remove governments. The mocking term \"banana republic\" was born right here, in Honduras.",
        "Anyone who stood in the company's way ran into trouble; several times US Marines landed \"to protect American interests\". In 1903 Washington even helped Panama break away from Colombia – in order to build the Panama Canal, which opened in 1914.",
      ],
      points: [
        "Kaffee machte eine kleine Oberschicht reich",
        "„Bananenrepublik“ – der Begriff stammt aus Honduras",
        "1914: Eröffnung des Panamakanals",
      ],
      pointsEn: [
        "Coffee made a small upper class rich",
        "\"Banana republic\" – the term comes from Honduras",
        "1914: opening of the Panama Canal",
      ],
      level: "B2",
      es: [
        "En el siglo XIX, el café se convirtió en un gran negocio. Un pequeño grupo de *dueños* de grandes tierras se hizo muy rico y *poderoso*, mientras la mayoría de la gente seguía siendo pobre y *trabajaba* en las plantaciones.",
        "Después llegaron los bananos. Empresas de Estados Unidos, como la United Fruit Company, compraron tierras enormes y construyeron *ferrocarriles* y puertos. Se hicieron tan fuertes que podían *poner* y quitar gobiernos. Por eso nació aquí, en Honduras, el nombre burlón de „república bananera“.",
        "Quien *molestaba* a la compañía tenía problemas, y varias veces llegaron soldados estadounidenses „para *proteger* sus intereses“. En 1903, Washington incluso ayudó a Panamá a separarse de Colombia para poder construir el *canal*, que se abrió en 1914.",
      ],
      vocab: [
        { es: "dueños", de: "die Besitzer", en: "owners", take: true },
        { es: "poderoso", de: "mächtig", en: "powerful", take: true },
        { es: "trabajaba", de: "arbeitete (trabajar)", en: "worked (trabajar)", take: false },
        { es: "ferrocarriles", de: "die Eisenbahnen", en: "railways", take: true },
        { es: "poner", de: "setzen, einsetzen", en: "to put, install", take: false },
        { es: "molestaba", de: "störte (molestar)", en: "bothered (molestar)", take: true },
        { es: "proteger", de: "schützen", en: "to protect", take: true },
        { es: "canal", de: "der Kanal", en: "canal", take: true },
      ],
    },
    {
      id: "guerras",
      icon: "lc:bird",
      period: "1960–1996",
      periodEn: "1960–1996",
      title: "Bürgerkriege & Kalter Krieg",
      titleEn: "Civil wars & the Cold War",
      lead: "Drei Länder versanken im Krieg zwischen links und rechts.",
      leadEn: "Three countries sank into war between left and right.",
      body: [
        "Im Kalten Krieg wurde Mittelamerika zum Schlachtfeld. In Guatemala stürzte 1954 ein von der CIA unterstützter Putsch eine gewählte Regierung. Es folgte ein 36 Jahre langer Bürgerkrieg (1960–1996), in dem das Militär ganze Maya-Dörfer auslöschte – ein Völkermord mit rund 200.000 Toten.",
        "In El Salvador kämpfte die linke Guerilla FMLN gegen die Armee (1980–1992). 1980 wurde Erzbischof Óscar Romero, der für die Armen sprach, am Altar erschossen. In Nicaragua stürzten die Sandinisten 1979 den Diktator Somoza – dann finanzierten die USA die „Contra“-Rebellen gegen die neue Regierung.",
        "Hunderttausende starben, Millionen flohen. Ab 1987 ebnete ein Friedensplan des costa-ricanischen Präsidenten Óscar Arias (Friedensnobelpreis) den Weg; bis 1996 schwiegen überall die Waffen. Costa Rica war die große Ausnahme: Es hatte seine Armee schon 1948 abgeschafft.",
      ],
      bodyEn: [
        "During the Cold War, Central America became a battlefield. In Guatemala a CIA-backed coup overthrew an elected government in 1954. A 36-year civil war followed (1960–1996), in which the military wiped out entire Maya villages – a genocide with around 200,000 dead.",
        "In El Salvador the leftist FMLN guerrillas fought the army (1980–1992). In 1980 Archbishop Óscar Romero, who spoke for the poor, was shot at the altar. In Nicaragua the Sandinistas overthrew the dictator Somoza in 1979 – then the USA funded the \"Contra\" rebels against the new government.",
        "Hundreds of thousands died, millions fled. From 1987 a peace plan by Costa Rican president Óscar Arias (Nobel Peace Prize) paved the way; by 1996 the guns fell silent everywhere. Costa Rica was the great exception: it had abolished its army back in 1948.",
      ],
      points: [
        "Guatemala: 36 Jahre Krieg, Völkermord an den Maya",
        "El Salvador & Nicaragua: Guerilla, Contras, US-Eingriffe",
        "Costa Rica schaffte schon 1948 seine Armee ab",
      ],
      pointsEn: [
        "Guatemala: 36 years of war, genocide of the Maya",
        "El Salvador & Nicaragua: guerrillas, Contras, US intervention",
        "Costa Rica abolished its army back in 1948",
      ],
      level: "B2",
      es: [
        "Durante la Guerra Fría, Centroamérica se convirtió en un *campo* de batalla. En Guatemala, un golpe apoyado por la CIA *derrocó* en 1954 a un gobierno elegido. Después vino una guerra civil de 36 años, en la que el ejército *destruyó* pueblos mayas enteros: un genocidio con unos 200.000 muertos.",
        "En El Salvador, la guerrilla de izquierda luchó contra el ejército. En 1980, el arzobispo Óscar Romero, que defendía a los *pobres*, fue *asesinado* mientras daba misa. En Nicaragua, los sandinistas *derribaron* en 1979 al dictador Somoza, y entonces Estados Unidos pagó a los rebeldes „contras“ para luchar contra el nuevo gobierno.",
        "Murieron cientos de miles de personas y millones *huyeron*. Desde 1987, un plan de *paz* del presidente costarricense Óscar Arias abrió el camino, y hacia 1996 callaron las armas. Costa Rica fue la gran excepción: había *eliminado* su ejército ya en 1948.",
      ],
      vocab: [
        { es: "campo", de: "das Feld", en: "field", take: true },
        { es: "derrocó", de: "stürzte (derrocar)", en: "overthrew (derrocar)", take: true },
        { es: "destruyó", de: "zerstörte (destruir)", en: "destroyed (destruir)", take: true },
        { es: "pobres", de: "die Armen", en: "the poor", take: true },
        { es: "asesinado", de: "ermordet (asesinar)", en: "murdered (asesinar)", take: true },
        { es: "derribaron", de: "stürzten (derribar)", en: "overthrew (derribar)", take: false },
        { es: "huyeron", de: "flohen (huir)", en: "fled (huir)", take: true },
        { es: "paz", de: "der Frieden", en: "peace", take: true },
        { es: "eliminado", de: "abgeschafft (eliminar)", en: "abolished (eliminar)", take: false },
      ],
    },
    {
      id: "hoy",
      icon: "lc:globe",
      period: "heute",
      periodEn: "today",
      title: "Bis heute – Demokratie, Migration, Wandel",
      titleEn: "Up to today – democracy, migration, change",
      lead: "Sieben Republiken zwischen Hoffnung, Gewalt und Aufbruch.",
      leadEn: "Seven republics between hope, violence and new beginnings.",
      body: [
        "Nach den Kriegen kehrten fast überall Wahlen und Demokratie zurück. Doch der Frieden blieb fragil: Armut, Korruption und die Banden (maras) wie die MS-13 machten den „Nördlichen Dreieck“-Ländern Guatemala, Honduras und El Salvador schwer zu schaffen – und trieben viele Menschen auf die gefährliche Reise Richtung USA.",
        "Heute geht jedes Land seinen eigenen Weg: El Salvador setzt unter Präsident Bukele auf eine extrem harte Hand gegen die Banden, Nicaragua rutscht unter Daniel Ortega zurück in die Autokratie, und Guatemala ringt mit einem Antikorruptions-Präsidenten um einen Neuanfang.",
        "Costa Rica und Panama gelten als die stabilsten und wohlhabendsten Länder. Geld von Verwandten im Ausland (remesas) hält ganze Volkswirtschaften am Laufen. Mittelamerika bleibt eine Region voller Energie – jung, eng vernetzt und mitten im Wandel.",
      ],
      bodyEn: [
        "After the wars, elections and democracy returned almost everywhere. But peace stayed fragile: poverty, corruption and gangs (maras) like MS-13 hit the \"Northern Triangle\" countries Guatemala, Honduras and El Salvador hard – and drove many people onto the dangerous journey towards the USA.",
        "Today each country goes its own way: El Salvador, under President Bukele, relies on an extremely hard hand against the gangs; Nicaragua, under Daniel Ortega, slides back into autocracy; and Guatemala wrestles with an anti-corruption president for a fresh start.",
        "Costa Rica and Panama are considered the most stable and prosperous countries. Money from relatives abroad (remesas) keeps whole economies running. Central America remains a region full of energy – young, closely connected and in the middle of change.",
      ],
      points: [
        "Banden (maras) & Armut treiben die Migration nach Norden",
        "El Salvador, Nicaragua, Guatemala: drei sehr verschiedene Wege",
        "Remesas aus dem Ausland tragen ganze Volkswirtschaften",
      ],
      pointsEn: [
        "Gangs (maras) & poverty drive migration north",
        "El Salvador, Nicaragua, Guatemala: three very different paths",
        "Remittances from abroad carry whole economies",
      ],
      level: "B1",
      es: [
        "Después de las guerras, casi en todas partes *volvieron* las elecciones y la democracia. Pero la paz quedó *frágil*: la pobreza, la corrupción y las pandillas, las *maras*, golpearon con fuerza a Guatemala, Honduras y El Salvador, y empujaron a mucha gente a *viajar* hacia el norte.",
        "Hoy cada país sigue su propio camino. El Salvador, con el presidente Bukele, usa mano muy dura contra las pandillas; Nicaragua, con Daniel Ortega, vuelve poco a poco a la *dictadura*; y Guatemala *lucha* por un nuevo comienzo contra la corrupción.",
        "Costa Rica y Panamá son los países más *estables* y ricos. El dinero que *envían* los familiares desde el extranjero, las remesas, mantiene vivas economías enteras. Centroamérica sigue siendo una región joven, muy *conectada* y en pleno cambio.",
      ],
      vocab: [
        { es: "volvieron", de: "kehrten zurück (volver)", en: "returned (volver)", take: true },
        { es: "frágil", de: "zerbrechlich, fragil", en: "fragile", take: true },
        { es: "maras", de: "die Jugendbanden", en: "gangs", take: true },
        { es: "viajar", de: "reisen", en: "to travel", take: false },
        { es: "dictadura", de: "die Diktatur", en: "dictatorship", take: true },
        { es: "lucha", de: "kämpft (luchar)", en: "fights (luchar)", take: true },
        { es: "estables", de: "stabil", en: "stable", take: true },
        { es: "envían", de: "schicken (enviar)", en: "send (enviar)", take: true },
        { es: "conectada", de: "vernetzt, verbunden", en: "connected", take: false },
      ],
    },
  ];

  // ---------- Die Protagonisten ----------
  const FIGURES = [
    {
      id: "morazan",
      name: "Francisco Morazán",
      role: "Präsident der Föderation, liberaler Held",
      roleEn: "President of the Federation, liberal hero",
      years: "1792–1842",
      flag: "🇭🇳",
      img: "Francisco Morazán Quesada.JPG",
      text: "Der „Bolívar Mittelamerikas“: Als Präsident der jungen Föderation kämpfte er für Schulen, Religionsfreiheit und ein einziges, geeintes Mittelamerika. Gegen ihn standen die Kirche und die Konservativen. Als sein Staat zerfiel, wurde er 1842 in Costa Rica erschossen – heute ehren ihn mehrere Länder als Helden.",
      textEn: "The \"Bolívar of Central America\": as president of the young federation he fought for schools, freedom of religion and a single, united Central America. Against him stood the Church and the conservatives. When his state fell apart, he was shot in Costa Rica in 1842 – today several countries honour him as a hero.",
      quote: "„Die Nachwelt wird uns Gerechtigkeit widerfahren lassen.“",
      quoteEn: "\"Posterity will do us justice.\"",
      level: "B1",
      es: [
        "A Francisco Morazán lo llaman el „Bolívar de Centroamérica“. Como presidente de la joven federación, *luchó* por escuelas públicas, por la libertad de religión y por mantener a los cinco países *unidos* en una sola nación.",
        "Contra él estaban la Iglesia y los conservadores, que no querían perder su poder. Cuando la federación se *deshizo*, Morazán fue *fusilado* en Costa Rica en 1842. Hoy varios países lo *honran* como un héroe que soñó con una Centroamérica unida.",
      ],
      vocab: [
        { es: "luchó", de: "kämpfte (luchar)", en: "fought (luchar)", take: true },
        { es: "unidos", de: "geeint, vereint", en: "united", take: true },
        { es: "deshizo", de: "zerfiel (deshacerse)", en: "fell apart (deshacerse)", take: true },
        { es: "fusilado", de: "erschossen (fusilar)", en: "shot (executed)", take: true },
        { es: "honran", de: "ehren (honrar)", en: "honour (honrar)", take: true },
      ],
    },
    {
      id: "sandino",
      name: "Augusto César Sandino",
      role: "Guerillaführer gegen die US-Besatzung",
      roleEn: "Guerrilla leader against the US occupation",
      years: "1895–1934",
      flag: "🇳🇮",
      img: "Sandino.jpg",
      text: "Mit einer kleinen Bauern-Guerilla kämpfte er jahrelang gegen die US-Marines, die Nicaragua besetzt hielten – und wurde zum Symbol des Widerstands in ganz Lateinamerika. 1934 wurde er bei Friedensgesprächen heimtückisch ermordet. Sein Name lebt weiter: Die „Sandinisten“ benannten sich nach ihm.",
      textEn: "With a small peasant guerrilla force he fought for years against the US Marines occupying Nicaragua – and became a symbol of resistance across Latin America. In 1934 he was treacherously murdered during peace talks. His name lives on: the \"Sandinistas\" named themselves after him.",
      quote: "„Die Souveränität eines Volkes verhandelt man nicht – man verteidigt sie mit den Waffen in der Hand.“",
      quoteEn: "\"A people's sovereignty is not up for debate – it is defended with weapons in hand.\"",
      level: "B2",
      es: [
        "Con un pequeño *ejército* de campesinos, Augusto César Sandino luchó durante años contra los soldados estadounidenses que *ocupaban* Nicaragua. Por eso se convirtió en un *símbolo* de la resistencia en toda América Latina.",
        "En 1934, cuando ya había negociaciones de paz, fue *asesinado* a *traición*. Pero su nombre no murió: muchos años después, los „sandinistas“ que *derribaron* al dictador Somoza tomaron su nombre para honrar su lucha.",
      ],
      vocab: [
        { es: "ejército", de: "das Heer, die Armee", en: "army", take: true },
        { es: "ocupaban", de: "besetzten (ocupar)", en: "occupied (ocupar)", take: true },
        { es: "símbolo", de: "das Symbol", en: "symbol", take: false },
        { es: "asesinado", de: "ermordet (asesinar)", en: "murdered (asesinar)", take: true },
        { es: "traición", de: "der Verrat", en: "betrayal", take: true },
        { es: "derribaron", de: "stürzten (derribar)", en: "overthrew (derribar)", take: true },
      ],
    },
    {
      id: "romero",
      name: "Óscar Romero",
      role: "Erzbischof & Stimme der Armen",
      roleEn: "Archbishop & voice of the poor",
      years: "1917–1980",
      flag: "🇸🇻",
      text: "Als Erzbischof von San Salvador prangerte er mutig die Gewalt des Militärs gegen die einfachen Leute an. Einen Tag nach der Bitte an die Soldaten, das Töten einzustellen, wurde er 1980 am Altar erschossen – der Funke, der den Bürgerkrieg entzündete. 2018 sprach ihn die Kirche heilig.",
      textEn: "As archbishop of San Salvador he courageously denounced the military's violence against ordinary people. A day after pleading with the soldiers to stop the killing, he was shot at the altar in 1980 – the spark that ignited the civil war. In 2018 the Church canonised him as a saint.",
      quote: "„Hört auf mit der Unterdrückung!“",
      quoteEn: "\"Stop the repression!\"",
      level: "B2",
      es: [
        "Como arzobispo de San Salvador, Óscar Romero *denunció* con valentía la violencia del ejército contra la gente más pobre. Cada domingo, miles de personas escuchaban sus *sermones* por la radio.",
        "Un día después de *pedir* a los soldados que dejaran de matar, fue *asesinado* mientras daba misa, en 1980. Su muerte fue la *chispa* que encendió la guerra civil. En 2018, la Iglesia lo declaró *santo*.",
      ],
      vocab: [
        { es: "denunció", de: "prangerte an (denunciar)", en: "denounced (denunciar)", take: true },
        { es: "sermones", de: "die Predigten", en: "sermons", take: false },
        { es: "pedir", de: "bitten", en: "to ask, plead", take: true },
        { es: "asesinado", de: "ermordet (asesinar)", en: "murdered (asesinar)", take: true },
        { es: "chispa", de: "der Funke", en: "spark", take: true },
        { es: "santo", de: "der Heilige", en: "saint", take: true },
      ],
    },
    {
      id: "menchu",
      name: "Rigoberta Menchú",
      role: "Maya-Aktivistin, Friedensnobelpreis",
      roleEn: "Maya activist, Nobel Peace Prize",
      years: "1959–",
      flag: "🇬🇹",
      img: "Rigoberta Menchu.jpg",
      text: "Aus einer armen Maya-Familie, verlor sie im Bürgerkrieg Eltern und Bruder. Sie machte die Verfolgung der indigenen Völker Guatemalas weltweit bekannt und erhielt 1992 den Friedensnobelpreis – als erste indigene Frau überhaupt. Bis heute kämpft sie für die Rechte der Ureinwohner.",
      textEn: "From a poor Maya family, she lost her parents and brother in the civil war. She brought the persecution of Guatemala's indigenous peoples to the world's attention and received the Nobel Peace Prize in 1992 – the first indigenous woman ever to do so. To this day she fights for the rights of native peoples.",
      quote: "„… und so erwachte in mir das Bewusstsein.“",
      quoteEn: "\"… and so my consciousness was born.\"",
      level: "B1",
      es: [
        "Rigoberta Menchú nació en una familia maya muy *pobre*. Durante la guerra civil de Guatemala perdió a sus padres y a un hermano, *asesinados* por el ejército.",
        "En lugar de callar, *contó* al mundo entero el sufrimiento de los pueblos indígenas. En 1992 recibió el Premio Nobel de la Paz, la primera mujer indígena en *lograrlo*. Todavía hoy *defiende* los derechos de los pueblos originarios.",
      ],
      vocab: [
        { es: "pobre", de: "arm", en: "poor", take: true },
        { es: "asesinados", de: "ermordet (asesinar)", en: "murdered (asesinar)", take: true },
        { es: "contó", de: "erzählte (contar)", en: "told (contar)", take: true },
        { es: "lograrlo", de: "es schaffen (lograr)", en: "to achieve it (lograr)", take: true },
        { es: "defiende", de: "verteidigt (defender)", en: "defends (defender)", take: true },
      ],
    },
    {
      id: "figueres",
      name: "José Figueres Ferrer",
      role: "Costa Rica: schaffte die Armee ab",
      roleEn: "Costa Rica: abolished the army",
      years: "1906–1990",
      flag: "🇨🇷",
      text: "Nach einem kurzen Bürgerkrieg traf er 1948 eine historische Entscheidung: Er schaffte das Heer Costa Ricas komplett ab und steckte das Geld in Schulen und Gesundheit. Er führte das Frauenwahlrecht ein. Bis heute hat Costa Rica keine Armee – und gilt als die stabilste Demokratie der Region.",
      textEn: "After a short civil war he made a historic decision in 1948: he abolished Costa Rica's army entirely and put the money into schools and health. He introduced women's suffrage. To this day Costa Rica has no army – and is considered the most stable democracy in the region.",
      quote: "„Wozu Traktoren ohne Geigen?“",
      quoteEn: "\"What is the point of tractors without violins?\"",
      level: "B1",
      es: [
        "Después de una corta guerra civil, en 1948 José Figueres tomó una decisión *histórica*: *eliminó* por completo el ejército de Costa Rica y puso ese dinero en escuelas y hospitales. También dio a las mujeres el *derecho* a votar.",
        "Desde entonces, Costa Rica no tiene *ejército*. Gracias a esa decisión, el país se convirtió en la *democracia* más estable y *tranquila* de toda Centroamérica.",
      ],
      vocab: [
        { es: "histórica", de: "historisch", en: "historic", take: false },
        { es: "eliminó", de: "schaffte ab (eliminar)", en: "abolished (eliminar)", take: true },
        { es: "derecho", de: "das Recht", en: "right", take: true },
        { es: "ejército", de: "das Heer, die Armee", en: "army", take: true },
        { es: "democracia", de: "die Demokratie", en: "democracy", take: true },
        { es: "tranquila", de: "ruhig, friedlich", en: "calm, peaceful", take: true },
      ],
    },
  ];

  // ---------- "Heute": Lage & Spannungen ----------
  const TENSIONS = [
    {
      id: "el-salvador-bukele",
      icon: "lc:bird",
      title: "El Salvador: Bukeles harte Hand",
      titleEn: "El Salvador: Bukele's hard hand",
      where: "El Salvador",
      whereEn: "El Salvador",
      tone: "shift",
      status: "Umbruch",
      statusEn: "Shift",
      text: "Präsident Nayib Bukele ließ unter einem Ausnahmezustand zehntausende mutmaßliche Bandenmitglieder einsperren – in einem riesigen Mega-Gefängnis (CECOT). Die einst höchste Mordrate der Welt fiel drastisch, und Bukele ist enorm beliebt. Kritiker warnen jedoch vor Massenverhaftungen ohne fairen Prozess und dem Abbau der Demokratie.",
      textEn: "Under a state of emergency, President Nayib Bukele had tens of thousands of suspected gang members locked up – in a huge mega-prison (CECOT). Once the highest murder rate in the world fell drastically, and Bukele is hugely popular. Critics, however, warn of mass arrests without fair trial and the erosion of democracy.",
      level: "B1",
      es: [
        "El presidente Nayib Bukele declaró un „régimen de excepción“ y *encarceló* a decenas de miles de presuntos *pandilleros* en una cárcel enorme. La violencia *bajó* muchísimo, y por eso Bukele es muy *popular* entre la gente.",
        "Pero muchos *critican* que hay personas inocentes en prisión, sin un juicio justo, y *temen* que el país pierda poco a poco su democracia.",
      ],
      vocab: [
        { es: "encarceló", de: "sperrte ein (encarcelar)", en: "imprisoned (encarcelar)", take: true },
        { es: "pandilleros", de: "die Bandenmitglieder", en: "gang members", take: true },
        { es: "bajó", de: "sank (bajar)", en: "dropped (bajar)", take: true },
        { es: "popular", de: "beliebt", en: "popular", take: true },
        { es: "critican", de: "kritisieren (criticar)", en: "criticise (criticar)", take: true },
        { es: "temen", de: "fürchten (temer)", en: "fear (temer)", take: true },
      ],
    },
    {
      id: "nicaragua-ortega",
      icon: "lc:flag",
      title: "Nicaragua: Ortegas Machtkonzentration",
      titleEn: "Nicaragua: Ortega's grip on power",
      where: "Nicaragua",
      whereEn: "Nicaragua",
      tone: "crisis",
      status: "Krise",
      statusEn: "Crisis",
      text: "Der einstige Revolutionsheld Daniel Ortega regiert Nicaragua heute zusammen mit seiner Frau autoritär. Proteste 2018 wurden blutig niedergeschlagen, die Opposition sitzt im Gefängnis oder im Exil; manchen Gegnern wurde sogar die Staatsbürgerschaft entzogen. Auch die katholische Kirche wird verfolgt.",
      textEn: "The former revolutionary hero Daniel Ortega now rules Nicaragua authoritatively together with his wife. Protests in 2018 were crushed bloodily, the opposition is in prison or in exile; some opponents were even stripped of their citizenship. The Catholic Church, too, is persecuted.",
      level: "B2",
      es: [
        "Daniel Ortega, que de joven fue un héroe de la *revolución* sandinista, hoy gobierna Nicaragua junto a su esposa de forma *autoritaria*. En 2018, las protestas en las calles fueron *reprimidas* con mucha violencia.",
        "Desde entonces, la *oposición* está en la cárcel o en el *exilio*, y el gobierno incluso quitó la *ciudadanía* a algunos de sus críticos. También persigue a la Iglesia católica.",
      ],
      vocab: [
        { es: "revolución", de: "die Revolution", en: "revolution", take: false },
        { es: "autoritaria", de: "autoritär", en: "authoritarian", take: true },
        { es: "reprimidas", de: "niedergeschlagen (reprimir)", en: "repressed (reprimir)", take: true },
        { es: "oposición", de: "die Opposition", en: "opposition", take: true },
        { es: "exilio", de: "das Exil", en: "exile", take: true },
        { es: "ciudadanía", de: "die Staatsbürgerschaft", en: "citizenship", take: true },
      ],
    },
    {
      id: "panama-canal",
      icon: "lc:ship",
      title: "Panamá: der Kanal & der Druck aus dem Norden",
      titleEn: "Panama: the canal & pressure from the north",
      where: "Panama",
      whereEn: "Panama",
      tone: "tense",
      status: "Angespannt",
      statusEn: "Tense",
      text: "Der Panamakanal, seit 1999 vollständig in panamaischer Hand, ist das Herz der Weltwirtschaft – fast jedes Containerschiff zwischen Asien und Amerika fährt hindurch. 2025 forderte US-Präsident Trump den Kanal lautstark „zurück“ und warf China zu großen Einfluss vor. Dürren lassen zudem den Wasserstand sinken.",
      textEn: "The Panama Canal, fully in Panamanian hands since 1999, is the heart of the world economy – almost every container ship between Asia and the Americas passes through it. In 2025 US President Trump loudly demanded the canal \"back\" and accused China of too much influence. Droughts are also lowering the water level.",
      level: "B1",
      es: [
        "El canal de Panamá, que es totalmente panameño desde 1999, es uno de los lugares más importantes del *comercio* mundial: casi todos los grandes barcos entre Asia y América pasan por él.",
        "En 2025, el presidente Trump pidió en voz alta *recuperar* el canal y *acusó* a China de tener demasiada *influencia*. Además, las *sequías* hacen bajar el nivel del agua y *amenazan* el paso de los barcos.",
      ],
      vocab: [
        { es: "comercio", de: "der Handel", en: "trade", take: true },
        { es: "recuperar", de: "zurückholen", en: "to take back", take: true },
        { es: "acusó", de: "beschuldigte (acusar)", en: "accused (acusar)", take: true },
        { es: "influencia", de: "der Einfluss", en: "influence", take: true },
        { es: "sequías", de: "die Dürren", en: "droughts", take: true },
        { es: "amenazan", de: "bedrohen (amenazar)", en: "threaten (amenazar)", take: true },
      ],
    },
    {
      id: "maras-migracion",
      icon: "lc:route",
      title: "Maras & Migration nach Norden",
      titleEn: "Gangs & migration northward",
      where: "Guatemala · Honduras · El Salvador",
      whereEn: "Guatemala · Honduras · El Salvador",
      tone: "crisis",
      status: "Krise",
      statusEn: "Crisis",
      text: "Die Jugendbanden MS-13 und Barrio 18 entstanden einst in den USA und wurden nach Mittelamerika abgeschoben. Zusammen mit Armut und Korruption machten sie das „Nördliche Dreieck“ jahrelang zu einer der gefährlichsten Regionen der Welt – und treiben bis heute viele Menschen auf den langen Weg Richtung US-Grenze.",
      textEn: "The youth gangs MS-13 and Barrio 18 originally formed in the USA and were deported to Central America. Together with poverty and corruption they made the \"Northern Triangle\" one of the most dangerous regions in the world for years – and still drive many people onto the long road towards the US border.",
      level: "B2",
      es: [
        "Las pandillas MS-13 y Barrio 18 *nacieron* en realidad en Estados Unidos, y desde allí fueron *deportadas* a Centroamérica. Junto con la pobreza y la corrupción, convirtieron al „Triángulo Norte“ en una de las regiones más *peligrosas* del mundo.",
        "Por eso, muchas familias *deciden* dejar su país y *emprender* un viaje largo y arriesgado hacia la *frontera* de Estados Unidos, buscando una vida más segura.",
      ],
      vocab: [
        { es: "nacieron", de: "entstanden (nacer)", en: "were born (nacer)", take: true },
        { es: "deportadas", de: "abgeschoben (deportar)", en: "deported (deportar)", take: true },
        { es: "peligrosas", de: "gefährlich", en: "dangerous", take: true },
        { es: "deciden", de: "entscheiden (decidir)", en: "decide (decidir)", take: true },
        { es: "emprender", de: "antreten, beginnen", en: "to undertake", take: false },
        { es: "frontera", de: "die Grenze", en: "border", take: true },
      ],
    },
    {
      id: "guatemala-arevalo",
      icon: "lc:vote",
      title: "Guatemala: ein fragiler Neuanfang",
      titleEn: "Guatemala: a fragile fresh start",
      where: "Guatemala",
      whereEn: "Guatemala",
      tone: "shift",
      status: "Umbruch",
      statusEn: "Shift",
      text: "Überraschend gewann 2023 der Antikorruptions-Kandidat Bernardo Arévalo die Wahl. Die alte Elite – der „Pakt der Korrupten“ – versuchte mit allen Mitteln, seinen Amtsantritt zu verhindern. Nach Massenprotesten, getragen besonders von den indigenen Gemeinden, wurde er Anfang 2024 doch vereidigt.",
      textEn: "Surprisingly, the anti-corruption candidate Bernardo Arévalo won the 2023 election. The old elite – the \"pact of the corrupt\" – tried by every means to prevent his inauguration. After mass protests, carried especially by the indigenous communities, he was finally sworn in in early 2024.",
      level: "B2",
      es: [
        "En 2023, para sorpresa de todos, el candidato contra la corrupción, Bernardo Arévalo, *ganó* las elecciones. La vieja *élite* del país intentó por todos los medios *impedir* que llegara al poder.",
        "Pero hubo grandes *protestas* en las calles, *apoyadas* sobre todo por los pueblos indígenas, y al final Arévalo pudo *asumir* la presidencia a principios de 2024.",
      ],
      vocab: [
        { es: "ganó", de: "gewann (ganar)", en: "won (ganar)", take: true },
        { es: "élite", de: "die Elite", en: "elite", take: false },
        { es: "impedir", de: "verhindern", en: "to prevent", take: true },
        { es: "protestas", de: "die Proteste", en: "protests", take: true },
        { es: "apoyadas", de: "unterstützt (apoyar)", en: "supported (apoyar)", take: true },
        { es: "asumir", de: "übernehmen (Amt)", en: "to take office", take: true },
      ],
    },
    {
      id: "costa-rica",
      icon: "lc:leaf",
      title: "Costa Rica: die stabile Ausnahme",
      titleEn: "Costa Rica: the stable exception",
      where: "Costa Rica",
      whereEn: "Costa Rica",
      tone: "progress",
      status: "Stabil",
      statusEn: "Stable",
      text: "Ohne Armee seit 1948, mit lebendiger Demokratie und berühmtem Naturschutz gilt Costa Rica als die ruhige Ausnahme der Region – „pura vida“. Der Tourismus floriert, ein großer Teil des Stroms ist erneuerbar. Doch zuletzt steigt auch hier die Gewalt durch den internationalen Drogenhandel spürbar an.",
      textEn: "With no army since 1948, a lively democracy and famous nature conservation, Costa Rica is seen as the calm exception of the region – \"pura vida\". Tourism flourishes, much of its electricity is renewable. But lately violence from international drug trafficking has been noticeably rising here too.",
      level: "B1",
      es: [
        "Sin ejército desde 1948 y con una democracia *viva*, Costa Rica es la gran excepción tranquila de la región: aquí la gente dice „pura vida“. El *turismo* y la protección de la *naturaleza* son el orgullo del país.",
        "Casi toda su *electricidad* es de energías limpias. Sin embargo, en los últimos años también ha *crecido* la violencia por culpa del *narcotráfico* internacional.",
      ],
      vocab: [
        { es: "viva", de: "lebendig", en: "alive, lively", take: true },
        { es: "turismo", de: "der Tourismus", en: "tourism", take: true },
        { es: "naturaleza", de: "die Natur", en: "nature", take: true },
        { es: "electricidad", de: "die Elektrizität, der Strom", en: "electricity", take: true },
        { es: "crecido", de: "gewachsen (crecer)", en: "grown (crecer)", take: true },
        { es: "narcotráfico", de: "der Drogenhandel", en: "drug trafficking", take: false },
      ],
    },
  ];

  // ---------- ¿Sabías que…? (kurze Häppchen) ----------
  const FACTS = [
    {
      de: "Costa Rica hat seit 1948 keine Armee – das gesparte Geld floss in Bildung und Gesundheit.",
      en: "Costa Rica has had no army since 1948 – the money saved went into education and health.",
    },
    {
      de: "Das Wort „Bananenrepublik“ erfand der US-Autor O. Henry, inspiriert von Honduras.",
      en: "The term \"banana republic\" was coined by the US author O. Henry, inspired by Honduras.",
    },
    {
      de: "Die Maya kannten die Null und eine echte Schrift – Jahrhunderte vor Europa.",
      en: "The Maya knew the zero and a true writing system – centuries before Europe.",
    },
    {
      de: "Belize ist das einzige Land Mittelamerikas mit Englisch als Amtssprache (früher Britisch-Honduras).",
      en: "Belize is the only country in Central America with English as its official language (formerly British Honduras).",
    },
    {
      de: "Morazán träumte – wie Bolívar im Süden – von einem einzigen Land; beide Träume scheiterten.",
      en: "Morazán dreamed – like Bolívar in the south – of a single country; both dreams failed.",
    },
    {
      de: "El Salvador machte 2021 als erstes Land der Welt Bitcoin zum gesetzlichen Zahlungsmittel.",
      en: "In 2021 El Salvador became the first country in the world to make Bitcoin legal tender.",
    },
  ];

  window.SC.historiaCentro = { INTRO, ERAS, FIGURES, TENSIONS, FACTS };
})();
