/*
 * knigge.js  (SC.knigge) – Modell für "Reise-Knigge: Verhalten unterwegs".
 * REINE DATEN, keine Logik (wie countries.js / frases.js). Wird von
 * dem Feature-Modul SC.etiqueta (features/etiqueta.js) gerendert; der Controller
 * (app.js) wählt per Dropdown ein
 * Land aus (geteilt mit der Länderkunde über state.countryId).
 *
 * TOPICS:  allgemeine DOs & Don'ts, die überall gelten (vier Themenblöcke).
 *   { id, icon, title, intro, dos:[…], donts:[…] }
 *   id  = Schlüssel, über den die landesspezifischen Akzente zugeordnet werden.
 *
 * ACCENTS: kurze, konkrete Besonderheit pro Land und Thema (1 Satz je Thema).
 *   { <countryId>: { hostel, bus, grupo, cultura } }  – Felder optional.
 *   countryId muss exakt der id aus countries.js LIST entsprechen.
 *
 * Hinweis: Inhalte sind Backpacker-Erfahrungswerte/Faustregeln – keine
 * verbindlichen Vorschriften. Im Zweifel zählt die Hausordnung vor Ort.
 */
(function () {
  "use strict";

  const TOPICS = [
    {
      id: "hostel",
      icon: "lc:bed",
      title: "Hostel & Dorm",
      titleEn: "Hostel & dorm",
      intro: "Im Schlafsaal teilst du den Raum mit Fremden – Rücksicht ist die halbe Miete.",
      introEn: "In the dorm you're sharing the room with strangers – being considerate gets you halfway there.",
      dos: [
        "Nachtruhe ab ca. 22–23 Uhr: leise reden, kein grelles Deckenlicht – nutze die Handy-Taschenlampe.",
        "Wenn du früh los musst, packe deinen Rucksack schon am Vorabend, nicht im dunklen Dorm.",
        "Kopfhörer für Musik/Videos benutzen und das Handy auf lautlos stellen.",
        "Bring ein eigenes Schloss mit und schließ Wertsachen ins Locker (locker / casillero).",
        "Gemeinschaftsküche: sofort abspülen, Geschirr wegräumen, eigenes Essen im Kühlschrank beschriften.",
        "Stell dich kurz vor, wenn du ankommst – ein „Hola, soy nuevo aquí“ bricht das Eis.",
      ],
      dosEn: [
        "Quiet time from around 10–11pm: talk softly, no harsh ceiling light – use your phone torch.",
        "If you have to leave early, pack your backpack the night before, not in the dark dorm.",
        "Use headphones for music/videos and put your phone on silent.",
        "Bring your own padlock and lock valuables in the locker (locker / casillero).",
        "Shared kitchen: wash up straight away, put dishes away, label your own food in the fridge.",
        "Introduce yourself briefly when you arrive – a „Hola, soy nuevo aquí“ breaks the ice.",
      ],
      dosDeEn: [
        "Nachtruhe ab ca. 22–23 Uhr: leise reden, kein grelles Deckenlicht – nutze die Handy-Taschenlampe.",
        "Wenn du früh los musst, packe deinen Rucksack schon am Vorabend, nicht im dunklen Dorm.",
        "Kopfhörer für Musik/Videos benutzen und das Handy auf lautlos stellen.",
        "Bring ein eigenes Schloss mit und schließ Wertsachen ins Fach – im Hostel heißt das einfach „locker“.",
        "Gemeinschaftsküche: sofort abspülen, Geschirr wegräumen, eigenes Essen im Kühlschrank beschriften.",
        "Stell dich kurz vor, wenn du ankommst – ein „Hi, I'm new here“ bricht das Eis.",
      ],
      donts: [
        "Kein Deckenlicht anschalten, wenn andere schlafen.",
        "Nachts nicht in Plastiktüten rascheln und keine Telefonate im Dorm führen.",
        "Fremde Betten, Handtücher oder Steckdosen-Plätze nicht einfach belegen – auch nicht zum Sitzen.",
        "Nasse oder stark riechende Kleidung nicht im Schlafsaal trocknen.",
        "Den Wecker nicht zigmal auf Schlummern stellen – einmal klingeln, aufstehen.",
      ],
      dontsEn: [
        "Don't switch on the ceiling light when others are asleep.",
        "Don't rustle plastic bags at night and don't take phone calls in the dorm.",
        "Don't just take over other people's beds, towels or sockets – not even to sit on.",
        "Don't dry wet or strong-smelling clothes in the dorm.",
        "Don't hit snooze a dozen times – one alarm, then get up.",
      ],
    },
    {
      id: "bus",
      icon: "lc:bus",
      title: "Bus & Transport",
      titleEn: "Bus & transport",
      intro: "Nachtbusse sparen eine Übernachtung – mit etwas Umsicht reist du sicher und entspannt.",
      introEn: "Night buses save you a night's accommodation – with a bit of care you travel safely and relaxed.",
      dos: [
        "Wertsachen (Pass, Geld, Handy) immer am Körper tragen, nie im Gepäckfach oder über dem Sitz.",
        "Im Nachtbus Jacke, Schal oder Schlafsack-Inlett dabeihaben – die Klimaanlage läuft oft eiskalt.",
        "Ticket und Gepäckschein gut aufheben und die Endhaltestelle vorher kennen.",
        "Den Sitz nur sachte zurücklehnen und beim Aussteigen prüfen, ob das richtige Gepäck mitkommt.",
        "Bei kurzen Stopps fragen: „¿Cuánto tiempo paramos?“ – damit du den Bus nicht verpasst.",
      ],
      dosEn: [
        "Always keep valuables (passport, money, phone) on you, never in the luggage hold or overhead.",
        "On a night bus, bring a jacket, scarf or sleeping-bag liner – the air conditioning is often freezing.",
        "Keep your ticket and luggage tag safe and know your final stop in advance.",
        "Only recline your seat gently and, when getting off, check you take the right luggage.",
        "At short stops, ask: „¿Cuánto tiempo paramos?“ – so you don't miss the bus.",
      ],
      dosDeEn: [
        "Wertsachen (Pass, Geld, Handy) immer am Körper tragen, nie im Gepäckfach oder über dem Sitz.",
        "Im Nachtbus (National Express, Greyhound, Megabus) Jacke oder Schal dabeihaben – die Klimaanlage läuft oft eiskalt.",
        "Ticket und Gepäckabschnitt gut aufheben und die Endhaltestelle vorher kennen.",
        "Den Sitz nur sachte zurücklehnen und beim Aussteigen prüfen, ob das richtige Gepäck mitkommt.",
        "Bei kurzen Stopps fragen: „How long do we stop here?“ – damit du den Bus nicht verpasst.",
      ],
      donts: [
        "Die Tasche nicht offen am Gang oder lose unter dem Sitz liegen lassen.",
        "Keine laute Musik ohne Kopfhörer; nicht den Sitznachbarn mit Gepäck oder Beinen zustellen.",
        "Wechselgeld und Tarif nicht blind vertrauen – vorab nach dem Fahrpreis fragen.",
        "Nachts nicht mit sichtbarem Handy/Laptop hantieren, vor allem nah an der Tür.",
      ],
      dontsEn: [
        "Don't leave your bag open on the aisle or loose under the seat.",
        "No loud music without headphones; don't block your neighbour with luggage or your legs.",
        "Don't blindly trust the change and fare – ask the price beforehand.",
        "Don't handle a visible phone/laptop at night, especially near the door.",
      ],
    },
    {
      id: "grupo",
      icon: "lc:hand",
      title: "Gruppen & Leute",
      titleEn: "Groups & people",
      intro: "Reisende sind offen – ein ehrliches „Hola“ öffnet fast überall Türen.",
      introEn: "Travellers are open – an honest „Hola“ opens doors almost everywhere.",
      introDeEn: "Reisende sind offen – ein ehrliches „Hi“ öffnet fast überall Türen.",
      dos: [
        "Trau dich, anzusprechen: „¿De dónde eres?“ oder „¿Viajas solo/a?“ – Smalltalk ist normal und erwünscht.",
        "Frag, ob du mitkommen darfst: „¿Te unes?“ / „¿Vamos juntos?“ – statt dich einfach anzuhängen.",
        "Gemeinsame Pläne früh absprechen und Kosten fair & transparent teilen.",
        "Bei Gruppenaktivitäten Treffpunkt und Uhrzeit klar vereinbaren – und pünktlich sein.",
        "Kontakte sichern: „Escríbeme por WhatsApp“ – so bleibt man unterwegs in Verbindung.",
      ],
      dosEn: [
        "Be brave and start a chat: „¿De dónde eres?“ or „¿Viajas solo/a?“ – small talk is normal and welcome.",
        "Ask if you can join: „¿Te unes?“ / „¿Vamos juntos?“ – rather than just tagging along.",
        "Agree shared plans early and split costs fairly and transparently.",
        "For group activities, agree a clear meeting point and time – and be punctual.",
        "Swap contacts: „Escríbeme por WhatsApp“ – that way you stay in touch on the road.",
      ],
      dosDeEn: [
        "Trau dich, anzusprechen: „Where are you from?“ oder „Are you travelling solo?“ – Smalltalk ist normal und erwünscht.",
        "Frag, ob du mitkommen darfst: „Mind if I join you?“ / „Shall we go together?“ – statt dich einfach anzuhängen.",
        "Gemeinsame Pläne früh absprechen und Kosten fair & transparent teilen.",
        "Bei Gruppenaktivitäten Treffpunkt und Uhrzeit klar vereinbaren – und pünktlich sein.",
        "Kontakte sichern: „Text me on WhatsApp“ – so bleibt man unterwegs in Verbindung.",
      ],
      donts: [
        "Sich niemandem aufdrängen, der sichtbar Ruhe oder Zeit für sich will.",
        "Keine versteckten Kosten – die Rechnung sauber und nachvollziehbar splitten.",
        "Niemanden zum Trinken, Feiern oder zu Ausgaben drängen.",
        "Nicht ständig nur in der eigenen Sprachblase bleiben – ein paar Brocken Spanisch öffnen mehr.",
      ],
      dontsEn: [
        "Don't force yourself on anyone who clearly wants peace or time to themselves.",
        "No hidden costs – split the bill cleanly and clearly.",
        "Don't pressure anyone into drinking, partying or spending.",
        "Don't stay stuck in your own language bubble – a few words of Spanish open more doors.",
      ],
      dontsDeEn: [
        "Sich niemandem aufdrängen, der sichtbar Ruhe oder Zeit für sich will.",
        "Keine versteckten Kosten – die Rechnung sauber und nachvollziehbar splitten.",
        "Niemanden zum Trinken, Feiern oder zu Ausgaben drängen.",
        "Nicht ständig nur in der eigenen Sprachblase bleiben – ein paar Brocken Englisch öffnen mehr Türen.",
      ],
    },
    {
      id: "cultura",
      icon: "lc:handshake",
      title: "Kultur & Etikette",
      titleEn: "Culture & etiquette",
      intro: "Kleine Gesten – Begrüßung, Trinkgeld, Pünktlichkeit – zeigen Respekt und werden gemerkt.",
      introEn: "Small gestures – a greeting, a tip, punctuality – show respect and don't go unnoticed.",
      dos: [
        "Freundlich grüßen: „Buenos días / buenas tardes“ beim Betreten von Läden, Bussen oder Lokalen.",
        "„Por favor“ und „gracias“ großzügig benutzen – Höflichkeit zählt viel in Lateinamerika.",
        "Trinkgeld ~10 % im Restaurant geben, sofern nicht schon „servicio“ auf der Rechnung steht.",
        "Beim Feilschen freundlich und mit Humor bleiben – ein Lächeln bringt mehr als Härte.",
        "Lokale Gepflogenheiten beobachten und mitmachen, statt sie zu bewerten.",
        "Toilettenpapier in den Mülleimer (papelera) neben der Toilette werfen – in weiten Teilen Lateinamerikas sind die Rohre zu eng fürs WC (Schild: „No arrojar papeles ni toallas sanitarias“).",
      ],
      dosEn: [
        "Greet people warmly: „Buenos días / buenas tardes“ when entering shops, buses or eateries.",
        "Use „Por favor“ and „gracias“ generously – politeness counts for a lot in Latin America.",
        "Tip ~10% in restaurants, unless „servicio“ is already on the bill.",
        "When haggling, stay friendly and good-humoured – a smile gets you further than being tough.",
        "Observe local customs and join in, rather than judging them.",
        "Put toilet paper in the bin (papelera) next to the loo – in much of Latin America the pipes are too narrow for the WC (sign: „No arrojar papeles ni toallas sanitarias“).",
      ],
      dosDeEn: [
        "Freundlich grüßen: „Good morning / good afternoon“ beim Betreten von Läden, Bussen oder Pubs.",
        "„Please“ und „thank you“ großzügig benutzen – Höflichkeit zählt in UK, Irland & Co. besonders viel.",
        "Trinkgeld gehört dazu: in UK/Irland ~10–12 %, in den USA/Kanada 15–20 % – außer es steht schon ein „service charge“ auf der Rechnung.",
        "Schlangestehen ist heilig: ordentlich anstellen („queue“) und warten, bis du dran bist.",
        "Lokale Gepflogenheiten beobachten und mitmachen, statt sie zu bewerten.",
        "In Läden gelten feste Preise – nur auf Flohmärkten oder „car boot sales“ ist mal freundliches Handeln drin.",
      ],
      donts: [
        "Nicht mit der Tür ins Haus fallen – erst grüßen, dann fragen oder bestellen.",
        "Menschen, Häuser oder Märkte nicht ungefragt fotografieren.",
        "Heikle Themen (Politik, Drogen, Vergleiche mit den USA) zurückhaltend behandeln.",
        "Nicht überall hart verhandeln – in Geschäften mit festen Preisen ist Feilschen unüblich.",
        "Papier nicht ins WC werfen, wenn ein Eimer danebensteht – das verstopft die Leitungen sofort.",
      ],
      dontsEn: [
        "Don't dive straight in – greet first, then ask or order.",
        "Don't photograph people, houses or markets without asking.",
        "Handle sensitive topics (politics, drugs, comparisons with the USA) with restraint.",
        "Don't haggle hard everywhere – in shops with fixed prices haggling isn't the done thing.",
        "Don't put paper down the loo if there's a bin beside it – it blocks the pipes immediately.",
      ],
      dontsDeEn: [
        "Nicht mit der Tür ins Haus fallen – erst grüßen, dann fragen oder bestellen.",
        "Menschen, Häuser oder Märkte nicht ungefragt fotografieren.",
        "Heikle Themen (Politik, Religion, Geld/Gehalt) lieber zurückhaltend behandeln.",
        "Nicht handeln wollen – in Läden gelten feste Preise, Feilschen wirkt befremdlich.",
        "Sich nicht in die Schlange vordrängeln – „queue-jumping“ gilt als grober Verstoß.",
      ],
    },
  ];

  // Landesspezifische Akzente – knapp gehalten, eine Zeile je Thema.
  const ACCENTS = {
    mexico: {
      hostel: "In Touristenorten (Tulum, Oaxaca, CDMX) sind Dorms voll – früh reservieren und beim Check-in nach den horas de silencio fragen.",
      hostelEn: "In tourist spots (Tulum, Oaxaca, CDMX) dorms fill up – book early and ask about the horas de silencio at check-in.",
      bus: "Fernbusse (ADO, ETN) sind komfortabel und sicher; für Überland lieber diese als billige Minibusse, vor allem nachts.",
      busEn: "Long-distance buses (ADO, ETN) are comfortable and safe; for overland trips prefer these to cheap minibuses, especially at night.",
      grupo: "Locker im Ton: Mexikaner sagen gern „¿Qué onda?“ – mit „¡Órale!“ zeigst du, dass du dabei bist.",
      grupoEn: "Relaxed in tone: Mexicans love to say „¿Qué onda?“ – with „¡Órale!“ you show you're up for it.",
      cultura: "Propina von 10–15 % ist im Restaurant Standard; Tacos am Stand zahlt man bar und passend.",
      culturaEn: "A propina of 10–15% is standard in restaurants; tacos at a stall you pay in cash and with the right change.",
    },
    guatemala: {
      hostel: "In Antigua und am Lago Atitlán sind Hostels Backpacker-Treffpunkte – Wertsachen trotzdem immer ins Locker.",
      hostelEn: "In Antigua and at Lago Atitlán hostels are backpacker hubs – still always lock your valuables away.",
      bus: "Die bunten „chicken buses“ (camionetas) sind günstig und ein Erlebnis, aber voll und nachts zu meiden; für lange Strecken Shuttle nehmen.",
      busEn: "The colourful „chicken buses“ (camionetas) are cheap and an experience, but crowded and best avoided at night; take a shuttle for long trips.",
      grupo: "Viele organisieren gemeinsam den Acatenango-Vulkan – frag im Hostel, da findet sich schnell eine Gruppe.",
      grupoEn: "Lots of people organise the Acatenango volcano together – ask at the hostel, you'll soon find a group.",
      cultura: "In den Maya-Dörfern Menschen und Trachten nie ohne Erlaubnis fotografieren.",
      culturaEn: "In the Maya villages, never photograph people or traditional dress without permission.",
    },
    honduras: {
      hostel: "Auf den Bay Islands (Utila, Roatán) drehen sich Hostels ums Tauchen – Ausrüstung sicher verstauen.",
      hostelEn: "On the Bay Islands (Utila, Roatán) hostels revolve around diving – store your gear safely.",
      bus: "Für Strecken auf dem Festland Direktbusse (z. B. Hedman Alas) nehmen; nach Einbruch der Dunkelheit nicht überland fahren.",
      busEn: "For mainland routes take direct buses (e.g. Hedman Alas); don't travel overland after dark.",
      grupo: "Tauchkurse verbinden – über die offene Divemaster-Crew lernt man schnell Leute kennen.",
      grupoEn: "Diving courses bring people together – through the friendly divemaster crew you soon meet people.",
      cultura: "Sicherheit ernst nehmen: abends Taxi statt Fußweg, Wertsachen unsichtbar tragen.",
      culturaEn: "Take safety seriously: a taxi rather than walking in the evening, and keep valuables out of sight.",
    },
    elsalvador: {
      hostel: "Surf-Hostels an der Küste (El Tunco, El Zonte) sind entspannt – Boards und Nasszeug draußen, nicht im Dorm.",
      hostelEn: "Surf hostels on the coast (El Tunco, El Zonte) are laid-back – keep boards and wet gear outside, not in the dorm.",
      bus: "Lokale Busse sind günstig, aber langsam; für längere Strecken Shuttle oder Sammeltaxi bevorzugen.",
      busEn: "Local buses are cheap but slow; for longer trips prefer a shuttle or shared taxi.",
      grupo: "In „Bitcoin Beach“ trifft sich eine internationale Szene – ideal, um beim Surfen Anschluss zu finden.",
      grupoEn: "An international crowd gathers at „Bitcoin Beach“ – ideal for making friends while surfing.",
      cultura: "Salvadorianer sind herzlich; ein einfaches „¡Buena onda!“ kommt gut an.",
      culturaEn: "Salvadorans are warm; a simple „¡Buena onda!“ goes down well.",
    },
    nicaragua: {
      hostel: "In Granada und León sind Hostels mit Hängematten-Höfen die Norm – schön zum Leutetreffen, Wertsachen trotzdem wegschließen.",
      hostelEn: "In Granada and León, hostels with hammock courtyards are the norm – great for meeting people, but still lock your valuables away.",
      bus: "Auch hier fahren ausrangierte US-Schulbusse als günstige „chicken buses“; für Komfort und Sicherheit Shuttles nutzen.",
      busEn: "Here too, retired US school buses run as cheap „chicken buses“; for comfort and safety use shuttles.",
      grupo: "Vulkan-Boarding am Cerro Negro bucht man meist als Gruppe übers Hostel.",
      grupoEn: "Volcano boarding at Cerro Negro is usually booked as a group through the hostel.",
      cultura: "Geduld bei „ahorita“ – Zeitangaben sind oft dehnbar, plane Puffer ein.",
      culturaEn: "Be patient with „ahorita“ – times are often flexible, so build in some buffer.",
    },
    costarica: {
      hostel: "Hostels sind sauber, aber teurer als in Nachbarländern; viele liegen am Strand – Sand draußen lassen.",
      hostelEn: "Hostels are clean but pricier than in neighbouring countries; many are by the beach – leave the sand outside.",
      bus: "Öffentliche Busse sind günstig und zuverlässig; Touristen-Shuttles sparen Zeit zwischen den Hotspots.",
      busEn: "Public buses are cheap and reliable; tourist shuttles save time between the hotspots.",
      grupo: "„Pura vida“ ist Lebensgefühl und Floskel zugleich – damit knüpfst du sofort Kontakt.",
      grupoEn: "„Pura vida“ is both a way of life and a stock phrase – use it to connect with people instantly.",
      cultura: "Ticos sind sehr umweltbewusst – Müll trennen und Natur/Tiere nie füttern oder anfassen.",
      culturaEn: "Ticos are very eco-conscious – separate your rubbish and never feed or touch wildlife.",
    },
    panama: {
      hostel: "In Panama City und Bocas del Toro sind Dorms oft klimatisiert – nachts wird's kühl, Decke dabeihaben.",
      hostelEn: "In Panama City and Bocas del Toro dorms are often air-conditioned – it gets cool at night, so bring a blanket.",
      bus: "In der Hauptstadt mit dem Metrobus (Tarjeta nötig); zu den San-Blas-Inseln per 4x4 + Boot über Veranstalter.",
      busEn: "In the capital use the Metrobus (a Tarjeta is needed); to the San Blas islands by 4x4 + boat through an operator.",
      grupo: "Bocas ist Partyinsel – Bootstouren und Inselhüpfen organisiert man leicht in der Gruppe.",
      grupoEn: "Bocas is a party island – boat trips and island-hopping are easy to organise as a group.",
      cultura: "US-Dollar ist offizielle Währung; Trinkgeld 10 % üblich, Wechselgeld passend bereithalten.",
      culturaEn: "The US dollar is the official currency; a 10% tip is usual, so keep the right change handy.",
    },
    cuba: {
      hostel: "Statt Hostels übernachtet man in „casas particulares“ (Privatzimmer) – respektiere, dass es ein Familienhaus ist.",
      hostelEn: "Instead of hostels you stay in „casas particulares“ (private rooms) – respect that it's a family home.",
      bus: "Víazul-Busse verbinden Touristenstädte (im Voraus buchen); zwischendurch teilt man sich „colectivos“ (Sammeltaxis).",
      busEn: "Víazul buses connect the tourist cities (book ahead); in between, people share „colectivos“ (shared taxis).",
      grupo: "Andere Reisende trifft man in der casa beim Frühstück – WLAN gibt's nur an öffentlichen Plätzen mit Karte.",
      grupoEn: "You meet other travellers at breakfast in the casa – WiFi is only available in public squares with a card.",
      cultura: "Zwei Währungswelten und knappe Waren: kleine Gastgeschenke (Stifte, Seife) werden geschätzt, Politik lieber meiden.",
      culturaEn: "Two currency worlds and scarce goods: small gifts (pens, soap) are appreciated, and it's best to avoid politics.",
    },
    "republica-dominicana": {
      hostel: "Außerhalb der All-inclusive-Zonen (Las Terrenas, Cabarete) gibt es entspannte Surf-/Backpacker-Hostels.",
      hostelEn: "Outside the all-inclusive zones (Las Terrenas, Cabarete) there are laid-back surf/backpacker hostels.",
      bus: "Komfortbusse (Caribe Tours, Metro) für Fernstrecken; lokal fahren „guaguas“ (Minibusse) – voll, aber günstig.",
      busEn: "Comfortable buses (Caribe Tours, Metro) for long distances; locally there are „guaguas“ (minibuses) – crowded but cheap.",
      grupo: "Beim Kitesurfen in Cabarete findet man schnell Anschluss an die internationale Szene.",
      grupoEn: "Kitesurfing in Cabarete is a quick way to plug into the international scene.",
      cultura: "Merengue und Bachata gehören dazu – eine Einladung zum Tanzen ist gut gemeint, ein Nein wird akzeptiert.",
      culturaEn: "Merengue and bachata are part of life – an invitation to dance is well-meant, and a no is accepted.",
    },
    "puerto-rico": {
      hostel: "In San Juan (Old San Juan, Condado) gibt es nur wenige echte Hostels – früh buchen, sie sind beliebt.",
      hostelEn: "In San Juan (Old San Juan, Condado) there are only a few real hostels – book early, they're popular.",
      bus: "Öffentlicher Nahverkehr ist dünn; viele nutzen Mietwagen oder Apps wie Uber, vor allem außerhalb San Juans.",
      busEn: "Public transport is thin on the ground; many use a hire car or apps like Uber, especially outside San Juan.",
      grupo: "Strände und der El-Yunque-Regenwald lassen sich gut als Gruppe per Mietwagen teilen (Kosten splitten).",
      grupoEn: "Beaches and the El Yunque rainforest are great to share as a group by hire car (split the costs).",
      cultura: "Englisch ist verbreitet, US-Dollar gilt; Trinkgeld 15–20 % wie in den USA erwartet.",
      culturaEn: "English is widespread and the US dollar is used; a 15–20% tip is expected, as in the USA.",
    },
    colombia: {
      hostel: "Cartagena, Medellín und die Zona Cafetera haben top Hostels; in Großstädten abends Wertsachen unsichtbar tragen.",
      hostelEn: "Cartagena, Medellín and the Zona Cafetera have top hostels; in big cities keep valuables out of sight in the evening.",
      bus: "Fernbusse sind gut, aber Strecken lang und kurvig – Reisetabletten helfen; Nachtbus spart eine Übernachtung.",
      busEn: "Long-distance buses are good, but routes are long and winding – travel-sickness tablets help; a night bus saves a night's accommodation.",
      grupo: "„No dar papaya“ heißt: keine Gelegenheit bieten – aber Kolumbianer sind extrem herzlich und hilfsbereit.",
      grupoEn: "„No dar papaya“ means: don't give anyone an opening – but Colombians are extremely warm and helpful.",
      cultura: "Anrede oft förmlich mit „usted“, selbst unter Freunden; Trinkgeld („la propina“) wird meist erfragt.",
      culturaEn: "People often use the formal „usted“, even among friends; the tip („la propina“) is usually asked about.",
    },
    venezuela: {
      hostel: "Touristische Infrastruktur ist begrenzt; auf der Isla Margarita und in Mérida gibt es Posadas (Pensionen).",
      hostelEn: "Tourist infrastructure is limited; on Isla Margarita and in Mérida there are posadas (guesthouses).",
      bus: "Überlandreisen gut planen und aktuelle Sicherheitslage prüfen – nachts möglichst nicht fahren.",
      busEn: "Plan overland trips carefully and check the current security situation – avoid travelling at night.",
      grupo: "Reise möglichst nicht allein und schließ dich erfahrenen Gruppen/Guides an.",
      grupoEn: "Try not to travel alone and join experienced groups/guides.",
      cultura: "Bargeld/Devisen-Situation ist komplex – vorab informieren und nur Nötiges sichtbar tragen.",
      culturaEn: "The cash/foreign-currency situation is complex – read up beforehand and keep only what's necessary in view.",
    },
    ecuador: {
      hostel: "Quito (Altstadt) und Baños haben gute Hostels; auf 2.800 m Höhe ist es nachts kalt – warme Decke nutzen.",
      hostelEn: "Quito (old town) and Baños have good hostels; at 2,800m it's cold at night – use a warm blanket.",
      bus: "Busnetz ist dicht und günstig; auf Taschen achten und Gepäck im Auge behalten, besonders an Terminals.",
      busEn: "The bus network is dense and cheap; mind your bags and keep an eye on your luggage, especially at terminals.",
      grupo: "Für den Quilotoa-Loop oder Dschungeltouren finden sich leicht Gruppen übers Hostel.",
      grupoEn: "For the Quilotoa Loop or jungle tours you'll easily find groups through the hostel.",
      cultura: "In den Anden indigene Gemeinschaften respektvoll behandeln – fürs Fotografieren um Erlaubnis fragen; Toilettenpapier gehört fast überall in die papelera, nicht ins WC.",
      culturaEn: "In the Andes, treat indigenous communities with respect – ask permission before photographing; almost everywhere, toilet paper goes in the papelera, not the WC.",
    },
    peru: {
      hostel: "In Cusco (3.400 m) erst akklimatisieren – die erste Nacht ruhig angehen, viel Wasser, Coca-Tee hilft.",
      hostelEn: "In Cusco (3,400m) acclimatise first – take the first night easy, drink plenty of water, and coca tea helps.",
      bus: "Cruz del Sur & Co. bieten sichere, bequeme Fernbusse mit Sitzkontrolle – für lange Strecken klar empfehlenswert.",
      busEn: "Cruz del Sur & co. offer safe, comfortable long-distance buses with seat checks – clearly worth it for long trips.",
      grupo: "Den Salkantay-/Inca-Trek bucht man oft als Gruppe; Trekkingpartner findet man im Hostel.",
      grupoEn: "The Salkantay/Inca trek is often booked as a group; you'll find trekking partners at the hostel.",
      cultura: "Auf Märkten ist moderates Feilschen okay; beim Essen „buen provecho“ wünschen kommt gut an.",
      culturaEn: "At markets, moderate haggling is fine; wishing „buen provecho“ at mealtimes goes down well.",
    },
    bolivia: {
      hostel: "La Paz und Uyuni liegen sehr hoch – langsam machen, warm anziehen, Dorms sind oft unbeheizt.",
      hostelEn: "La Paz and Uyuni are very high up – take it slow, wrap up warm, and dorms are often unheated.",
      bus: "Nachtbusse sind günstig, aber Straßen rau und kalt – Schlafsack/Decke mitnehmen, seriösen Anbieter wählen.",
      busEn: "Night buses are cheap, but roads are rough and cold – bring a sleeping bag/blanket and pick a reputable operator.",
      grupo: "Die Salar-de-Uyuni-Tour (3 Tage) fährt man als Jeep-Gruppe – such dir Mitreisende vorher aus.",
      grupoEn: "The Salar de Uyuni tour (3 days) is done as a jeep group – pick your fellow travellers beforehand.",
      cultura: "In indigenen Regionen zurückhaltend fotografieren; cholitas reagieren oft empfindlich auf Kameras.",
      culturaEn: "In indigenous regions, photograph sparingly; cholitas are often sensitive about cameras.",
    },
    chile: {
      hostel: "Hostels sind gut organisiert, aber teuer; in Patagonien (Torres del Paine) Plätze weit im Voraus sichern.",
      hostelEn: "Hostels are well run but expensive; in Patagonia (Torres del Paine) secure your spots well in advance.",
      bus: "Fernbusse (z. B. Turbus, Pullman) sind komfortabel und pünktlich – Chile ist verlässlicher als viele Nachbarn.",
      busEn: "Long-distance buses (e.g. Turbus, Pullman) are comfortable and punctual – Chile is more reliable than many of its neighbours.",
      grupo: "Für Patagonien-Treks („W“-Trek) Ausrüstung und Camps teilen – Gruppen senken Kosten deutlich.",
      grupoEn: "For Patagonia treks (the „W“ trek) share gear and camps – groups cut costs significantly.",
      cultura: "Chilenisches Spanisch ist schnell und voller Slang („¿cachái?“); ruhig nachfragen, das ist okay.",
      culturaEn: "Chilean Spanish is fast and full of slang („¿cachái?“); feel free to ask again, that's fine.",
    },
    argentina: {
      hostel: "In Buenos Aires startet das Nachtleben spät – Dorm-Mitbewohner kommen um 3–4 Uhr, also Ohrstöpsel parat.",
      hostelEn: "In Buenos Aires nightlife starts late – dorm-mates roll in at 3–4am, so have earplugs ready.",
      bus: "Fernbusse („micros“) sind exzellent: „cama“ oder „cama-suite“ buchen für flache Sitze auf langen Strecken.",
      busEn: "Long-distance buses („micros“) are excellent: book „cama“ or „cama-suite“ for flat seats on long journeys.",
      grupo: "Beim Asado (Grillen) und Mate-Teilen wird man schnell Teil der Runde – Mate kreisen lassen, nicht umrühren.",
      grupoEn: "Over an asado (barbecue) and sharing mate you quickly become part of the group – pass the mate round, don't stir it.",
      cultura: "Hier gilt Voseo (vos statt tú) und „che“ als Anrede; Begrüßung oft mit Wangenkuss, auch unter Männern.",
      culturaEn: "Here voseo applies (vos instead of tú) and „che“ as a form of address; greetings are often with a kiss on the cheek, even between men.",
    },
    uruguay: {
      hostel: "In Montevideo und Punta del Este ruhig und sicher; in der Nebensaison sind viele Küsten-Hostels geschlossen.",
      hostelEn: "In Montevideo and Punta del Este it's quiet and safe; in the off-season many coastal hostels are closed.",
      bus: "Busnetz ist sauber, pünktlich und sicher – Tickets am Terminal (Tres Cruces) lösen.",
      busEn: "The bus network is clean, punctual and safe – buy tickets at the terminal (Tres Cruces).",
      grupo: "Strandorte wie La Paloma/Cabo Polonio sind klein und gesellig – man lernt sich von selbst kennen.",
      grupoEn: "Beach spots like La Paloma/Cabo Polonio are small and sociable – you get to know people naturally.",
      cultura: "Mate ist überall dabei (Thermoskanne unterm Arm); entspannter, formeller Umgangston, Trinkgeld ~10 %.",
      culturaEn: "Mate goes everywhere (a flask under the arm); a relaxed yet formal manner, and a tip of ~10%.",
    },
    paraguay: {
      hostel: "Wenig touristisch – in Asunción gibt es einige Hostels, sonst eher Pensionen; Hitze beachten (Ventilator/AC).",
      hostelEn: "Not very touristy – in Asunción there are a few hostels, otherwise mostly guesthouses; mind the heat (fan/AC).",
      bus: "Fernbusse verbinden die größeren Städte; für den Chaco gute Planung und seriöse Anbieter wählen.",
      busEn: "Long-distance buses connect the larger cities; for the Chaco, plan well and choose a reputable operator.",
      grupo: "Reisende sind selten – sei offen, dann ergeben sich Kontakte fast von allein.",
      grupoEn: "Travellers are rare – be open and connections will come about almost on their own.",
      cultura: "Guaraní wird neben Spanisch gesprochen; ein „mba'éichapa“ (Hallo auf Guaraní) sorgt für Begeisterung.",
      culturaEn: "Guaraní is spoken alongside Spanish; a „mba'éichapa“ (hello in Guaraní) goes down a treat.",
    },
  };

  window.SC = window.SC || {};
  window.SC.knigge = { TOPICS, ACCENTS };
})();
